JoinColony/colonyCDapp

- Readme.md
- scripts/provision_submodules.sh
The `provision_submodules.sh` was referencing a local `yarn` path that was not a dependency and thus not being installed. This now calls `yarn` directly, which should pick up the global path.
Resolves #17
> Remove provisioning script using local yarn path

- package.json
- temp-voyager/voyager.html
- temp-voyager/voyager.ts
This PR adds a `voyager` script that spins up a GraphQL Voyager, a tool for visualising and inspecting GraphQL API schemas:
It allows you to inspect the queries, mutations, input and return types as well as explore the relations between types. I found it quite handy when previously working with GraphQL APIs.
To run:
```
npm run voyager
```
> Add GraphQL Voyager

- package.json
- scripts/generate-temp-files.sh
This PR fixes lambda function creation _(well, actually fixes the whole `amplify` script, which would crash otherwise)_ when running `npm run amplify`
It does so, by generating some temporary, local, config files which `amplify` expects to exist prior to running.
Besides that, I've also made sure that if the CDapp doesn't have a local `.env` file already, it will generate one from the example file
> Fix generating local config files

- src/components/common/ColonyHome/ColonyDomainDescription/ColonyDomainDescription.tsx
- src/components/common/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
- src/components/common/ColonyHome/ColonyDomainSelector/CreateDomainButton.tsx
- src/components/common/ColonyHome/ColonyExtensions/ColonyExtensions.tsx
- src/components/common/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.tsx
- src/components/common/ColonyHome/ColonyFundingWidget/ColonyFundingWidget.tsx
- src/components/common/ColonyHome/ColonyHome.tsx
- src/components/common/ColonyHome/ColonyHomeLayout.css
- src/components/common/ColonyHome/ColonyHomeLayout.css.d.ts
- src/components/common/ColonyHome/ColonyHomeLayout.tsx
- src/components/common/ColonyHome/ColonyMembersWidget/ColonyMembersWidget.tsx
- src/components/common/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
- src/components/common/ColonyHome/ColonySubscription/ColonySubscription.tsx
- src/components/common/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.tsx
- src/components/common/ColonyHome/ColonyTitle/ColonyTitle.tsx
- src/components/common/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
- src/components/common/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
- src/components/common/ColonyHome/ExtensionUpgrade/ExtensionUpgrade.tsx
- src/components/common/ColonyMembers/ColonyMembers.tsx
- src/components/common/ColonyTotalFunds/ColonyTotalFunds.tsx
- src/components/common/NewActionButton/NewActionButton.tsx
- src/components/frame/ColonyBackText/ColonyBackText.tsx
- src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx
- src/context/ColonyContext.tsx
- src/context/index.ts
- src/hooks/index.ts
- src/hooks/useCanInteractWithColony.ts
- src/hooks/useColonyContext.ts
- src/routes/Routes.tsx
This PR introduces a new `ColonyContext` and related components. The main purpose is to streamline colony fetching, handling loading and error states and provide better typing.
All the components making the `getFullColonyByName` query or getting the colony via props have been refactored to use the new context.
Additionally, the boolean returned by `useCanInteractWithColony` hook is also exposed via that context. 
~~@rdig a couple of questions before I mark this as ready:~~
- ~~Instead of "encapsulating" the logic from `useCanInteractWithColony` hook I just called it from the context - is that fine or should I move the logic entirely?~~
- ~~There's a bunch of components that get colony passed as a prop. I held on for now with refactoring them to use context as it could lead to us having to …
> Introduce Colony Provider

- Readme.md
- docker/colony-cdapp-dev-env-orchestration.yaml
- docker/colony-cdapp-dev-env-reputation-monitor
The reputation monitor wasn't available in the CDapp. This PR puts it on 3001. I think while setting up the Docker environments there was some confusion between the miner/oracle (which remains on 3002) and this monitor (which is now on 3001), and this seems to work from my (very) cursory testing without breaking access to the oracle, but it's possible there's some subtlety's I'm unaware of.
> Make reputation monitor available on port 3001

- docker/files/network/run.sh.base
It's specifically the address at [index 5](https://github.com/JoinColony/colonyDapp/blob/d9211aabff928e2d0f9fc8908adad492112b6f37/scripts/start_all.js#L46) in the array that's set up for mining, so that's the address that should be used.
In the current state, the environment (and miner) comes up, but the address being used for mining has no CLNY staked, and so is unable to mine.
> Fix ganache address used for mining in local dev

- scripts/temp-create-data.js
- src/constants/extensions.ts
- src/hooks/useExtensionsData.ts
- src/types/extensions.ts
This PR adds support for `VotingReputation` extension.
@Note:
The CDapp currently uses Yup to validate some input parameters to the `VotingReputation` extension, which i have disabled for the time being. If we're moving to a new validation package, this should be updated.
For testing, please use the same approach as #95.
Resolves #113
> Port `VotingReputation` extension

- src/components/common/CreateColonyWizard/ConfirmTransactions.tsx
- src/components/common/CreateColonyWizard/CreateColonyCardRow.tsx
- src/components/common/CreateColonyWizard/StepColonyName.tsx
- src/components/common/CreateColonyWizard/StepConfirmAllInput.tsx
- src/components/common/CreateColonyWizard/StepConfirmTransactions.tsx
- src/components/common/CreateColonyWizard/StepCreateToken.tsx
- src/components/common/CreateColonyWizard/StepSelectToken.tsx
- src/components/common/CreateColonyWizard/StepTokenChoice.tsx
- src/components/common/CreateColonyWizard/TokenSelector.tsx
- src/components/common/CreateColonyWizard/index.ts
- src/components/common/CreateColonyWizard/validation.ts
- src/components/common/CreateUserWizard/CreateUserWizard.tsx
- src/components/common/CreateUserWizard/StepUserEmail.tsx
- src/components/common/CreateUserWizard/StepUserName.tsx
- src/components/common/CreateUserWizard/index.ts
- src/components/shared/DecisionHub/DecisionHub.tsx
- src/components/shared/DecisionHub/DecisionOption.tsx
- src/components/shared/Fields/Form/HookForm.tsx
- src/components/shared/Fields/Input/HookForm/Input.tsx
- src/components/shared/Fields/Input/HookForm/InputComponent.tsx
- src/components/shared/Fields/InputStatus/HookForm/InputStatus.tsx
- src/components/shared/Fields/InputStatus/HookForm/index.ts
- src/components/shared/Fields/index.ts
- src/i18n/en.json
- src/utils/lodash.ts
- src/utils/network.ts
- src/utils/yup/tests/index.ts
This PR migrates the Colony Creation wizard from Formik to React Hook Form. It should work the same as before, just now it's using the React Hook Form components.
* HookForm-specific `InputStatus`
* `utils/network`: some helpers to see what network speed the user has. May be useful to conditionally show a loading status based on this information. Faster connections may make a loading status redundant, e.g. if we're querying our own db, it's typically very fast and thus no need to display a loading status. The loading status also appears to flash in this case, because of the connection speed, which is also good to avoid.
**Changes** 🏗
* `ColonyCreationWizard`: now using React Hook Form components.
* Tidied up imports in `UserCreationWizard`
Resolves  #116
> Migrate Colony Creation Wizard to use React Hook Forms

- src/components/common/CreateColonyWizard/StepColonyNameInputs.tsx
- src/components/common/CreateUserWizard/index.ts
**Today I Learned** that the order of exports matters in `index.ts` files. This PR corrects the export order in the `UserCreationWizard` so imports are defined when the wizard loads.
**Changes** 🏗
* Move "main" export to bottom of `index.ts`
* I also update a tooltip in the ColonyCreationWizard which I meant to include in the previous commit
> Fix user wizard `index.ts` export order

- src/Entry.tsx
- src/components/common/ColonyHome/ColonyMembersWidget/MembersSubsection.tsx
- src/components/common/UserProfileEdit/UserAvatarUploader.tsx
- src/components/common/UserProfileEdit/UserMainSettings.tsx
- src/components/common/UserProfileEdit/UserProfileEdit.tsx
- src/components/frame/AvatarDropdown/AvatarDropdown.tsx
- src/components/shared/InfoPopover/UserInfo.tsx
- src/components/shared/UserAvatar/UserAvatar.tsx
- src/components/shared/UserInfoPopover/UserInfo.tsx
- src/context/AppContext.tsx
- src/hooks/index.ts
- src/hooks/useCanEditProfile.ts
This PR fixes [the problem](https://github.com/JoinColony/colonyCDapp/pull/79#issuecomment-1341046043) with the loading state at `/edit-profile`.
I have covered the following scenarios:
1. Navigate to /edit-profile with no wallet connected. --> redirects to /landing
2. Connect wallet to a wallet with a registered user, then navigate to edit-profile. --> displays Profile Edit screen
3. While on edit-profile, refresh the browser. --> shows loading spinner, then displays Profile Edit screen
4. Disconnect wallet while at edit-profile --> redirects to /landing
5. Navigate to edit-profile with a wallet that doesn't have a user associated. --> shows loading spinner, then redirects to /landing
Please double-check each and any others you can think of.
* `useCanEditProfile.ts` to …
> Fix `/edit-profile` loading state

- src/components/common/Extensions/ExtensionStatusBadge/ExtensionStatusBadge.tsx
- src/hooks/useEnabledExtensions.tsx
- src/types/extensions.ts
- src/utils/extensions.ts
This small PR ports over the `useEnabledExtensions` hook. I spotted an opportunity to extract and encapsulate some logic related to checking whether an extension is enabled so I added a new field `isEnabled` to `InstalledExtensionData`. 
This also brings in a small change to `ExtensionStatusBadge` which helps us avoid weird statuses like the following:
From now, there will only be a maximum of one status shown (and deprecated will take precedence over enabled).
It doesn't look like anything previously relying on this hook has been ported over, so you'll just have to call it anywhere in the CDapp and log out the results to verify that they're correct. For the `ExtensionStatusBadge`, try to deprecate an enabled extension, and it should show as just "Deprecated".
Resolves #128
> Port `useEnabledExtensions` hook

- src/redux/sagas/extensions/extensionEnable.ts
- src/redux/sagas/utils/refreshExtension.ts
This small PR adds a `refreshEnabledExtension` util, similarly to other functions from #147 
For testing, try to enable `VotingReputation`. You should see the status updated immediately. Please note, the status will revert back to Disabled when you refresh unless you follow the first two steps from [block-ingestor#3](https://github.com/JoinColony/block-ingestor/pull/3). Otherwise, the block ingestor simply won't pick up the enable event and won't update the db.
Resolves #152
> Add `refreshEnabledExtension` util

- src/components/common/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
- src/components/common/ColonyHome/ColonyNavigation/NavItem.tsx
- src/components/common/ColonyHome/ColonyNavigation/colonyNavigationConfig.ts
- src/components/shared/NavLink/NavLink.tsx
- src/routes/Routes.tsx
This PR adds the Decisions item to Colony Navigation. 
It also tidies up the Colony Navigation view and fixes a bug where the nav item wasn't active at the correct route if you refreshed the page.
It does nothing else. I therefore suggest reviewing this in conjunction with #176, which handles the route wiring.
**Changes** 🏗
* Add Decision item to Colony Navigation
Resolves #165
> Add decisions to colony navigation

- src/redux/sagas/extensions/extensionUpgrade.ts
- src/redux/sagas/utils/refreshExtension.ts
Small PR, adds a refreshUpgradedExtension function similar to all other refresh functions.
Testing is tricky, since we still haven't figured out how to install a newer version of extension in the network (I wasted some time on it yesterday with no luck), so I think we'll just have to "trust" that it works and test it comprehensively when testing the main extensions branch.
Resolves #151
> Add refreshUpgradedExtension util function

- src/components/common/Extensions/ExtensionActionButton/ExtensionActionButton.tsx
- src/components/common/Extensions/ExtensionDetails/ExtensionDetails.css
- src/components/common/Extensions/ExtensionDetails/ExtensionDetails.css.d.ts
- src/components/common/Extensions/ExtensionDetails/ExtensionDetails.tsx
- src/components/common/Extensions/ExtensionDetails/ExtensionDetailsAside.tsx
- src/components/common/Extensions/ExtensionDetails/tableData.tsx
- src/components/common/Extensions/ExtensionUpgradeButton/ExtensionUpgradeButton.tsx
- src/components/shared/DetailsWidgetUser/DetailsWidgetUser.css.d.ts
- src/components/shared/DetailsWidgetUser/DetailsWidgetUser.tsx
- src/components/shared/InfoPopover/InfoPopover.tsx
- src/components/shared/InfoPopover/MemberInfoPopover/MemberInfoPopover.tsx
- src/components/shared/InfoPopover/TokenInfo.tsx
- src/components/shared/InfoPopover/TokenInfoPopover.tsx
- src/components/shared/InfoPopover/UserInfo.tsx
- src/components/shared/UserAvatar/UserAvatar.tsx
- src/components/shared/UserMention/UserMention.tsx
- src/constants/extensions.ts
- src/hooks/useUserReputation.ts
- src/types/extensions.ts
This PR ports over the missing parts of `ExtensionDetails`. It also fixes the React Intl warning in console as well as refactoring the checks for allowed interactions (installing, enabling, upgrading, etc.) to simplify things.
To test, look at the details page of an installed and uninstalled extension. You should see results similar to the screenshots below.
Resolves #124 and #146
> Port Extension Details

- src/components/common/UserProfileEdit/AdvancedSettingsRow.css
- src/components/common/UserProfileEdit/AdvancedSettingsRow.css.d.ts
- src/components/common/UserProfileEdit/AdvancedSettingsRow.tsx
- src/components/common/UserProfileEdit/CustomEndpointInput.css
- src/components/common/UserProfileEdit/CustomEndpointInput.css.d.ts
- src/components/common/UserProfileEdit/CustomEndpointInput.tsx
- src/components/common/UserProfileEdit/UserAdvancedSettings.tsx
- src/components/common/UserProfileEdit/validation.ts
- src/components/shared/Fields/Input/HookForm/types.ts
- src/components/shared/Fields/InputStatus/HookForm/InputStatus.tsx
- src/utils/lodash.ts
- src/utils/yup/tests/index.ts
This PR implements validation for a custom gnosis chain rpc in the user advanced settings. 
Go to user advanced settings. Enter a url. Only a valid gnosis  rpc endpoint will validate (you can find some at [chainlist](https://chainlist.org/chain/100)) 
If URL is not a valid RPC: 
If RPC is not gnosis:
* Added gnosis chain rpc validation
* Removed the validate button since validation normally occurs automatically.
Resolves #145
> Implement Custom Rpc Validation

- src/components/common/ColonyDecisions/DecisionDialog/DecisionDialog.tsx
- src/components/common/ColonyDecisions/DecisionDialog/index.ts
- src/components/common/ColonyDecisions/DecisionPreview/DecisionData/DecisionContent.tsx
- src/components/common/ColonyDecisions/DecisionPreview/DecisionData/DecisionData.tsx
- src/components/common/ColonyDecisions/DecisionPreview/DecisionData/DecisionNotFound.tsx
- src/components/common/ColonyDecisions/DecisionPreview/DecisionData/index.ts
- src/components/common/ColonyDecisions/DecisionPreview/DecisionPreview.tsx
- src/components/common/ColonyDecisions/DecisionPreview/DecisionPreviewControls/DecisionPreviewControls.tsx
- src/components/common/ColonyDecisions/DeleteDecisionDialog/DeleteDecisionDialog.css
- src/components/common/ColonyDecisions/DeleteDecisionDialog/DeleteDecisionDialog.css.d.ts
- src/components/common/ColonyDecisions/DeleteDecisionDialog/DeleteDecisionDialog.tsx
- src/components/common/ColonyDecisions/DeleteDecisionDialog/index.ts
- src/components/common/ColonyDecisions/index.ts
- src/routes/routeConstants.ts
- src/utils/decisions.ts
This PR wires in the delete and edit decision modals, and well as the "Create new decision" button at `/preview` when there is 
no stored decision. "Publish" is being handled separately.
Note: It's worth reviewing https://github.com/JoinColony/colonyCDapp/pull/201 first, since it updates the state-related logic introduced here to account for the DraftDecisionItem.
Delete decision
Create new decision
Edit existing decision
Clicking delete should: 
1. Open the delete decision modal
2. Clicking "Delete" in the modal should: 
3. Navigate to `/decisions` and remove the decision from local storage.
Click edit should: 
1. Open the DecisionDialog
2. Making an update should close the modal and update the preview. 
3. If you go back to the main `/decisions` page, open the dialog, and submit it, you …
> Wire in Decision Preview Controls

- src/components/common/ColonyDecisions/DeleteDecisionDialog/DeleteDecisionDialog.tsx
- src/components/common/ColonyDecisions/NewDecisionButton/NewDecisionButton.tsx
- src/components/common/ColonyDecisions/RemoveExistingDecisionDialog/RemoveDecisionMessage.css
- src/components/common/ColonyDecisions/RemoveExistingDecisionDialog/RemoveDecisionMessage.css.d.ts
- src/components/common/ColonyDecisions/RemoveExistingDecisionDialog/RemoveDecisionMessage.tsx
- src/components/common/ColonyDecisions/RemoveExistingDecisionDialog/RemoveExistingDecisionDialog.tsx
- src/components/common/ColonyDecisions/RemoveExistingDecisionDialog/index.ts
- src/components/common/ColonyDecisions/index.ts
This PR wires in the "Remove Draft Decision" modal. When you click "New Decision", if you have a decision stored, this modal should appear. Clicking "view draft" should take you to `/preview`; else, clicking "New Decision" should open the Editor and clear the existing decision from local storage.
Remove Saved Decision:
* `RemoveExistingDecisionDialog`
Resolves #188
> Add "Remove Draft Decision" modal

- docker/colony-cdapp-dev-env-orchestration.yaml
- scripts/temp-create-data.js
- src/components/shared/Alert/Alert.css.d.ts
- src/constants/index.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/utils/extensionVersion.ts
This PR adds a healthcheck for amplify image, and makes block-ingestor dependent on amplify so that it can call the necessary mutations on startup (tracking extensions for now, but I expect this will also be needed for actions and motions)
It also fixes the failing colony creation by refactoring hardcoded OneTxPayment version in `colonyCreate` saga to programatically get it from the db (something I missed while bumping the colony network version), and removes the `setCurrentVersion` mutation calls from temp-create-data script.
Resolves #137
> Refactor ingestor image to depend on amplify 

- scripts/lambda-functions-dependencies.sh
Small fix for #244.
> I can confirm the issue, it happens whenever there's a folder in `/amplify/backend/function` that is missing `src/package.json` (it tends to happen when you switch between branches and have some leftover untracked files).
If package.json is missing, `npm i` will look in the parent directories until it finds the root package.json, which specifies the `postinstall` script, causing the infinite loop.
Resolves #244
> Fix infinite loop when missing package.json in lambda function directory

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ActionDetailsPage/ActionDetailsPage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/EscalateButton/EscalateButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/TransactionNotFound/TransactionNotFound.tsx
- src/components/common/ColonyActions/ActionDetailsPage/index.ts
- src/components/common/ColonyActions/ColonyActions.tsx
- src/components/common/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
- src/components/common/Extensions/ExtensionActionButton/ExtensionActionButton.tsx
- src/components/common/Extensions/ExtensionDetails/ExtensionDetailsAside.tsx
- src/components/common/Extensions/ExtensionUpgradeButton/ExtensionUpgradeButton.tsx
- src/components/frame/LoadingTemplate/LoadingTemplate.tsx
- src/components/frame/LoadingTemplate/index.ts
- src/components/shared/ActionsList/ActionsList.tsx
- src/components/shared/Button/ActionButton.tsx
- src/components/shared/Button/DialogActionButton.tsx
- src/components/shared/DetailsWidget/detailsWidgetConfig.tsx
- src/components/shared/PopoverSection/MetaSection.tsx
- src/graphql/fragments/actions.graphql
- src/graphql/generated.ts
- src/graphql/queries/actions.graphql
- src/hooks/index.ts
- src/hooks/useGetColonyAction.ts
- src/redux/sagas/motions/index.ts
- src/redux/sagas/motions/rootMotion.ts
- src/redux/sagas/setupUserContext.ts
- src/redux/sagas/utils/effects.ts
- src/redux/sagas/utils/getNetworkClient.ts
- src/redux/types/actions/index.ts
- src/redux/types/actions/motion.ts
This PR is responsible for wiring in the root motion saga and handling the first phase of the motion lifecycle, such that we have record of the motion in the db (via block-ingestor) and can access relevant data (such as action type) for display in the ui.
It does not handle any subsequent phases of the motion lifecycle (staking, voting etc.). This will be handled subsequently.
Switch to this branch and run a fresh build (`npm run dev`). I've updated the block ingestor hash to point to block-ingestor#16.
Then go to https://github.com/JoinColony/block-ingestor/pull/16 and follow the instructions to get the reputation and the voting extension installed.
Finally, once all set up, click "Test mint tokens". It should redirect you to the relevant motion page:
You can change the amount of tokens …
> Port root motion saga

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ColonyActions.tsx
- src/redux/sagas/actions/index.ts
- src/redux/sagas/actions/unlockToken.ts
- src/redux/types/actions/colonyActions.ts
This PR adds support for the UnlockToken action.
1. Create a colony using the wizard.
1. Click on the Test Unlock Token action.
1. You'll be redirected to a transaction not found page, wait a few seconds and refresh.
1. You should see the action details (including the token symbol and the team). Please check that the properties displayed are the same as in the Dapp, e.g.: https://xdai.colony.io/colony/jakub/tx/0xa9cf3bc60a59c6c972700f8b3d881bdb0b8d71cb8237988e9fc949c218a4a21f
Resolves #278
> Add support for UnlockToken action

- src/hooks/useEnabledExtensions.tsx
This small PR refactors the `useEnabledExtensions` hook back into a shape similar to the Dapp's one.
I initially did some work to add relation between `CurrentVersion` and `ColonyExtension` models but then I realised we still need separate current version queries so I ditched all that.
Log the value returned by the hook somewhere. Install, enable, deprecate and uninstall both extensions and see if the value returned matches your actions.
Resolves #304
> Expose current VotingReputation version in `useEnabledExtensions` hook

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingInput.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderAnnotation.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderAnnotation.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderAnnotation.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderDescription.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderDescription.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderDescription.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/RequiredStakeMessage.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/RequiredStakeMessage.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/RequiredStakeMessage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingWidgetSlider.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingWidgetSlider.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingWidgetSlider.tsx
- src/components/shared/Numeral/Numeral.tsx
- src/components/shared/Slider/Slider.css.d.ts
- src/components/shared/Slider/Slider.tsx
This PR ports the slider and slider description / annotation in the staking widget input. UI only, no wiring.
Mainly code review. If you want to see "live", follow instructions in #329
* Staking widget slider  components
**Changes**
* Updated `Slider` to use hook form
* Updated `Numeral` to accept a Decimal as a value type
Contributes to #270
> Port staking input slider

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/ObjectButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakeButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakingControls.tsx
- src/i18n/en.json
This PR ports the "Stake" and "Object" buttons that constitute the `StakingControls` component inside `StakingInput`. UI only, no wiring.
Really just code review, however if you want to see it "live", follow instructions in #329 
* Stake and object buttons
Contributes to #270
> Port Stake and Object buttons for staking widget input

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStake.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStake.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStake.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStakeHeading.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStakeHeading.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStakeHeading.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/UserStakeMessage.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/UserStakeMessage.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/UserStakeMessage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingWidget.tsx
- src/components/shared/Heading/Heading5.tsx
- src/components/shared/Heading/index.ts
- src/components/shared/ProgressBar/ProgressBar.css
- src/components/shared/ProgressBar/ProgressBar.css.d.ts
- src/components/shared/ProgressBar/ProgressBar.tsx
This PR ports the SingleTotalStake component, which contains the staking progress bar. 
It is the ui only. No wiring of any kind.
More of a code review as not wired in. If you want to see "live", see instructions in #329 
* `Heading5` component
* Port Single Total Stake components (i.e. staking widget progress bar)
**Changes** 🏗
* Updates to `ProgressBar`
Contributes to #270
> Port `SingleTotalStake` (staking widget component)

- src/components/common/ColonyActions/ActionDetailsPage/ActionDetailsPage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/DefaultMotion.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/MotionPhaseWidget.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/SingleTotalStake/SingleTotalStake.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingInput.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/RequiredStakeMessage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingWidget.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingWidgetProvider.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/helpers.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/index.ts
- src/components/common/Dialogs/RaiseObjectionDialog/RaiseObjectionDialog.tsx
- src/components/shared/Fields/Form/ActionHookForm.tsx
- src/components/shared/Fields/Form/index.ts
- src/components/shared/Fields/index.ts
- src/constants/index.ts
- src/hooks/helpers/index.ts
- src/hooks/helpers/motionHookHelpers.ts
- src/hooks/index.ts
- src/hooks/useGetColonyAction.ts
- src/hooks/useObjectButton.ts
- src/hooks/useStakingInput.ts
- src/hooks/useStakingWidgetUpdate.ts
I initially intended this PR to "optimistically" update the ui, however, it transpires that it's much simpler just to poll the db and show a loading spinner while we wait. So the tradeoff is increased simplicity at the expense of waiting for the block ingestor to process the staking event before we show the user the updated values (where optimistic ui would be instant, but require every component to keep track of its own state, in addition to it already being held in the db). 
Therefore, this PR adds ensures the staking widget updates correctly after staking or objecting.
Set up your env via [these instructions](https://github.com/JoinColony/colonyCDapp/pull/338)
Then stake both for and against the motion. You should see a loading state while we poll the db, and then updated values in the …
> Update staking widget ui after staking

- package-lock.json
- package.json
- src/components/common/ColonyHome/ColonyHomeLayout.tsx
- src/components/common/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
- src/utils/checks/canColonyBeUpgraded.ts
- src/utils/external/index.ts
`colony-js` had to be updated to import the latest network release tag from it as the previous import was no longer available.
**When the user can update to a newer version:**
In order to test, the process should be the same as the one for https://github.com/JoinColony/colonyCDapp/pull/313 but now a warning should appear in the colony's home.
**When the colony version is below v4:**
In order to test, I just changed `colonyContractVersion` in line 60 of `ColonyUpgrade` to `3`.
Resolves #59
> Wire up ColonyUpgrade component

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/ClaimMotionStakes.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/MotionPhaseWidget.tsx
- src/graphql/fragments/actions.graphql
- src/graphql/queries/actions.graphql
- src/hooks/helpers/motionHookHelpers.ts
- src/hooks/index.ts
- src/hooks/useClaimWidgetConfig.tsx
- src/i18n/en.json
- src/redux/sagas/motions/claimMotionRewards.ts
- src/redux/sagas/motions/index.ts
- src/utils/colonyMotions.ts
This PR implements the claim widget.
Testing for both functionality (does it all work as expected) and ui (does it look right).
Follow the [set up instructions](https://github.com/JoinColony/colonyCDapp/pull/338) to be able to stake. Be sure to set the staking duration to something longer than 72 hours, as occasionally this causes the motion to fail due to how time works in development. 720 would do.
Stake in favour of the motion 100%. Do not stake against. This will break it since we haven't set up voting/reveal yet.
Fast forward time by running the following in your terminal (fast forwards by 1000 hours):
```
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600000],"id":1}' localhost:8545
curl -X POST --data …
```
> Port motion reward claim

- package-lock.json
- package.json
- src/components/common/Dialogs/DomainFundSelectorSection/DomainBalance.tsx
- src/components/common/Dialogs/DomainFundSelectorSection/DomainFundSelector.tsx
- src/components/common/Dialogs/DomainFundSelectorSection/DomainFundSelectorSection.tsx
- src/components/common/Dialogs/MintTokenDialog/MintTokenDialog.tsx
- src/components/common/Dialogs/TokenAmountInput/TokenAmountInput.tsx
- src/components/common/Dialogs/TransferFundsDialog/TransferFundsDialog.tsx
- src/components/common/Dialogs/TransferFundsDialog/TransferFundsDialogForm.tsx
- src/components/common/Dialogs/TransferFundsDialog/helpers.ts
- src/components/common/Dialogs/TransferFundsDialog/validation.ts
- src/components/common/TokenCard/TokenCard.tsx
- src/components/shared/EthUsd/EthUsd.tsx
- src/components/shared/Fields/Input/HookForm/FormattedInputComponent.tsx
- src/components/shared/Fields/Input/HookForm/Input.tsx
- src/components/shared/Fields/Input/HookForm/InputComponent.tsx
- src/components/shared/Fields/InputStatus/HookForm/InputStatus.tsx
- src/components/shared/Fields/Select/HookForm/HookFormSelect.tsx
- src/components/shared/Fields/Select/index.ts
- src/components/shared/Fields/Select/types.ts
- src/components/shared/Fields/TokenSymbolSelector/TokenSymbolSelector.tsx
- src/graphql/fragments/colony.graphql
- src/graphql/generated.ts
- src/types/graphql.ts
- src/utils/css/index.ts
- src/utils/tokens.ts
What started as a simple ticket grew quite a bit... But we now have a working Manage Funds dialog!
I struggled with setting a custom error in `react-hook-form`. Apparently `setError` doesn't influence the `isValid` property of the form state (which I find counterintuitive, but that's how it is: https://react-hook-form.com/api/useformstate/). I had to resort to conditionally passing a custom error to the input component
Test the Transfer Funds, Mint Tokens, and Unlock Tokens dialog. Ensure the validation works as intended and the correct action is created, and then picked up by block-ingestor.
Resolves #306
> Wire the Manage Funds dialog with action sagas

- src/components/common/ColonyActions/ColonyActions.tsx
- src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
- src/components/common/Dialogs/EditColonyDetailsDialog/helpers.ts
- src/components/frame/SubscribedColoniesList/SubscribedColoniesList.tsx
- src/redux/sagas/actions/editColony.ts
- src/redux/sagas/utils/metadataChangelog.ts
Connected EditColonyDetails with the related saga. Also updated sidebar and dialog `ColonyAvatar` to prefer avatar over the thumbnail so that the actual uploaded image is shown.
Contributes to #309
> Connect Edit Colony Details dialog with saga

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/ActivateButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakeButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakingControls.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakingControls.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/useStakingControls.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingInput.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSlider.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/StakingValidationMessage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingWidgetSlider.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/helpers.ts
- src/components/common/Dialogs/RaiseObjectionDialog/ObjectionSlider.tsx
- src/hooks/helpers/motionHookHelpers.ts
- src/hooks/useStakingSlider.ts
- src/i18n/en.json
This PR ports the activate tokens button as well as the corresponding error message when a user hits a staking limit caused by insufficient active tokens.
Following on from #364, you can activate tokens in the UI via TokenActivationPopover. Activate fewer than the required stake, and then refresh the browser. 
You should see a limit on the staking slider and the activate button/error msg appear if you hit that limit.
* Activate Button
* Limit exceeded message
**Changes** 🏗
* `getStakeFromSlider` to use Decimal for increased precision
Contributes to #270
> Port activate button (II)

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/ObjectButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakeButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/StakingControls.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/useStakingControls.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSlider.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/NotEnoughReputationMessage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/StakingValidationMessage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/helpers.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingWidgetSlider.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/index.ts
- src/hooks/helpers/motionHookHelpers.ts
- src/hooks/useStakingSlider.ts
This PR ports the following staking validation error messages:
1. Amount left to stake is less than min user stake 
Stake a motion 99%. You should find yourself in that awkward position where the amount left to stake is less than the min user stake. I have copied the logic over exactly from the dapp, but updated the copy as the previous message said: 
"The motion can't be staked more than the minimum stake", which is obviously false.
2.  User does not have enough reputation to stake 100% of the motion
For this it'll be easiest to manually hardcode the `userMaxStake` values in `useStakingSlider` and `useStakingControls`. It needs to be more than the min user stake, but less than the required stake. `10000000000000000` worked for me.
(Note that we have userMaxStake in two places due to the …
> Port staking error messages (III)

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/DefaultMotion.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/MotionPhaseWidget.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteButton.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteButton.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteDetails.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteDetails.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteDetails.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteRewardItem.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteRewardItem.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VoteRewardItem.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingPanel.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingWidget.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingWidget.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingWidget.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingWidgetHeading.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingWidgetHeading.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/VotingWidgetHeading.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/getVotingPanelConfig.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/index.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/useVoteDetailsConfig.tsx
- src/components/shared/DetailsWidget/DetailItem.tsx
- src/components/shared/DetailsWidget/index.ts
- src/components/shared/Fields/RadioGroup/CustomRadioGroup.tsx
- src/components/shared/Numeral/Numeral.css
- src/components/shared/Numeral/Numeral.css.d.ts
- src/components/shared/Numeral/Numeral.tsx
- src/i18n/en.json
This PR ports the voting widget ui (only, no wiring).
Just follow the basic set up to "Test mint token", as I've hardcoded it to show the voting widget for convenience in this pr.
I.e:
Install voting rep, then in truffle console:
```
c = await IColony.at('<colony-address>')
c.emitDomainReputationReward(1, accounts[0], '1000000000000000000')
c.setArbitrationRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<voting-rep-extn-address>', 1, true)
```
After clicking "Test mint token", you should see the voting widget. It does nothing so just testing for ui.
* Voting widget components
Contributes to #326
> Port Voting widget UI

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/ClaimMotionStakes.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/ClaimMotionStakes.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/ClaimMotionStakes.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/useVotingWidgetUpdate.ts
- src/components/shared/DetailsWidget/DetailItem.tsx
- src/hooks/useClaimWidgetConfig.tsx
This PR keeps the `hasUserVoted` and `isClaimed` state in sync with the user, so that it's accurate after a user switches account or logs out.
I've also thrown in a small presentational fix by emboldening the "Claim your tokens" detail in the ClaimWidget.
**Changes** 🏗
*  sync `hasUserVoted` and `isClaimed` state with the user
*  embolden the "Claim your tokens" detail
> Fix `isClaimed` and `hasUserVoted` state in motions

- amplify/backend/api/colonycdapp/schema.graphql
- amplify/backend/function/fetchMotionState/src/graphql.js
- amplify/backend/function/fetchMotionState/src/index.js
- amplify/backend/function/fetchMotionState/src/package-lock.json
- amplify/backend/function/fetchMotionState/src/package.json
- amplify/backend/function/fetchMotionState/src/utils.js
- src/graphql/generated.ts
- src/hooks/useGetColonyAction.ts
This PR fixes a problem with staker rewards not being present in the db in the event where a motion fails before it goes to a vote. Previously, I was exclusively populating staker rewards via the block ingestor (when a motion is finalized). 
However, it's also necessary in the event that the motion failed without going to a vote. If this happens, there is no specific event emitted via the contracts to let us know, so I have updated the `fetchMotionState` lamda we already have to check and update the db with staker rewards in the event the motion has failed without going to a vote. 
Get yourself set up (see instructions in #380) and create a motion.
Stake / object, but don't: 
stake in favour 100% (so the motion doesn't pass)
stake in favour 100% and object 100% (so we don't trigger a …
> Fix inability to claim rewards when motion fails without vote

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/EscalateButton/EscalateButton.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/MotionCountdown.css
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/MotionCountdown.css.d.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/MotionCountdown.tsx
- src/redux/sagas/motions/escalateMotion.ts
This PR wires in the escalate button. It is disabled (intentionally) so just a ui / code check.
Easiest way to test this is to manually set the `networkMotionState` to `4` in `DefaultMotion.tsx` (at `getMotionState`), and then set `showEscalateButton` to `true` at `MotionCountdown.tsx`
No special set up needed, just get yourself over to the motions page.
**Changes** 🏗
* Tweaks to escalate button
Resolves #407
> Wire in escalate button

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ActionDetailsPage/staticMaps.ts
- src/components/common/ColonyActions/ColonyActions.tsx
- src/components/shared/DetailsWidget/detailsWidgetConfig.tsx
- src/utils/colonyActions.ts
This PR makes a few small adjustments that enable testing of the other motions that use the rootMotion saga:
1. Unlock token
2. VersionUpgrade
It also updates the logic in the DetailsWidget so we can control whether the Motion item gets appended to the widget or replaces another item.
Install voting rep extn
Give yourself reputation
1. Unlock Token: via the UAC, unlock your token
2. VersionUpgrade: via the testing button on ColonyHome, upgrade the version
Resolves  #428
> Add UnlockToken and VersionUpgrade motion support

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/MotionCountdown.tsx
- src/components/common/ColonyActions/ActionsListItem/ActionsListItem.tsx
- src/components/common/ColonyActions/ActionsListItem/helpers.ts
- src/utils/colonyMotions.ts
To test just follow the same process for #367 or #410. 
Once you have rep, you can turn the monitor off and just create a bunch of motions with 2 users or more and advance the motion phases via staking/voting YAY and/or NAY like so:
The timer should only show for the motion states above.
Resolves #416
> Wire up motion countdown timer in action list

- docker/colony-cdapp-dev-env-block-ingestor
The bulk of this update is in the block-ingestor counterpart: https://github.com/JoinColony/block-ingestor/pull/64
- You can test this by following the same process needed to go through the whole motion ex. Get rep, get tokens to stake with, and assign the correct permissions. In the particular case of the add/edit domain motions, the voting extension needs the `Architecture` permission to create them:
- `c.setArchitectureRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<voting-reputation-id>', 1, true) `
- and if you want to edit a domain and create the motion in the domain itself, you are going to need rep in that team, for example:
`c.emitDomainReputationReward(<id-of-subdomain>, accounts[0], '1000000000000000000')`
- The Add/Edit domain motions can be …
> Handle add/edit domain on motion finalized

- amplify/backend/api/colonycdapp/schema.graphql
- amplify/backend/function/fetchMotionState/src/index.js
- amplify/backend/function/fetchMotionState/src/utils.js
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ActionDetailsPage/ActionDetailsPage.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionCountdown/MotionCountdown.tsx
- src/components/common/ColonyActions/ActionsListItem/ActionsListItem.tsx
- src/components/common/ColonyActions/ActionsListItem/helpers.ts
- src/components/common/ColonyActions/helpers/getEventTitleValues.ts
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/graphql/generated.ts
- src/hooks/useGetColonyAction.ts
- src/utils/colonyMotions.ts
This PR ensures that we "disable" motions that do not belong to the current installation of the voting rep extn.
By this, I mean that:
- You can still view the details, at their most recent state
- You can't interact with the motion via the widget (because it's not present)
- If a new voting rep extn is currently enabled, you will see an "invalid" tag; else, you won't see any tag (because we don't display motion tags when the voting rep extn isn't enabled).
This applies in the following cases:
* The voting rep extn is uninstalled
* The voting rep extn is deprecated
* The voting rep extn is installed, but not the same installation that created the motion
Note that this hasn't been specced so I'm just relying on showing the "invalid" tag for motions that don't belong to the currently …
> Hide Motion widget when voting rep uninstalled

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialog.tsx
- src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
- src/components/common/Dialogs/CreatePaymentDialog/helpers.ts
Some things that deserve an explicit mention:
- If the colony/team doesn't have rep, an error message should appear and the form should be disabled except for the domain selector.
- You should be able to create a motion in the parent domain (Root) even if the targeted domain is a subdomain.
- You can now get reputation by making a payment action/motion, so no need to get it via truffle console.
- To test creating motions in a subdomain, now you should be able to create domains through the UAC.
- To get funds in a team to make a payment, you can force the Transfer Funds action through the UAC by manually changing the saga to the non-motion action type.
Related block-ingestor PR: https://github.com/JoinColony/block-ingestor/pull/66
Resolves #475
> Integrate motion components with Create Payment dialog

- src/components/common/Dialogs/MintTokenDialog/MintTokenDialog.tsx
- src/components/common/Dialogs/MintTokenDialog/MintTokenDialogForm.tsx
Some things that deserve an explicit mention:
- If the colony doesn't have rep, an error message should appear and the form should be disabled.
- You can now get reputation by making a payment action, so no need to get it via truffle console.
Resolves #476
> Integrate motion components with Mint Tokens dialog

- src/components/common/Dialogs/NetworkContractUpgradeDialog/NetworkContractUpgradeDialog.tsx
- src/components/common/Dialogs/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.tsx
- To test, you can follow the instructions to add a new colony version detailed here: https://github.com/JoinColony/colonyCDapp/pull/313
- If the colony doesn't have rep, an error message should appear and the form should be disabled.
- You can now get reputation by making a payment action, so no need to get it via truffle console.
Resolves #482
> Integrate motion components with NetworkContractUpgradeDialog

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/MotionPhaseWidget.tsx
- src/context/ColonyContext.tsx
This PR refetches the colony data after finalizing a motion, so data like the added domain is instantly available without needing a broswer refresh.
**Changes** 🏗
* Expose colony refetch from context
Run a motion through to completion (e.g. Create Domain). Once you hit finalize, go back to Colony Home without reloading the browser and your data (e.g. the new domain) should be there.
> Update colony post finalize motion

- src/components/common/Dialogs/TransferFundsDialog/TransferFundsDialog.tsx
- src/components/common/Dialogs/TransferFundsDialog/TransferFundsDialogForm.tsx
Some things that deserve an explicit mention:
- If the colony doesn't have rep, an error message should appear and the form should be disabled.
- You can now get reputation by making a payment action, so no need to get it via truffle console.
- You can get funds in a team by creating/forcing a transfer funds action.
Resolves #477
> Integrate motion components with Transfer Funds dialog

- src/components/common/Dialogs/UnlockTokenDialog/UnlockTokenDialog.tsx
- src/components/common/Dialogs/UnlockTokenDialog/UnlockTokenForm.tsx
Some things that deserve an explicit mention:
- If the colony doesn't have rep, an error message should appear and the form should be disabled.
- You can now get reputation by making a payment action, so no need to get it via truffle console.
Resolves #478
> Integrate motion components with Unlock Token dialog

- src/redux/sagas/users/index.ts
Removing the colony manager's context on logout is something that we do in the Dapp and it seems like it would be required for us to do here as well in order to avoid using a manager instance with an outdated signer.
You should be able to go through the whole motion flow without having to reload the page when you switch users. I haven't noticed any drawbacks/side effects from us removing this context on logout.
Resolves #392
> Update user logout to allow for user switching

- src/components/common/CreateColonyWizard/StepConfirmTransactions.tsx
- src/context/ColonyContext.tsx
Fix to the redirect to ColonyHome from Colony creation wizard. Changing the network policy in #485 has surfaced a race condition after creating a colony via the wizard. 
`cache-and-network` appears to behave differently to `network-only`, in that now, we're not getting a loading state that persists  long enough for the colony to be populated in the db. Previously, it seems we were being shown a loading state that endured just enough for the redirect to be successful (margins are small here, for the record).
Anyway, to be absolutely sure we don't redirect to 404 when there is actually the colony in the db, I've implemented the same polling strategy as at the ActionDetailsPage. 
**Changes** 🏗
* Poll for colony inside colony context. 
Resolves #498
> Fix colony redirect

- src/redux/sagas/motions/claimMotionRewards.ts
This pr fixes a bug I introduced when porting across the claim motion saga. I was getting an error when claiming both sides of a motion, and it was caused by passing an undefined motion id to the claimRewardWithProofs function.
See the reproduction steps in the issue. 
**Changes** 🏗
* Fix undefined motion id
Resolves #500
> Fix inability to claim both sides of a motion

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/FinalizeMotion/FinalizeMotion.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/MotionPhaseWidget.tsx
- src/utils/domains.ts
This pr fixes a bug with fetching the domain balance when we finalize a motion. I wasn't discriminating by the token address, so was getting the wrong token balance. 
**Changes** 🏗
* Find domain balance by domain **and** token address
Resolves #502
> Fix incorrect domain balance in finalize motion

- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/components/common/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx
- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/helpers.ts
- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/validation.ts
- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
- src/components/shared/DetailsWidget/ReputationChangeDetail/ReputationChangeDetail.tsx
- src/components/shared/Fields/Input/HookForm/FormattedInputComponent.tsx
- src/components/shared/MemberReputation/MemberReputation.css
- src/hooks/useColonyHasReputation.ts
- src/hooks/useDialogActionPermissions.ts
- src/hooks/useSelectedUser.ts
- src/index.ts
- src/redux/sagas/motions/manageReputationMotion.ts
- src/redux/types/actions/motion.ts
- src/utils/arrays/index.ts
- src/utils/reputation.ts
This PR makes it possible to create an Award / Smite Rep motion via the UAC.
It also makes some small refactors to the ManageReputation Dialog components, like moving validation logic to a separate file.
Install voting rep. 
c.setArchitectureRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<voting-rep-extn-address>', 1, true)
You should:
- Not be able to submit the form without rep. (i.e. you see the NotEnoughRep and form is disabled).
After adding rep, you should be able to award/smite rep in any combination of domain and subdomain that is possible via the ui. (i.e from the subdomain in the subdomain, from root in root, or from root in the subdomain).
**Changes** 🏗
* Wire in motion components with Award/Smite
* Display reputation penalty as positive value in …
> Add Motion Functionality to Manage Rep Dialog

- src/hooks/useGetColonyAction.ts
I was seeing the following lamda error caused by an effect refetching motion state without checking if there's any motion data. This PR fixes it.
**Changes** 🏗
* Don't refetch motion state without motion data
> Fix motion refetching without data

- src/components/common/ColonyActions/ActionDetailsPage/ActionDetailsPageFeed/MotionDetailsPageEvent/MotionEventData.tsx
- src/components/common/ColonyActions/helpers/getEventTitleValues.ts
- src/components/common/ColonyActions/helpers/itemStyles.css
- src/components/common/ColonyActions/helpers/itemStyles.css.d.ts
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/hooks/useUserReputation.ts
In order to test this, just make sure to go through the whole motion flow and see if the name of the user displays the correct reputation amount. Also, make sure we are using the correct root hash to get the reputation, or in other words, that the reputation of the users in past motions doesn't change, it should stay the same as the time the motion was created.
Resolves #420
> Add user reputation to motion messages

- src/components/frame/GasStation/MessageCardDetails/MessageCardDetails.css
- src/components/frame/GasStation/MessageCardDetails/MessageCardDetails.css.d.ts
- src/components/frame/GasStation/MessageCardDetails/MessageCardDetails.tsx
- src/redux/sagas/motions/voteMotion.ts
This PR fixes a problem with the gas station message content not being wrapped correctly. It also fixes a mistake with the message title for the vote motion message, which was using the reveal vote message.
In the gas station, you should now see when voting / revealing:
Resolves #515
> Fix gas station message

- .env.example
- src/components/frame/LandingPage/LandingPage.tsx
- src/components/frame/RouteLayouts/UserNavigation/Wallet/Wallet.tsx
- src/constants/externalUrls.ts
- src/constants/index.ts
- src/context/AppContext.tsx
- src/context/index.ts
- src/hooks/useCanInteractWithColony.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/setupUserContext.ts
- src/redux/sagas/setupWalletContext.ts
- src/redux/sagas/users/index.ts
- src/redux/sagas/wallet/ganacheModule.ts
- src/redux/sagas/wallet/index.ts
- src/redux/sagas/wallet/onboard.ts
- src/types/definitions/index.d.ts
- src/types/wallet.ts
- src/utils/autoLogin.ts
This PR implements a "quick login" functionality to the wallet connection process. If there is wallet information saved in local storage when setting up the user context (e.g. after a logged-in user refreshes the browser), instead of waiting for a full login, we store a simplified wallet in context with address and chain information. This allows queries to run and the app to be interacted with.
Then, we run the standard login via web3-onboard in the background, and once that completes store a full wallet in context.  
- Log in and refresh the browser. Wallet connection should be instant and the app fully interactive right away.
- Log in via metamask -> same story.
- Log in via metamask to an unsupported chain. `useCanInteractWithNetwork` should return false, which should restrict what you …
> Refactor wallet autologin

- src/components/common/Extensions/UserNavigation/UserNavigation.tsx
- src/stories/common/UserNavigation.stories.tsx
Adding not connected wallet view for user navigation.
> feat: added not connected state to user navigation

- amplify/backend/api/colonycdapp/schema.graphql
- amplify/backend/function/fetchMotionState/src/graphql.js
- amplify/backend/function/fetchMotionState/src/utils.js
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/graphql/fragments/actions.graphql
- src/graphql/generated.ts
- Makes MotionMessage a mode
- Makes initiatorAddress required
- Removes the extra query, useGetUserByAddressQuery as the initiator user is already fetched with the model
Use [block-ingestor#72](https://github.com/JoinColony/block-ingestor/pull/72) for testing as this adds the required values for initiatorAddress
Contributes to #423
> Convert MotionMessages to a Model

- src/redux/sagas/actions/createDomain.ts
- src/redux/sagas/actions/editColony.ts
- src/redux/sagas/actions/editDomain.ts
- src/redux/sagas/actions/unlockToken.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/extensions/extensionEnable.ts
- src/redux/sagas/motions/escalateMotion.ts
- src/redux/sagas/motions/finalizeMotion.ts
- src/redux/sagas/utils/enableExtensionHelpers.ts
Spring cleaning. All sagas that were copy/pasting the function definition of `createGroupTransaction` are now using the same function.
I have tested by ensuring all the affected sagas still behave as intended.
Resolves #344
> Refactor sagas to use createGroupTransaction utility

- .storybook/main.css
- src/components/common/Extensions/SubNavigation/SubNavigationItem/SubNavigationItem.module.css
- src/components/common/Extensions/SubNavigation/SubNavigationItem/SubNavigationItemMobile.module.css
- src/components/common/Extensions/SupportingDocuments/LinkWrapper.tsx
- src/components/shared/Extensions/Avatar/Avatar.module.css
- src/components/shared/Icon/Icon.module.css
- src/styles/main.global.css
This small PR fixes the icon weight issue and the overflowing of icons, which is cutting off icons due to the weight. This was being caused by stroke being applied which was not needed.
Image showing incorrect icon weight and clipping:
Image showing updates from this PR including correct weight and without clipping:
> Fixing icon weight and overflowing

- amplify/backend/function/createUniqueColony/src/index.js
- src/components/common/ColonyHome/ColonyDomainDescription/ColonyDomainDescription.tsx
- src/components/common/Dialogs/ManageFundsDialog/ManageFundsDialog.tsx
- src/components/common/Dialogs/UnlockTokenDialog/UnlockTokenForm.tsx
- src/components/common/Dialogs/UnlockTokenDialog/helpers.ts
- src/components/frame/TokenActivation/TokensTab/ChangeTokenStateForm.tsx
- src/constants/index.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/transformers/index.ts
- src/utils/external/index.ts
- Fixed the max button on the token action popover not triggering the validation/dirtying/touching logic, therefore the submit button not enabling.
- Updated `getBlockExplorerLink` to return a valid Gnosis Chain block explorer link.
- Updated `ColonyDomainDescription`'s outdated way of getting the domain's color.
- Updated `getUserRolesForDomain` logic to catch the inherited domain permissions correctly.
- Added native token status logic to track if the token is mintable, unlockable, or if it has been unlocked already (The `unlocked` status needs https://github.com/JoinColony/block-ingestor/pull/75 to work properly)
> Misc fixes for QA

- src/components/common/Dialogs/EditColonyDetailsDialog/ColonyAvatarUploader.tsx
- src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialog.tsx
- src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
- src/components/common/Dialogs/EditColonyDetailsDialog/helpers.ts
- src/components/common/UserProfileEdit/UserAvatarUploader.tsx
- src/components/shared/AvatarUploader/AvatarUploader.tsx
- src/components/shared/AvatarUploader/UploadControls.tsx
- src/components/shared/AvatarUploader/helpers.ts
- src/components/shared/Fields/InputStatus/HookForm/InputStatus.tsx
- src/components/shared/FileUpload/limits.ts
- src/images/optimisation/index.ts
- src/redux/types/actions/motion.ts
This PR wires up the colony edit form with motion components.
Create a motion to edit your colony. Avatar / displayname should be updated upon finalizing the motion. Try removing the avatar as well.
Also note that finalizing a motion to change the avatar only won't affect the colony's display name, even if the display name changed after the motion was created (and vice versa). 
For dialog specs see #433
**Changes** 🏗
* Adding motion components to colony edit form.
Resolves #433
> Integrate Colony Edit dialog with motion components

- amplify/backend/function/fetchMotionState/src/index.js
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/FinalizeMotion/FinalizeMotion.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/MotionPhaseWidget.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/RevealWidget/useRevealWidgetUpdate.ts
- src/components/common/ColonyActions/ActionDetailsPage/useGetColonyAction.ts
- src/utils/colonyMotions.ts
Per #569, very occasionally the fetchMotionState lamda gets called after the motion state becomes finalizable, but before the revealed votes have been populated to the db. This was having the effect of the wrong vote outcome being shown.
I have mitigated this by checking that the votes are indeed present as we expect before adding messages to the motion message feed. 
The root cause is still not certain. I have not been able to reproduce at all. I thought it might be due to the refetch occuring in the motion timer, but @ArmandoGraterol has not been able to verify this. In any case, if it happens again now, the user will be able to reload the browser, which will fetch the latest data and display everything as expected. 
To test, just run through the motion lifecycle and confirm the reveal …
> Mitigate reveal state race condition (motions)

- amplify/backend/function/fetchMotionState/src/utils.js
- docker/colony-cdapp-dev-env-block-ingestor
Fixed 0 staking rewards appearing in the stakes tab of the token activation popover.
To reproduce just enable the extension with a 50% voting reward, fully stake 1 side, lose with that same side, and then when you finalize the motion the reward should be 0 and no new claims should appear in the stake tab.
Block ingestor counterpart: https://github.com/JoinColony/block-ingestor/pull/85
Resolves #614
> Add filtering for 0 staking reward

- src/constants/index.ts
- src/redux/sagas/extensions/extensionEnable.ts
- src/redux/types/actions/colony.ts
This pr adds the logic to set extension permissions when an extension is enabled.
**Changes** 🏗
* Add permissions logic to enable extn saga
1. Create a colony.
2. Install the voting rep extension. Ensure the rep extn address is picked up in the extension details widget (you will need to refresh the browser). (@jakubcolony We need to fix this before launching to production, since we can't expect users to know to refresh the browser after installing the extension. If you don't, the wrong extension address ("0x000...") gets passed to the block ingestor.)
3. Enable the voting rep extension. All permissions should be enabled, and thus you should be able to freely create, stake, and finalize motions.
Resolves #619
> Set extension permissions on initialisation

- src/components/frame/TokenActivation/StakesTab/StakesListItem.tsx
This solves the issue that when linking from one motion to the next using go to motion from the stakes tab, each motion is added to the history stack and the back button goes back to the previous motion.
if linking to a motion when already on a motion, the history stack will be replaced instead of pushed and now the back button will go to the previous location in the stack before navigating between motions.
Resolves #602
> Replace link history if traveling between transactions

- src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementDialog.tsx
- src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementForm.tsx
- src/components/common/Dialogs/PermissionManagementDialog/helpers.ts
The permissions management dialog should work now that the voting reputation extension enabled and it is now possible to create a motion.
Resolves #483
> Port permissions dialog

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/ClaimMotionStakes.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/useClaimWidgetConfig.tsx
Hide the claim widget when the motion fails without staking or voting as there would be nothing to claim, so to test just create a motion and let the timer run out.
Resolves #603
> Update useClaimWidgetConfig to hide claim widget on motion failed

- src/components/common/UserProfile/UserProfile.tsx
- src/hooks/index.ts
- src/hooks/useUserByNameOrAddress.ts
* Adds userUserByNameOrAddress hook that only makes one query depending if the input is a username or an address
Make sure a user can be loaded by both username or address in the route:
`/user/0x9dF24e73f40b2a911Eb254A8825103723E13209C`
`/user/a`
Resolves #512
> Add `useUserByNameOrAddress` hook

- src/components/common/Dialogs/CreateDomainDialog/helpers.ts
- src/graphql/generated.ts
- src/redux/sagas/actions/createDomain.ts
- src/redux/types/actions/colonyActions.ts
Fixed the create domain payload having a different structure than the one we use in the edit domain saga and create/edit domain motion saga.
You should be able to create "create/edit domain" actions and motions without problems.
Resolves #647
> Update Create Domain action payload

- amplify/backend/api/colonycdapp/schema.graphql
- src/graphql/generated.ts
In block-ingestor#88, there's a need for fetching extensions by their hash and in such scenarios @index should help speed things up.
> Add @index to extension hash field

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSlider.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderLabel.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingSliderMessages/StakingValidationMessage.tsx
The error messages in the staking slider should work as always but now this shouldn't be reproducible:
```
Have two users. User 2 has 0 activated tokens.
User 1 stakes a motion 100%.
Then, switch to User 2.
The staking widget input is correctly disabled, but, there's no message to inform the user to activate their tokens.
```
Resolves #601
> Update error message display conditional on staking slider

- docker/colony-cdapp-dev-env-block-ingestor
Make sure the minimum user stake is always displayed as 1%
Block ingestor PR counterpart: https://github.com/JoinColony/block-ingestor/pull/91
Test:
Stake and object a motion with the minimum possible stake and make sure the percentage is 1% instead of 0% every place the user stake is displayed in the UI.
Contributes to #648
> Fix: set minimum stake percentage to 1%

- src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementForm.tsx
- src/components/common/Dialogs/PermissionManagementDialog/helpers.ts
This is not a perfect solution. I think `canRoleBeSet` or the permission validation, and the UI in this dialog needs to be reworked to accommodate for the user actually needing `Root` or `Architecture` roles depending on the domain and permissions being modified. 
That would require more time and effort which is why I'm just uploading this fix, which should be enough to fix a user with no permissions not being able to create a motion.
Resolves #696
> Update permission management read only permission logic

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/ClaimMotionStakes/useClaimWidgetConfig.tsx
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/useObjectButton.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/helpers.ts
- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/useStakingInput.ts
- src/components/frame/AvatarDropdown/AvatarDropdown.tsx
- src/components/frame/AvatarDropdown/AvatarDropdownPopoverMobile.tsx
- src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx
- src/components/frame/TokenActivation/StakesTab/ClaimAllButton.tsx
- src/components/frame/TokenActivation/TokenActivationContent/TokenActivationContent.tsx
- src/components/frame/TokenActivation/TokenActivationPopover.tsx
- src/components/frame/TokenActivation/TokensTab/ChangeTokenStateForm.tsx
- src/components/frame/TokenActivation/TokensTab/TokensTab.tsx
- src/components/frame/UserTokenActivationButton/UserTokenActivationButton.tsx
- src/context/ColonyContext.tsx
- src/context/UserTokenBalanceContext.tsx
- src/context/index.ts
This PR updates the Staked Tokens item in the Token Activation Popover after staking a motion, and also after claiming token rewards (via widget and via stakes tab in Token Activation Popover).
We're testing two things. The first is that the "Staked" item in the Token Activation Popover correctly updates whenever we stake a motion, or claim our rewards (either via the widget, or via the Token Activation Popover).
This is fairly simple to test: ensure that the value updates after staking / claiming.
The second is that the Staking limit updates after staking. To test this, you need to activate enough tokens to stake but not enough to stake 100%. Then stake. Once the widget updates, the staking limit should have updated to reflect the fact that you have fewer active tokens now.
**New stuff** …
> Update staked tokens after staking a motion

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VotingWidget/useVoteDetailsConfig.tsx
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
Currently, the reputation for the motion messages is using the reputation in the `fromDomain`, as opposed to the reputation in the `motionDomain`, which means that in the example below, it's showing that I have no rep, when I do. 
We are interested in displaying the rep in the `motionDomain` because that's what is used in the voting calculation. 
**Changes** 🏗
* Use the motion domain, not from domain, to calculate rep in the motion messages
> Fix reputation in motion msg

- src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/helpers.ts
I noticed a bug (difficult to reproduce) in which the staking slider would only stake 99% of the remaining stake, even if I had enough tokens. 
This is a rounding error, and so I've updated the logic to capture the state in which a user wants to stake 100% of the remaining stake amount.
**Changes** 🏗
* Add case specifically if slider is at 100
> Ensure staking slider has correct max value

- amplify/backend/function/getMembersForColony/src/index.js
This PR prevents the contributors sort function in the `getMembersForColony` lambda from erroring in the event that a contributor's reputation percentage is undefined. This is the source of a recent error in fetching colony members on Qa: https://qa-cdapp.colony.io/colony/leaningtowerofpisa
The problem is the we're calling the Decimal constructor with values that might be undefined (I can see this in the AWS Lambda console). So, this should fix that error. Can't easily be tested locally, therefore just code review.
**Changes** 🏗
* Guard Decimal constructor from undefined values
> Fix error in getMembersForColony Lambda

- .editorconfig
- amplify/backend/api/colonycdapp/schema.graphql
- src/graphql/generated.ts
This PR adds schema annotations to all types and models that are not auto-generated. This is to be able to create a markdown documentation for the team and external developers. The annotations will also find their way into the TypeScript types generated (meaning they will show up in the developer's IDE) and the GraphiQL explorer.
* Added annotations for the amplify schema file
**Changes** 🏗
* Adjust the codegen to use a local file loader instead of passing the string (which seems to be only useful for small schemas or testing purposes)
> Add GraphQL schema annotations

- src/components/common/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
- src/components/common/UnclaimedTransfers/UnclaimedTransfersItem.tsx
- src/context/ColonyContext.tsx
- src/context/UserTokenBalanceContext.tsx
This PR updates the colony object after claiming an incoming funds item, meaning the ui will update automatically without need for a browser refresh.
Transfer a colony some token so there's an incoming funds claim. Make the claim, either from the funding widget or the funds page. You should see the ui update automatically some seconds later.
**Changes** 🏗
* Poll colony object after claiming
> Update funds after claim

- src/components/common/Extensions/ExtensionUpgradeButton/ExtensionUpgradeButton.tsx
This PR adds a permission check from the dapp for the upgrade extn button. Currently it's hardcoded.
> Add permission check to can upgrade extn

- src/components/common/CreateColonyWizard/StepColonyNameInputs.tsx
- src/components/common/CreateColonyWizard/validation.ts
- src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
- src/constants/index.ts
This PR makes the colony (display) name max length consistent
* A new constant has been created in `MAX_DISPLAY_NAME` 
**Changes** 🏗
* `MAX_DISPLAY_NAME` is now used in colony creation validation and colony editing input limiting
Resolves #711
> Consistent max colony name

- package-lock.json
- package.json
- scripts/lambda-functions-dependencies.sh
-------
This PR fixes the postinstall script and adds it back in so that new developers can seamlessly get started 
**Changes** ✨
* `lambda-functions-dependencies.sh` has been refactored to short circuit to stop it from breaking QA (the new bash script is courtesy of @willm30 )
* `lambda-functions-dependencies.sh`'s method to find the bash interpreter has been changed in order to improve portability (IE it doesn't work on some distros)
> Fix postinstall script

- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/validation.ts
- src/components/common/Dialogs/CreateDomainDialog/CreateDomainDialog.tsx
- src/components/common/Dialogs/CreatePaymentDialog/validation.ts
- src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialog.tsx
- src/components/common/Dialogs/EditDomainDialog/EditDomainDialog.tsx
- src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
- src/components/common/Dialogs/MintTokenDialog/MintTokenDialog.tsx
- src/components/common/Dialogs/NetworkContractUpgradeDialog/NetworkContractUpgradeDialog.tsx
- src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementDialog.tsx
- src/components/common/Dialogs/RaiseObjectionDialog/ObjectionAnnotation.tsx
- src/components/common/Dialogs/RecoveryModeDialog/RecoveryModeDialog.tsx
- src/components/common/Dialogs/TokenManagementDialog/validation.ts
- src/components/common/Dialogs/TransferFundsDialog/validation.ts
- src/components/common/Dialogs/UnlockTokenDialog/UnlockTokenDialog.tsx
- src/components/shared/Fields/Annotations/Annotations.tsx
- src/constants/index.ts
- This PR uses a new constant in place of all the hard coded 4000 character limits
* A `MAX_ANNOTATION_LENGTH` constant was added to `constants/index.ts`
Resolves #355
> Use constant for annotation limit

- src/components/common/ColonyHome/ColonyHomeLayout.tsx
- src/components/common/ColonyHome/ColonySafes/ColonySafes.css
- src/components/common/ColonyHome/ColonySafes/ColonySafes.css.d.ts
- src/components/common/ColonyHome/ColonySafes/ColonySafes.tsx
- src/components/common/ColonyHome/ColonySafes/index.ts
- src/components/shared/SafeInfoPopover/SafeInfo/SafeInfo.css
- src/components/shared/SafeInfoPopover/SafeInfo/SafeInfo.css.d.ts
- src/components/shared/SafeInfoPopover/SafeInfo/SafeInfo.tsx
- src/components/shared/SafeInfoPopover/SafeInfo/index.ts
- src/components/shared/SafeInfoPopover/SafeInfoPopover.css
- src/components/shared/SafeInfoPopover/SafeInfoPopover.css.d.ts
- src/components/shared/SafeInfoPopover/SafeInfoPopover.tsx
- src/components/shared/SafeInfoPopover/index.ts
When you add a safe, a new "Linked assets" section should appear in the sidebar:
if you click on the name, a popover should appear with 2 buttons on the bottom ("Control safe" should not work yet as that dialog doesn't exist in this branch yet).
Resolves #734
> Port "Linked Assets" section

- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/components/shared/FriendlyName/FriendlyName.tsx
- src/components/shared/FriendlyName/helpers.ts
Currently, the logic for generating recipient / initiator info in the action message doesn't properly account for the fact that it could be a Colony, Colony Extension or Token as well as a user. This is resulting in the following when paying a Colony:
It's incorrectly and inconsistently displaying the recipient
This PR fixes it. 
Create an action such as paying another colony, and the correct data should be displayed in the message. 
*Add logic to detect the type of the initiator / recipient
> Fix user name in action message

- docker/colony-cdapp-dev-env-network
- src/components/common/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
This PR bumps the commit of `colonyNetwork` to support v12. This version is required to allow meta transactions for Control Safe.
To test this PR, we just need to make sure nothing broke and that the warning in the Control Safe dialog disappeared :)
> Bump colony version to v12

- src/components/common/ColonyHome/ColonyMembersWidget/ColonyMembersWidget.tsx
- src/components/common/ColonyMembers/ColonyMembers.tsx
- src/components/common/ColonyMembers/MemberControls/MemberControls.tsx
- src/components/common/ColonyMembers/MembersFilter/Filter.tsx
- src/components/common/ColonyMembers/MembersFilter/MembersFilter.tsx
- src/components/common/ColonyMembers/MembersFilter/filtersConfig.ts
- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx
- src/components/common/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/helpers.ts
- src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialog.tsx
- src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.css
- src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
- src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
- src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.tsx
- src/components/common/Dialogs/ManageWhitelistDialog/helpers.ts
- src/components/common/Dialogs/ManageWhitelistDialog/whitelistValidation.ts
- src/components/common/Members/Members.tsx
- src/components/common/Members/MembersList/Actions/MemberActionsPopover.tsx
- src/components/common/Members/MembersList/MembersListItem.tsx
- src/components/common/Members/filterMembers.ts
- src/hooks/index.ts
- src/hooks/useGetColonyMembers.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/utils/verifiedUsers.ts
This PR wires in the whitelist functionality. It also adds some missing features from the members page, namely, the address book / permissions controls, and the verified filter.
Verified filter:
Whitelist activated, users filtered out if not verified:
Whitelist activated, warning if trying to pay an address not on it:
Add to address book:
**Changes** 🏗
* Wire in whitelist with create payment and manage reputation dialogs
* Wire in members controls items (whitelist and permissions)
* Add verified filter
Dialogs:
- Payment: 
- warning should appear if you try and pay someone who's not verified when the whitelist is activated
- The user picker should also filter out non verified users when the whitelist is activated
- Manage reputation
- User picker should filter out non verified users when …
> Wire in whitelist

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/graphql/generated.ts
This PR makes the nativeFundingPotId an index on the Expenditure model, so we can easily see if an expenditure exists in the db with a given nativeFundingPotId.
Test with: https://github.com/JoinColony/block-ingestor/pull/115
Resolves #914
> Hide move funds from actions list (expenditures)

- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureAdvanceButton/ExpenditureAdvanceButton.tsx
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureAdvanceButton/index.ts
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureBalances/ExpenditureBalances.module.css
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureBalances/ExpenditureBalances.module.css.d.ts
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureBalances/ExpenditureBalances.tsx
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureBalances/index.ts
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureDetailsPage.module.css
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureDetailsPage.module.css.d.ts
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureDetailsPage.tsx
- src/components/common/Expenditures/ExpendituresPage/ExpendituresPage.tsx
- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/i18n/en.json
- src/redux/sagas/expenditures/fundExpenditure.ts
- src/redux/types/actions/expenditures.ts
- src/utils/expenditures.ts
This PR wires expenditure funding functionality with the information received from the expenditure's `balances` field. The balances are displayed on the expenditure details page and now, the UI will only ask for an expenditure to be funded if it's locked and not fully funded:
Contributes to #897
> Wire expenditure funding

- src/redux/sagas/setupWalletContext.ts
This PR fixes a bug where the wallet would always switch to Metamask when page is refreshed, even when the dev wallet is connected.
Connect any of the dev wallets and refresh the page. You should see the connected wallet staying the same, instead of switching to Metamask.
> Fix: Wallet switching to Metamask when page refreshed

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureAdvanceButton/ExpenditureAdvanceButton.tsx
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureDetailsPage.tsx
- src/components/common/Expenditures/ExpenditureForm/ExpenditureForm.tsx
- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/expenditures/createExpenditure.ts
- src/redux/sagas/extensions/extensionEnable.ts
- src/redux/types/actions/expenditures.ts
This PR implements the refactoring of expenditure domains as described in #955. 
* `nativeDomainId` field on the Expenditure model
**Changes** 🏗
* ExpenditureMetadata's `nativeDomainId` renamed to `fundFromDomainNativeId`
* Deleted the dev only delays (aka waiting for block-ingestor) since they're not needed anymore 
There should be no changes in functionality, so it's sufficient to only test if creating expenditures still works.
Resolves #955
> Re-implement expenditure domains

- src/components/common/Expenditures/ExpenditureForm/ExpenditureForm.module.css
- src/components/common/Expenditures/ExpenditureForm/ExpenditureFormFields.tsx
- src/components/common/Expenditures/ExpenditureForm/helpers.ts
- src/components/common/Expenditures/ExpenditureForm/types.ts
- src/redux/sagas/expenditures/editExpenditure.ts
- src/redux/sagas/utils/expenditures.ts
This PR modifies the expenditure form to allow setting claim delay both while creating and updating an expenditure.
Creating an expenditure: Try setting claim delay for one or more recipients when creating an expenditure. You should see the correct delays displayed next to slots on the expenditure details page.
Editing an expenditure: On the expenditure details page, while an expenditure is in Draft status, modify some of the claim delays. After refreshing the page, you should see the updated values.
Note there's no validation of the form inputs at the moment, so entering anything that's not a number will break things.
Resolves #927
> Setting expenditure claim delay

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/constants/extensions.ts
- src/context/ColonyManager.ts
- src/graphql/generated.ts
- src/hooks/useEnabledExtensions.tsx
- src/i18n/en.json
This PR adds support for the Staked Expenditure extension. You should be able to install and initialize this extension in your colony.
It should accept a simple param, Stake Fraction, that should be stored in the DB after initialization.
Usual extension interactions should be tested. You can verify the params have been stored in the DB by running the following query:
```gql
query ListExtensions {
listColonyExtensions {
items {
id
params {
stakedExpenditure {
stakeFraction
}
}
}
}
}
```
Resolves #898
> Installing and initializing Staked Expenditure extension

- src/components/shared/Button/ActionButton.tsx
- src/redux/sagas/extensions/extensionDeprecate.ts
- src/redux/sagas/extensions/extensionEnable.ts
- src/redux/sagas/extensions/extensionInstall.ts
- src/redux/sagas/extensions/extensionUninstall.ts
- src/redux/sagas/extensions/extensionUpgrade.ts
This PR tweaks the extension sagas logic so that errors correctly propagate to the UI. 
**Changes** 🏗
* Listen for the success / error tx action, before resolving the saga as successful
Contributes to #1018
> Ensure errors propagate to ui from extension sagas

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/ActionDetailsPage/ActionDetailsPageFeed/ActionDetailsPageFeed.tsx
- src/components/common/ColonyActions/ActionDetailsPage/staticMaps.ts
- src/components/common/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
- src/components/common/Dialogs/ControlSafeDialog/TransactionHeader/TransactionHeader.tsx
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection/ContractInteractionSection.css
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection/ContractInteractionSection.css.d.ts
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection/ContractInteractionSection.tsx
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection/MethodParamInput.tsx
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection/index.ts
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/RawTransactionSection.tsx
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
- src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection/TransferNFTSection.tsx
- src/components/common/Dialogs/ControlSafeDialog/validation.ts
- src/components/shared/OmniPicker/withOmniPicker.ts
- src/components/shared/SingleUserPicker/utils.ts
- Fixed removal of tabs in the Control Safe dialog. They weren't being deleted properly and that caused a bunch of other weird behaviours.
- Fixed safe balance validation of the Transfer Funds transaction type. The validation wasn't taking into account the safe's balance at all.
- Fixed numeral inputs in the Contract Interaction transaction type not being updated properly after a re-render caused by a bug of Cleave.js. To reproduce in the feature branch or any other branch besides this one, add a contract interaction section in the second or more position in the dialog that has a`UINT` or `INT` param input filled and remove the transaction tab that comes before the contract interaction one, and try to change the number input value. 
- Fixed the CDapp crashing when a custom wallet address …
> Include various fixes to Safe Control

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureClaimButton/ExpenditureClaimButton.tsx
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditurePayouts/ExpenditurePayouts.tsx
- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/redux/sagas/expenditures/claimExpenditure.ts
- src/redux/types/actions/expenditures.ts
This PR brings in the necessary changes to store expenditure payout claimed status in the DB.
- Create an expenditure with 2 slots, one with no claim delay, the other with an arbitrary claim delay.
- Progress the expenditure to finalization. Both slots should have claimed status of "No".
- Click on the claim button. If the second slot claim delay is far enough in the future, only the first slot would be claimed. 
- See that the claimed status changed to "Yes". You should also be unable to claim the same slot again.
Resolves #982
> Cache expenditure payout claimed status

- src/components/common/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
Added improvements to one of the upgraded colony version banners.
A long time ago, Juliana correctly pointed out that the upgrade colony version banner comes back after a refresh even if you dismiss it, which is bad UX. This PR should remedy that.
To test the banner, just invert the `canUpgrade` in line 103 of `ColonyUpgrade`, click the `Dismiss` button, and reload the page to check if the banner reappears.
Resolves #372
> Improve upgrade banner dismissal

- lib/pinata/PinataCache.ts
This pr checks `caches` for `undefined` in the event the app is being run in an insecure context.
This resolves an error when building for production.
> Fix: `caches` undefined

- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- tailwind.config.js
Subtracting header height from content, to always take full screen height.
https://tw.auroracreation.com/app/tasks/15602047
> fix: changed sidebar height on mobile

- package.json
- src/workers/firebase-messaging-sw.ts
- tsconfig.base.json
- webpack.base.js
- webpack.dev.js
This PR adds the firebase notification messaging web worker to the project
https://firebase.google.com/docs/cloud-messaging/js/receive
It is built using [workbox](https://developer.chrome.com/docs/workbox/) by Chrome team as I could not get any other method of building it to work. 
Currently it is setup to get the data from the firebase message and create a notification using it.
To test go to the `useNotifications` PR and send a notification while the app is in the background. A notification with the colony logo should appear.
- A workers folder in `src` where we can but any future web workers
- The firebase web worker 
Resolves #1138
> Add notifications web worker

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Expenditures/ExpenditureDetailsPage/ExpenditureDetailsPage.tsx
- src/components/common/Expenditures/ExpenditureForm/CreateExpenditure/AdvancedPaymentForm.tsx
- src/components/common/Expenditures/ExpenditureForm/CreateExpenditure/StreamingPaymentForm.tsx
- src/components/common/Expenditures/ExpenditureForm/EditExpenditure/EditExpenditureForm.tsx
- src/components/common/Expenditures/ExpenditureForm/helpers.ts
- src/components/common/Expenditures/Expenditures.tsx
- src/components/common/Expenditures/ExpendituresPage/ExpendituresList.tsx
- src/components/common/Expenditures/ExpendituresPage/ExpendituresPage.module.css
- src/components/common/Expenditures/ExpendituresPage/ExpendituresPage.module.css.d.ts
- src/components/common/Expenditures/ExpendituresPage/ExpendituresPage.tsx
- src/components/common/Expenditures/StakedExpenditure/CancelStakedExpenditureButton/CancelStakedExpenditureDialog/CancelStakedExpenditureDialog.tsx
- src/components/common/Expenditures/StreamingPaymentDetailsPage/StreamingPaymentDetailsPage.module.css
- src/components/common/Expenditures/StreamingPaymentDetailsPage/StreamingPaymentDetailsPage.tsx
- src/components/common/Expenditures/StreamingPaymentDetailsPage/StreamingPaymentPayouts/StreamingPaymentPayouts.tsx
- src/components/common/Expenditures/StreamingPaymentDetailsPage/StreamingPaymentPayouts/index.ts
- src/components/common/Expenditures/StreamingPaymentDetailsPage/index.ts
- src/graphql/fragments/expenditures.graphql
- src/graphql/generated.ts
- src/graphql/queries/expenditures.graphql
- src/redux/sagas/expenditures/createStreamingPayment.ts
- src/redux/sagas/utils/expenditures.ts
- src/redux/types/actions/expenditures.ts
- src/types/graphql.ts
- src/utils/expenditures.ts
This PR adds a streaming payment details page which shows all the data we store in the DB:
You should get redirected to the streaming payment details page after creating a streaming payment.
Resolves #1106
> Streaming payment details UI

- amplify/backend/function/createPrivateBetaInvite/createPrivateBetaInvite-cloudformation-template.json
QA is broken because we are trying to provision a lambda url via cloudformation but the aws amplify user doesnt have this permission. 
The commit that adds this is reverted until this permission is added
> Hot fix for broken QA env

- src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
Fixed error that occurred while loading motion - motionStakes were undefined and we couldn't get the data from it.
> fix: update motion state enum value logic

- amplify/backend/api/colonycdapp/schema.graphql
- src/graphql/fragments/user.graphql
- src/graphql/queries/user.graphql
This PR adds the notification types and models to the amplify schema including the notification settings.
These models will undoubtably change as the feature develops but this PR gives a solid baseline to work from.
Resolves #1124
> Add notifications to schema

- src/components/v5/common/AvatarUploader/hooks.tsx
- src/components/v5/common/CreateColonyWizard/CreateColonyCardRow.tsx
This PR is a hot fix for the current inability to create a colony. 
It was breaking due to a rebase failing to completely remove the `AvatarUploaders` dependency on the user context.
Until the whole beta create colony flow is finished it is important to remember that you will need to run the `temp-create-colony` script in the scripts folder for the new beta flow to work as we are currently not creating a user before the colony and a user is now a hard requirement in the creation of a colony due to associating said user with beta invite codes
> Hot fix for the inability to create colony

- amplify/backend/api/colonycdapp/schema.graphql
- amplify/backend/backend-config.json
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/frame/Extensions/pages/partials/ActiveInstalls.tsx
- src/constants/index.ts
- src/graphql/generated.ts
- src/graphql/queries/extensions.graphql
- src/hooks/useActiveInstalls.ts
This PR enables the storing of global extension installation information in the db, so users can see how many times an extension has been installed on the chain.
* Add `ExtensionInstallationsCount` to schema
Block ingestor: https://github.com/JoinColony/block-ingestor/pull/141
Resolves #1134
> Change active installs to use db 

- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/components/frame/Extensions/layouts/MainLayout.tsx
- src/components/frame/Extensions/layouts/SharedLayout.tsx
- src/components/frame/Extensions/layouts/index.ts
- src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/ColonySwitcherContent.tsx
- src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/types.ts
- src/components/frame/Extensions/layouts/partials/UserNavigationWrapper.tsx
- src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/UserNavigationWrapper.tsx
- src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/index.ts
- src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/types.ts
- src/components/frame/Extensions/layouts/types.ts
- src/context/PageHeadingContext/PageHeadingContext.tsx
- src/context/PageHeadingContext/hooks.ts
- src/context/PageHeadingContext/index.ts
- src/context/index.ts
- src/hooks/index.ts
- src/routes/ColonyMembersRoute.tsx
- src/routes/ColonyRoute.tsx
- src/routes/MainRoute.tsx
- src/routes/RootRoute.tsx
In short: `useColonyContext` can only be used in a route that is a child of `ColonyRoute`.
I made a few changes to existing components, but tried to keep the general style. The main change is that `SharedRoute` is now `MainRoute` again and `ColonyRoute` has the `ColonyContext`.
This introduces a little bit of code duplication but that can be improved further down the line. It is late.
There will be a follow up to this as we need a more flexible sidebar component (e.g. for the create user and create colony wizards). I suggest just passing in a component instead of all of these props.
@joanna-pagepro, please give this a review and let me know if you're ok with it.
> Factor out the ColonyContext again

- src/components/v5/shared/Button/CloseButton.module.css
- src/components/v5/shared/CalamityBanner/CalamityBanner.tsx
- src/components/v5/shared/CalamityBanner/partials/CalamityBannerContent.tsx
This small PR adds styling updates to the Calamity banner in order to better align it with the design updates and to resolve padding issues.
To test, you will need to force the banner to appear, testing both the `info` and `error` mode.
Resolves #1264
> Updates to calamity banner design

- src/redux/sagas/colony/colonyCreate.ts
When creating a colony OneTxPayment wasn't being given the Arbitration permissions
> Fix: Missing OneTx permissions in colonyCreate saga

- amplify/backend/function/fetchColonyBalances/src/index.js
- amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js
- amplify/backend/function/fetchExpenditureBalances/src/index.js
- amplify/backend/function/fetchMotionState/src/utils.js
- amplify/backend/function/fetchMotionTimeoutPeriods/src/index.js
- amplify/backend/function/fetchTokenFromChain/src/utils.js
- amplify/backend/function/fetchVoterRewards/src/utils.js
- amplify/backend/function/getMembersForColony/src/index.js
- amplify/backend/function/getReputationForTopDomains/src/index.js
- amplify/backend/function/getSafeTransactionStatus/src/index.js
- amplify/backend/function/getUserReputation/src/index.js
- amplify/backend/function/getUserTokenBalance/src/index.js
- amplify/backend/function/updateContributorsWithReputation/src/index.js
- docker/colony-cdapp-dev-env-amplify
- docker/colony-cdapp-dev-env-orchestration-all.yaml
- docker/colony-cdapp-dev-env-orchestration.yaml
- docker/files/block-ingestor/env.base
- package.json
This PR improves the compatibility of our docker setup with newer docker versions and tools like podman which in turn enables us to run our setup as non-root users in Linux.
Most importantly the `links` entries were removed from the docker-compose files which is an option that's [long deprecated](https://docs.docker.com/network/links/) and not necessary anymore. 
-----
To use with `podman` if you like (rootless, on Linux - **DO NOT DO THIS IF YOU'RE ON A MAC OR WINDOWS**):
- Remove docker from your system :scream: 
- We need `podman` in version 4.7.x to support the `docker compose` command
- Use either `docker-compose` (standalone, without docker) or `podman-compose` (untested)
- Make sure you have the podman [`dnsname`](https://github.com/containers/dnsname/blob/main/README_PODMAN.md) …
> Improve docker compatibility

- src/components/frame/v5/pages/VerifiedPage/partials/VerifiedTable/VerifiedTable.tsx
Task: https://tw.auroracreation.com/app/tasks/15661600
This task is already resolved on master branch, but I realised that, the top border radius is incorrect.
**Changes** 🏗
before:
after:
> Fix[15661600]: border radius for verified members table

- src/components/frame/Extensions/layouts/hooks.tsx
- src/components/v5/frame/NavigationSidebar/consts.ts
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarThirdLevel/NavigationSidebarThirdLevel.tsx
https://tw.auroracreation.com/app/tasks/15661128
The functionality to show related actions on the second level menu open was added in https://github.com/JoinColony/colonyCDapp/pull/1312
> feat: finances related actions

- .github/workflows/scripts/on-demand-env-script.sh
Enable on demand log streaming to cloudwatch logs and send notification to discord with link to logs.
**Changes** 🏗
> cicd: Enable on-demand dev environments log streaming to cloudwatch logs

- src/components/shared/Icon/Icon.tsx
- src/components/v5/common/Filter/partials/FilterOptions.tsx
- src/components/v5/shared/SubNavigationItem/SubNavigationItem.tsx
- src/components/v5/shared/SubNavigationItem/types.ts
Task: https://tw.auroracreation.com/app/tasks/15661610
**Changes** 🏗
before:
after:
> Fix[15661610]: change icon size for filter items

- src/routes/Routes.tsx
- src/routes/routeConstants.ts
This PR introduces a route that will render the "old" (v4) colony home dashboard since the new UI will now take over the default route.
Once we're done with the new UI and everything is wired up in the correct way, we can remove it
> Introduce OLD colony dashboard route

- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/StakingStep.tsx
- src/components/v5/common/Fields/RadioButtons/ButtonRadioButtons/ButtonRadioButtons.tsx
- I noticed that radio buttons aren't disabled when I create a motion, and I don't have enough reputation. It turned out that the 'disabled' state in the component wasn't being passed on. Now it's fixed.
> Fix: forwarding the disabled status for radio buttons

- src/components/common/Extensions/UserNavigation/hooks.ts
- src/graphql/generated.ts
- src/graphql/queries/transactions.graphql
- src/redux/sagas/transactions/transactionsToDb.ts
This PR is two-parter:
- First, fix UserHub transaction persistence
- Second, prevent messages from showing up in the UserHub transactions list
**UserHub Transaction Persistence**
This was implemented using a wrong spec, as it tried to only load transactions based on the currently selected colony, which should not be case.
I refactored this to fetch all transactions from the database that were initiated by this user.
**Prevent messages from showing up in UserHub**
Messages should not show up (at least for now) in the transactions list. So I refactored the hook to use the `transactionsGroup` selector vs. the original `transactionsAndMessagesGroup`. 
This was both a UI issue, as the messages that showed up in the list were unstyled, and both a logic one, as the mutation would try to save …
> Fix Message Signing, User Transaction Persistance

- src/redux/sagas/motions/expenditures/fundExpenditureMotion.ts
- src/redux/sagas/utils/proofs.ts
Exactly as it says on the tin, this PR fixes two instances of the `getPermissionProofs` call, which didn't pass in the first argument (network client)
Because of this, both the `TransferFundsBetweenPots` and `FundExpenditureMotion` transactions would fail.
Checked all the other instances and everything seems to be correct, so I have no idea how these slipped between the cracks.
> Fix sagas with incorrect getPermissionProofs calls

- amplify/backend/backend-config.json
- amplify/backend/function/createPrivateBetaInvite/createPrivateBetaInvite-cloudformation-template.json
- amplify/backend/function/createPrivateBetaInvite/function-parameters.json
This PR adds the function url to the `createPrivateBeta` lambda and fixes a bug with the lambda that stopped it from being able to access the AWS Param store to correctly set the environment variables it needed.
A new `parameter` has been added to the lambda Parameters:
```json
"CreateLambdaUrl": {
"Type": "String",
"AllowedValues": [
"true",
"false"
],
"Default": "false",
"Description": "Specifies whether to create the Lambda function URL"
}
```
in order to control the condition on wherever the lambda url is created or not.
This condition is by default false and only needs to be run once. It mainly serves as documentation in code that this function url is required.
The bug fixes which have added the required layers to the lambda in order for it to gain access to the AWS param store are …
> Add function url to createPrivateBeta lambda

- amplify/backend/function/getTotalMemberCount/getTotalMemberCount-cloudformation-template.json
- Appsync api id changed as a consequence of redeploying the cdapp amplify stack a while back.
**Changes** 🏗
> fix: update appsync api id with correct value

- src/components/v5/shared/Modal/ModalBase.tsx
Our base modal component had a lighter background than it is in the designs.
This PR addresses that.
**Changes** 🏗
* Colour of the modal overlay aligned
Resolves  #1255
> fix: align modal background colour

- src/components/common/Extensions/SpecificSidePanel/hooks.tsx
- src/components/common/Extensions/SpecificSidePanel/types.ts
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/common/Extensions/UserNavigation/partials/HeaderAvatar/HeaderAvatar.tsx
- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/UserProfilePageForm.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/shared/UserAvatar/UserAvatar.tsx
- src/components/v5/shared/UserAvatar/types.ts
- src/components/v5/shared/UserAvatarDetails/UserAvatarDetails.tsx
- src/components/v5/shared/UserAvatarDetails/types.ts
- src/components/v5/shared/UserAvatarPopover/UserAvatarPopover.tsx
- src/stories/common/UserNavigation.stories.tsx
- src/stories/shared/UserAvatar.stories.tsx
- src/stories/shared/UserAvatarPopover.stories.tsx
- src/stories/shared/UserInfoList.stories.tsx
- src/stories/shared/UserInfoSectionList.stories.tsx
On my journey through the dapp I noticed that the UserAvatar would show a new blockie on every reload. That's not cool, so I fixed it.
Also I think I improved the UserAvatar in a way that it takes some of the mental load off the developers. The experience should be pretty consistent now, basically pass in a user object or a wallet address as string as the `user` prop. Then `showUsername` will do the right thing.
Mind that `user` is a _required_ prop now. I would argue if we don't have a wallet connected, we shouldn't render this component in any case.
@joanna-pagepro can you maybe make sure that I didn't break any of the stories?
> Fix UserAvatar showing alternating blockies

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
https://tw.auroracreation.com/app/tasks/15629368
Fixed action sidebar disabled scroll when there is too much content:
> fix: removed overflow-hidden on mobile when isMotion

- codegen.js
- scripts/dev.sh
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/NotEnoughTokensInfo/NotEnoughTokensInfo.tsx
When clicking on the activate link, the modal should open:
https://github.com/JoinColony/colonyCDapp/assets/112586815/63974122-4180-4f2b-a5d0-09c994c378aa
This PR also removes codegen starting automatically and running in a loop.
Resolves #1364
> Activate tokens link should open the Activate tokens modal

- amplify/backend/custom/lambdaParams/lambdaParams-cloudformation-template.json
- Update rpc url to https due to security changes on the webserver not allowing http anymore.
**Changes** 🏗
> fix: add https to rpc url

- amplify/backend/function/validateUserInvite/src/index.js
Colony contributor's can come into existence in multiple ways not just via this lambda
This PR does not make the lambda error on existence
> Don't create contributor if already in existence

- src/components/v5/common/Fields/Input/Input.tsx
- src/components/v5/shared/FormError/FormError.tsx
- src/components/v5/shared/FormError/types.ts
This PR fixes the broken form error display in #1415 by allowing in some cases the original design of layout shifting to occur on error:
Resolves #1415
> Fix broken form error display

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/shared/MeatBallMenu/MeatBallMenu.tsx
Quick PR to fix a couple of small issues introduced in this PR https://github.com/JoinColony/colonyCDapp/pull/1406 and this PR https://github.com/JoinColony/colonyCDapp/pull/1384.
- Fixes alignment of text in action metadata.
- Removes unnecessary icon string.
**Before**
**After**
> Fixes Action metadata alignment and unneeded icon string

- src/components/frame/v5/pages/ColonyPreviewPage/ColonyPreviewPage.tsx
- src/components/v5/shared/SocialLinks/SocialLinks.tsx
This PR fixes the display of social links on mobile. When there are no labels (like on the colony beta splash page - "request access"), the icons are no longer stacked on mobile.
> fix: social links on mobile

- src/components/frame/Extensions/layouts/MainLayout.tsx
- src/components/frame/LandingPage/LandingPage.tsx
- src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
- src/components/v5/frame/PageLayout/partials/PageHeading/PageHeading.tsx
- src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx
- src/components/v5/shared/Breadcrumbs/BreadcrumbsCardSelect.tsx
- src/components/v5/shared/Breadcrumbs/types.ts
- src/components/v5/shared/SimpleSidebar/SimpleSidebar.tsx
- src/components/v5/shared/SimpleSidebar/index.ts
- src/context/AppContext.tsx
- src/routes/LandingPageRoute/LandingPageRoute.tsx
I've updated the page headers to allow the breadcrumbs to show without the need for a title, which is the case for the landing page. The changes introduced should be specifically for this, but they are made in general components so make sure to test the breadcrumbs and titles of other pages in order to check that they haven't changed with this.
Resolves #1412
> Add missing colony logo and breadcrumb to landing page

- amplify/backend/function/createUniqueUser/src/index.js
- src/components/common/Onboarding/wizardSteps/CreateColony/StepConfirmTransactions.tsx
- src/components/common/UserProfileEdit/UserAdvancedSettings.tsx
- src/components/common/UserProfileEdit/UserAvatarUploader.tsx
- src/components/common/UserProfileEdit/UserMainSettings.tsx
- src/components/frame/v5/pages/UserAdvancedPage/partials/FeesForm/FeesForm.tsx
- src/components/frame/v5/pages/UserAdvancedPage/partials/FeesForm/hooks.tsx
- src/components/frame/v5/pages/UserAdvancedPage/partials/RpcForm/RpcForm.tsx
- src/components/frame/v5/pages/UserPreferencesPage/hooks.tsx
- src/components/frame/v5/pages/UserProfilePage/hooks.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/UserProfilePageForm.tsx
- src/components/v5/common/Fields/Switch/FormSwitch.tsx
- src/components/v5/common/Fields/Switch/types.ts
- src/components/v5/common/SettingsRow/SettingsRow.tsx
- src/components/v5/common/SettingsRow/types.ts
- src/context/AppContext.tsx
- src/hooks/useColonySubscription.ts
- src/redux/types/actions/index.ts
With this PR, whenever you create a user, either via the script or manually, it should have meta transactions already enabled by default.
Also, the toggle in the advance settings page should work as expected, and change your settings. You can check this by refreshing the page after toggling it off or on, and by querying the value through amplify's playground.
[screenity (6).webm](https://github.com/JoinColony/colonyCDapp/assets/18473896/7313e175-78b2-4e21-abad-773b9e6a9c72)
Resolves #1422
> Fix metatransaction toggle

- src/components/frame/Extensions/layouts/hooks.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarSecondLevel/NavigationSidebarSecondLevel.tsx
- src/styles/main.global.css
This PR uses the colony values for the colonyName and description in the Navigation Sidebar
Resolves #1474
> Use dynamic colony name and description in sidebar

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
With this PR, if the action is executed by an extension and that extension doesn't have all the required permissions, it should show a banner warning the user. For the actions that we currently have, this could apply to simple payment and any motions, for example.
Resolves #1092
> Add missing permission banner to action form

- src/components/frame/Extensions/layouts/ColonyLayout.tsx
In order to roll out access to the UI more consistently, we would like to hide the self serve "Invite members" button from the UI.
This PR is intended to do just that.
> Hide invite members button initially

- Dockerfile
This quick PR correctly includes the newly added env variable into the docker build for Webpack for GTM.
> Fix GTM ID being set during build

- src/components/frame/v5/pages/UserPreferencesPage/UserPreferencesPage.tsx
- src/components/frame/v5/pages/UserPreferencesPage/hooks.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/LeftColumn.tsx
- src/components/frame/v5/pages/UserProfilePage/types.ts
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/constants/index.ts
This PR stores a user's action panel display preferences in local storage, so they can be retrieved by the component whenever it is rendered. 
1. Toggle the display preference in user preferences. It should persist even when reloading.
2. Open the actions panel, either by adding `?tx={tx_hash}` to the url or directly via the ui. It should open to the width stored in your preferences.
* Display preferences toggle 
**Changes** 🏗
* If present, use display preference value from local storage for action panel width
Resolves #1168
> Store display preferences in local storage

- src/components/common/ColonyHome/ColonyHome.tsx
- src/components/v5/common/WidgetBox/WidgetBox.tsx
- src/components/v5/common/WidgetBox/types.ts
Now when you filter by teams in the dashboard, the 3 top widgets should also take you to their related pages with the filter you applied beforehand.
Resolves #1416
> Add team filtering to widget boxes on colony home

- src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/TableWithMeatballMenu/TableWithMeatballMenu.tsx
Changed the icon so it fits the designs, also had to use a different popup.
Our table rows had `scale(1)` which brought them to the very forefront of our app, thus displaying over the popup.
The hack was introduced due to Safari not handling `position: relative` on table rows, but I think we shouldn't be relying on those, our popups are mostly on single cells or components in there.
**Changes** 🏗
* new icon and tooltip for the native token popup
* removed the scale transform on the entire table row
Resolves #1523
> fix: native token in table popup

- src/components/frame/Extensions/pages/ColonyDetailsPage/ColonyDetailsPage.tsx
- src/components/v5/common/ColonyDashboardHeader/ColonyDashboardHeader.tsx
- src/components/v5/common/NativeTokenPill/NativeTokenPill.tsx
- src/components/v5/common/NativeTokenPill/index.ts
Fix styles according to the issue.
Added a new native token pill so we can reuse it between the details page and the dashboard header.
* `NativeTokenPill` component which displays a tooltip 
**Changes** 🏗
* Use the new component instead of doing it twice
Resolves  #1389
> fix: colony details styles, new native token pill

- src/components/frame/Extensions/pages/ExtensionDetailsPage/ParamDetailsTab.tsx
https://tw.auroracreation.com/app/tasks/15705120
**Changes** 🏗
* Filtering out params that are not available in `paramsMap` const.
Resolves [#1554](https://github.com/JoinColony/colonyCDapp/issues/1554)
> fix: filtering out params that are unavailable

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/types.ts
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
https://tw.auroracreation.com/app/tasks/15701850
**Changes** 🏗
* Pending and complete buttons now open transactions tab in user hub but default tab is balance
> fix: pending and complete buttons now open transactions tab in user hub

- src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
- src/components/shared/TokenInfoPopover/TokenInfo.tsx
https://tw.auroracreation.com/app/tasks/15695351
Changes:
- Add missing info in token popover on Balance page
Resolves:
https://github.com/JoinColony/colonyCDapp/issues/1562
> fix: 15695351 - add missing info in token popover

- docker/colony-cdapp-dev-env-block-ingestor
This PR updates the ingestor hash to include changes from [block-ingestor#153](https://github.com/JoinColony/block-ingestor/pull/153). Without those changes, a `ColonyContributor` entry is created for metacolony which doesn't exist in the database, causing the `getContributorsByAddress` query to fail.
> block-ingestor update: Fix `getContributorsByAddress` query

- src/components/frame/v5/pages/ActivityPage/ActivityPage.tsx
- src/components/v5/common/TableWithActionsHeader/TableWithActionsHeader.tsx
This PR addresses the colony pages (Any page other than the dashboard, landing page, profile, and onboarding pages) having different spacing between the content and the header. As far as I know, I've only observed this was the case for the incoming funds page, which had an extra padding between the subtitle and the header. Let me know if you guys find that I've missed a place in any of the other colony pages.
Basically, all pages that are accessible through the navigation of a colony, should have a gap of ONLY `32px` between the header and the start of the content.
Resolves #1507
> Fix content alignment on colony pages

- src/components/common/Extensions/UserHub/partials/StakesTab/helpers.ts
- src/components/common/Extensions/UserHub/partials/StakesTab/partials/ClaimAllButton.tsx
- src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakeItem.tsx
- src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakesList.tsx
- src/components/common/Extensions/UserHub/partials/StakesTab/types.ts
- src/components/common/Extensions/UserHub/partials/StakesTab/useStakesByFilterType.ts
- src/graphql/fragments/stake.graphql
- src/graphql/generated.ts
- src/redux/sagas/motions/rootMotion.ts
- src/types/index.ts
This PR wires the action title and metadata with stakes shown in the User Hub:
Resolves #1575
> Wire action title and metadata with User Hub stakes tab

- src/components/common/ColonyHome/hooks.ts
- src/components/frame/Extensions/pages/ColonyDetailsPage/ColonyDetailsPage.tsx
- src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
- src/components/v5/common/ColonyDashboardHeader/ColonyDashboardHeader.tsx
- src/components/v5/common/ColonyDashboardHeader/types.ts
- src/components/v5/common/NativeTokenPill/NativeTokenPill.tsx
Display the token info popover by clicking on the text of `NativeTokenPill`.
Also align the balance table token name turning blue when popup is showing.
Resolves #1383
> feat: add token info popover for native token pill

- src/hooks/useToggle/index.ts
https://tw.auroracreation.com/app/tasks/15637174
This change fixes the issue when selecting the text inside of  `container` element and releasing the mouse outside of it would trigger outside click detection.
This was mostly an issue in action sidebar as seen here:
After changes:
https://github.com/JoinColony/colonyCDapp/assets/38806520/b2682a31-c5c6-4def-8e4d-198b638d7894
> Changed useToggle event type form click to mousedown

- docker/files/auth/env.base
This change fixes the action metadata and annotation mutations hanging indefinitely in the auth-proxy.
> Fix: auth-proxy block time set in wrong units

- src/components/v5/shared/SearchSelect/SearchSelect.tsx
https://tw.auroracreation.com/app/tasks/15639549
Description:
sometimes when I remove a search phrase, not all items are returned. Note the example with 'root'.
https://jam.dev/c/59874007-5e5e-410e-a903-77264aadcfc6
Changes: 
-fixed returning correct data in dropdown list when value in search changes
> fix: 15639549 - searching in dropdown

- package.json
- src/cache/colony/tokens.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/SocialLinksTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/partials/SocialLinkModal/SocialLinkModal.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/partials/SocialLinkModal/consts.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/partials/SocialLinkModal/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/partials/SocialLinkModal/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/utils.tsx
- src/components/v5/common/Fields/RadioButtons/TileRadioButtons/TileRadioButtons.tsx
- src/context/apolloClient.ts
- src/utils/yup/tests/index.ts
This PR fixes editing of social links.
The issue was that we used `linkType` and `url` as the values, which wasn't the case anymore.
Also fixed a minor CSS alignment on the links modal.
I updated our version of apollo, so we could strip `__typename` on the mutation and so that the `haveExternalLinksChanged` flag isn't always true when editing details. 
**Changes** 🏗
* renamed the attributes accordingly
* updated apollo client version
Resolves  #1522
> fix: use name and link instead of linkType and url for external links

- docker/colony-cdapp-dev-env-block-ingestor
This PR updates block-ingestor hash to a commit which increases max retries for the colony metadata query in `ColonyAdded` handler. Without it, the create data script tends to fail intermittently.
> block-ingestor update: increase colony metadata query max retries

- src/components/frame/Extensions/layouts/hooks.tsx
- src/components/shared/FeedbackButton/FeedbackButton.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationFeedbackWidget/NavigationFeedbackWidget.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarButton/NavigationSidebarButton.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarButton/types.ts
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarMainMenu/NavigationSidebarMainMenu.tsx
- Added highlighted state to "Create action" button.
- Removed the highlighted state styles from `Feedback button` and added normal nav button styles.
- Changed colors on the navigation feedback section
- Updated height of navigation buttons to `38px`
Resolves #1563
> Update navigation buttons styles

- src/index.ts
Fixed CDapp crash when custom yup methods aren't available fast enough for components. This was caused due to the recent changes to the import/order.
Also fixed global styles overwriting the custom styles of some components like buttons.
> Fix crash due to custom yup methods

- amplify/backend/api/colonycdapp/schema.graphql
- src/graphql/generated.ts
- src/hooks/index.ts
- src/hooks/useCurrency.ts
- src/utils/currency/config.ts
- src/utils/currency/currency.ts
- src/utils/currency/types.ts
- src/utils/currency/utils.ts
This PR adds a utility for performing conversions from a given token to a given currency.
It will be used around the app to show, for example, the value of a user's balances in USD (or whatever currency they select).
It's using the [CoinGecko](https://www.coingecko.com/api/documentation) api, which does not require an api key, allows 30 calls/minute from the client, is free and supports multichain. 
It does [require attribution](https://www.coingecko.com/en/branding) though, so thoughts on where/how to add that are welcome. @arrenv 
I've made it clear in the code what does and does not make assumptions about the specific api being used, which should make code easier to change if the api gets changed.
Mainly code review. If you want, test with #1594 by calling `useCurrency` inside …
> Add currency conversion util

- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
https://tw.auroracreation.com/app/tasks/15701598
Adds a fallback for activity feed/transaction item titles.
Before
After
> Fallback to action metadata description when cutom title is empty

- .env.example
- src/components/common/ColonyHome/ColonyHome.tsx
- src/components/common/ColonyHome/hooks.ts
- src/components/common/ColonyHome/types.ts
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
- src/components/shared/CurrencyConversion/CurrencyConversion.tsx
- src/components/shared/CurrencyConversion/index.ts
- src/context/CurrencyContext.tsx
- src/hooks/useCurrency.ts
- src/utils/currency/config.ts
- src/utils/currency/currency.ts
- src/utils/currency/index.ts
- src/utils/currency/memo.ts
This PR wires in the currency conversion util in all places it's needed in the app.
Using coingecko's free api key ensures you get a stable rate limit of 30 calls/minute. Create a [demo account](https://www.coingecko.com/) to get your own or add mine to your `.env` file: `CG-d4y9hVCNMRU53fFfmV7AiyKr`
Production may need higher call / rate limits (see https://www.coingecko.com/en/api/pricing). We can also use a different api if desired, we're not at all wedded to coingecko (it was just easiest for proof of concept).
You should see the total funds conversion on ColonyHome, as well as conversions on the balances page. It's a bit tricky to test locally because it's searching for token addresses on gnosis chain, but you can mock a balance that has the same address as a token on gnosis chain …
> Wire currency conversion util

- src/components/frame/Extensions/pages/ColonyDetailsPage/ColonyDetailsPage.tsx
- src/hooks/useCurrency.ts
- src/utils/currency/currency.ts
- src/utils/currency/types.ts
Both primary buttons on the Colony detail page have been updated to match the button size as per the figma design.
**Changes** 🏗
* Added size small prop to buttons
Resolves #1638
> Fix: Colony detail button regression

- src/styles/main.global.css
This PR removes the 8px top padding for the tab component globally.
Tabs found in members page, profile and extensions now have this top padding removed
**Changes** 🏗
Changed 'py-2' to 'pb-2 pt-0' in the main.global.css file 
Resolves #1634
> Fix: Remove tab component top padding

- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/common/Extensions/UserNavigation/UserNavigation.tsx
- src/components/v5/shared/Button/Hamburger.tsx
User header hover state has been changed from border-gray-900 to border-blue-400.
Border colour now stays blue whilst menu is visible.
Padding between username and reputation star changed from 12px to 8px.
Hamburger menu icon now stays blue whilst menu is visible.
**Changes** 🏗
* Added hover:!border-blue-400 to override existing tertiary button style on hover
* Removed 'isMobile' from className check so that border stays blue when the menu is open on desktop as well as mobile
*  Changed outer div from gap-3 to gap-2 to fix padding size
* Removed 'isMobile' from 'isOpened' check on Hamburger element
* Removed border hover state from Hamburger is menu is open to ensure it remains solid blue when open
Hover state border colour changed
Active state border colour changed
Hamburger icon active …
> Fix: User header hover state and padding

- src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/ColonySwitcherContent.tsx
- src/components/v5/common/Filter/partials/SearchInput/SearchInput.module.css
- src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
Added clear functionality to Colony Switcher and Members file search inputs.
* Added clear functionality to Colony Switcher search input by passing a value to the 'value' property which ensures the clear button prefix is shown when there is a value
* Added clear functionality to Members filter search input. This input is slightly different as it has a search submit button that only appears on mobile when the input has a value. The clear button has been added and positioned appropriately on mobile to accommodate the submit button.
All action sidebar search inputs already have the clear functionality, so does the filter on the incoming funds page. Please let me know if there are any search inputs that have been missed.
Colony Switcher search input
Members filter search input …
> Feat: Add clear functionality to all search inputs

- src/hooks/members/useMemberFilters.ts
Fixed members without rep or roles disappearing from the `All members` tab. Now they should appear when you are not filtering by a team. The rest of the filters should work as expected (Tested various combinations, let me know if you find any that is not working as expected and I'll fix it in this PR)
Resolves #1583
> Tweak member page filtering

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/workflows/chromatic.yml
This PR is intended to resolve the Chromatic Github Actions workflow failing continually.
Chromatic is still failing due to Storybook component issues, this is a feature, which I think we should use. However, for now, I have added the flag `exitOnceUploaded` to prevent it from failing the build until we can remove the Storybook components.
I have tested locally using ACT to simulate Github actions - https://github.com/nektos/act
You can see the successful build here - https://github.com/JoinColony/colonyCDapp/actions/runs/7504573403/job/20431926449
I have also taken the opportunity to add Github issue templates, pretty much copied from the Dapp repo.
> Fixes Chromatic build workflow and adds issue templates for Github

- src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
- src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
Added hover state to token title on balance page.
Added pop over to token title on incoming funds page - opens in portal on desktop and modal on mobile.
* Added group to token title button so when token icon or name is hovered, token title changes to text-blue-400
* Added portal for token pop over on desktop on incoming funds page
* Added modal for token pop over on mobile on incoming funds page
* Added active state to token title on incoming funds page
**Changes** 🏗
* On incoming funds page, converted token title / avatar div to a button to open token pop over onClick
Token title hover state on balance page
Token pop over on incoming funds page desktop
Token pop over on incoming funds page mobile
Resolves #1633
> Fix: Add interaction states to token titles

- src/components/common/Dialogs/TransferFundsDialog/helpers.ts
- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
- src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/EnterRecoveryModeForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/consts.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/hooks.ts
- src/components/v5/shared/SearchSelect/hooks.ts
- src/components/v5/shared/SearchSelect/partials/SearchItem/types.ts
- src/components/v5/shared/SearchSelect/types.ts
- src/hooks/useTeamsOptions.ts
Updated action sidebar forms to not convert domain ids to strings; instead, leave them as numbers like it is everywhere else in the codebase.
The forms should be working as they were before this change. These changes are "dev facing" only, they are made to keep the data type consistent with the rest of the CDapp.
Resolves #1426
> Update domain ids on forms to numbers

- src/components/frame/Extensions/layouts/consts.ts
This PR removes (hides) the 'About' page link which shows under the dashboard tab in the navigation menu. The about link has been commented out, so it can be reused again when needed.
**Changes** 🏗
Resolves #1688
> Hide about page link

- .eslintrc.js
- src/components/common/ColonyActionsTable/hooks.tsx
- src/components/common/ColonyHome/ColonyHome.tsx
- src/components/common/ColonyHome/partials/Members/Members.tsx
- src/components/common/ColonyHome/partials/Objective/Objective.tsx
- src/components/common/ColonyHome/partials/TotalActions/TotalActions.tsx
- src/components/common/ColonyHome/types.ts
- src/components/frame/v5/pages/ActivityPage/hooks.tsx
- src/components/frame/v5/pages/BalancePage/hooks.ts
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
- src/components/frame/v5/pages/MembersPage/hooks.ts
- src/components/shared/FriendlyName/helpers.ts
- src/context/ipfs/ipfsnode/IPFSNode.ts
- src/hooks/index.ts
- src/hooks/members/useMemberFilters.ts
- src/hooks/useActionsCount.ts
- src/hooks/useActivityFeed/helpers.ts
- src/hooks/useActivityFeed/types.ts
- src/hooks/useGetSelectedDomainFilter.tsx
- src/hooks/useTeamsBreadcrumbs.ts
https://github.com/JoinColony/colonyCDapp/assets/112586815/8bd01ca4-5a6e-48b6-9a9f-dce73663dce7
https://github.com/JoinColony/colonyCDapp/assets/112586815/95c7f85b-83c0-451b-bf19-df7525287e6c
Changes:
- Some renaming of `team` to `domain` for consistency
- `useActionsCount` - new shared hook for getting actions count
Resolves #1542
> Fix actions count not respecting selected domain filter

- src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/partials/ColonyAvatarField/ColonyAvatarField.tsx
- src/components/v5/common/AvatarUploader/partials/FileUpload.tsx
Resized the size of the icon within ColonyAvatarField to match figma spec - this changes the avatar preview image to be larger when trying to upload a new avatar icon
Upload text aligned to center to match figma
Resolves #1544
> resize upload colony avatar icon

- src/components/v5/shared/Modal/ModalBase.tsx
All modals are now positioned 155px from the top of the window - modal remains centred when screen height is short. Mobile fullscreen modals and pop overs are unaffected.
**Changes** 🏗
* Added before / after pseudo elements with a max-height of 9.688rem (155px). Changed the flex-direction to column and gave the modal content shrink-0. As the height of the window shrinks, the size of the pseudo elements shrink so that the modal remains centred. (The top pseudo will never exceed 155px height so modal will sit at 155px from the top when possible).
Fullsize desktop
Short window height
Resolves #1686
> Fix: Adjust all modals positioning on desktop

- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/partials/PermissionsTable/PermissionsTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/partials/PermissionsTable/consts.tsx
Removed `Owner` set of permissions and `Root/Recovery` when the selected domain is not ROOT.
Resolves #1655
> Remove root/recovery permissions from selection on child domain

- src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/hooks.ts
This PR fixes the validation of the manage colony objective form. The problem was that the form didn't have default/initial values for the title, description, and progress so when you submitted the form still required you to enter a value on those fields even if you didn't want to change them but that's because for the form they were empty.
I also added validation for the action title as it was missing.
Resolves #1464
> Fix validation of manage colony objective form

- src/components/common/ColonyActionsTable/hooks.tsx
https://tw.auroracreation.com/app/tasks/15695137
https://github.com/JoinColony/colonyCDapp/issues/1584
Replaced default table cell wrapper with custom one, with the same styles as the link to make cell the same size.
> fix: activity table cell height in loading state

- amplify/backend/function/createColonyEtherealMetadata/src/index.js
- amplify/backend/function/createPrivateBetaInvite/src/index.js
- amplify/backend/function/createUniqueColony/src/index.js
- amplify/backend/function/createUniqueUser/src/index.js
- amplify/backend/function/fetchColonyBalances/src/index.js
- amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js
- amplify/backend/function/fetchExpenditureBalances/src/index.js
- amplify/backend/function/fetchMotionState/src/utils.js
- amplify/backend/function/fetchMotionTimeoutPeriods/src/index.js
- amplify/backend/function/fetchTokenFromChain/src/index.js
- amplify/backend/function/fetchTokenFromChain/src/utils.js
- amplify/backend/function/fetchVoterRewards/src/utils.js
- amplify/backend/function/getSafeTransactionStatus/src/index.js
- amplify/backend/function/getSafeTransactionStatus/src/utils.js
- amplify/backend/function/getUserReputation/src/index.js
- amplify/backend/function/getUserTokenBalance/src/index.js
- amplify/backend/function/qaSSMtest/src/index.js
- amplify/backend/function/setCurrentVersion/src/index.js
- amplify/backend/function/updateContributorsWithReputation/src/index.js
- amplify/backend/function/validateUserInvite/src/index.js
This quick PR fixes a value I hard-coded during the first production deployment rush, in an effort to quickly fix the "token not found in db" issue that we were having.
The error was introduced initially by the [Safe Control](https://github.com/JoinColony/colonyCDapp/pull/705) feature which didn't account for other chains besides the bridges, in a non-dev environment.
The fix was to simply add a new default case for the `getRpcUrlParamName` util, which will default to gnosis in a `qa` or `prod` environments.
While I was at it, I also removed all references to the test `sc` environment, which no longer exists in our deployment infrastructure.
**Notes on testing**
You can't really test my fix while running this locally, as it only affects `qa` and `prod` environments which all run on the …
> Fix `fetchTokenFromChain` lambda rpc env variables

- amplify/backend/function/createUniqueColony/src/package-lock.json
- amplify/backend/function/createUniqueColony/src/package.json
- amplify/backend/function/fetchColonyBalances/src/package-lock.json
- amplify/backend/function/fetchColonyBalances/src/package.json
- amplify/backend/function/fetchExpenditureBalances/src/package-lock.json
- amplify/backend/function/fetchExpenditureBalances/src/package.json
- amplify/backend/function/fetchMotionState/src/package-lock.json
- amplify/backend/function/fetchMotionState/src/package.json
- amplify/backend/function/fetchMotionTimeoutPeriods/src/index.js
- amplify/backend/function/fetchMotionTimeoutPeriods/src/package-lock.json
- amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
- amplify/backend/function/fetchVoterRewards/src/package-lock.json
- amplify/backend/function/fetchVoterRewards/src/package.json
- amplify/backend/function/getUserReputation/src/package-lock.json
- amplify/backend/function/getUserReputation/src/package.json
- amplify/backend/function/getUserTokenBalance/src/package-lock.json
- amplify/backend/function/getUserTokenBalance/src/package.json
- amplify/backend/function/qaSSMtest/src/package-lock.json
- amplify/backend/function/qaSSMtest/src/package.json
- amplify/backend/function/updateContributorsWithReputation/src/package-lock.json
- amplify/backend/function/updateContributorsWithReputation/src/package.json
- package.json
Currently, once creating a motion, a spinner will show up next to the staking tab, signifying that it can't load the timeout until the staking is finished.
This is because the `fetMotionTimeoutPeriods` lambda breaks, and returns all values as `-1` which triggers a infinite loading state in the component.
The issue at fault here is that the call to `getBlockTime` has the params inversed _(`blockHash` and `provider` vs. `provider` and `blockHash`)_
This issue fixes this, making motions work once again.
~~Note that if you try to create a motion with a description _(annotation)_, it will still crash, but that is a separate issue, that was highlighted here: https://discord.com/channels/562263648173555742/998629903740182580/1198967494564646932~~
While I was at it, I also fixed the above issue, …
> Fix motion timeouts query data

- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/context/CurrencyContext.tsx
In the public version of the app, users should be able to switch currencies without having a wallet connected. Previously, when no wallet was connected, the currency switcher did not function properly. This PR makes changes to the CurrencyContext so that the preferred currency can be set even when no wallet is connected. This is saved to local storage to persist the selection and will fallback to the defaultCurrency if nothing is found in local storage. Once a wallet is connected, user.profile.preferredCurrency will take priority over the selection in local storage.
However, whilst the app is in beta, the currency switcher should be hidden unless a wallet is connected as users need a connected wallet in order to access a colony. This PR hides the currency switcher when no wallet is …
> Fix: disconnected wallet currency conversion

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
- src/components/v5/frame/NavigationSidebar/NavigationSidebar.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarContext/NavigationSidebarContext.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarContext/types.ts
- src/components/v5/frame/NavigationSidebar/types.ts
- src/components/v5/shared/Modal/Modal.tsx
https://tw.auroracreation.com/app/tasks/15637182
https://tw.auroracreation.com/app/tasks/15637067
https://tw.auroracreation.com/app/tasks/15665111
https://tw.auroracreation.com/app/tasks/15692685
**Changes** 🏗
* Changed cancel button border color
* Navigation sidebar 3rd level now `remembers` close/open state
* Sizes in amount field
* Title change in transfer funds form from `recipient` to `to`
Resolves [#1643](https://github.com/JoinColony/colonyCDapp/issues/1643) and [1642](https://github.com/JoinColony/colonyCDapp/issues/1642)
> fix: cancel button color, nav 3rd lvl, amount sizes

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/CancelTransaction.tsx
- src/components/shared/FeedbackButton/FeedbackButton.tsx
- src/components/v5/common/AvatarUploader/partials/DefaultContent.tsx
- src/components/v5/common/Fields/RadioButtons/ButtonRadioButtons/ButtonRadioButtons.tsx
- src/components/v5/common/Fields/RadioButtons/TileRadioButtons/TileRadioButtons.tsx
- src/components/v5/common/Fields/Select/Select.module.css
- src/components/v5/common/Filter/partials/SearchInput/SearchInput.module.css
- src/components/v5/common/SubNavigation/partials/SubNavigationItem/SubNavigationItem.module.css
- src/components/v5/frame/NavigationSidebar/NavigationSidebar.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarButton/NavigationSidebarButton.tsx
- src/components/v5/shared/Modal/Modal.tsx
- src/stories/common/UserNavigation.stories.tsx
- src/stories/shared/MenuWithSections.stories.tsx
- tailwind.config.js
We need to limit the color palette of tailwind to only colors that are defined in the style guide. Two advantages here:
- People won't get tempted to use colors that aren't in our palette
- Dark mode will work if light mode looks good
> Move colors out of extend to only allow styleguide colors

- src/components/shared/TokenInfoPopover/TokenInfo.tsx
- src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
- src/components/v5/shared/UserAvatar/types.ts
This PR fixes the issue where blockies for tokens were showing inconsistently, when in the colony balance token list, each token has it's own thumbnail, if this thumbnail / image is a default blockie it'll appear as a different blockie when the user clicks on the token for more info. This is because currently a new blockie is being generated specifically for this token info image instead of using the tokens original blockie default
The same blockie is now shown in the token info image
User blockies in the user drop down menu now show consistently with the user's blockie
**Changes** 🏗
Changed <avatar> within TokenInfo.tsx to <TokenIcon> 
Removed the <Avatar> import 
Added <TokenIcon> import
Removed { avatar, thumbnail } as they are no longer used.
Resolves #1712
> fix token blockies not showing consistently

- src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.module.css
- src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.tsx
- src/components/v5/common/MemberCard/MemberCard.tsx
- src/components/v5/shared/RolesTooltip/RolesTooltip.tsx
- src/components/v5/shared/RolesTooltip/index.tsx
- src/components/v5/shared/RolesTooltip/types.ts
- src/i18n/en.json
https://tw.auroracreation.com/app/tasks/15670058
* Moved Permission Roles from MemberCard as new shared component called: `RolesTooltip`
* Added `RolesTooltip` for Extension Details
Resolves https://github.com/JoinColony/colonyCDapp/issues/1694
> feat: add permission roles for extensions

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/ActionSidebar/partials/UserSelect/hooks.ts
- src/components/v5/shared/SearchSelect/types.ts
* Show verified / non verified icon correctly for transfer recipient
* (Also fixed transfer recipient thumbnail as there was some overlap)
**Changes** 🏗
* useUserSelect hook now returns isVerified property for each member
* Conditional UI changes now depend on selectedUser?.isVerified rather than unused showVerifiedUsers property
* useUserSelect hook now returns thumbnail property for each member
Verified user:
Unverified user:
Resolves #1780
> Fix: Verified and Non-verified users actions icon

- amplify/backend/api/colonycdapp/schema.graphql
- scripts/create-data.js
- src/graphql/generated.ts
I've updated the graphql schema to include the `VerifiedMember` entity, and let Amplify autogenerate all the queries for us.
I've used a combination of primary and sort key for the `VerifiedMember` entity, this is basically a compound primary key.
* `VerifiedMember` entity
* the 3 dev wallets get automatically added as verified members
Resolves #1721
> [Verified members] feat: add graphql entities for verified members

- src/components/v5/common/TeamCard/TeamCard.tsx
- src/components/v5/common/TeamCardList/TeamCardList.tsx
- src/components/v5/shared/ReputationBadge/ReputationBadge.tsx
- Increased the number of cards shown per row on the teams page from 2 to 3 on desktop. Remains at 2 on tablet and 1 on mobile.
- Changed the colour of the team funds and reputation to text-gray-600
- Reduced the max number of avatars shown to 4
- Reduced the size of the avatars to 30 x 30px
- Set the min-height of the card to ensure the content block is 94px high regardless of content
3 cards on desktop
2 cards on tablet
1 card on mobile
Card example showing changed text colour and max avatars
Avatar size
Card content size with no description
Card content size with description
Resolves #1796
> Fix: Teams UI optimisations

- src/components/v5/common/CompletedAction/partials/TransferFunds/TransferFunds.tsx
TeamWork: https://tw.auroracreation.com/app/tasks/15637182
This is a small text correction for created "Transfer funds" actions.
**Changes** 🏗
before:
after:
> Fix: change the label "recipient" to "to" for TransferFunds

- amplify/backend/api/colonycdapp/schema.graphql
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/frame/ColonyHome/TmpAddVerifiedMembers.tsx
- src/graphql/generated.ts
- src/redux/sagas/actions/addVerifiedMembers.ts
- src/redux/sagas/actions/index.ts
- src/redux/sagas/utils/verifiedMembers.ts
- src/redux/types/actions/colonyActions.ts
This PR adds a saga to add verified members, construct the JSON object for the block ingestor, and call the saga from a very dumb component for testing purposes (will remove once we merge the form).
* `addVerifiedMembers` saga
* `TmpVerifiedMembers` component
Resolves  #1729
> [Verified members] feat: add verified members via permissions saga

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/graphql/generated.ts
This PR fixes a couple of issues discovered while investigating the incoming funds bug. For context, sending tokens to a colony triggers a `Transfer` event, which block-ingestor is supposed to pick up and process.
1. block-ingestor was not able to match the `Transfer` events with any of the existing event listeners and it was simply ignoring it.
2. We had a bug in setting up the listeners anyway, and it would only ever set up a single listener (presumably for the first colony it starts tracking).
3. When it finally made it to the correct handler, we failed to ensure the transferred token is in the DB, and it would make entire CDapp crash (BTW. This is another good arguments to break down the massive `GetFullColonyByName` query into smaller queries, since a single field failure will lead …
> Fix incoming transfers: ingestor hash update

- src/components/v5/common/ActionFormRow/ActionFormRow.tsx
- src/components/v5/common/ActionFormRow/types.ts
- src/components/v5/common/ActionSidebar/consts.tsx
- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
- src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
- src/components/v5/common/ActionSidebar/partials/DescriptionField/DescriptionField.tsx
- src/components/v5/common/ActionSidebar/partials/DescriptionField/types.ts
- src/components/v5/common/ActionSidebar/partials/DescriptionRow/DescriptionRow.tsx
- src/components/v5/common/ActionSidebar/partials/DescriptionRow/types.ts
- src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
- src/components/v5/common/ActionSidebar/partials/TeamsSelect/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/CreateDecisionForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/hooks.ts
- src/components/v5/common/CompletedAction/partials/CreateDecision/CreateDecision.tsx
- src/components/v5/common/CompletedAction/partials/rows/Description.tsx
- src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
- src/components/v5/shared/ActionTypeNotification/index.ts
- src/components/v5/shared/ActionTypeNotification/types.ts
- src/components/v5/shared/RichText/RichText.tsx
- src/components/v5/shared/RichText/types.ts
- src/i18n/en.json
- src/utils/objects/index.ts
https://tw.auroracreation.com/app/tasks/15687539
- disable fields when extension is not installed
- display banner
- redirect to extension
> Fix: disable fields when extenstion is not installed in create decision action

- src/components/v5/shared/UserPopover/partials/UserInfo.tsx
Users who have not joined a team or have no reputation should have equal padding above and below on their members pop over. Previously there was too much bottom padding.
On the all members page, click on a user who is not in a team and has no reputation.
**Changes** 🏗
* Remove margin bottom when no userStatus
Resolves #1450
> Fix: Members pop over UI equal padding when no team or reputation

- src/components/v5/common/CompletedAction/partials/TransferFunds/TransferFunds.tsx
- src/components/v5/common/CompletedAction/partials/rows/TeamFrom.tsx
When using the "transfer funds" action, the team colours should show the correct colour in the completed state.
* Transfer funds from one team to another - team colours should be correct in the completed state
**Changes** 🏗
* Added color prop to TeamBadge component in the completedAction rows
Resolves #1819
> Fix: Team pill colour now correct in completed state

- src/components/v5/shared/RichText/hooks.ts
- src/components/v5/shared/RichText/partials/RichTextContent/RichTextContent.module.css
https://tw.auroracreation.com/app/tasks/15771891
* Step 1. Open create action side panel and choose any action type.
* Step 2. Add some text into description.
* Step 3. Wrap selected line as heading and bold - it shouldn't change font-size
* Step 4. Add blockquote - it should have 32px of margin left.
**IMPORTANT NOTE**: Setting bold for heading has no visual effect. It's simply because headings font-weight is set for 600 (SemiBold) which is highest possible weight for Inter font in the app. If we want the bold to have an effect on headings we need to install additional font-weight for 900 Black (Heavy). I will need a feedback if we want to install this extra font weight.
**Changes** 🏗
* Removed `text-md` class for bold wrapper in richtext. It wasn't necessary and it caused an issue that …
> fix: richtext bold heading font-size

- src/components/frame/v5/pages/MembersPage/partials/MembersTabContent/hooks.tsx
Implement the fix, where selecting the "Make Payment" option from the user's kebab menu automatically fills in the "Recipient" field, ensuring this functionality works for both colony members and non-members.
Automatic filling of the "Recipient" field for users who are not colony members
Instructions for testing this branch:
* Step 1. Award permissions to an address in a Colony that is not a member.
* Step 2. Navigate to the members page where that member should appear as a contributor.
* Step 3. From the kebab menu, select the option to "Make payment".
* Step 4. Take note of the "Recipient" field, which will not have an address pre-filled.
**Changes** 🏗
https://github.com/JoinColony/colonyCDapp/assets/90605528/6a285d37-7f9d-4347-9599-49a198dccfb6
Resolves: …
> Fix: prefilling recipient for non members

- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/hooks.tsx
The logic was already there, althought a bit wrong as it was considering the motion domain instead of `fromDomain` which actually has the domain from which the funds are going to be extracted.
Besides that, now you should see this error whenever you create a simple payment or transfer funds motion with an amount that by the time the motion is ready to be finalized, is larger than the domain's balance:
Resolves #1482
> Add "Not enough funds" error to finalize step

- src/components/v5/common/WidgetBox/WidgetBox.tsx
- src/components/v5/frame/ColonyHome/partials/Members/Members.tsx
- src/components/v5/frame/ColonyHome/partials/TokenBalance/TokenBalance.tsx
Changed base colors for member and funds widgets
Colors for member and funds widgets match the designs on [Figma](https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1781-5904&mode=design&t=sV3pM07H74aLrg8m-0).
Instructions for testing this branch:
* Step 1. Go to the dashboard
* Step 2. Compare widget colors with designs
**Changes** 🏗
https://github.com/JoinColony/colonyCDapp/assets/90605528/17a87d19-8328-4fee-bd39-376f7dfcfa4b
Resolves: https://github.com/JoinColony/colonyCDapp/issues/1832
> Fix: colors of member and funds widgets

- amplify/backend/function/fetchTokenFromChain/src/graphql.js
- src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenInputs.tsx
- src/components/v5/common/AvatarUploader/partials/DefaultContent.tsx
Previously when creating a colony, you would get shown two different blockies when creating the native token. This PR replaces the temporary blockie with a placeholder graphic.
1. Generate a new beta invite code.
```
createPrivateBetaInviteCode(input: {}) {
id
}
}
```
2. Go to: http://localhost:9091/create-colony/{beta-invite-code}
3. Follow the onboarding flow, when creating the token there should be a placeholder image (unless you upload your own image).
4. When completing the onboarding flow a new blockie will be generated for the colony as before.
**Changes** 🏗
* Temporary blockie replaced with placeholder
* (I also noticed the icon on the AvatarUploader was the wrong colour, so have snuck that fix into this PR too)
Resolves #1532
> Fix: Blockies placeholder during colony creation onboarding flow

- src/components/common/ColonyActionsTable/hooks.tsx
- src/components/v5/common/Pills/MotionStateBadge/consts.ts
- src/components/v5/common/Pills/MotionStateBadge/types.ts
- src/i18n/en-motion-states.ts
- src/utils/colonyMotions.ts
https://tw.auroracreation.com/app/tasks/15776112
- Changed fallback action pill to `unknown` instead of `forced`
Resolves [1857](https://github.com/JoinColony/colonyCDapp/issues/1857#issue-2118372699)
> fix: changed fallback pill to unknown

- src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.module.css
- src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.tsx
- src/components/v5/common/Pills/ExtensionStatusBadge/ExtensionStatusBadge.tsx
Fixed issues with extension details UI:
- corrected color for "disabled" status
- changed columns gap
The tests consist of checking whether the extension details section is compatible with Figma.
Instructions for testing this branch:
* Step 1. Go to extensions screen
* Step 2. Click "Manage" button for some extension 
* Step 3. Check if the "Extension details" section is compatible with Figma
**Changes** 🏗
Before:
After:
Resolves: https://github.com/JoinColony/colonyCDapp/issues/1869
> Fix[1875]: extension ui issues

- src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
- src/components/v5/shared/Button/IconButton.tsx
Main CTA button was not compatible with styles in Figma
The tests consist in verifying whether the main CTA button in the pending state is compatible with Figma
Instructions for testing this branch:
* Step 1. Create some action
* Step 2. Create a situation in which the button confirming adding an action is in the "pending" state
* Step 3. Compare button styles with Figma
**Changes** 🏗
Before:
After:
Resolves: https://github.com/JoinColony/colonyCDapp/issues/1884
> Fix[1884]: styles for main cta button in pending state

- src/components/v5/common/ActionSidebar/consts.tsx
- src/components/v5/shared/RichTextDisplay/RichTextDisplay.module.css
- src/components/v5/shared/RichTextDisplay/RichTextDisplay.tsx
- src/i18n/en.json
Rich text should be formatted correctly in both the creation and completed state.
Previously the HTML from the description input field was being stripped out as part of the error validation, as such it was not being properly submitted. This has been replaced with a custom yup test.
Formatted the completed action description to match the action description input.
1. Write a rich text description in an action.
2. Create a Simple payment action with a description.
3. Complete the action and view the description in the completed state.
**Changes** 🏗
* `ACTION_BASE_VALIDATION_SCHEMA` description max length validation replaced with custom yup test.
* Applied the same styles from the action description input to the completed action description
Resolves #1776
> Fix: Completed action rich text description formatting

- src/components/v5/shared/CalamityBanner/partials/CalamityBannerContent.tsx
Calamity banner 'learn more' text link should match the figma styling.
Get the calamity banner to show and verify the 'learn more' text has the correct styling. The easiest way to do this is to change 'canUpgrade' to true on line 125 in `/src/components/frame/Extensions/layouts/ColonyLayout.tsx`
**Changes** 🏗
* Changed link styling to `text-sm font-semibold` to set the font-size to 12px, line-height to 18px and font-weight to 600 as per the figma design.
Resolves #1868
> Fix: Calamity banner learn more link styling

- src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/hooks.ts
- src/components/frame/Extensions/layouts/partials/ColonySwitcherItem/ColonySwitcherItem.tsx
The Joined Colonies list in the Colony Switcher should show all joined colonies, including the currently selected colony.
In selecting the current colony from the colony switcher, the navigation sidebar should close.
1. Switch to a colony
2. Ensure the colony still shows in the joined colonies list
3. Click the current colony and the navigation sidebar should close.
**Changes**
* Navigation sidebar now closes when selecting the current colony from the colony switcher (in both the current colony section at the top, and the joined colonies section) - Achieved this by adding an onClick handler to setOpenItemIndex to undefined only if the link matches the current pathname.
* Removed the filter from the joinedColonies list which previously removed the current colony
Member in multiple …
> Fix: Show joined colonies in the joined colonies list

- docker/colony-cdapp-dev-env-auth-proxy
- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
This PR addresses the pending colony metadata not appearing on the motion side panel.
The data wasn't appearing before because the auth proxy was blocking the request: https://github.com/JoinColony/colonyCDappAuthProxy/pull/11
NOTE: This PR doesn't address the mess that is the edit colony action side panel. Only the motion version.
Resolves #1560
> Fix pending colony metadata not appearing on side panel

- src/components/frame/Extensions/pages/ExtensionDetailsPage/ExtensionDetailsPage.tsx
This PR fixes the bug where a blank extension page is shown when an invalid extension name is used in the web address. The expected behaviour is to redirect any invalid extension names to a 404 page.
1. Go to extensions
2. Try use an invalid extension name in the link like 'http://localhost:9091/wayne/extensions/VotingReputati' 
**Changes** 🏗
Changed code so the page redirects to 404 instead of displaying an empty page when extension name is invalid.
Resolves #1841
> Fix: Redirect to 404 when using an invalid extension name

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-auth-proxy
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/utils.tsx
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/graphql/generated.ts
- src/redux/sagas/actions/payment.ts
- src/redux/sagas/expenditures/createExpenditure.ts
- src/redux/sagas/expenditures/createStakedExpenditure.ts
- src/redux/sagas/expenditures/editExpenditure.ts
- src/redux/sagas/motions/paymentMotion.ts
- src/redux/sagas/utils/expenditures.ts
- src/redux/types/actions/colonyActions.ts
- src/redux/types/actions/expenditures.ts
- src/utils/tokens.ts
- src/utils/yup/tests/index.ts
This PR ensures the network fee is included in every payout amount set by the sagas.
There is a temporary button to create an expenditure from root domain to the currently logged in user with one payout of 10 ETH in colony's native token.
You can then run the following query to confirm the network fee has been saved correctly:
```gql
query ListExpenditures {
listExpenditures {
items {
slots {
recipientAddress
payouts {
amount
tokenAddress
networkFee
}
}
}
}
}
```
There is gonna be quite a few if you ran `create-data` script, however only the one created from the UI will have a single slot with non-null `networkFee`. **Note:** The list is not sorted chronologically so you might find the new payments get added somewhere in the middle. I find it easiest to locate them by searching the …
> Include network fee when setting advanced payments payouts

- src/components/common/Onboarding/wizardSteps/CreateColony/StepColonyName.tsx
This PR changes the description step found in the create colony page from 
"set up your Colony. Enter a name for your Colony and a short description about your Colony’s mission and purpose." 
to 
"Let’s set up your Colony. Enter a name and custom URL."
This is a small change
* Step 1. go to create colony page
* Step 2. Look at the description found under the 'Welcome' heading
Resolves #1915
> fix: Update create colony step description

- amplify/backend/api/colonycdapp/schema.graphql
- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/graphql/generated.ts
- src/redux/sagas/expenditures/createExpenditure.ts
- src/redux/sagas/expenditures/createStakedExpenditure.ts
- src/redux/sagas/utils/expenditures.ts
- src/redux/types/actions/expenditures.ts
The UI requires storing the selected decision method for an expenditure for later reference.
This PR:
- Modifies the `createExpenditure`, `createStakedExpenditure` sagas to accept a decision method parameter
- Modifies the schema (`ExpenditureMetadata` model) to add a field storing the selected method 
There is a temporary button to create an expenditure from root domain to the currently logged in user with one payout of 10 ETH in colony's native token with the 'Permissions' decision method.
You can then run the following query to confirm the decision method has been saved correctly: (If you have previously ran the create-data script there will be a bunch of expenditures without metadata, but the newly created expenditure should be correct)
```
query ListExpenditures {
listExpenditures { …
```
> Advanced Payments: Store selected decision method for an expenditure

- src/components/v5/frame/ColonyHome/partials/LeaveColonyModal/LeaveColonyModal.tsx
- src/components/v5/shared/Button/JoinButton/JoinButton.tsx
- src/graphql/generated.ts
- src/graphql/queries/contributors.graphql
- src/hooks/useColonySubscription.ts
- src/hooks/useJoinedColonies.ts
Leave this colony button results in a 400 error.
Leaving a colony should also remove it from the 'joined colonies' list in the colony switcher and the 'join' button in the top right should also reappear.
1. Join a Colony.
2. Try to leave the colony.
3. 'Joined colonies' list in the colony switcher should show correct list of colonies
4. 'Join' button should show after leaving the colony.
**Changes** 🏗
* 'Leave this colony' button no longer results in a 400 error (caused by not passing ColonyFragment to useColonySubscription)
* `GetContributorsByAddress` query now accepts an `isWatching` filter to ensure the joined colonies list only shows colonies a user is watching
* `getContributorsByAddress` and `getColonyContributor` caches are now cleared when watching / unwatching a colony. This …
> Fix: Unable to leave a colony

- src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
When creating a new action, title validation should not happen when selecting an action type.
This PR removes a form trigger which was forcing validation whenever the action type was changed. This addresses the title validation as described in the original issue, but also resolves the bug where validation messages do not correctly update when changing action types.
(Please comment if there is a valid reason why the form validation should be forced when changing action types)
1. Create a new action and select an action type
2. No title validation should occur
3. Submit the form with an empty title and the title validation should occur
---
1. Create a new action and select an action type
2. Put the form into an invalid state so that validation messages show
3. Change action type, the …
> Fix: Action form no longer forces validation on action type change

- src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
This PR fixes the incoming funds table always using the colony's native token decimals to display the incoming funds from other tokens.
The testing will be done pretty much on the same way it was done over  https://github.com/JoinColony/colonyCDapp/pull/1825 except the idea is to transfer a token with different decimals other than the classic `18`, for example:
```ts
// create new token (name, symbol, decimals)
t = await Token.new('Token name', 'TKN', 6)
t.unlock()
// mint some tokens
t.mint('10000000000000000000')
// transfer some tokens to your colony (0.5 in the case of 18 decimals, 500B in the case of 6)
t.transfer('<COLONY_ADDRESS>', '500000000000000000')
```
And see if the amount is displayed correctly, instead of using the wrong decimals.
Resolves #1843
> Fix incoming funds table always using native token's decimals

- src/components/v5/common/ActionSidebar/hooks/useCloseSidebarClick.ts
this PR fixes the issue when a user tries closing an action summary on mobile. this issue only occurs on devices which use the close button. desktop doesn't use this close button so when testing please test on smaller devices.
1. use mobile view / device that shows 'close' button on action summary
2. Create an action & submit
3. Try to close the action summary
**Changes** 🏗
Added extra check to the conditional check
now the close button works:
Resolves #1954
> fix: close button not working on mobile actionSidebar

- src/components/v5/shared/CardWithBios/partials/UserStatus.tsx
- src/components/v5/shared/CardWithBios/partials/consts.ts
This removes the weird question mark icon from a contributor's UserAvatar.
Check the contributors page http://localhost:9091/planex/members/contributors (see also the issue itself)
- Only show UserBadge pill icon if there's meant to be one.
Fixes #1938
> fix: do not show question mark on user pills

- src/components/v5/common/Fields/Input/partials/InputPills.tsx
- src/components/v5/common/Fields/InputBase/FormattedInput.tsx
- src/components/v5/common/Fields/Textarea/Textarea.tsx
- src/components/v5/shared/FormError/FormError.tsx
This PR fixes the differences in the error validation type designs. this includes the padding between the input field and the standard error message, and the gap between the icon and message for errors which show the icon (error, warning, success) 
Perform actions which would get the different types of messages to show. e.g. create a colony and use the URL inut field (like in the linked issue)
As far as we understand, yellow (warning) errors haven't been implemented in the new UI so we are unable to test these types of errors.
**Changes** 🏗
top padding is now 4px between standard error and input field
gap between icon and error message is also now 4px
the gap in the activate / withdraw token modal input field and error reduced to 4px
standard text errors in user settings now have a 4px …
> Fix: styling for different error states

- src/components/v5/common/CompletedAction/partials/SimplePayment/SimplePayment.tsx
- src/components/v5/shared/UserAvatarPopover/UserAvatarPopover.tsx
- This PR fixes the complete action side pannel not showing the address of a user with no profile. With the changes, now the shortened address should appear on the description and the recipient row.
- Just create a simple payment action with a user without a profile and check that we are showing the masked address.
- The action should continue to show the other cases correctly, with no regressions.
Resolves #1858
> Fix non-members address not appearing on payment side pannel

- src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/hooks.tsx
- src/components/v5/common/Fields/Input/Input.tsx
This issue was first detected when trying to update the location at `/account/profile`, but this issue was actually affecting both text inputs on the page (website and location).
The ref forwarding in the input component was preventing the register function from properly updating the form values. This PR refactors the shouldFocus useEffect to remove the ref forwarding.
1. Navigate to your account profile /account/profile
2. Update the "Location" and/or "website" field.
3. Reload the page, you and the values should remain updated.
**Changes** 🏗
* Refactored shouldFocus useEffect
* Added MAX_LOCATION_CHARS validation to location input
Resolves #1928
> Fix: Colony profile location field is not saving

- src/components/frame/Extensions/pages/ExtensionsPage/ExtensionsPage.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/UpgradeColonyDescription.tsx
- src/components/v5/common/ActionSidebar/partials/ColonyVersionField/ColonyVersionField.tsx
There are various inconsistencies with Colony network versions and extension versions that are shown or are being picked up in the UI.
Previously, the action sidebar new version was hardcoded to be +1 from the current version. This PR gets the correct version from the context.
Previously, the extensions page would show the latest available version even if an older version was installed, this would result in inconsistencies with the extension details page which shows the current version. This PR shows the currentVersion if the extension is enabled.
Please someone suggest a better approach to this as it feels bad. extension.isEnabled feels like the better thing to check against, but typescript will complain that extension.currentVersion does not exist on AnyExtensionData as it only exists …
> Fix: Inconsistent versions of colony network and extensions

- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/redux/sagas/expenditures/cancelDraftExpenditure.ts
- src/redux/sagas/expenditures/cancelStakedExpenditure.ts
- src/redux/sagas/expenditures/claimExpenditure.ts
- src/redux/sagas/expenditures/createExpenditure.ts
- src/redux/sagas/expenditures/createStakedExpenditure.ts
- src/redux/sagas/expenditures/createStreamingPayment.ts
- src/redux/sagas/expenditures/editExpenditure.ts
- src/redux/sagas/expenditures/finalizeExpenditure.ts
- src/redux/sagas/expenditures/fundExpenditure.ts
- src/redux/sagas/expenditures/lockExpenditure.ts
- src/redux/sagas/expenditures/releaseExpenditureStage.ts
- src/redux/types/actions/expenditures.ts
Add annotation and custom title support to all expenditure sagas.
Spin up a fresh environment/create a new colony.
You can also go to "Wayne enterprises" and click `Create expenditure`
Check that the transaction is pending and the last step should be `Annotating transaction`
It should pass, check it by going to GraphiQL and running 
```
listAnnotations {
items {
actionId
message
}
}
}
```
And you should see annotations there!
* Support for sending annotations and custom titles in all expenditure sagas
Resolves #1043
> [Advanced payments] feat: add annotation support to all expenditure sagas

- src/components/frame/v5/pages/AgreementsPage/AgreementsPage.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementCard/AgreementCard.tsx
There was an error on the agreements page - https://jam.dev/c/a471bcb3-ea8f-4cd0-8fbe-f092b5c52646
It was caused by the fallback value of `createdIn` field. I've removed this fallback and right now I'm displaying the date only when `cretedIn` is not undefined.
Description should also be hidden if it's undefined.
> fix: agreements page error with date

- src/components/v5/common/TeamReputationSummary/TeamReputationSummary.tsx
- src/components/v5/frame/ColonyHome/partials/Agreements/Agreements.tsx
Agreement widget:
Before:
After: 
Team reputation Summary widget:
https://github.com/JoinColony/colonyCDapp/issues/1935
Does not show `M` when not needed
> fix: team reputation summary and agreements widget

- src/routes/Routes.tsx
- Removed `! WEBPACK_IS_PRODUCTION` from permission page route so it should be visible on QA
> fix: added permissions page to prod route

- src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EnterRecoveryModeForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/utils.tsx
- src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/utils.tsx
- src/components/v5/shared/RichTextDisplay/RichTextDisplay.tsx
- src/utils/strings/index.ts
So turns out tiptap handles sanitization, and I wasn't able to inject a hacky iframe.
Nonetheless, I've created a helper for sanitizing HTML which we now call before sending annotation data to the saga.
You can use this hacky iframe `<iframe src="javascript:alert(1)" />`
1. Install governance extension
2. Create new decision, save draft.
3. Go to localstorage to see where decision is being saved. Edit the html string with that iframe.
4. Refresh decision preview to see how it renders.
5. Publish decision to see how it renders.
You can also try setting the description to the iframe, it shouldn't alert you when pasting it or creating any action.
**Changes** 🏗
* Before submitting data to the saga, we sanitize the HTML
Resolves #1028
> feat: sanitize HTML before sending description to saga

- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/StakingStep.tsx
- src/i18n/en.json
This PR changes the error message a user gets when they don't have enough reputation to contribute to a stake decision
1. Create a motion in a team using the Reputation Decision method (I created an agreement).
2. View the decision from a user without any reputation in the team
3. Correctly, you won't be able to stake on the action and you will get an error message.
**Changes** 🏗
New error message can be seen here:
I've added some code to get the user's team / domain name to display it in the error message, however it feels messy, if someone has a better suggestion on how to get the team name please let me know.
Resolves #1940
> Fix: change not enough reputation error message

- src/components/shared/Fields/Form/ActionForm.tsx
- src/redux/sagas/actions/createDomain.ts
- src/redux/sagas/actions/editColony.ts
- src/redux/sagas/actions/editDomain.ts
- src/redux/sagas/actions/initiateSafeTransaction.ts
- src/redux/sagas/actions/manageExistingSafes.ts
- src/redux/sagas/actions/managePermissions.ts
- src/redux/sagas/actions/manageReputation.ts
- src/redux/sagas/actions/mintTokens.ts
- src/redux/sagas/actions/moveFunds.ts
- src/redux/sagas/actions/payment.ts
- src/redux/sagas/actions/unlockToken.ts
- src/redux/sagas/actions/versionUpgrade.ts
- src/redux/sagas/motions/createDecisionMotion.ts
- src/redux/sagas/motions/createEditDomainMotion.ts
- src/redux/sagas/motions/editColonyMotion.ts
- src/redux/sagas/motions/initiateSafeTransactionMotion.ts
- src/redux/sagas/motions/managePermissionsMotion.ts
- src/redux/sagas/motions/manageReputationMotion.ts
- src/redux/sagas/motions/moveFundsMotion.ts
- src/redux/sagas/motions/paymentMotion.ts
- src/redux/sagas/motions/rootMotion.ts
- src/redux/sagas/motions/stakeMotion.ts
- src/redux/sagas/transactions/createTransaction.ts
- src/redux/sagas/transactions/transactionChannel.ts
Turns out, our way of doing sagas failed if the user rejected a transaction when it was first created.
This was due to us trying to get the `txHash` but not listening to events for a transaction failing.
I've unified that to just always get the result and use the `txHash` from there.
Additionally, the helper for sending transactions emits a transaction failed error if the signing failed.
My friend, I am very sorry.... The testing scope for this is to test **ALL** the actions.
1. Start up your dev environment, enable the Reputation extension
2. go to `http://localhost:3006/ganache-accounts.json` and copy the private key for "leela" - the wallet address is `0xb77d57f4959eafa0339424b83fcfaf9c15407461`
3. Go to Metamask and add an account by importing the private key
4. Maybe you will need to …
> fix: handle transaction rejected from wallet error 

- src/i18n/en.json
https://tw.auroracreation.com/app/tasks/15814597
- Changed description in finances sidebar to `The financial overview, asset balances, revenue, and expenses of the colony."`
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2008](https://github.com/JoinColony/colonyCDapp/issues/2008)
> fix: changed copy in finances sidebar

- amplify/backend/function/fetchVoterRewards/src/utils.js
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/redux/sagas/expenditures/createExpenditure.ts
- src/redux/sagas/expenditures/createStakedExpenditure.ts
- src/redux/sagas/expenditures/editExpenditure.ts
- src/redux/sagas/utils/expenditureMulticallData.ts
- src/redux/sagas/utils/expenditures.ts
- src/redux/sagas/utils/expendituresMulticall.ts
- src/redux/sagas/utils/index.ts
- src/redux/types/actions/expenditures.ts
- src/redux/types/actions/motion.ts
This PR will enable making changes to locked expenditures using permissions.
block-ingestor PR: https://github.com/JoinColony/block-ingestor/pull/181
Test the following scenario with draft and locked expenditure:
1. Create an expenditure. Run the following query and inspect the values of the slots (recipient address, claim delay, payouts):
```gql
query ListExpenditures {
listExpenditures(filter: {nativeId: {gt: 32}}) {
items {
nativeId
slots {
id
recipientAddress
claimDelay
payouts {
amount
tokenAddress
}
}
}
}
}
```
2. Enter the expenditure ID in the field and click on "Edit expenditure". The hardcoded payload should change the existing slot's recipient to the colony address, change its token address to the native token and set the amount to `23.45`. It should also add a second slot with …
> Changes to expenditures after locking using permissions

- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/common/Extensions/UserHubButton/utils.ts
Implemented logic to open the user hub when a transaction fails. Inspired by the logic we had in the Dapp/Old UI.
- We need to make a transaction fail and check if the user hub opens automatically and shows the error.
- One way I could think of is to transfer 1 token to a newly created team, and then try to make a simple payment from that team to any user for 1 token. This transaction should fail because you don't have enough tokens to cover the network fees.
- Another one is to try to transfer all of the tokens from one team to another through a motion, and before finalizing it, create an action and transfer any amount from the same team so that now the transfer motion can't be finalized because the funds aren't enough. (You are gonna have to go to `FinalizeStep` and remove the …
> Add auto-opening functionality to user hub after tx error

- src/components/v5/common/ActionSidebar/partials/CreatedIn/CreatedIn.tsx
Not reported on the issue but the same was happening in the "Unlock token" action.
Resolves #2009
> Hide created in field when it's read only on actions

- src/components/frame/Extensions/pages/ExtensionDetailsPage/ExtensionDetailsPage.tsx
This PR fixes the issue where an extension directs to a 404 page when the direct URL is used, or if the page is refreshed on the extension details page. This happens because extensionData is not available fast enough so NotFoundRoute is rendered.
Use a direct URL like `http://localhost:9091/planex/extensions/OneTxPayment` and see if the extension details page loads
AND
go to an extension detail page e.g. Voting reputation or One tx payment and refresh the page
The expected behaviour is that the extension details page is loaded without issues and does not redirect to a 404.
**Changes** 🏗
!loading added to the if check which renders NotFoundRoute
Resolves #1995
> Fix: not able to load extension pages directly in production

- Readme.md
- package-lock.json
- package.json
- scripts/watchAmplifyFiles.ts
Please see issue for description.
Run `npm run dev` and wait for the `amplify` container to start.
Make some changes in the `amplify` directory, e.g.: 
- modify the schema
- create a new lambda (`npm run amplify function add`)
- add a new file
The files you add/update should be copied over to `amplify` container. You'll see a relevant message in the console. If you are Docker Desktop user, you can go to the container > Files and check they've been copied:
For CLI people, I think you can use `docker exec -it amplify /bin/sh` to enter the container's shell and run a combination of `cd` and `ls` to see the copied files.
Resolves #1972
> Fix: Changes to files inside amplify folder are not being picked up by amplify container

- src/components/frame/Extensions/pages/PermissionsPage/hooks.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
- tailwind.config.js
- Added search by permission type to permissions filters
- Changed xl size so it starts at 1401
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2051](https://github.com/JoinColony/colonyCDapp/issues/2051)
> fix: permissions type filtering, page layout

- Readme.md
- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- package-lock.json
- package.json
- scripts/watchAmplifyFiles.ts
- src/graphql/generated.ts
Advanced payments feature requires displaying payments in the activity feed. This PR introduces relations between expenditures and actions model so that there's a corresponding action created for each expenditure.
Additionally, it refactors the relation between Expenditure and UserStake models, making the latter available as a field on the expenditure.
I have also pulled in the commits from #1973 to make them available on `feat/advanced-payments-2` after merge - it's not the last time we modify the schema on this feature branch and manual copying has become a bit annoying.
block-ingestor PR: https://github.com/JoinColony/block-ingestor/pull/179
1. Create an expenditure using testing UI.
2. Run a query to verify an action of type `CREATE_EXPENDITURE` has been created and that it has a …
> Connect expenditures with actions model

- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
- src/i18n/en.json
This PR fixes the issue which was occuring when trying to finalize an agreement / decision action. this was done by adding a condition so agreements used `MOTION_CLAIM` instead of `MOTION_FINALIZE`. By doing this the stakes can be returned to the user and the agreement is closed. When the agreement is at the 'Finalize' step, the button should also be labelled 'Return Stakes' rather than 'Claim' like other actions. 
* Install reputation extension
* Create agreement motion and go through the steps
* Get to finalize step, and return the stakes
Expected result: you should not see any errors and the stakes are returned to the user:
You can also repeat these steps but instead of claiming via the motion 'Return stakes' claim via the user hub and check if the decision finalizes without any …
> fix: Not able to finalize agreements

- src/components/v5/common/ActionSidebar/partials/SaveDraftButton/SaveDraftButton.tsx
The entire app was freezing when switching from 'Create agreement' to 'Simple payment' (this would also occur when switching from 'Create agreement' to any other action type then to 'Simple payment').
Create a new action, select 'Create agreement', switch to 'Simple payment'. No freeze should occur.
**Changes** 🏗
* Changed `SaveDraftButton` `isValidating` check.
Resolves #2047
> Fix: App freezes when switching from create agreement to simple payment

- src/components/v5/common/ActionSidebar/partials/ExpenditureBadge/ExpenditureBadge.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/hooks.tsx
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizeWithPermissionsInfo/FinalizeWithPermissionsInfo.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizeWithPermissionsInfo/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizeWithPermissionsInfo/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/PaymentStepDetailsBlock.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentItem/PaymentItem.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentItem/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentItem/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentOverview/PaymentOverview.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentOverview/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentOverview/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StepDetailsBlock/StepDetailsBlock.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StepDetailsBlock/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StepDetailsBlock/types.ts
- src/components/v5/common/CompletedAction/partials/rows/PaymentBuilderTable/PaymentBuilderTable.tsx
- src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
- src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
- src/i18n/en.json
- src/utils/sortPayouts.ts
Part of https://github.com/JoinColony/colonyCDapp/issues/2005
**Payment Builder widget with mock data. Right now you can go to the next steps, but no actual action will be triggered to proceed with the action. I also wasn't able to get the info about who clicked `Fund` or `Release` buttons, and because of that I wasn't able to display the box with the info about it when going back to these stages.** - there's an issue related to this: https://github.com/JoinColony/colonyCDapp/issues/2082
**We are focusing on one flow right now - with the permissions decision method only.**
**Stepper - Stage - Create**
- Clicking back on the Create stage pill will show the permission decision method was used.
**Stepper - Stage - Review**
- First stage after creating the payment, it makes the payment public …
> Payment builder widgets UI

- src/components/v5/common/Fields/InputBase/FormFormattedInput.tsx
This fixes 2 bugs, both appearing on the token activation modal
and the staking widget
The first bug was that if you entered a number manually, it didn't work, it just threw an error that you need to enter a value.
The second bug was that if you clicked `Max` and then tried to change the value, it broke and the console spat out an error.
Try both of those cases to see if they were fixed :D 
**Changes** 🏗
* two way data binding for `FormFormattedInput` restored
Resolves #2092 and #2093 (maybe I should have foreseen them being the same issue :facepalm: )
> fix: two way binding of FormFormattedInput

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/ReleasePaymentModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/types.ts
- Refetching expenditure data after funding and releasing actions. This is needed to refresh the data in the stepper and move to the next step
- Going from funding step to release is handled in this [PR](https://github.com/JoinColony/colonyCDapp/pull/2101)
> fix: added expenditure refetch after funding/releasing

- src/components/frame/Extensions/layouts/ColonySidebar.tsx
- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarThirdLevel/NavigationSidebarThirdLevel.tsx
When on mobile or generally small-ish screens the colony menu stayed open when clicking the "Create action" button. This resulted in a state where seemingly nothing happened as the colony menu was covering the action sidebar. This fixes that by closing the colony menu before the action sidebar is opened. This also applies for all the "related actions" that now close the menu as well, when clicked.
* Step 1. Be on mobile or a small screen
* Step 2. Click the "Create action" button in the colony sidebar
* Step 2a) Click on any of the "related actions"
* Step 3. The action sidebar appears
Closes #2078
> Close colony menu on action button push

- src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
- src/components/v5/common/ActionSidebar/consts.ts
- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
With these changes, now the modal should show only when you edit any fields other than the action type and title. Otherwise, it should never show when you change from one action type to another, for example.
Resolves #2089
> Update Change Action modal logic

- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/Contact/Contact.tsx
- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/Currency/Currency.tsx
- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/Developers/Developers.tsx
- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/Legal/Legal.tsx
- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/MenuListItem/MenuListItem.tsx
- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/submenu.styles.ts
This PR restores the UserNavigation submenu classes that were accidentally removed as part of the vite refactor.
Check each of the usernavigation submenus are styled as expected.
**Changes** 🏗
* Created new submenu.styles.ts file for shared tailwind classes
* Restored the classes to each of the submenus.
Resolves #2091
> Fix: Restore UserNavigation submenu classes

- src/components/v5/common/Fields/CardSelect/CardSelect.tsx
This PR adjusts the "Card select" title padding to bring it inline with similar components. This was initially raised specifically referencing the decision method dropdown in the action sidebar, however the same component is used in multiple places - for the sake of consistency this PR changes them all (@JoinColony/design please let me know if this is not desired!)
1. Create a new action
2. Open the "Decision method" dropdown
3. Check the padding below the words "Available dcision methods" - it should be 8px
**Changes** 🏗
* Increased padding on card select title
Resolves #2113
Available decision methods:
Add/Remove verified members
Permission types
Team select breadcrumb
> Fix: Card select title and Action sidebar decision method dropdown padding increased

- src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx
The colony URL on the 'Create Colony' conformation should not allow capital letters. This PR enforces lowercase.
1. Create a new colony.
2. Proceed to the confirmation step.
3. Pay attention to the capitalization of the domain.
**Changes** 🏗
* Colony URL is now lowercase
Resolves #2136
> Fix: URL showing capitalization on create colony confirmation

- src/components/frame/v5/pages/UserPreferencesPage/hooks.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/RowItem/RowItem.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/hooks.tsx
- src/components/shared/Extensions/Toast/Toast.css
- src/components/v5/common/Fields/Input/Input.tsx
- src/components/v5/common/Fields/Input/types.ts
- User account area styles update on mobile
* Step 1. Go to the user account page
* Step 2. Check the `User account` tab using mobile view
* Step 3. Go to the `Preferences` tab on mobile and check if it's the same as on a design.
* 
**Changes** 🏗
* Styles update for `Toast` component
* Styles update for the items that are returned from `useUserPreferencesPage` and `useUserProfilePageForm` hooks
* `allowLayoutShift` prop added to `InputProps` to avoid error text overflow
* removed redundant classNames and `!important`s
Resolves https://github.com/JoinColony/colonyCDapp/issues/2079
> fix: user account area mobile styles

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizeWithPermissionsInfo/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/index.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StepDetailsBlock/index.ts
- Added overview box for funding step
* Step 1. Create Payment Builder Action
* Step 2. Click the "Confirm details" button and wait for the lock expenditure action to be completed
* Step 3. Click the "Fund" button to open the Funding modal, select "Permissions" decision method and click "Confirm payment" and wait for the action to be completed
* Step 4. Click on "Funding" step pill
* `FinalizeWithPermissionsInfo` component rendered instead of `StepDetailsBlock` component, when the active step is different than `ExpenditureStep.Funding` and if there are any `items` in `fundingActions` object from `expenditure`
**Changes** 🏗
* no changes
* no deletions
Contributes to https://github.com/JoinColony/colonyCDapp/issues/2005
Waiting for …
> feat: funding overview box

- src/components/common/Extensions/UserHub/partials/ReputationTab/partials/PendingReputation/PendingReputation.tsx
When the "Next update" time is passed, it does not update - so it will show an incorrect time: "15 seconds ago".
This PR adds a check to see if the "next update" time has passed, and gets the next cycle date to update the time.
1. Select a colony.
2. Open the User Hub.
3. Navigate to the "Your balance" tab.
4. The "Next reputation update" field will show how much time there is left untill the next reputation update.
5. The countdown is reached and the user does not refresh the page or open a new page.
Once the timer reaches 0, it should briefly show "Now" before refreshing to the new time "60 minutes".
**Changes** 🏗
* `PendingReputation` component now checks if the `nextMiningCycleDate` has passed and updates it if necessary
Resolves #2121 …
> Fix: Pending reputation next update shows incorrect time

- amplify/backend/function/createColonyEtherealMetadata/src/index.js
- src/components/common/Onboarding/wizardSteps/CreateColony/CreateColonyCardRow.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/validation.ts
The colony URL input in the new colony creation wizard appears to only let you enter lowercase letters, however the actual value will accept uppercase and lowercase letters.
This PR adds new validation to the input to ensure only lowercase letters are allowed.
1. Create a new colony.
2. Try entering capital letters to the colony URL field
3. Proceed with the creation wizard and create the colony.
4. Check in the database that the colony has been created with a lowercase name:
```
listColonies {
items {
name
}
}
}
```
**Changes** 🏗
* Added lowercase validation to the new colony URL input
* Removed the now unnecessary .toLowerCase() on the confirmation screen
Resolves #2145
> Fix: New colony URL should not allow capital letters

- docker/colony-cdapp-dev-env-block-ingestor
This fix is on the block-ingestor (https://github.com/JoinColony/block-ingestor/pull/198). This PR simply updates the block-ingestor hash.
Incoming funds were incorrectly being duplicated. This was due to both the 'transfer' and 'expenditurePayoutClaimed' events being emitted when a payment is made from one colony to another via the OneTxPayment extension.
This PR adds a check to the 'expenditurePayoutClaimed' event to check if the event was emitted by the OneTxPayment extension and to skip creating a new claim if so (as the 'transfer' event will already do this).
1. Send funds to a colony. (Copy the colony wallet address, switch to another colony, create a simple payment action with the colony address as the recipient)
2. Navigate to the incoming funds page.
3. The incoming funds should …
> Fix: Duplicate incoming funds

- src/components/frame/v5/pages/FundsPage/partials/FundsTable/FundsTable.tsx
When in the empty state, the incoming funds table was displaying a double border across all responsive sizes. This PR removes the extra border when in the empty state.
1. Navigate to the 'Incoming funds' page
2. Claim an incoming funds
3. The empty table should not have any duplicate borders
* Removed unnecessary border on funds table when empty
Resolves #2155
> Fix: Incoming funds table border UI issue

- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/ActionsTableFilters.tsx
- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/partials/filters/ActionTypeFilters/ActionTypeFilters.tsx
- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/partials/filters/DateFilters/DateFilters.tsx
- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/partials/filters/DecisionMethodFilters/DecisionMethodFilters.tsx
- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/partials/filters/StatusFilters/StatusFilters.tsx
- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/components/frame/Extensions/pages/PermissionsPage/partials/FilterItem.tsx
- src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementsPageFilters/AgreementsPageFilters.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementsPageFilters/partials/DateFilters/DateFilters.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementsPageFilters/partials/StatusFilters/StatusFilters.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/Filters/BalanceFilters/BalanceFilters.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/Filters/partials/filters/AttributeFilters/AttributeFilters.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/Filters/partials/filters/TokenFilters/TokenFilters.tsx
- src/components/frame/v5/pages/FundsPage/partials/Filter/Filter.tsx
- src/components/frame/v5/pages/FundsPage/partials/Filter/FilterItem.tsx
- src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/FilterItem.tsx
- src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/TeamsPageFilter.tsx
- src/components/v5/common/Filter/partials/FilterOptions.tsx
- src/components/v5/shared/SubNavigationItem/partials/NestedOptions.tsx
Add padding to the headings of dropdown cards / filters across the app. Applies on both desktop and mobile.
Check that the padding is correct on all filter dropdown cards across all pages where a filter is present (including sub filter menus).
Check the dropdown cards / filters in the following places:
* Contributors and All Members pages
* Permissions page
* Teams page
* Balance page
* Incoming funds page
* Agreements page
* Hamburger menu
**Changes** 🏗
* Increased paddings for headings in dropdown cards.
Resolves #2133
> Global dropdown H5 padding

- src/components/v5/shared/UserPopover/UserPopover.tsx
Added masked address to the user popover, so now every place where the popover is used and there's no user profile, it should show the partial address instead like the other places where we show addresses.
Every recipient address in the completed action side panel should now be masked:
Resolves #2177
> Add masked address to user popover

- src/components/v5/common/ActionSidebar/hooks/permissions/helpers.ts
- src/components/v5/common/ActionSidebar/hooks/permissions/useHasNoDecisionMethods.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/DecisionMethodField.tsx
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/PaymentBuilderForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
- Removed reputation decision method from payment builder form
* Step 1. Check if you have the `Reputation Weighted` extension installed and enabled
* Step 2. Open Action sidebar
* Step 2. Select `Payment builder` action type
* Step 3. Open `Decision method` dropdown - `Reputation` option shouldn't be on the list
* 
**Changes** 🏗
* `filterOptionsFn` prop added to `DecisionMethodField`
* `filterOptionsFn` prop used on `DecisionMethodField` component in `PaymentBuilderForm` to filter Reputation decision method
* 
Contributes to https://github.com/JoinColony/colonyCDapp/issues/2005
> feat: remove reputation decision method from payment builder form

- src/components/frame/v5/pages/MembersPage/partials/MembersTabContent/MembersTabContent.tsx
- src/components/v5/common/MemberCard/MemberCardSkeleton.tsx
- src/components/v5/common/MemberCardList/MemberCardList.tsx
Create a new skeleton member card component and use it on the contributors tab when the cards are loading.
Update the number of cards shown in the contributors tab when it is loading, and update the grid columns / rows for this page. 
https://github.com/JoinColony/colonyCDapp/assets/38098203/37f8ddfc-63b6-4cd1-b7e2-f52f56897204
Load the contributors page and check that the correct skeleton member cards are shown while the page is loading. There should be a different grid on desktop (4x2), tablet (2x4) and mobile (1x8).
* New skeleton member card
**Changes** 🏗
* Update the number of member cards shown when loading the contributors tab, and update the grid on that page.
Resolves #2176
> Update skeleton loader in contributors tab

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
A user was able to scroll page content while the cursor was positioned over the action sidebar.
* Step 1. Open the action sidebar
* Step 2. Position your cursor over the action sidebar.
* Step 3. Start scrolling.
* 
**Changes** 🏗
* height is now set on page content wrapper and overflow auto is applied
* 
Resolves [#31415](https://github.com/JoinColony/colonyCDapp/issues/2138)
> fix: prevent page body from scrolling when sidebar is visible

- src/components/v5/common/ActionSidebar/partials/AmountField/hooks.ts
- src/utils/elements.ts
A letter wasn't displayed in the amount field, but it was detected in `getInputTextWidth` as the input's value and then used to calculate the input width 
* Step 1. Create an action that includes the amount field, for example, `Simple payment`
* Step 2. Try to add a letter, number (or a few more) then a letter
* 
**Changes** 🏗
* `formattingOptions` added to `getInputTextWidth` function
* 
Resolves [#31415](https://github.com/JoinColony/colonyCDapp/issues/2164)
> fix: calculate cleave input width excluding letters

- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/DecisionMethodField.tsx
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageVerifiedMembersForm/ManageVerifiedMembersForm.tsx
- src/i18n/en.json
Small bug was found by our QA, in [issue](https://github.com/JoinColony/colonyCDapp/issues/1570) it says to change the tooltip content to `"The decision to Manage verified members can only be done in the Root domain."`
- Changed decision method field tooltip content in verified members action
> fix: changed decision method tooltip in verified action

- src/components/v5/common/MemberCard/MemberCard.tsx
- src/components/v5/common/SimpleMemberCard/SimpleMemberCard.tsx
* Truncate addresses on member cards and simple member cards.
Check that the addresses are truncated on all member cards.
* Step 1. Find a member card without a display name
* Step 2. Check that the address is truncated properly
**Changes** 🏗
* Truncate addresses on member cards and simple member cards.
Resolves #2204
> Truncate addresses on member cards

- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/constants/extensions.ts
- src/redux/sagas/expenditures/createStreamingPayment.ts
- src/redux/types/actions/expenditures.ts
* Add a button to the testing UI to test streaming payment create.
* Add a conversion of the amount in the create streaming payment saga to ensure the correct amount is sent.
Test that streaming payments can be created in the db successfully.
* Step 1. Click on the create streaming payment button in the temporary testing UI on the dashboard.
* Step 2. Wait for it to complete.
* Step 3. Check that the payment was created in the db with the correct payload.
* New temporary button on the dashboard for testing.
**Changes** 🏗
* Changed the createStreamingPayment saga to ensure the correct amount is sent.
Resolves #2211
> Add streaming payment testing UI and add amount conversion in saga

- src/components/v5/common/ActionSidebar/hooks/permissions/helpers.ts
- src/components/v5/common/ActionSidebar/hooks/permissions/useHasNoDecisionMethods.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/NoPermissionsError.tsx
- src/components/v5/common/ActionSidebar/partials/SaveDraftButton/SaveDraftButton.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageVerifiedMembersForm/ManageVerifiedMembersForm.tsx
All inputs (except title and action type) should be disabled when you lack the permissions for the action.
The description field was not disabled for "Manage verified members" or "Create agreement".
On "Manage verified members" the "Decision method" field is not disabled and the "You don't have the correct permissions" error message does not show.
This PR fixes these issues. It also fixes similar issues with "Manage reputation" which was not included in the original issue as it has only recently been merged into master.
For "Manage verified members" the form should only be interactive if the current user has the correct permissions in the root domain (having the administration role in a team only will not be enough).
The PR also handles a TODO comment to ensure "removing reputation" …
> Fix: Ensure action fields are disabled when no permissions

- src/components/v5/common/ActionFormRow/ActionFormRow.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/partials/ColonyAvatarField/ColonyAvatarField.tsx
- src/components/v5/common/ActionSidebar/partials/ColonyObjectiveFields/ColonyObjectiveFields.tsx
- src/components/v5/common/ActionSidebar/partials/ColonyVersionField/ColonyVersionField.tsx
- src/components/v5/common/ActionSidebar/partials/ManageReputationTable/ManageReputationTable.tsx
- src/components/v5/common/ActionSidebar/partials/TeamColorField/TeamColorField.tsx
- src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/partials/TokenSymbol/TokenSymbol.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/partials/TokenSymbol/types.ts
- src/components/v5/common/ActionSidebar/partials/TokenSelect/types.ts
- src/components/v5/common/ActionSidebar/partials/TokensTable/TokensTable.tsx
- src/components/v5/common/ActionSidebar/partials/TokensTable/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/ManageReputationTable.tsx
- src/components/v5/common/Fields/CardSelect/CardSelect.tsx
- src/components/v5/common/Fields/InputBase/InputBase.tsx
- src/components/v5/common/Fields/TextareaBase/TextareaBase.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/Table/types.ts
- src/components/v5/shared/RichText/RichText.tsx
- src/hooks/useSocialLinksTableColumns.tsx
Action sidebar fields should be text-gray-300 when disabled, currently they are text-gray-400.
This PR changes the current colour value. I also picked up a few cases where the disabled styling was not being properly applied.
(Using #2233 as a base branch as it contains new logic for disabling fields)
This is most easily checked by switching to a user who has no permissions. Look through all the action types and confirm the disabled states are using text-gray-300.
Switch to a user who does have permissions and check the default and error states are unaffected.
**Changes** 🏗
* Disabled fields now use text-gray-300
* Some tables now have a "disabled" prop to show disabled states
Resolves #2234
> Fix: Action sidebar fields should be text-gray-300 when disabled

- src/components/v5/common/ActionSidebar/hooks/useFilterCreatedInField.ts
- src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/AdvancedPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/BatchPaymentForm/BatchPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/ManageReputationForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/UpgradeColonyForm.tsx
* The created in field (in action forms) should be filtered based on the currently selected team.
* You should only be able to select to create the motion in the selected team, or general.
* You should not have the option to select any other team.
* Changing the team above it should update the created in field to match it.
* If the team above has not been selected and the created in field is changed, then any team can be chosen, but it should also change the team field above it to match, which in turn then filters the created in options.
https://github.com/JoinColony/colonyCDapp/assets/38098203/8ee06a8b-d1df-490f-995b-ab7e1cd2785d
* Ensure you have voting reputation installed.
* Create an action with the Reputation Decision method in a team.
* Click on the created in field and check that …
> Fix: Created in field should only show current team or general

- src/components/common/Extensions/UserNavigation/UserNavigation.tsx
- src/components/common/Extensions/UserNavigation/partials/NetworkName/NetworkName.tsx
- Update the UI of the wrong chain connected warning & tooltip to match the Figma designs.
* Step 1. Connect to a different network in metamask (not Ganache and not Arbitrum)
* Step 2. Connect the metamask wallet to Colony
* Step 3. Check and hover over the network pill in the top right. It should display the correct warnings and the correct tooltip as per designs.
**Changes** 🏗
* Update the UI of the wrong chain connected warning & tooltip
Resolves #2218
> Update UI of the wrong chain connected tooltip

- src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakeItem.tsx
Agreements should now show the correct title on the stakes tab of the user hub:
Resolves #2260
> Fix agreement titles not showing on stake tab

- src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/partials/ColonyAvatarField/ColonyAvatarField.tsx
- src/components/v5/common/AvatarUploader/partials/ErrorContent.tsx
- src/components/v5/shared/Button/TextButton.tsx
- src/i18n/en.json
Fix some image upload form UI issues:
- Fix text of the confirm change button
- Fix styling of error state
- Don't show the cancel and confirm buttons in the Colony Avatar upload modal when there's an error
More details here:
https://github.com/JoinColony/colonyCDapp/issues/2267
Note: I could not reproduce issue number 4 in the above issue, and since there is already another investigation ticket raised to fix some problems with the image upload, I think it is better if this part of the issue is moved to that ticket, since it seems very related. Details in comments of issue 2267.
Check that the UI of the image upload is as expected
* Confirm Change button text
* Styling of the error
* Buttons don't show on the colony avatar modal when there's an error in uploading
**Changes** 🏗
* Changes …
> Image upload form styling & interaction issues

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/CancelTransaction.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/TransactionStatus.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/hooks.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/utils.ts
- src/components/common/Extensions/UserHub/partials/TransactionsTab/types.ts
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/StepConfirmTransactions.tsx
- src/components/v5/shared/NotificationBanner/NotificationBanner.tsx
- src/components/v5/shared/NotificationBanner/types.ts
- src/i18n/en.json
- src/redux/sagas/transactions/createTransaction.ts
There were a few issues with how transaction errors were handled in the user hub.
Issue 1 - UserHub transactions were missing the "Cancel" option. This PR adds a "Cancel" button in addition to the existing "Retry" button. It has the same behaviour as the existing "Cancel" button and requires a confirmation step.
Issue 2 - Transaction error message character limits were too short. This PR increases the allowed length and fixes the logic in the short description utility function.
Issue 3 - The transaction error messages were incorrectly styled. Should now match [figma](https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-51131&mode=design&t=EIF9brlfr9amkOk9-4)
Issue 4 - Clicking "Retry" was closing the UserHub. This was occurring only when the …
> Fix: Improvements to transaction errors

- docker/colony-cdapp-dev-env-block-ingestor
> ## Disclamer
>
> This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
>
> We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
>
> This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
This fixes a issue where an amount being payed out of the colony would decrease the colony's balance for twice that amount.
This was due to a issue where the simple payment's …
> Fix Colony Balance being subtracted twice for each Payment

- src/redux/sagas/motions/revealVoteMotion.ts
- src/redux/sagas/motions/voteMotion.ts
- src/redux/sagas/utils/getNetworkClient.ts
This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
For a long time _(ever since we've introduced the `RetryProvider`)_ revealing your motion vote was broken, but since no one really tested the Gnosis production deployment, people didn't really notice _(this …
> Fix Motion Vote Reveal

- src/auth/index.ts
- src/components/shared/Fields/Form/ActionForm.tsx
> ## Disclamer
>
> This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
>
> We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
>
> This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
This is a simple PR that adds the `authenticateWallet` call inside the `ActionForm` to ensure the user is authenticated before sending a transaction _(and potentially saving …
> Make sure user is authenticated before sending a Transaction

- src/components/common/Extensions/UserNavigation/UserNavigation.tsx
- src/components/common/Extensions/UserNavigation/partials/NetworkName/NetworkName.tsx
- src/components/common/Extensions/UserNavigation/partials/NetworkName/types.ts
- src/components/shared/Extensions/Tooltip/Tooltip.tsx
- src/components/shared/Extensions/Tooltip/types.ts
> ## Disclamer
>
> This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
>
> We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
>
> This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
This PR implements a visual indication _(network pill lights up)_, if the user's wallet is connected to a network other than the current app is deployed to. This was done in a …
> Visual indicator if user's wallet is connected to the wrong network

- package-lock.json
- package.json
There's an error when I tried to run `npm run frontend`
The issue and suggested solutions can be found here: https://github.com/vitejs/vite-plugin-react-swc/issues/74
I'm using Mac Sonoma 14.4.1
* `@swc/core` package
**Changes** 🏗
* 
*
> fix: bindings not found

- src/components/frame/Extensions/layouts/hooks.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
- src/components/v5/common/ActionSidebar/hooks/useActionsList.ts
- src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
- src/components/v5/shared/SearchSelect/types.ts
This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
This PR adds some checks to disable the _"Mint Token"_ and _"Unlock Token"_ actions if the colony doesn't have permissions to do so. This usually happens when you are using an external token, not one created …
> Disable Token Actions if Not Available

- src/components/v5/common/CompletedAction/partials/ManageTeam/ManageTeam.tsx
- src/components/v5/common/CompletedAction/partials/rows/TeamPurpose.tsx
- src/components/v5/common/CompletedAction/partials/rows/index.ts
- src/i18n/en-actions.ts
The team purpose field looked different in the edit and completed state. The text was aligned differently in both cases. Right now it should be top-aligned all the time.
* Step 1. Create a `Create new team` action and add a text to the `team purpose` field that is longer than one line.
* Step 2. Submit the action and open the completed state.
* 
**Changes** 🏗
* `TeamPurpose` component with `subgrid`
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2285
> fix: team purpose field text alignment

- src/components/common/Onboarding/wizardSteps/CreateColony/TokenSelector.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/TokenSelectorInput.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/hooks.tsx
- src/components/v5/shared/SearchSelect/hooks.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/wallet/RetryProvider.ts
- src/types/rpcMethods.ts
This PR is part of the set that will be opened by me to (re)introduce all the changes made to support the Arbitrum deployment, from the `master-arbitrum` branch back into `master` so that the two branches can be _(more or less)_ identical 
We need to run two branches, since AWS enforces one deployment per branch, meaning we can't run both the `Gnosis` and `Arbitrum` deployment from the same branch.
This will get cleaned up, once we get to Multichain and we will be back to only supporting one main deployment _(which itself will support multiple networks, whatever form this might take)_
Code for this fix was implemented while pair programming with @area 
This PR introduces a fix to allow colonies to be created with non colony network created tokens _(basically any random token out there, as …
> Fix Colony Creation with Non Colony Tokens

- src/components/v5/shared/Modal/Modal.tsx
- src/components/v5/shared/PopoverBase/PopoverBase.tsx
- tailwind.config.js
Fixes the issue with z-index between action process pills, modal inputs, and the Userhub.
* Step 1. Create an action with the Reputation decision method.
* Step 2. Open the Userhub, ensure the pills of the Action process pills don't overlap.
* Step 3. You can also click the Activate button to open the modal, and open the Userhub again to make sure there is not an overlapping issue there either
* Added addition z-index to tailwind config.
* Added z-index to modal
**Changes** 🏗
* Changed popover z-index to newly added one for the header.
Also fixes this issue:
Resolves #2277
> Fix: Action process pills overlapping Userhub

- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/hooks.ts
This fixes the issue when the decimals of the token being used for payment is different to the decimals of the native token of a colony, which is being used for staking.
* Step 1. Transfer a 6 decimal token to a colony that has an 18 decimal native token.
- This can be done locally, but it is a little bit of a pain. Ask me if you wish to pursue it and I will provide scripts and instructions, as messy as it was.
* Step 2. Create a motion where the different tokens are used one for the payment and one for staking.
* Step 3. You should be able to stake the max without validation appearing.
* Step 4. You should be able to complete staking without any issues.
**Changes** 🏗
* Removed payment token decimal from staking.
Resolves #2354
> Removes usage of the payment token decimal in staking

- src/components/v5/common/ActionSidebar/hooks/permissions/useHasNoDecisionMethods.ts
The CDapp was crashing when loading the completed action for edit colony details.
This PR adds a check to the `useHasNoDecisionMethods` hook so that if `watch` is undefined it will return false. `watch` will only ever be undefined if the `useHasNoDecisionMethods` hook is called outside of a form (as is the case on the edit colony details completed action screen).
Create a new edit colony details action. The completed action screen should show without issue.
**Changes** 🏗
* The `useHasNoDecisionMethods` hook returns false if `watch` is undefined.
Resolves #2278
> Fix: useHasNoDecisionMethods hook causes edit colony details completed action to crash

- src/hooks/useSocialLinksTableColumns.tsx
The External Links on the 'Edit Colony Details' action should be truncated on desktop.
This PR adds a max width to the row to ensure the text is properly truncated.
Create a new 'Edit Colony Details' action, edit one of the external links so that the text is too long for the row. The text should be truncated.
**Changes** 🏗
* Added max width to external links row to ensure text is truncated
Resolves #2276
> Fix: Edit Colony Details external links truncated

- src/components/v5/shared/RichText/hooks.ts
- src/components/v5/shared/RichTextDisplay/RichTextDisplay.tsx
- src/utils/strings.ts
- Ensure that in descriptions in a collapsed state (actions and agreements) do not show header elements.
Details here: https://github.com/JoinColony/colonyCDapp/issues/2273
- Open any action type
- Use the WYSIWYG or markup to add headings into the description field and add a regular block of content
- Complete the action
- View the description field in the collapsed state and check that the headings don't show
- Open the agreement action type
- Use the WYSIWYG or markup to add headings into the description field and add a regular block of content
- Save it as a draft or complete the agreement flow
- Visit the agreements page and view the draft or completed agreement card, and check that the headings don't show
* New strings util `stripAndremoveHeadingsFromHTML` …
> Strip headers in minimised descriptions

- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
Adding close feature within the side panel on desktop and tablet will enable uses to close the side panel via the header. This adds an extra close mechanism to the side panel giving greater usability control for users within the CDapp.
The close icon should be available to the user in all states of the side panel including:
During the active action stage where a user is creating a new action;
When the transaction is completed; and
And when the transaction is in a motion state.
When the side panel is in the full width state.
If the user selects the close icon during the active action stage and has changed content within the action type chosen, the closing modal should be triggered (which matches the current modal trigger).
For all other states, the side panel should close when selected by …
> feat: action sidebar close button

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/PaymentStepDetailsBlock.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/ReleasePaymentModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/types.ts
Showing loader until expenditure status is updated after each step
* Step 1. Create a Payment Builder action.
* Step 2. Get to the Fund step.
* Step 3. Click and fund the payment and complete the transactions.
* Step 4. Check if the Fund button will still be clickable.
* 
**Changes** 🏗
* `onSuccess` prop instead of `refetchExpenditure` passed to modals and payment step
* `isLoading` state added to show loader instead of clickable button on action success
* `strategy: 'fixed'` added to `UserSelect` component, so that the tooltip is visible when inside the table
* removed `refetchExpenditure` from each modal and payment step
Resolves https://github.com/JoinColony/colonyCDapp/issues/2372
> fix: show loader until expenditure status is updated

- src/components/frame/Extensions/pages/LazyConsensusPage/consts.tsx
- Remove reputation weighted step validation
- Install the Reputation Weighted extension.
- On the settings screen, set the value for "Required Stake" to a fraction of a percent.
- Click the Enable button.
- The form should allow you to do it.
Resolves #2284
> Remove reputation weighted step validation

- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/OutcomeStep/partials/VoteStatuses/VoteStatuses.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/partials/RevealInformationItem/RevealInformationItem.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/StakingStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakesList/StakesList.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/VotingStep.tsx
- src/components/v5/shared/MenuWithSections/MenuWithSections.tsx
- src/components/v5/shared/UserPopover/UserPopover.tsx
- src/components/v5/shared/UserPopover/types.ts
This PR resolves a number of UI regressions in the motion widgets.
1. Username fonts are now the correct size in staking information and reveal information.
2. Padding between all motion widgets is now 18px increased from 12px.
3 + 4. Icon in completed state is now correct.
5 + 6. Progress bar is now correctly aligned with the start of the text, and padding has been increased between the text and the progress bar.
7. Outcome widget now has the correct colour for oppose.
Create a new motion and check the changes listed above.
**Changes** 🏗
* Various small UI changes as detailed above
Resolves #2288
> Fix: Motion widgets UI regressions

- amplify/backend/function/fetchColonyBalances/src/index.js
- amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js
- amplify/backend/function/fetchMotionState/src/utils.js
- amplify/backend/function/fetchMotionTimeoutPeriods/src/index.js
- amplify/backend/function/fetchTokenFromChain/src/index.js
- amplify/backend/function/fetchVoterRewards/src/utils.js
- amplify/backend/function/getSafeTransactionStatus/src/index.js
- amplify/backend/function/getSafeTransactionStatus/src/utils.js
- amplify/backend/function/getUserReputation/src/index.js
- amplify/backend/function/getUserTokenBalance/src/index.js
- amplify/backend/function/qaSSMtest/src/index.js
- amplify/backend/function/updateContributorsWithReputation/src/index.js
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/frame/v5/pages/UserAdvancedPage/partials/RpcForm/helpers.ts
- src/redux/sagas/motions/revealVoteMotion.ts
[Related block-ingestor PR](https://github.com/JoinColony/block-ingestor/pull/221)
We currently use [JsonRPCProvider](https://docs.ethers.org/v5/api/providers/jsonrpc-provider/#JsonRpcProvider) everywhere, which makes a lot of sense, but as we are paying per-request currently, it would be a benefit to use [StaticJsonRPCProvider](https://docs.ethers.org/v5/api/providers/jsonrpc-provider/#StaticJsonRpcProvider) where appropriate. That means in lambdas, and in the block ingestor - nowhere in the frontend, where a user can change the network their metamask or equivalent is connected to.
This PR changes JsonRPCProvider to StaticJsonRPCProvider in the lambdas and block-ingestor.
Perform some actions which utilise the lambdas (and block-ingestor) and ensure nothing has broken.
**Changes** 🏗
* …
> Fix: Use StaticJsonRpcProvider where appropriate

- docker/colony-cdapp-dev-env-block-ingestor
- src/i18n/en.json
- src/redux/sagas/expenditures/claimExpenditure.ts
- src/redux/sagas/expenditures/finalizeExpenditure.ts
- src/redux/sagas/expenditures/fundExpenditure.ts
- src/redux/sagas/expenditures/releaseExpenditureStage.ts
- src/redux/sagas/utils/expenditures.ts
This PR refactors funding and claiming expenditure to use multicall instead of many transactions.
Check that funding expenditure still works, and that finalizing expenditure claims payouts automatically.
Resolves #2391
> Advanced Payments API: Use multicall wherever possible

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/graphql/generated.ts
- src/hooks/useActivityFeed/helpers.ts
- src/redux/sagas/motions/expenditures/releaseExpenditureStageMotion.ts
- src/redux/sagas/utils/setExpenditureStateHelpers.ts
- src/redux/types/actions/motion.ts
This PR modifies the release expenditure stage via motion saga and block-ingestor handler to take advantage of the `releaseStagedPaymentViaArbitration` contract method in order to make the release stage flow functional again.
[block-ingestor counterpart](https://github.com/JoinColony/block-ingestor/pull/224)
1. Install both the weighted reputation extension and the staged payments extension.
2. Enter a transaction amount greater than 0 and create a new staged payment via the temporary dashboard UI. (The expenditure ID will be logged to the console).
3. Lock, fund and finalize the payment.
4. Refetch the expenditure, and enter the stage to release (1 or 2) into 'stage to release' input and submit.
5. Run the following query to check the current state of the database:
``` …
```
> Fix: Release expenditure stage via motion

- src/components/v5/common/ActionSidebar/hooks/permissions/helpers.ts
- src/components/v5/common/ActionSidebar/hooks/permissions/useHasActionPermissions.ts
- src/components/v5/common/ActionSidebar/hooks/permissions/useHasNoDecisionMethods.ts
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/DecisionMethodField.tsx
- src/transformers/index.ts
- src/types/actions.ts
- src/utils/checks/userHasRoles.ts
As a user creating an action, I shouldn't be able to create actions I don't have permissions for.
This PR changes the permissions checks for actions to include multi sig permissions to ensure the invalid permissions notification banner.
(For extra thorough testing, check the notification banner shows as expected before the multi sig extension is installed to check the existing functionality hasn't been impacted.)
Step 1 - Install the multi sig extension.
Step 2 - Give Amy 'Payer' permissions in any team other than General with 'multi-sig' authority.
Step 3 - Switch to Amy and attempt to create an action.
Step 4 - Switch between the different actions, the notification should show on actions which are not covered by the payer permission.
Step 5 - Switch to an action which is covered by the …
> [Multi-sig] Gate user access to multi sig action creation

- src/components/v5/frame/PageLayout/PageLayout.tsx
- Fix the position of the userhub on mobile when the action sidebar is open
* Step 1. Open the app on mobile screen size
* Step 2. Open the action sidebar / start creating a new action
* Step 3. Open the userhub
* Step 4. Check that the userhub is positioned correctly in relation to the top of the screen, and you can close it / navigate away as needed.
**Changes** 🏗
* CSS variable changes to position the userhub menu properly on mobile
Resolves #2286
> Fix userhub positioning on mobile

- src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
- src/components/v5/common/ActionSidebar/partials/NonVerifiedMembersSelect/NonVerifiedMembersSelect.tsx
- src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx
This PR aims to make the distance between popover menus and their respective anchors consistent.
Please inspect the follow fields and verify that their distance from the popover menus they open are consistent:
- Action type
- Non-verified member
- Verified member
- Team selection
- User selection
- Token selection
**Changes** 🏗
Followed the current standard of 8px as the distance between popover menus and their anchors.
Resolves #2385
> fix: Fix popover menu distances from their anchors

- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
Ensures that the Avatar components skeleton always preserves its 1:1 aspect ratio.
1. Visit a Colony you've joined
2. Make sure there's at least 1 action available in the activity widget
3. Toggle the device toolbar
4. Set the dimensions to "Galaxy Fold"
5. Throttle the network speed and choose "Low-end mobile"
6. Reload the page
7. Wait for the content to load and verify that the Skeleton for the Avatar is round as per designs
**Changes** 🏗
Keep the Avatar Skeleton's aspect ratio in tact.
Resolves #2290
> fix: Preserve Avatar Skeleton's Aspect Ratio

- src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
- src/components/v5/common/ActionSidebar/hooks/useActiveActionType.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/NoPermissionsError.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/ActionSidebarDescription.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/types.ts
- src/components/v5/common/ActionSidebar/partials/AmountRow/AmountRow.tsx
- src/components/v5/common/ActionSidebar/partials/hooks.ts
- src/components/v5/common/ActionSidebar/utils.ts
This will disable the token selection when the mint form is presented to the user.
1. Visit a Colony you've joined
2. Bring up the Action form
3. Set the Action type field to "Mint tokens"
4.  Verify that:
a.) Hovering on the token symbol doesn't do anything
b.) Clicking the token symbol doesn't do anything
I noticed that the `ACTION_TYPE_FIELD_NAME` action is being tracked in multiple places so I made a new hook called `useActionActionType` to keep things dry.
**Changes** 🏗
Token selection should now be disabled when the mint form is active.
Resolves #2383
> fix: Disable token selection when mint form is active

- src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakeItem.tsx
- src/i18n/en.json
This PR fixes missing padding in User Hub stakes list and adds missing i18n messages (which also fixes #2423).
- Check padding in User Hub stakes list
- See #2423
Resolves #2423
> Advanced payments deployment fixes

- src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts
Previously, we were converting the wei version of the balance by its currency equivalent which was producing a "wei-like" format of the conversion price.
In this PR, it is now first converting the wei version of the balance to its unit version before applying the final currency conversion.
1. Visit your Colony's Balances page
2. Take note of the "Total funds" value
3. Click on the the Total Funds cell
4. Verify that it matches the "Balance" value for ETH
**Changes** 🏗
Added an extra step to first derive the non-wei value of the token's balance prior to finalising its currency conversion.
| before | after |
| ------ | ------ |
| ![Screenshot 2024-05-23 at 00 15 39](https://github.com/JoinColony/colonyCDapp/assets/50642296/dd433db7-b13d-4ae9-bd47-02560068d7d0) | …
> fix: Update the total balances currency conversion arithmetic

- amplify/backend/api/colonycdapp/schema.graphql
- src/graphql/generated.ts
- Update the ColonyFundsClaim and ColonyChainFundsClaim models to include an `isClaimed` flag.
* Check that in your amplify graphql explorer you can query those properties.
Here's a handy query for you:
```
getColonyByName(name: "planex") {
items {
fundsClaims {
items {
amount
isClaimed
}
}
chainFundsClaim {
amount
isClaimed
}
}
}
}
```
**Changes** 🏗
* Updated schemas and generated code.
Resolves #2444
> Update incoming funds schemas

- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/consts.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/types.ts
- src/utils/validation/hasEnoughFundsValidation.ts
Validation to check if there are enough funds in the team to fund an expenditure
* Step 1. Mint tokens for a colony. E.g. 100 CLNY
* Step 2. Create a Payment builder action, but don't fund it. E.g. for 80 CLNY
* Step 3. Make a Simple payment from the from team used in the first step. E.g. 50 CLNY, leaving the balance at 50 CLNY.
* Step 4. Return to the Payment builder action and try to fund it.
* `FundingModalContent` component to trigger validation on modal opening
**Changes** 🏗
* `fundingItems` added to validation schema
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2415
> fix: missing validation for funds available to fund an expenditure

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/types.ts
- src/components/common/Onboarding/wizardSteps/CreateColony/ConfirmTransactions.tsx
- src/i18n/en.json
- Fix issues with userhub transactions overflowing.
- Fix issues with grouped transactions having a hover / click state during colony creation. (Userhub components being reused across the app 🤔)
- Add missing translation keys.
- Perform some transactions (especially adding an extension with metacolony transactions enabled).
- Open up the UserHub Transactions tab.
- Check that the transactions items are not overflowing the Userhub container.
---
- Make a new colony.
- During the final creation stage, try to hover over the grouped transactions as they are loading.
- They should not have a flickering grey background hover state.
**Changes** 🏗
* UI fixes in userhub
Resolves #2457
> Fix UI issues with userhub transactions

- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
An object was being passed to the `amount` field via the `toggleActionSidebarOn()` function which was then causing the `formatNumeral()` function within the `AmountField` component to throw an exception. So I'm now just passing an expected payload to `toggleActionSidebarOn()` function. The same crash scenario happens when initiating a "Transfer Funds" action from the Balances page so I fixed both under this PR.
1. Visit the Balances page
2. Click the meatball menu button for a token row
3. Click "Make payment using this token"
4. Verify that:
a.) The app does not crash
b.) The Action Sidebar Menu opens and is set to the Simple Payment action
c.) The token is correctly set
1. Visit the Balances page
2. Click the meatball menu button for a token row
3. Click "Transfer funds"
4. Verify that: …
> Fix: Prevent app crash when initiating a Simple Payment/Funds Transfer via the Balances page

- src/components/v5/common/CompletedAction/CompletedAction.tsx
I just added the `AddVerifiedMembersMotion` Colony Action type to the list of action types that the `Motions` component can handle.
| Verified a member via Reputation decision method | Viewing it from the Activities table |
| ![2452_a](https://github.com/JoinColony/colonyCDapp/assets/50642296/c102e195-0183-4249-b202-f6dad1cb8479) | ![2452_b](https://github.com/JoinColony/colonyCDapp/assets/50642296/5ed6a159-d922-49f6-848a-90c660676d24) |
1. Install the Reputation Weighted extension
2. Bring up the Manage Verified Members form
3. Set the decision method to Reputation
4. Set the add/remove field to Add members
5. Fill in the other required fields
6. Submit the form and wait for the Completed Action component to come up
7. Verify that you can see the Motions component
8. …
> Fix: Correctly show staking information for the Manage Verified Members action

- src/components/v5/common/ActionSidebar/partials/TeamColorField/TeamColorField.tsx
- src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
It's not pixel perfect compared to the [Figma designs](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-177&t=I6SkwLY4baMEi24f-4) when it comes to non-mobile phone specific viewports below the 768px width breakpoint but hopefully this satisfies the AC when it comes to actual phone dimensions like the iPhone SE or the iPhone 14 Pro Max.
As a side note, this `SearchItem` component seems to manage various scenarios, resulting in a couple of conditional and shared styles that can be challenging to maintain over time. Ideally, in the future, we should create a dedicated component specifically for the colour picker.
| Before (iPhone SE) | (After) iPhone SE |
| ![Screenshot 2024-06-04 at 19 18 …
> Fix: Team colour picker mobile view UI adjustments

- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/redux/sagas/expenditures/createStakedExpenditure.ts
- src/redux/types/actions/expenditures.ts
This will allow the `createStakedExpenditure` saga to handle Payment Builder actions that were made using the "Reputation" decision method.
I was using @jakubcolony's local API debugger while developing this. 
1. Enter an amount in the Transaction Amount field
2. Click the "Create staked expenditure" button
3. Reload the page ( important❗)
4. Click the most recent transaction in the Activities table
5. Ignore the Title, just make sure that:
a.) The amount field value is correct
b.) The staking information is correct
6. Open the User Hub popover and click on the Transactions tab
7. Expand the first Transaction in the list
8. Verify that the information is correct and the step indices (1. 2. 3. 4. 5.) are sequentially correct
**Changes** 🏗
The `createStakedExpenditure` can now automatically …
> Feat: Conditionally auto activate tokens when processing a Staked Expenditure

- src/components/frame/Extensions/pages/PermissionsPage/IndividualPermissionsPage.tsx
- src/components/frame/Extensions/pages/PermissionsPage/hooks.tsx
- src/components/frame/v5/pages/MembersPage/utils.ts
When the "All teams" filter is toggled, the selected team ID is `undefined` which was throwing off the logic. This PR handles that scenario so members are correctly filtered when the "All teams" filter is enabled.
| Amy shown as Admin in Serenity | Amy shown as Admin in All teams |
| ![Screenshot 2024-06-05 at 20 44 01](https://github.com/JoinColony/colonyCDapp/assets/50642296/27ee832d-85f4-4439-b46a-c9254cc2a127) | ![Screenshot 2024-06-05 at 20 43 40](https://github.com/JoinColony/colonyCDapp/assets/50642296/01e228a4-3639-47b5-93ef-cfb1d063a552) |
1. Give a user, let's call them USER, Admin permissions for the Serenity team
2. Reload the page ( important ❗️)
3. Head over to the Permissions page `http://localhost:9091/{colonyName}/permissions`
4. Set the teams filter to …
> Fix: Correctly show members and their role categorisations based on the Team filter

- src/components/v5/common/ActionSidebar/hooks/useGetColonyAction.ts
Currently, there's a bit of a race condition that occurs whereby polling for a Colony Action gets cancelled prematurely even though the intention is to only stop it when the Action Sidebar unmounts.
This PR ensures the original intent of stopping a poll only when the component unmounts is respected.
**Prerequisite**: If you don't currently have a network monitoring tool for GraphQL queries, install the [GraphQL Network Inspector browser add-on](https://chromewebstore.google.com/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln?hl=en-GB)
1. Bring up the Payment Builder action form
2. Fill in all required fields
3. Make sure to enter a description
4. Submit the form
5. Open your GraphQL monitoring tool
6. When the Completed Action component mounts, verify that the …
> Fix: Show the Expenditure's description on the Completed Action component

- src/components/v5/common/CompletedAction/partials/rows/Description.tsx
Wrapping too long words in action description
* Step 1. Create a new action.
* Step 2. Add a description with a long string, e.g. a long URL.
* Step 3. Complete the action and then view the description.
* 
**Changes** 🏗
* styles update in the `Description` component that is used for completed actions
* 
- 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2393
> fix: description word break

- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/hooks.ts
- Fix issue where the user could fully stake for support twice
- Create a simple payment action and select the reputation decision method.
- Create and sign action
- Fully stake and support
- Try to immediately stake and support again. The buttons should be disabled and not allow you to.
Video of original issue can be found here: https://github.com/JoinColony/colonyCDapp/issues/2416
**Changes** 🏗
* Disable staking buttons while a motion is being refetched.
Resolves #2416
> Fix: Don't allow user to stake while a previous stake is loading

- src/components/v5/common/AvatarUploader/hooks.ts
- src/components/v5/common/AvatarUploader/partials/ErrorContent.tsx
- src/components/v5/common/AvatarUploader/utils.ts
There's currently an error being thrown by the `pica` lib whenever a file is being selected in our image uploader due to Brave's fingerprint blocking mechanism which is enabled when the Brave Shields are up.
I'm waiting for Arren's thoughts on this but last time I discussed this with Raul & Chris, it was decided that the most optimal solution **for now** is to describe to the user what the error is. Because the preferred fix is much more complex and will take up a lot of time. Here's a proposal for the error message:
<div align="center">
</div>
I will need @rdig's or @chmanie's thoughts with this one. I am unable to find a way to replicate it locally. From what I understand, the on-demand qa environment isn't set up yet so I'm guessing we should just take a gamble and test this once it's …
> Fix: Handle image upload error due to fingerprint blocking

- src/components/frame/Extensions/pages/PermissionsPage/hooks.tsx
This PR will now show the correct member list when the "All teams" filter is set on the Permissions page.
**Testing steps**
> I'm choosing `adam-advent` because he doesn't appear in the first chunk of a paginated members list
>
> For anyone else testing: `adam-advent` won't necessarily appear outside of the first chunk of the paginated members list (the order in which users are generated is different each time the create-data script is ran) pick a member low down the list when giving them permissions
1. Using the Manage Permissions action, give user `adam-advent` Owner permissions
2. Reload the page
3. Visit the Permissions page
4. Verify that you can see `adam-advent` under the Owner group
I guess for an easy comparison:
1. Checkout to the `master` branch
2. Reload the Permissions page …
> Fix: Correctly show user permission groupings on the Permissions page

- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- Fix an issue where the balance was not being consistent in different places across the UI
- Add loading state to balance table
- Go to the balances page note the balance.
- Create a Payment builder action (while still on balances page in the background) and fund it, but don't release it.
- Close the sidebar to go back to the balances page. The balance should still be the same.
- Start to create a new simple payment action (don't actually create it).
- Check the available funds from token drop down. This should be equal to the balance shown in the balance table minus the amounts currently held in expenditure funding.
- Close the sidebar to go back to the balances page.
- Refresh the page and be ready to check the loading state.
- Once the page reloads it should show a skeleton loader, …
> Fix: Inconsistent balances across the ui

- .github/workflows/build-deploy.yaml
- src/components/shared/CurrencyConversion/CurrencyConversion.tsx
- src/hooks/useCurrency.ts
- src/utils/currency/config.ts
- src/utils/currency/currency.ts
- src/utils/currency/tokenPriceByAddress.ts
- Use the network_id environment variable to determine which asset platform should be used while calling the CoinGecko api.
A little trickier to test properly, but there's some things you can do:
- Go to the balances table and refresh the page with the network tab open in dev tools.
- If you check the network tab you should find some calls to the CoinGecko api:
- Change`NETWORK_ID="ganache"` in your .env.local file to be `NETWORK_ID="gnosis"`
- Repeat the first two steps
- You should now see the call being made with `xdai` instead of `arbitrum-one` as the asset platform
The main idea here is that on production, it is currently incorrectly calling with `xdai` as the asset platform, whereas it should be using `arbitrum-one`. The network_id environment variable on production is …
> Fix: Use correct asset platform when calling CoinGecko

- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx
This PR simply unmounts the the staking form if the user is not allowed to stake.
**Prerequisites:**
1. Visit the GraphQL playground and run the following query to generate an invite code for the "planex" Colony
```
getColonyByName(name: "newcolony") {
items {
colonyMemberInviteCode
}
}
}
```
2. Copy the invite code i.e. `bf7ebc5a-ccff-4d14-a195-dc6b88cb72a3`
**Steps**
1. `*incognito window*` Connect Dev Wallet 16 and create a profile
3. `*incognito window*` Visit the invite page for the "planex" Colony at http://localhost:9091/invite/planex/{yourInviteCode}
4. `*non-incognito window*` Log in as Leela (Dev wallet 1)
5. `*non-incognito window*` Install and Enable the "Reputation weighted" extension http://localhost:9091/planex/extensions/VotingReputation
6. `*non-incognito …
> Fx: Remove staking form for users who are not allowed to stake

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
- src/i18n/en-actions.ts
- src/i18n/en.json
Rename Payment Builder action to Advanced Payment
Refactor 'Payment Builder' action to 'Advanced payment'
* Step 1. Create new payment builder action 
* Step 2. Check naming is 'Advanced payment'
Resolves #2493
> Chore: Rename payment builder action

- src/components/common/InvitationBlock/InvitationBlock.tsx
- src/components/common/Onboarding/WizardSidebar/DesktopWizardSidebar.tsx
- src/components/common/Onboarding/WizardSidebar/MobileWizardSidebar.tsx
- src/components/common/Onboarding/WizardSidebar/WizardSidebar.tsx
- src/components/common/Onboarding/helpers.ts
- src/components/common/Onboarding/wizardSteps/ButtonRow.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenComponents.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenInputs.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/StepTokenChoice.tsx
- src/components/frame/LandingPage/LandingPage.tsx
- src/components/frame/LandingPage/LandingPageItem.tsx
- src/components/v5/common/AvatarUploader/AvatarUploader.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/components/v5/shared/Stepper/Stepper.tsx
- src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
- src/components/v5/shared/Stepper/partials/StepperButton/types.ts
- src/components/v5/shared/Stepper/types.ts
- src/hooks/useScrollIntoView.ts
Refactor landing page item to render children
Fix styling issue on smaller devices
TODO: Button styling issue for actionable item list on landing page.
* Step 1. Open landing page
* Step 2. Check the actionable item list on both mobile and desktop
Resolves #2111
> Fix: Style for onboarding flow

- src/components/frame/v5/pages/MembersPage/partials/MembersTabContent/MembersTabContentWrapper.tsx
Fixed padding for members tabbed menu.
| <img width="600" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/cc760500-0dd4-4a44-951c-fd2f379a041e"> | <img width="600" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/51f427a8-8872-40a6-ba0b-b40a6a8d3387"> | 
(Resolves | Contributes to) #2504
> fix: Update members pages tabbed menu padding

- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
Fixed opening settings in action sidebar. The problem was that the settings had top: `100% !important`, which helped position it under the header. However, in the case of the action sidebar, the "relative"-fixed value was higher on the wrapper with the header plus action form, so the settings screen was positioned down, under the action form.
Position: relative on the correct div fixed that.
* Step 1 Set screen size to mobile
* Step 2 Create a new action to open the action sidebar
* Step 3 Attempt to open the settings menu
(Resolves | Contributes to) #2548
> fix: Unable to open settings menu on mobile when action sidebar is open

- package.json
- scripts/forward-time.js
This is a cherry-pick of a commit from #2513 as I want to make it available before it gets merged. 
The days of manually copying curls from https://www.notion.so/colony/Time-in-development-f1283a43c09e46bb97f15accd438069b and adjusting the params (pity if you pasted into console before doing so!) are finally gone, as now you can simply run:
```
npm run forward-time -- <number_of_hours>
```
Which will do all the "heavy" lifting for you. 
On a side note, I really don't like the `--` bit but it's necessary when you run a script using npm run.
**Note:** as @rdig mentioned, advancing time when reputation monitor is on will not work properly, and similarly any time-bound features such as staking won't function, so please make sure to disable it before adjusting time manually.
Navigate to some …
> Feat: Add `forward-time` script advancing EVM time

- docker/colony-cdapp-dev-env-base
For a while now, we've been plagued by our docker builds failing at the `npm ci` step intermittently 
https://discord.com/channels/@me/1184783345406705766/1250770038194180167
https://discord.com/channels/@me/1184783345406705766/1251124500792213615
https://discord.com/channels/@me/1184783345406705766/1252368133046665271
Some of us just brute forced our way through, by re-running the build until it succeeded, others used VPN while building _(which strangely helped)_, and for others, like me, this would actually saturate my load balancer and kill my network
The issue _seems_ to be related to an old version of `npm` that we were running inside the docker images, so the obvious solution here was to just update it to the latest version.
Current latest is `10.8.1`, and while I want the latest, I …
> Fix Local Dev Env Docker NPM Flakiness 

- src/components/v5/frame/ColonyHome/partials/TokenBalance/hooks.ts
- src/utils/currency/currency.ts
- Ensure that the total funds widget on the dashboard updates when the team filter is changed.
* Go to the balances page and take note of the balances for all teams, and for a specific team by changing the team filter at the top.
* For example, here under `all teams`, the total balance is 12.9996M EUR, but under `serenity`, the total balance is 168 EUR.
* Go to the dashboard, and check the total funds widget to ensure that the funds are correct for `all teams` and the team you looked at before.
* Added a new dev mode mock when the current price of a token is fetched.
**Changes** 🏗
* Fix the total funds widget to take the currently selected domain into account.
Resolves #2503
> Fix: Show correct funds amount per team in the total funds widget

- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/ManageReputationTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/hooks.tsx
- src/components/v5/common/Fields/InputBase/hooks.ts
- src/i18n/en.json
Update payment builder action input placeholder values 
Update manage reputation action input placeholder value 
Use usePlaceholderAsFallback flag for InputBase width 
Add translations
* Step 1. Create Payment builder/Advanced Payment action
* Step 2. Check the placeholder for the Amount field is 'Enter amount'
* Step 3. Check the placeholder for the Claim delay field is 'Enter value'
* Step 4. Create Manage Reputation action
* Step 5. Check the placeholder for the Change field is 'Enter value'
Resolves #2507
> Fix: update action input fields placeholders

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/frame/v5/pages/MembersPage/utils.ts
- src/context/ColonyManager.ts
- src/graphql/generated.ts
- src/redux/sagas/extensions/extensionUninstall.ts
This PR adds the functionality to deprecate and uninstall the multi sig extension.
The heavy lifting is done by the block-ingestor :)
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/236)
This is gonna be a lot to test, but here are 2 handy queries
Getting multisig motions:
```
listColonyMultiSigs(
filter: {colonyAddress: {eq: "YOUR_COLONY_ADDRESS"}}
) {
items {
action {
type
}
colonyAddress
createdAt
isExecuted
isRejected
isSuccess
nativeMultiSigId
signatures {
items {
colonyAddress
multiSigId
role
userAddress
vote
user {
profile {
displayName
}
}
}
}
}
}
```
Get multisig roles:
```
listColonyRoles(
filter: {isMultiSig: {eq: true}, colonyAddress: {eq: "YOUR_COLONY_ADDRESS"}}
) {
items {
colonyAddress
id
isMultiSig
targetUser {
profile {
displayName
}
}
targetAddress …
```
> [Multi-sig] feat: uninstallation of multi-sig extension

- src/components/v5/frame/ColonyHome/partials/Members/Members.tsx
1. Create a new team
2. Go to the Dashboard
3. Filter the view by the team you just made
4. Keep track of the Members count
5. Click on the Members widget
6. Verify that the number of members you see corresponds to the number shown on the Members widget from the Dashboard
**Changes** 🏗
* Updated the members array being used to show the number of members per team on the Dashboard
Resolves #2502
> Fix: show the correct team members count when a team filter is applied on the Dasbhoard

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/shared/UserInfoPopover/UserInfoPopover.tsx
- src/components/v5/shared/UserInfoPopover/partials/UserNotVerified.tsx
Members page
* Go to the members page.
* Click on a member who is not verified to open their Memberpopover.
* Click on the Add as verified member link.
Action panel
* Create a new action.
* Select the Simple payments action type.
* Select a member who is not verified.
* Click on the yellow warning icon.
**Changes** 🏗
* `Add as verified member` button will now open sidebar with selected action and member.
Resolves [#2117](https://github.com/JoinColony/colonyCDapp/issues/2117)
> fix: add verified member from user popover

- src/components/v5/common/Fields/InputBase/FormattedInput.tsx
Fix: Unnecessary outline styles for withdrawing modal input
Bug related only to the Firefox browser 
Issue: https://github.com/w3c/csswg-drafts/issues/4925
| ![image](https://github.com/JoinColony/colonyCDapp/assets/15706494/b96cb36e-a56b-4ba3-9877-1ee9a9f1f6f8) |  ![image](https://github.com/JoinColony/colonyCDapp/assets/15706494/b7d585e8-8713-40f8-af5d-08d5af6e9a6c") |
Resolves #2550
> Fix: Modal input: active state styling issue in Firefox

- src/components/v5/frame/ColonyHome/partials/Agreements/Agreements.tsx
Remove comments number from colony home agreement card
- Remove comments number from colony home agreement card
- Add TODO to re-enable the comment number once this feature is implemented
TODO: Check is comments number still shows for an agreement on the colony home page
* Step 1. Create an agreement
* Step 2. Go to colony dashboard
* Step 3. Check agreements section
Resolves #2505
> Fix: remove comments number from agreement

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
- src/i18n/en.json
- Fixed: missing title for claim funds if it was a meta transaction
- Fixed: no links for claim funds transactions 
1. Create two colonies.
2. Ensure you have MetaTransactions enabled. (this will likely require some trickery with local dev)
3. Transfer funds from one colony to another.
4. Go to the Incoming funds page.
5. Claim the incoming funds.
6. Check the Transactions tab in the UserHub.
7. Notice that the translation is missing for the claim incoming funds transaction when using MetaTransactions.
| ![image](https://github.com/JoinColony/colonyCDapp/assets/15706494/5a8d537e-808f-46d8-8033-f8d2a81b7786) | <img width="466" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/6dcc7feb-fb83-4555-89be-3b0e9484ca87"> |
8. Click on …
> fix: UserHub Missing transaction text and should not be clickable for claimFunds transaction

- src/components/common/ColonyActionsTable/hooks/useColonyActionsTableColumns.tsx
- src/components/common/ColonyActionsTable/partials/ActionMobileDescription/ActionMobileDescription.tsx
- src/components/common/ColonyActionsTable/utils.ts
- src/components/common/Extensions/SpecificSidePanel/hooks.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementCard/AgreementCard.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementsPageFilters/utils.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/PermissionSidebar.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizeWithPermissionsInfo/FinalizeWithPermissionsInfo.tsx
- src/components/v5/common/Fields/datepickers/common/consts.ts
- src/utils/getFormattedDateFrom.ts
- Date formatting in the app should be with months in shorthand, such as 14 Sep 2024
* Click through page and check if months are in shorthand (`14 Sep 2024`)
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2349](https://github.com/JoinColony/colonyCDapp/issues/2349)
> fix: unified date format

- scripts/create-data.js
Refactored the create-data script in order to minimise failure while creating too many users all at once.
The random users creation is batched in chunks of 3.
Also, added a new method  `graphqlRequestPreconfigured` to enclose the `GRAPHQL_URI` and `API_KEY` used for the `graphqlRequest`
Add character limits for 
- user fields: displayName, bio and location
- colony fields: displayName and objective.title
* Step 1. Run `npm ci`
* Step 2. Run `npm run dev`
* Step 3. Run `node ./scripts/create-data.js --yes`
* Step 4. Check if there are any errors while creating the data
Resolves #[2606](https://github.com/JoinColony/colonyCDapp/issues/2606)
> Fix: Create random users in batches in create-data script

- src/components/v5/shared/Stepper/Stepper.tsx
1. Enable the "Reputation weighted" extension and use the "Testing governance" preset
2. Create a Simple Payment and choose the "Reputation" decision method
3. Support the stake and submit the Max staking amount
4. Run the following commands to forward the time:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_increaseTime","params":[3600],"id":1}' localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","method":"evm_mine","params":[],"id":1}' localhost:8545
```
5. Reload the page
6. Make sure the app doesn't crash
* Just a good ol' optional chaining to make sure we're not extracting a field from an undefined object.
Resolves #2538
> Fix: prevent app crash on mobile view when viewing a transaction that's ready to be finalized

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/PaymentBuilderTable.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/RecipientField/RecipientField.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/RecipientField/types.ts
- src/components/v5/shared/UserInfoPopover/UserInfoPopover.tsx
- src/components/v5/shared/UserInfoPopover/types.ts
- src/components/v5/shared/UserPopover/UserPopover.tsx
Payment builder table loading state
* Step 1. Create a Payment builder action.
* Step 2. Add a few rows to the payment.
* Step 3. Create the payment, keeping an eye on the payment builder table.
* 
**Changes** 🏗
* loading state passed to `RecipientField` and `UserPopover` components
* 
- 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2414
> fix: payment builder table loading state

- src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarMobileContentWrapper/NavigationSidebarMobileContentWrapper.tsx
Keep z-index for NavigationSidebarMobileContentWrapper component regardless of open state
The navigation sidebar was getting behind the other elements on the page upon closing, causing it to appear as if it was losing it's background color.
* Step 1. Adjust viewport to mobile
* Step 2. Open navigation sidebar
* Step 3. Close navigation sidebar 
* Step 4. Check styling
Resolves [#2539](https://github.com/JoinColony/colonyCDapp/issues/2539)
> Fix: Keep z-index for mobile navigation sidebar regardless of open state

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/UserSelectRow.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/hooks.tsx
- src/components/v5/common/Table/Table.tsx
Fix: Select member incorrect tooltip on actions
1. Open any action type that has a select member input field
2. Hover over the placeholder
3. The tooltip will NOT show
4. The tooltip will show only for error state
Resolves #2514
> fix: Select member incorrect tooltip on actions

- amplify/backend/function/fetchTokenFromChain/src/graphql.js
- amplify/backend/function/fetchTokenFromChain/src/index.js
This PR adds some validation to the `fetchTokenFromChain` lambda to better check is the provided address is a "valid" token. (It is not really possible to check if it is a "valid" token, but it implements the following: )
* The function already returns the token if it exists in our database
* If it does not exist as a token in our database, it will now check if it exists as either a colony address or a user address and will throw an error if it is already in use for one of these as it therefore means it cannot be a token address.
* If it still does not exist in our database, it will call the required ERC20 functions - if none of these throw an error, it is likely an ERC20 token contract
This is probably still not foolproof, but it does at the very least prevent users from putting in …
> Feat: Add extra checks to fetchTokenFromChain to better validate address

- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
- Set the createdIn field to read only, and fix it as root, when making a motion of type Move Funds.
- Right now, only General (the root domain) should be allowed to be used when making this type of motion, since no other domain will work. The created in domain must be a parent domain of both the To and the From domains.
- Install the reputation weighted extension (then refresh the page).
- Create a new action, and select Transfer Funds as the action type, and Reputation as the decision method.
- Try to change the created in field. You should not be able to, and it should be `General`.
**Changes** 🏗
* Set the createdIn field to read only, and fix it as root, when making a motion of type Move Funds.
Resolves #2683
> Fix: CreatedIn Field should be read only for Move Funds motions

- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/UserNavigationWrapper.tsx
- src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/types.ts
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/types.ts
- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
- src/components/v5/frame/PageLayout/partials/PageHeading/PageHeading.tsx
- src/components/v5/shared/Modal/Modal.tsx
- src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx
- src/hooks/useAddClassToElement.ts
- src/styles/main.css
- src/utils/checks/isChildOf.ts
- src/utils/elements.ts
- tailwind.config.js
Fix for transaction pending button overlapping issue
* Step 1. Create an action, so that the side panel is open.
* Step 2. Click on the UserHub.
* Step 3. Click on the Activate button.
* Step 4. Activate some tokens.
* Step 5. Check if the transaction pending button is still overlapping.
* 
**Changes** 🏗
* blur-related styles are now added to elements with `modal-blur` or `modal-blur-navigation` classes
* there's no duplication of the user navigation component on the desktop view - the same component is shown when a modal is open and closed
* The user navigation component is moved to the top when the `shouldShowHeader` prop is passed to the `Modal` component
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2456
> fix: user hub placement

- src/components/shared/Fields/Form/Form.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/ClaimDelayField/ClaimDelayField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/ClaimDelayField/consts.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/ClaimDelayField/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/UserSelectRow.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/utils.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/PaymentBuilderTable.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/ClaimStatusBadge/ClaimStatusBadge.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentCounter/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/PaymentStepDetailsBlock.tsx
- src/components/v5/common/Fields/InputBase/InputBase.tsx
- src/components/v5/common/Fields/InputBase/hooks.ts
- src/components/v5/common/Fields/InputBase/types.ts
- src/i18n/en.json
- src/utils/elements.ts
- src/utils/extensions.ts
Claim delay field validation updated so that a user has to add a number between 0.0001 and 99999.
* Step 1. Open action sidebar and select `Payment builder` action type
* Step 2. Edit `Claim delay` field inside the table with payments and check if the validation works as it should.
* `ClaimDelayField` component - uses `cleave-zen` inside
**Changes** 🏗
* `delay` field validation updated
* `claim delay` column value formatting updated for completed action
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2368
> fix: claim delay field validation

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/ColonyActions/helpers/getActionTitleValues.ts
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/components/v5/common/ActionSidebar/hooks/permissions/helpers.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/ManagePermissionsDescription.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/MultiSigWidget.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/RemoveVoteButton/RemoveVoteButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/VoteButton/VoteButton.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/utils.ts
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/components/v5/common/CompletedAction/partials/MintTokens/MintTokens.tsx
- src/components/v5/common/CompletedAction/partials/SetUserRoles/SetUserRoles.tsx
- src/components/v5/common/CompletedAction/partials/rows/TeamFrom.tsx
- src/i18n/en-actions.ts
- src/i18n/en.json
- src/redux/sagas/motions/managePermissionsMotion.ts
- src/redux/types/actions/motion.ts
- src/utils/multiSig.ts
Related block-ingestor PR: https://github.com/JoinColony/block-ingestor/pull/247
As a user moderating a colony, I want to be able to create and finalize a multi-sig manage roles motion.
It should be possible to create a manage permissions multi-sig motion in the general team. Users with the `root` role (owner) should be able to create, vote and finalize.
It should be possible to create a manage permissions multi-sig motion in any sub team. Users with the `architecture` role (admin) should be able to create, vote and finalize.
(At a later point, in a sub team it should be possible to vote if you have either the `root` or `architecture` role in `general`, but this will be addressed in a separate PR.)
(Note: The completed action screen will not show the correct permissions if you are …
> Feat: Refactor manage permissions motion to handle multi-sig

- package.json
- scripts/create-data.js
This PR adapts the create-data.js script to make it easier to generate colonies on the previous colony version.
Note: This will only actually work if you have deployed the previous colony version. Many thanks to @area  for making this super easy.
* Step 1 - Run `npm run dev` and `npm run frontend` as per usual
* Step 2 - Before running the create-data script, run `npm run hardhat` to open the hardhat console.
* Step 3 - Paste the following into the hardhat console:
```
deployHMWSS = require('./scripts/deployOldUpgradeableVersion.js').deployColonyVersionHMWSS
cn = await artifacts.require("IColonyNetwork").at("0x777760996135F0791E2e1a74aFAa060711197777")
await deployHMWSS(cn)
```
This will take some time to complete.
If you want to confirm both colony versions are available you can run the …
> Feat: Adapt create data script for previous colony versions

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/utils.ts
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/components/v5/common/CompletedAction/partials/ManageReputation/ManageReputation.tsx
- src/i18n/en-actions.ts
- src/redux/sagas/actions/manageReputation.ts
- src/redux/sagas/motions/manageReputationMotion.ts
- src/redux/types/actions/motion.ts
- src/utils/multiSig.ts
- Allow users to manage reputation using a multi-sig action.
Block Ingestor changes [here](https://github.com/JoinColony/block-ingestor/pull/253)
**First**: Restart your dev env so that you have the correct block ingestor version running. Also visit http://0.0.0.0:3001/reputation/monitor/toggle (make sure you do this only once [or three times, or five...]! - this is explained [here](https://www.notion.so/colony/Reputation-in-development-c05b7a1f79fc4465a220c2806792e4a7)) so that reputation updates happen in dev.
* Step 1. As Leela, install Multi Sig Extension, and set the threshold to 2 (then refresh the page).
* Step 2. Create an action to give Amy multi-sig permissions (then refresh the page).
* Step 3. Navigate to the Contributors tab, and make a note of Fry's reputation. Here you can …
> Feat: Manage Reputation via Multi-Sig

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/PermissionSidebar.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizeWithPermissionsInfo/FinalizeWithPermissionsInfo.tsx
- Changed font-size for usernames in permission cards
- Paddings of motion cards seems to be fixed in some other PR
* Create any action using permissions
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2337](https://github.com/JoinColony/colonyCDapp/issues/2337)
> fix: changed userpopover font-size

- src/components/shared/ExternalLink/ExternalLink.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/MultiSigSidebar.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/hooks/useRelevantUserRoles.ts
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/MultiSigWidget.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ThresholdPassedBanner/ThresholdPassedBanner.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/utils.ts
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/Signees/partials/RoleApprovalTooltip/RoleApprovalTooltip.tsx
- src/components/v5/shared/MenuWithSections/MenuWithSections.tsx
- src/constants/externalUrls.ts
- src/hooks/multiSig/useDomainThreshold.ts
- src/types/multisig.ts
- src/utils/colonyRoles.ts
Display a banner displaying info that a user's vote won't count towards the total if they only have roles which have already passed the threshold.
The only way to test this now is using the simple payment action.
There's gonna be a lot of setup, but it's not so hard to test once you have the initial setup done :)
You will need 3 browsers, `leela`, `amy` and `fry` logged into each of them
1. Install the multisig extension
2. Set the threshold to Fixed with the number of approvals of 2
3. Assign a random user that's not `fry` or `amy` Payer multi-sig permissions
4. Assign `amy` custom multi-sig permissions - Arbitration and funding
5. Assign `fry` just the funding multi-sig permission 
6. Refresh the page and create a `Simple payment` action as `leela`, note that all 4 users should display …
> [Multi-sig] feat: display banner if user's approval/rejection won't count towards the total

- docker/colony-cdapp-dev-env-block-ingestor
- scripts/create-data.js
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/components/v5/common/CompletedAction/partials/UpgradeColonyVersion/UpgradeColonyVersion.tsx
- src/i18n/en-actions.ts
- src/utils/multiSig.ts
This PR enables users to upgrade their Colony's version via a Multi-Sig motion.
As of the time this PR is created, the most recent Colony version is 16. In order to test a Colony version upgrade, we will need to deploy a newer Colony version since the Multi-Sig extension is only available from Colony version 16 upwards.
> [!IMPORTANT]
> Please test this with these block-ingestor updates: [block-ingestor#254  - Feat: Enable Colony version upgrade via a multi-sig motion](https://github.com/JoinColony/block-ingestor/pull/254)
> 1. Updates were made for `colony-js` so it's important you run `npm ci`
> 2. Run `npm run dev`
> 3. Wait for the auth proxy and block-ingestor services to be up and running
> 4. Open the `hardhat` console:
> ```bash
> npm run hardhat
> ```
> 5. Confirm that you are …
> Feat: Upgrade Colony version via Multi-Sig

- src/context/UserTransactionContext/UserTransactionContextProvider.tsx
Part of the fix for flashing "Pending" button when rejecting first transaction. 
* Step 1. Ensure you are connected locally via a Metamask wallet. (Let me know if you are unsure how to do this)
* Step 2. Perform a transaction with multiple grouped transactions, e.g. staking with no activated tokens.
* Step 3. Reject the first transaction.
* Step 4. Check if the Pending button is stuck in a flashing state.
* 
**Changes** 🏗
* Checking if any transaction group failed, so that the pending state won't be applied
* 
Contributes https://github.com/JoinColony/colonyCDapp/issues/2397
> fix: flashing pending button

- src/components/common/Onboarding/wizardSteps/StepCreateUser/StepCreateUser.tsx
- src/components/frame/v5/pages/OnboardingPage/OnboardingPage.tsx
- src/redux/sagas/users/index.ts
Due to check in OnboardingPage if it is user-flow and user exists, we were redirected to "/" , because the user were added on First step. So we never came to second (redirect) step because of it.
Step 1. Create invite link: 
```
listColonies {
items {
id
colonyMemberInviteCode
name
}
}
}
```
And put `colonyMemberInviteCode` in the URL:
`http://localhost:9091/invite/planex/{colonyMemberInviteCode}`
Step 2. Connect empty wallet (4-16 dev wallets are good for testing)
Step 3. Go to your generated link: http://localhost:9091/invite/planex/{colonyMemberInviteCode}  
You will be redirected to `/create-profile` page 
Step 4. Fill form and submit
Step 5. You should be redirected to http://localhost:9091/invite/planex/{colonyMemberInviteCode}  
Another case to test:
Step 1. Connect …
> fix: redirect back to invite colony screen after creating user

- src/redux/sagas/motions/stakeMotion.ts
In very specific cases there can be a problem with two transactions appearing to be pending when staking a motion (see @arrenv's [issue](https://github.com/JoinColony/colonyCDapp/issues/2739) for a full walkthrough).
This is a problem with the order certain transaction functions are called. In this case a transactions further down is set to pending while two others are not completed yet. This PR fixes that. For a fix that resolves this for good see my [Transactions API refactor](https://github.com/JoinColony/colonyCDapp/pull/2528) in which this can't happen.
Follow the steps in @arrenv's [issue](https://github.com/JoinColony/colonyCDapp/issues/2739). At least you should not be seeing two loading spinners.
**Changes** 🏗
* Fix `stakeMotion` action pending transaction order
* Add some more …
> Fix pending order of `stakeMotion` transactions

- src/components/v5/common/ActionSidebar/hooks/useGetColonyAction.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/hooks.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/MultiSigSidebar.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/MultiSigWidget.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ThresholdPassedBanner/ThresholdPassedBanner.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/utils.ts
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/RemoveVoteButton/RemoveVoteButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/VoteButton/VoteButton.tsx
- src/constants/permissions.ts
- src/graphql/fragments/roles.graphql
- src/graphql/generated.ts
- src/graphql/queries/roles.graphql
- src/hooks/multiSig/useDomainThreshold.ts
- src/hooks/multiSig/useEligibleSignees.ts
- src/hooks/useActivityFeed/helpers.ts
- src/redux/sagas/utils/proofs.ts
- src/redux/types/actions/multiSig.ts
- src/types/multiSig.ts
- src/types/multisig.ts
- src/utils/multiSig/getEligibleSignees.ts
- src/utils/multiSig/index.ts
This was a doozie :) I wanted to simplify our fetching of eligible signees to not use a 2d array anymore and it actually worked!
Only 2 test cases to try out, no need to reset anything in between
1. Install the MultiSig extension and give it a fixed threshold of 2
2. Refresh the page and try to create any action with Multi-Sig as the decision method
Manage reputation is also of special interest to us 
3. You shouldn't be able to create any multi sig motion, because `leela` is the only permission holder
On to the next test case we go!
1. Assign `amy` `arbitration` and `administration` Multisig roles
2. Assign `fry` `funding` and `architecture` Multisig roles
3. Refresh the page and create a simple payment motion
4. Verify that when hovering over `amy`'s `Awaiting 2` (the square for the 2 …
> [Multi-sig] feat: get eligible signees from the database instead of context

- docker/colony-cdapp-dev-env-auth-proxy
This PR simply updates the auth proxy hash, the real changes are [here](https://github.com/JoinColony/colonyCDappAuthProxy/pull/23)
Basically what we need to do is, ensure mutations to update a transaction only pass the auth proxy if the `from` parameter in the request is not only the same as the currently logged in user, but also the same as the `from` parameter of the actual transaction in the database. Give me (or @chmanie) a shout on Discord if you want more information on that!
**Restart your stack so that the correct auth proxy version is running.**
This is a little tricky to test, but bear with me here...
* Step 1. Open the dev console in the network tab, log in as Leela, and make a Mint tokens action.
* Step 2. In the network tab, find the graphql request where the operation name …
> Fix: Check transaction creator on transaction update calls

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
This is a very simple PR to hopefully solve a nuisance that has consistently been occurring for me for quite some time. I'm not really sure if it is the right way to solve it, but it seems to make sense.
Basically, I am just assigning a value to a visible component instead of having the initial value as undefined. Validation still works, and the field seems to work as expected still.
| Step | Expected |
| :--- | :-- |
| Create an action with an Amount field (e.g. Simple payment) and enter a value. | You should not get an error in console. |
- Changed initial undefined value to empty string in `AmountField` component.
- The first time entering a value in the Amount field of an action results in a console error "A component is changing an uncontrolled input to be controlled."
- Error can be …
> Change undefined to empty string in AmountField component

- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/MultiSigWidget.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/utils.ts
As the user who created the multi-sig motion, I should be able to cancel it when clicking "reject".
This PR fixes some conditional statements to correctly show the "reject as owner" notification and ensure the "reject" button calls the "cancel" saga when you are the user who created the multi-sig motion.
This PR also removes the "finalize cancellation" step now that the contract automatically rejects when the rejection threshold is met.
New addition: This PR also makes it so that once the approvals threshold has been met, it is possible to return to the "approval" step and remove your "approval" vote.
* Step 1 - Install the multi-sig motion, set the fixed threshold to 2 and assign Owner permissions to Amy.
* Step 2 - Create any multi-sig motion
* Step 3 - Remove your automatic approval …
> Fix: Reject multi-sig as owner button and message

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/hooks.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/MultiSigMembersError/MultiSigMembersError.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/MultiSigMembersError/useHasEnoughMembersWithPermissions.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
When we were loading member data, we didn't disable submit, so users with a slow connection could technically submit the form before we even know if they can
https://github.com/user-attachments/assets/6cab29b7-5430-4bca-a43a-d130d72c61dc
1. Install the Multi-Sig extension as `leela`
2. Give `amy` `Admin` Multi-Sig permissions in `General`
3. Refresh the page, open the dev tools on the `Network` tab (or use that GQL extension, whichever really), throttle the conenction to 3G
4. Try to create a mint tokens action, change all fields except changing the decision method to `Multi-Sig`, verify that nothing gets fetched
5. Choose `Multi-Sig` as the decision method, 2 things will happen in quick succession, verify both that:
a) The form submit is disabled at first with only 2 network requests …
> [Multi-sig] feat: disable submit motion until we know if there are enough members, fetching optimisation

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/CreateStakedExpenditureModal/CreateStakedExpenditureModal.tsx
- src/components/v5/common/ActionSidebar/partials/CreateStakedExpenditureModal/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/ReleasePaymentModal.tsx
- src/components/v5/common/TokensModal/TokensModal.tsx
* Adding the user hub to the header was agreed with @arrenv 
* Make sure you have Staking advanced payments extension enabled.
* Create a Split/advanced payment with Staking decision method.
* In the staking modal click the "Create payment" button and notice the loader.
**Changes** 🏗
* Changed button loader
* Added user hub to modal header
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2705](https://github.com/JoinColony/colonyCDapp/issues/2705)
> fix: changed loading component, modal header

- src/context/TokenSelectContext/TokenSelectContextProvider.tsx
- src/graphql/generated.ts
- src/graphql/queries/token.graphql
The `GetTokensList` is hitting the query limit due to the images for each token. This PR uses nextToken to continue to fetch all "validated" tokens.
This is a bit hard to test without creating a whole bunch of tokens. Instead edit the query on line 25 in this file to include `limit: 1`: `src/context/TokenSelectContext/TokenSelectContextProvider.tsx`
```
variables: {
isValidated: true,
limit: 1
},
```
Step 1: Open the action sidebar and select manage tokens
Step 2: Add a new row and confirm you can see the 3 "validated" tokens
**Changes** 🏗
* `GetTokensList` uses nextToken to fetch all validated tokens
> Fix: Fetch validated tokens limit

- amplify/backend/api/colonycdapp/schema.graphql
- scripts/create-data.js
- src/graphql/fragments/transactions.graphql
- src/graphql/generated.ts
- src/redux/actionCreators/transactions.ts
- src/redux/immutable/Transaction.ts
- src/redux/sagas/transactions/createTransaction.ts
- src/redux/sagas/transactions/sendTransaction.ts
- src/redux/sagas/transactions/transactionChannel.ts
- src/redux/sagas/utils/effects.ts
- src/redux/sagas/utils/getCanUserSendMetatransactions.ts
- src/redux/types/actions/transaction.ts
- src/state/transactionState.ts
- src/types/transactions.ts
Metatransactions are now checked on a general basis (e.g. if the user has them enabled, they are being used). This enables the users to retry transactions as metatransactions and the other way round.
I removed a metatransaction check that was mainly used for the vesting contracts. If we still have methods that don't support metatransactions this needs to be reinstated (it wasn't used though as far as I can tell).
1) Enable metatransactions for a user
2) Try to send a transaction
**Changes** 🏗
* Check whether user has metatransactions enabled on transaction sending not on creation
* Removed metatransaction property from transactions
* Removed forced non-metatransactions
> Hotfix for metatransaction checks

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/utils.ts
- src/components/v5/common/CompletedAction/partials/SetUserRoles/SetUserRoles.tsx
- src/utils/databaseId.ts
This is just a tiny fix that brings back the auto-populate behaviour for the Roles and Permissions fields in the Manage Permissions form which got slightly affected in the recent rebase.
> [!NOTE]
>
> I am not very familiar with this new flow where we also take into account the Multi-Sig Authority for a user to properly identify the role. These steps are ported over from #2565. Please let me know if my test steps needs updating.
> [!IMPORTANT]
> - Please test this with [block-ingestor#259: Fix: conditionally add multisig chunk to historic role id](https://github.com/JoinColony/block-ingestor/pull/259)
> - I don't want you to accidentally revoke your Owner permissions for your Colony so give Amy the Owner role in the General (Parent domain) team
> - Remove all permissions from Fry in team …
> Fix: Auto-populate the Role and Permissions fields in the Manage Permissions form

- src/hooks/multiSig/useDomainThreshold.ts
Long story short, somehow we changed the format of the domainId in multisig's installed params from `<COLONY_ADDRESS>_<DOMAIN_NATIVE_ID>` to just use it's native id. This means that all subdomain's just used the global threshold :D 
1. Install Multi-Sig extension
2. Set the global threshold to 2, threshold in Andromeda to 1
3. Refresh the page and open the action sidebar
4. Verify that you can't create a `Manage reputation` action in General (since there aren't 2 permission holders there)
5. Verify that however, this would work in Andromeda
**Changes** 🏗
* `useDomainThreshold` now checks the nativeId instead of constructing the full id (also added a note to remove nullish coalescence once we merge #2800 
Contributes to #2658 (point 23)
> [Multi-sig] fix: use native domainId for getting domain from multisig extension params

- src/components/v5/shared/UserInfoPopover/partials/UserInfo.tsx
- src/hooks/multiSig/useEligibleSignees.ts
Fixes point 20 on the QoL issue.
This PR fixes an issue where a user with no multi-sig permissions would still have the icon appear on their user info popover if they had core permissions.
It also fixes an issue with the requiredRoles useEffect dependancies.
Step 1 - Install the multi-sig extension
Step 2 - Remove all multi-sig permissions from Leela
Step 3 - Refresh and check the user info popover, only Leela's core permissions should show:
Step 4 - Assign Leela multi-sig permissions in a sub-domain. Refresh and check the user info popover, they should have the icon appear next to that domain:
Step 5 - Assign Leela multi-sig permissions in general. Refresh and check the user info popover, they should have the icon next to every domain as they will have inherited permissions from the root …
> Fix: User info popover should not show multi-sig icon if no multi-sig roles

- docker/colony-cdapp-dev-env-auth-proxy
- Add new auth proxy hash (for [this commit](https://github.com/JoinColony/colonyCDappAuthProxy/commit/f1d5e35271358946ec65e9a0f7d27fa66c2b878a))
Just make sure your docker can still run with that hash!
* New auth proxy hash
Resolves #2813
> Add new auth proxy docker hash

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/hooks.ts
- src/graphql/generated.ts
- src/graphql/queries/colony.graphql
- src/hooks/useTokenLockStates.ts
- src/i18n/en.json
- src/utils/tokens.ts
It is important that users cannot make a payment with a locked token from anywhere that is not the colony which created it.
For example:
- User creates new colony `Davecol` with a new token `DaveCoin`. This coin is locked by default, until a user with the correct permissions makes an 'unlock token' action.
- Whilst the coin is locked, you should still be able to make payments with this coin wherever you want, as long as you are making that payment from within the colony `Davecol`.
- Lets say the user makes another colony `NewDavecol`, and this colony uses the already existing `DaveCoin` as it's token.
- It is completely fine to transfer funds from `Davecol` to `NewDaveCol`, even when the token is locked.
- It should _not_ be possible however, to transfer funds or make any type of payment …
> Fix: Prevent payment actions with locked tokens

- src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/ManageTokensForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/PaymentBuilderForm.tsx
- src/redux/sagas/extensions/extensionInstall.ts
We shouldn't be allowing users to try and create unsupported multisig motions in the first place.
Additionally, as discussed with product, we shouldn't do any automatic role assignment when an extension is installed. We should handle that properly as part of #2765 
1. Install the Multi-Sig extension
2. Run the following query
```
getRoleByColony(
colonyAddress: "YOUR_COLONY_ADDRESS"
filter: {isMultiSig: {eq: true}}
) {
items {
isMultiSig
role_0
role_1
role_2
role_3
role_5
role_6
targetAddress
targetUser {
id
profile {
displayName
}
}
}
}
}
```
There should be no role entries here
`leela`'s popover however, shows the roles still there, this is a bug, if they aren't in the backend, they aren't in the UI
1. Give `leela` Owner Multi-sig permissions as `leela` 
2. Refresh the …
> [Multi-Sig]: feat: disable multisig decision method for unsupported actions and disable auto role assignment

- amplify/backend/api/colonycdapp/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/FinalizeButton/FinalizeButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/utils.ts
- src/graphql/fragments/actions.graphql
- src/graphql/generated.ts
- src/i18n/en.json
- src/redux/sagas/multiSig/finalizeMultiSig.ts
- src/redux/types/actions/multiSig.ts
Instead of calling `executeWithoutFailure` we need to call `execute` if a week has passed since the motion was created.
Additionally, I've realigned multisig's createdAt date with the blockchain date.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/257)
[Figma link](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=22256-71198&t=2x9d7EMZkK6MCGCF-4)
You can do all of this as just `leela` (but for testing the rejection timestamp, you need to assign `amy` the `Owner` multi-sig role, and reject the motion as both `leela` and `amy`)
1. Install the multisig extension, you can leave the threshold as is. Assign `leela` Multi-sig owner permissions
2. Go to the balances page, choose `Andromeda` and note the amount of CREDS it has
3. Create a transfer …
> [Multi-sig] feat: allow failing multi-sig if a week has passed and realign all dates with the blockchain

- scripts/create-data.js
- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx
- src/graphql/generated.ts
- src/graphql/queries/transactions.graphql
- src/state/transactionState.ts
There was a problem with pending transactions not being put into a failed state properly. This usually happens when a proper user wallet is initialized.
This PR uses Apollo paging to put _all_ pending transactions into a failed state.
1) Stop your dev environment
2) Apply this patch (it will create 120 pending transactions during the `create-data` script.
```diff
diff --git a/scripts/create-data.js b/scripts/create-data.js
index f0ed7968e..f0a528dd9 100644
--- a/scripts/create-data.js
+++ b/scripts/create-data.js
@@ -300,6 +300,27 @@ const addTxToDb = async ({
return graphqlRequest(createTransaction, { input }, GRAPHQL_URI, API_KEY);
};
+const create120Transactions = async (userAddress, colonyAddress) => {
+  const domainBatchKey = 'createDomain';
+  for(let i=0; i<120; i++) {
+    const …
```
> fix: use paging to fail all pending user transactions

- src/redux/sagas/users/index.ts
The Apollo cache wasn't cleared on logout/disconnect wallet. This fixes it.
Follow the steps in #2864. The transactions should be cleared out.
**Changes** 🏗
* Clear Apollo store cache when logging out
Resolves #2864
> Actually clear Apollo cache on logout

- src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx
This PR solves a little annoyance with the paging end element of the transaction list.
It looks like this now:
1) Start the CDapp
2) Go to a Colony, to the UserHub, click transactions
3) Scroll all the way down
4) You should see this little fella.
Here's the Figma: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-50890&t=oNC6Rrhij7U9pY3p-0
**Changes** 🏗
* Changed styling and copy of the tx end element
> Use proper styling and copy for tx paging end message

- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/FileUploadModal/hooks.ts
- src/redux/sagas/expenditures/createExpenditure.ts
- src/redux/sagas/utils/expenditures.ts
- src/redux/sagas/utils/multicall.ts
- src/utils/arrays/index.ts
When creating an advanced payment we hit a limit on the transaction size when creating a large number of payments in one go.
This PR adds a `chunkedMulticall` helper function to split large multicalls which are too big for a single transaction, into smaller chunks.
The `claimExpenditurePayouts` function has been refactored to make use of this. A limit of 78 payouts has been set as the multicall was failing with more than this.
The `createExpenditure` saga has been refactored to use the new helper. A limit of 164 payouts has been set, when creating multicalls with more than this the multicall function would work fine, but the resulting transaction receipt was too big to update the transaction in the db.
Step 1 - Create an advanced payment action
Step 2 - Upload this csv with 400 rows (feel …
> Feat: Handle batch payment limit

- src/hooks/useNetworkMotionStates.ts
This PR fixes an issue on the local dev environment where motion status could not be properly fetched after disconnecting and reconnecting your wallet. Thanks to some digging with @rdig and @Nortsova the culprit was found.
Step 1 - Install the voting reputation extension
Step 2 - Create a motion and stake to support it
Step 3 - Disconnect your wallet
Step 4 - Connect your wallet again
Step 5 - Check the motions in the activity feed and the userhub have the correct status
(On master they will have the "Unknown" status)
Test with both a metamask wallet and a dev wallet.
**Changes** 🏗
* Properly initialize signer for VotingReputationFactory
Resolves #2643
> Fix: Motion status showing as unknown

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/consts.ts
- src/components/common/Extensions/UserHub/partials/ReputationTab/partials/Balance.tsx
- src/components/common/Extensions/UserHub/partials/ReputationTab/types.ts
- src/components/common/Extensions/UserHub/types.ts
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/components/v5/shared/TxButton/TxButton.tsx
- src/stories/common/Select.stories.tsx
This PR tries to solve the UserHub opening/closing issues by just using a single state for the visibility of the UserHub. This sadly makes things a little more complicated but there are ambitions to try to solve these issues on the UX side of things (using an improved Modal flow).
For now this should do it. We got rid of the dual state and of the ominous `data-openhubifclicked` attribute by adding some state management wizardry. We basically set the tab that should open in the UserHub from outside and then reset it once it's visible.
1. Try to have a pending TX (e.g. use MetaMask and don't confirm)
2. Click the pending TX button and hope that the UserHub opens, showing the transactions list
3. Click outside the UserHub, it should close
4. Also click some other buttons within the UserHub …
> Open UserHub on pending button click

- src/components/v5/shared/UserInfoPopover/UserInfoPopover.tsx
Fix: update used profile for avatar, displayName and userName in UserInfoPopover
There were instances of the UserPopover where the wallet address was shown instead of the username.
eg.
Install any extension.
Click on the UserPopover shown next to the "Installed by" label.
* Step 1. Install any extension
* Step 2. Click on the user pill next to `Installed by`
* Step 3. Check user name is displayed properly
* Step 4. Go to the activity table -> open an action -> click on the user pill -> check username is displayed instead of wallet address
* Step 5. Check the members/contributors pages
Resolves #2891
> Fix: UserPopover shows username instead of address

- amplify/backend/api/colonycdapp/schema/schema.graphql
- amplify/backend/function/bridgeXYZMutation/src/handlers/checkKyc.js
- amplify/backend/function/bridgeXYZMutation/src/handlers/kycLinks.js
- amplify/backend/function/bridgeXYZMutation/src/handlers/updateExternalAccount.js
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/useBankDetailsFields.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/PaymentBuilderTable.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/RecipientField/RecipientField.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/RecipientField/types.ts
- src/components/v5/common/CompletedAction/partials/SimplePayment/SimplePayment.tsx
- src/graphql/generated.ts
- src/graphql/queries/liquidationAddress.graphql
- src/hooks/useUserByAddress.ts
- src/redux/sagas/transactions/getMetatransactionPromise.ts
- src/redux/sagas/users/index.ts
- src/redux/sagas/utils/metatransactions.ts
- src/utils/chainId.ts
This PR fixes a number of issues around displaying the relevant user whose liquidation address a payment was made to. 
When payment is made to the liquidation address, it should be swapped with relevant user in the following places:
- Simple payment action (action description, recipient field)
- Advanced payment action (recipients in the table)
- Activity feed action descriptions
Unless you're testing against Bridge production, there's no way to test this properly as the sandbox generated addresses are not valid ETH addresses.
For that reason, we'll create a liquidation address in the DB manually. In production, this will be done by the `checkKyc` handler whenever it finds that a user doesn't have an address linked to their bank account already.
```gql
mutation CreateLiqAdd { …
```
> Crypto-to-fiat: Payments to liquidation address should show relevant member

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx
- src/components/v5/shared/TxButton/TxButton.tsx
- src/redux/sagas/transactions/transactionChannel.ts
- src/state/transactionState.ts
Maybe it'd make sense to wait for #2867 to be merged so that the whole flow can be tested in an integrated way.
This PR fixes a few bugs raised in #2835. The TxButton now only shows "Completed" if the first transaction group in the list just was successful.
Furthermore we now show a detailed error message for the transaction that was failed. This is currently very rough still but @arrenv is creating an issue to improve the situation.
I also removed the cancel button that was showing for a brief second before the transaction goes into pending.
Send and fail a single transaction. A more detailed error message should now be shown. Also the "Completed" TxButton should not show.
**Changes** 🏗
* Do not show "Completed" TxButton when a transaction fails
* Show more detailed error messages on …
> Fix: transaction list logic fixes

- src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
1. Visit the Incoming Funds page
2. Expand the accordions on the table
3. Verify that they are following the Figma designs
Resolves #2788
> Fix: Update nested table styles in the incoming funds table

- src/components/common/Extensions/UserHub/partials/ReputationTab/partials/TotalReputation.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/ManageReputationDescription.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/utils.ts
- src/components/v5/common/CompletedAction/partials/ManageReputation/ManageReputation.tsx
- src/components/v5/common/CompletedAction/partials/ManageReputation/partials/ManageReputationTableCompletedState/ManageReputationTableCompletedState.tsx
- src/components/v5/common/CompletedAction/partials/ManageReputation/partials/ManageReputationTableInMotion/ManageReputationTableInMotion.tsx
- src/components/v5/common/CompletedAction/partials/ManageReputation/partials/ManageReputationTableInMotion/hooks.ts
- src/components/v5/shared/UserInfoPopover/partials/UserInfo.tsx
| ![image](https://github.com/user-attachments/assets/1f2c2f57-c295-4833-ab5f-09eee80379d9) | ![image](https://github.com/user-attachments/assets/d48fe68a-1efc-4550-9336-354a3878e42d) |
1. Visit the Members page
2. Click on leela, the User Info popover should come up
3. Hover on the Reputation percentage
4. Verify that reputation value in the tooltip is not being shown in scientific notation anymore
Resolves #2706
> Fix: Display user reputation in its non-scientific notation format

- src/components/v5/common/AvatarUploader/partials/ErrorContent.tsx
Just a good ol' break ol'
1. Find an image greater than 1MB
2. Give it the following filename: `theevilgalacticempirehasfallenandanewrepublichasrisentotakeitsplacehoweversinisteragentsarealreadyatworktounderminethefragilepeace`
3. Bring up the Action Form and set it to Edit Colony Details
4. Upload the photo
5. Verify that the filename doesn't overflow
Resolves #2777
> Fix: Prevent filename from overflowing

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
Following the Members list scroll behaviour whereby the header is also added to the scroll layer (validated by Arren)
1. Visit your planex colony
2. Bring up the Action Form
3. Set the Action type field to Manage tokens
4. Add all the suggested tokens:
5. At this point, you should already have 6 tokens (my screenshot shows 5, ignore that)
6. We need to more tokens to make the Tokens list overflow so please create 2 colonies, which effectively makes you create 2 more tokens
```console
node scripts/create-colony-url.js
```
7. Visit each of the newly created colonies and copy their token addresses
8. Go back to the planex Colony
9. Add the two tokens you've just created
10. Bring up the Action form and set the Action type to Transfer funds
11. Open dev tools and choose the iPhone SE viewport …
> Fix: Make the tokens list scrollable

- src/components/shared/Extensions/Tabs/Tabs.tsx
- src/styles/variables.css
- In order to not encounter anymore the orange background for the tabs, this PR enforces a transparent background
Please check the background for an active tab is transparent.
Places to check: 
- Extensions page
- User Account page
- Members page
- Permissions page
- User hub -> Stakes 
Resolves #2839
> Fix: enforce transparent background for the tabs

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/CompletedAction/partials/SetUserRoles/SetUserRoles.tsx
All multisig and voting reputation motions were showing up as `Remove permissions`, that's because we tried to use historical roles before they get created. We now create them on motions too.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/266)
We need to check if all of the completed action views still function correctly.
1. Install the Multi-Sig extension and give `leela` `Owner` permissions. Set the global threshold to 1.
2. Give `amy` `Payer` Multi-Sig permissions via Multi-Sig, the action should show exactly that
3. Finalize the motion, the completed action should show the same data 
4. Redo the action, take away her `Funding` permissions via permissions
5. The action should show only the impacted data
6. Redo the action again, and now toggle on the …
> [Multi-sig] fix: display correct permissions on motion completed actions

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PermissionsBox/PermissionsBox.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PermissionsBox/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/RequestBox/partials/RequestBoxItem.tsx
- src/context/PaymentBuilderContext/PaymentBuilderContext.ts
- src/context/PaymentBuilderContext/PaymentBuilderContextProvider.tsx
- Added list for funding using permission method
* Create a Payment builder action.
* At the Funding step, fund the payment twice. You should be able to do it by clicking the button twice.
* Continue to the next step.
* Click back in the funding step.
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2399](https://github.com/JoinColony/colonyCDapp/issues/2399)
> feat: added list for permissions fundings

- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/MobileJoinedColonies/MobileJoinedColonies.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/TitleSections/BaseTitleSection.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/TitleSections/ConnectWalletSection.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/TitleSections/EmptyJoinedColoniesSection.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/TitleSections/NoColoniesJoinedSection.tsx
- src/i18n/en.json
- This PR aims to add the proper section in the ColonySwitcher when either a wallet is not connected or there is no colonies joined
TODO: Check styling for both **no wallet connected** and **no joined colonies** on mobile/desktop are as in the [Figma designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3931-21252&t=hFhuCB862SULJVIc-0)
* Step 1. Go to `http://localhost:9091/`
* Step 2. Make sure no wallet is connected
* Step 3. Click on the colony.io logo in the sidebar
* Step 4. Check Connect your wallet appears + styling
* Step 5. Switch to a screen size >= `1024px`
* Step 6. Click on the colony.io logo in the header
* Step 7. Check Connect your wallet appears + styling
* Step 8. Connect to wallet 15
* Step 9. Click on the colony.io logo in the sidebar
* Step …
> Feat: show titled section for not connected wallet or no joined colony

- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/CancelButton/CancelButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/RemoveVoteButton/RemoveVoteButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/VoteButton/VoteButton.tsx
- src/components/v5/shared/Button/ActionButton.tsx
A small code improvement to reduce some complexity, we should use the new and improved `ActionButton` with `useTxLoader` instead of hacking our way through life with the `ActionForm`.
Basically a regression test of voting buttons, but try it out with `leela` as your Metamask user.
I highly suggest using Chrome for this, as I've had issues using Brave/Firefox in the past.
Go to `http://localhost:3006/ganache-accounts.json` and copy the private key for `0xb77D57F4959eAfA0339424b83FcFaf9c15407461`, import that account into Metamask and try it out.
1. Install the Multi-Sig extension
2. Set the global threshold to 2
3. Give `amy` and `leela` `Owner` Multi-Sig permissions
4. Create a mint tokens motion as `leela`, copy the URL/open the action as `amy` in another browser, click Approve and …
> [Multi-sig] refactor: remove action form from multisig voting buttons, fix behaviour with metamask

- src/components/frame/Extensions/pages/ExtensionDetailsPage/PermissionsNeededBanner.tsx
Fix: remove auto-enabling for MultisigPermissions extension in PermissionsNeededBanner
> [!IMPORTANT]
> This PR only handles showing back the banner; enabling the permissions in a multi-transaction after the extension is installed will be tackled in issue [#2909](https://github.com/JoinColony/colonyCDapp/issues/2909)
You should see the missing permissions banner if there are permissions missing, that only users with the right permissions can trigger.
TODO: Check the multi-sig permissions banner shows up after installing the Multi-Sig extension
* Step 1. Login as `leela` and go to Multi-Sig extension page
* Step 2. Install extension 
* Step 3. Check permissions banner shows up but **don't** enable the permissions yet
* Step 4. Login as `fry` and check permissions banner shows up, but the …
> Fix: remove auto-enabling for MultisigPermissions extension in PermissionsNeededBanner

- src/context/AppContext/AppContextProvider.tsx
- src/redux/sagas/setupUserContext.ts
`ethereum.selectedAddress` is deprecated and may be removed in the future.
This PR replaces uses of it with `window.ethereum.request({method: 'eth_accounts'})` so that we don't get caught out in the future!
More information can be found here: [https://github.com/MetaMask/metamask-improvement-proposals/discussions/23](https://github.com/MetaMask/metamask-improvement-proposals/discussions/23) and here: [https://docs.metamask.io/wallet/reference/eth_accounts/](https://docs.metamask.io/wallet/reference/eth_accounts/)
Test switching between two different metamask wallets.
https://github.com/user-attachments/assets/bdea21cd-0b41-4b98-8f63-2d2b6d4ce82b
Compared to master where you will get a console warning:
https://github.com/user-attachments/assets/e40e5d9c-1cd8-4ba6-9f02-9ac12d7225d3 …
> Maintenance: Replace uses of `ethereum.selectedAddress` as it is deprecated

- src/components/v5/common/ActionSidebar/partials/Description/Description.tsx
- src/components/v5/common/ActionSidebar/partials/RemoveDraftModal/RemoveDraftModal.tsx
- src/components/v5/shared/RichText/hooks.ts
Fix for: The description field flashes and clicking to expand the description field does not show your draft content.
* Create an Agreement action.
* Add some content and then save it as a draft.
* Close down the action sidebar.
* Navigate to the agreement page and click the "Create agreement" button, or create a new action.
* In the modal to asking to remove the draft, click the "View draft" button.
* Note if your draft shows up or not.
* 
**Changes** 🏗
* `onUpdate` - when `html` const is empty return without `field.onChange` and checking if `getAttributes` objects are empty, until now it returned true all the time
* 
- 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2790
> fix: draft agreement description flashing

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/CryptoToFiatTab.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/CardHeader.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/CardInput.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/CardWrapper.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/KycCard.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/ReceiveCard.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/SummaryCard.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/TransferForm.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/WithdrawCard.tsx
- tailwind.config.js
If the KYC status is not approved or if there is no liquidation address.
| non-loading state | loading state |
| ![Screenshot 2024-08-16 at 15 18 35](https://github.com/user-attachments/assets/e2f7d7f4-6587-4f66-83d2-e3571dca648e) | ![c2f loader](https://github.com/user-attachments/assets/186b7269-ca35-42ee-b4e2-380caf1ed6e0) |
> [!IMPORTANT]
> In the `bridgeXYZMutation/src/index.ts` file, make sure you update the `apiKey` with our sandbox api key.
> Connect a Dev Wallet that hasn't done a KYC check yet.
1. Visit a Colony
2. Open the UserHub
3. Go to the Crypto to fiat tab
4. Verify that you can see the KYC card and the form is disabled
5. Click "Complete verification"
6. Verify you are taken to the Crypto to fiat page
7. Completed step 1 Verification and make sure you're …
> Fix: Conditionally show the KYC Card in the Crypto-to-Fiat tab

- src/components/frame/Extensions/pages/Extensions/ExtensionDetailsPage/partials/StakedExpenditureSettings.tsx
- src/components/frame/Extensions/pages/Extensions/ExtensionsListingPage/ExtensionsListingPage.tsx
- src/components/frame/Extensions/pages/Extensions/ExtensionsListingPage/utils.ts
- src/constants/extensions.ts
- src/utils/arrays/index.ts
Extensions list order
* Go to the Extensions page.
* Note the order and grouping of extensions.
* Install an extension.
* Note the order of extensions.
* 
**Changes** 🏗
* `supportedExtensionsConfig` split into `paymentSupportedExtensionsConfig` and `decisionMethodSupportedExtensionsConfig`
* `StakedExpenditureSettings` component updated to use `initializationParams` array of the extension
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2928
> fix: extensions list order and copy update

- src/redux/sagas/expenditures/fundExpenditure.ts
Occasionally the fundingExpenditure saga would fail with a "not ready to send" transaction error.
This was occurring because the transaction status was set to `pending` rather than `ready`.
The incorrect transaction status was being caused by `yield put(transactionPending(fundMulticall.id))` which sets the transaction status to pending, **however** it doesn't wait for the mutation to complete before proceeding. This meant on some occasions the `pending` mutation would complete **after** the `ready` mutation even though it was called first.
This PR removes `yield put(transactionPending(fundMulticall.id))` as it was being set to `ready` straight away after anyway, so setting it to `pending` first was unnecessary.
I have opened a separate PR on master (#2994) to make `yield …
> Fix: Intermittent "not ready to send" transaction errors

- amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js
- src/components/frame/v5/pages/FundsPage/partials/FundsTable/hooks.tsx
- src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
- src/components/frame/v5/pages/FundsPage/partials/TokenTable/hooks.tsx
There was an [issue raised](https://github.com/JoinColony/colonyCDapp/issues/2787) where the chain's native token was disappearing from the Incoming Funds table after you claimed the funds. With the other tokens, the claim remains in a 'claimed' state. The problem is that the way chain native tokens are handled is very different - see the comments in the issue for more details on that.
This is a solution which will ensure there is no confusion when the chain native token is claimed and disappears from the list. In the future when financial reporting is worked on then this behaviour can be changed properly.
Here's a description of what this PR will do:
- Ensure that the chain's native token item will always be visible at the bottom of the Incoming Funds table.
Collapsed view:
- It will …
> Always show chain native tokens in incoming funds table

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/partials/TokenItem.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/partials/TokenList.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/partials/TokenNotFounds.tsx
- This PR addresses the token amount re-validation after a token is selected (and amount is present)
1. Run `create-data` script
2. Go to `wayne` colony 
3. Create an unlock token action for `Gotham Guilder`
4. Go to `planex` colony
5. Go to http://localhost:9091/planex/incoming and accept incoming `Gotham Guilder` funds 
6. Create a simply payment action
7. Enter `2` in the **Amount** field
8. Select the `Gotham Guilder` token
9. Error message should appear
10. Change amount value to `1`. Error message should be gone.
11. Now enter `10` as an amount. Error message is again shown.
12. Select `Space Creds` as the token. Error message should be gone.
* Added the `TokenItem`, `TokenList` and `TokenNotFound` components to refactor a bit the code ✨ 
**Changes** 🏗
* Relevant …
> Fix: Trigger token amount validation after token selection and refactoring

- amplify/backend/api/colonycdapp/schema/bridge.graphql
- amplify/backend/api/colonycdapp/schema/schema.graphql
- amplify/backend/function/bridgeXYZMutation/src/handlers/getGatewayFee.js
- amplify/backend/function/bridgeXYZMutation/src/index.js
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/ReceiveCard.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/SummaryAmountRow.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/SummaryCard.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/TransferForm.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/WithdrawCard.tsx
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/helpers.ts
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/hooks.ts
- src/components/common/Extensions/UserHub/partials/CryptoToFiatTab/partials/types.ts
- src/constants/index.ts
- src/graphql/generated.ts
- src/graphql/queries/bridgeXYZ.graphql
- src/hooks/useCurrencyConversionRate.ts
- src/utils/currency/config.ts
- src/utils/currency/tokenPriceDataByName.ts
- This PR handles computing the proper receive amount value based on the withdraw value and associated fees
> [!IMPORTANT]
> The user USDC balance is still hard coded
* Step 1. Please update the `apiKey` value in `colonyCDapp/amplify/backend/function/bridgeXYZMutation/src/index.js`
* Step 2. Please update the `COINGECKO_API_KEY` and `COINGECKO_API_URL` env vars and run `npm run prepare`
* Step 3. Now that we are all set, go to the `planex` colony
* Step 4. Open the user hub > Crypto to fiat tab
* Step 5.1. Check the conversion rate updates based on the call to Coin Gecko
* Step 5.2. Check the …
> Feat/2952: Calculate receive amount in user hub tab

- docker/colony-cdapp-dev-env-auth-proxy
- src/components/common/ColonyActionsTable/FiltersContext/FiltersContextProvider.tsx
- src/components/common/ColonyActionsTable/utils.ts
- src/hooks/useCurrentBlockTime.ts
We have the following predefined date filters:
- past hour
- past 24 hours
- past week
- past month
- past year
The filter wasn't working properly because our logic was basically:
```js
case dateFilter.pastHour: return data;
case dateFilter.pastDay: return data;
case dateFilter.pastWeek return data;
case dateFilter.pastMonth: return data;
case dateFilter.pastYear: return data; 
```
So if you applied the past hour filter + the past year filter, it will first enter the `case` block for `pastHour`. If there are actions in the past hour, it will return those actions without ever having the chance to check the `case` block for `pastYear`.
But luckily, we can easily re-order the checks and start with the most all-encompassing range:
```js
case dateFilter.pastYear: return data;
case …
```
> Fix: Return the correct list of actions based on the `createdAt` filter

- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/partials/StagedPaymentRecipientsField/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneItem/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/StagedPaymentTable.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/partials/ClaimDelayTooltip/ClaimDelayTooltip.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/types.ts
- Added a delay notification to staged payments table
- For testing purpose I've added hardcoded values
* Create staged payments action and go to `payment` step
* After a minute, an icon with information about the delay should appear
- Remove hardcoded variables before merging
Resolves https://github.com/JoinColony/colonyCDapp/issues/2899
> feat: added claim delay notification

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/CancelModal/CancelModal.tsx
You should be able to interact with the header in order to view and managed your transactions while in the modal.
* Create a new Adv. Payment action.
* Cancel the new action.
* The cancel modal will open.
* Check if header is accesible
* 
**Changes** 🏗
* `shouldShowHeader` set to true in `CancelModal` component
* 
- 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2863
> fix: show header when cancel modal is visible

- docker/colony-cdapp-dev-env-auth-proxy
- docker/colony-cdapp-dev-env-block-ingestor
> [!IMPORTANT]
> This requires the following block ingestor changes: [block-ingestor#267 Fix: Reveal domain for manage tokens action](https://github.com/JoinColony/block-ingestor/pull/267)
1. Bring up the Action form
2. Set the Action type to Manage tokens
3. Add a token
4. Visit the Activity page `/{colonyName}/activity`
5. Verify that the the entry for Manage tokens is showing the domain
Resolves #2830
> Fix: Reveal domain for manage tokens action

- src/components/frame/Extensions/pages/ColonyDetailsPage/ColonyDetailsPage.tsx
- src/components/v5/common/NativeTokenPill/NativeTokenPill.tsx
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/DashboardHeader.tsx
The one on the details page changed too, but we don't need to do anything as that page will be retired soon enough.
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=5072-23432&t=WWUSxHubtxhNqeaI-4)
1. Open up the colony home page and check the native token pill
2. Inspect it and make sure it looks like it should (I've aligned the padding to 10px on each side, in the designs it's 11 left and 9 right, probably not intentional?)
3. Open up the native token modal and verify it opens
4. verify that the tooltip shows upon hovering over the lock icon
5. verify that the modal works on mobile
**Changes** 🏗
* Reworked the native token pill to have just one source for opening and closing it and ofc restyled it
Resolves #2848
> [Dashboard] feat: redesign the native token pill

- src/utils/members.ts
Ez fix, just the query for getting colony contributors got switched in between.
1. Go to the members page as `leela`
2. Remove verified status from `amy` and `fry` by creating a `Manage verified members` action using `Permissions`
3. After the action passes, their verified checkmarks should disappear from both the members page and in the completed action view
4. Now add them back as verified members
Next up, we need to check if motions still work as intended :eyes: 
1. Install the voting reputation extension, then go back to the members page
2. Create a motion to remove `amy` and `fry` as verified members
3. Fully support it as `leela` and then run `npm run forward-time 1` in the terminal so the motion becomes finalizable (refresh the page). Assure that the verified flags are always …
> fix: real time updating of verified member flags

- src/components/common/ColonyActionsTable/ColonyActionsTable.tsx
- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/common/ColonyActionsTable/types.ts
- src/components/frame/v5/pages/ActivityPage/ActivityPage.tsx
- src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/SimplePaymentDescription.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/utils.tsx
- src/components/v5/common/CompletedAction/partials/CompletedExpenditureContent/CompletedExpenditureContent.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/SplitPayment.tsx
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- The member field should also be copied over when redoing an simple payment action.
- Redo action should be visible in the activity feed kebab menu as well.
- Redo action should be available for all Advanced payment options, including Staged and Split.
* Check if the action is 'copied' after selecting redo action option from meatball menu in activity table
* Added redo action option to activity table on homepage and activity page
Resolves https://github.com/JoinColony/colonyCDapp/issues/2840
> feat: added redo action to adv payments

- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/ColonyLinks.tsx
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/useHeaderLinks.ts
- src/components/v5/shared/SocialLinks/colonyLinks.ts
- src/i18n/en.json
As part of the dashboard redesign, the social icons require some small changes.
This PR makes some styling tweaks to the social icons, and re-orders the priority order.
[Check the original issue for the full requirements](https://github.com/JoinColony/colonyCDapp/issues/2846)
* Step 1: Navigate to the dashboard. Check the social icons match the [figma file](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4859-36367&t=3YmH0OCdhMXflaYC-0) on all screen widths.
* Step 2: Create an 'edit colony' action and remove the custom link and whitepaper link (and any other links you'd like)
* Step 3: Check the icon order respects the expected priority order (as detailed in the original issue).
**Changes** 🏗
* Social icon styling tweaks
* Social icon priority order changes
* `Copy …
> [Dashboard] Feat: Adjust social icons for colony header redesign

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/consts.ts
- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHub/types.ts
- src/i18n/en.json
This PR adds the notifications tab to UserHub with the empty notifications list state.
[Figma link](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6754-9623&t=DbRYLaxphOdTpK4N-4)
Simply load up a colony and open the UserHub. The notifications tab should be visible and show the empty state. Test on all screen widths.
The tab should also not be visible when the notifications service is disabled by the user. This has not yet been implemented, but to test it change this line in `src/components/common/Extensions/UserHub/UserHub.tsx`
```
const notificationsServiceIsEnabled = true; // change to false
```
* Added notifications tab to userhub
**Changes** 🏗
* Re-ordered tabs to match figma
Resolves #3006
> [Notifications] Feat: Add empty notifications list to UserHub

- src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/hooks.ts
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/hooks.tsx
This PR fixes an issue with the funding motion for an advanced payment getting stuck on the staking step.
The issue was occurring because the PaymentBuilderWidget would re-render whilst polling for motion updates, which would cause the `transform` function to change resulting in the `useAyncFunction` promiseListener to get unsubscribed.
This PR memoizes the `transform` function to prevent it changing on these re-renders unless the actual values change.
Whilst working on this I also noticed similar behaviour on the voting and reveal steps so have memoized those `transform` functions too.
This PR also disables the "Oppose" and "Support" buttons whilst the form is submitting.
Follow these steps on `feat/advanced-payments-ui-next` if you'd like to replicate the original issue - it is also …
> Fix: Advanced payments UI not updating after successful motion stake

- .env.example
- package-lock.json
- package.json
- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/partials/CountBadge.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/v5/shared/Button/Button.tsx
- src/components/v5/shared/Button/types.ts
- src/context/NotificationsContext/NotificationsContextProvider.tsx
Note: It probably makes sense to test #3066 straight after this one as it is such a tiny additional change.
This PR adds unread notifications alerts to the UserHub button and UserHub notifications tab. It also adds the MagicBell provider to get easy access to the unread notifications count.
Add `MAGICBELL_API_KEY="<API_KEY>"` to your `.env.local.secrets` file.
Add `MAGICBELL_API_KEY="<API_KEY>"` and `MAGICBELL_API_SECRET="<API_SECRET>"` to `amplify/backend/function/createUserNotificationsData/.env` if you don't already have it.
Log with a dev wallet where the user has unread notifications (at the time of writing this is true for Leela - dev wallet 1)
Check the unread notification alert appears on the UserHub when closed, then on the notifications tab. (If there are no notifications, you …
> [Notifications] Feat: Show unread notifications alert

- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
Builds on the work done on #3063 - probably makes sense to review that one first then this one straight after as this is such a small addition.
This PR adds the "Mark all as read" button the notifications tab of the UserHub.
Log in as Amy (dev wallet 2)
If there are no unread notifications, create one (or many) via the UI [https://app.magicbell.com/projects/8931/compose](https://app.magicbell.com/projects/8931/compose) - set the user's wallet address as the recipient.
Click the "Mark all as read" button in the notifications tab - the notification alert should disappear.
* Added "Mark all as read" button to UserHub notifications tab
Contributes to #3009
> [Notifications] Feat: Mark all as read

- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/common/Extensions/UserNavigation/partials/NetworkName/NetworkName.tsx
- src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
- src/components/v5/shared/Button/Hamburger.tsx
This PR makes two small fixes to the page header on mobile. The space between the colony logo and the menu icon has been increased. The width of the settings button has been increased to match the other icon buttons ~~(note: this does not match the figma design which has the borders on the inside of the component rather than the outside, so I have instead opted to make this consistent with the other two buttons as this would be a bigger change that needs a bit more thought)~~ I did a bit of digging found this was only an issue with these buttons, so have gone ahead and made the changes.
Before:
After:
Does the spacing match the figma design.
Does the settings button match the other buttons.
**Changes** 🏗
* Increased spacing
* Increased width
Resolves #3047
> [Navigation] Fix: UI Page header adjustments

- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColonyItem/JoinedColonyItem.tsx
This PR resolves the 3 UI issues described in the original issue.
* Increases the height of the switcher item on mobile
* Changes the token text colour to text-gray-600
* Reduces the gap between the token logo and name to 10px
It also removes the colony switcher hover state on mobile / tablet as discussed with Mel.
Open the colony switcher on mobile and check it matches the issue / figma design. (The height changes are more apparent if you create a third colony.
**Changes** 🏗
* Increases the height of the switcher item on mobile
* Changes the token text colour to text-gray-600
* Reduces the gap between the token logo and name to 10px
Resolves #3046
> [Navigation] Fix: Colony switcher UI adjustments

- src/components/common/ColonyActionsTable/RecentActivityTable.tsx
- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/common/ColonyActionsTable/hooks/useColonyActionsTableColumns.tsx
- src/components/common/ColonyActionsTable/hooks/useRenderRowLink.tsx
- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
- src/components/common/ColonyActionsTable/partials/ActionDescription/types.ts
- src/components/common/ColonyActionsTable/types.ts
- src/components/frame/v5/pages/ActivityPage/ActivityPage.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/Table/partials/TablePagination/TablePagination.tsx
- src/components/v5/common/Table/partials/TablePagination/types.ts
- src/components/v5/common/Table/types.ts
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/FundsCards.tsx
- src/components/v5/shared/KebapMenu/KebapMenu.tsx
- src/components/v5/shared/MeatBallMenu/MeatBallMenu.tsx
- src/components/v5/shared/UserAvatars/UserAvatars.tsx
- src/i18n/en.json
This PR makes changes to the activity table on the dashboard to reflect the new figma designs.
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4859-36367&t=3YmH0OCdhMXflaYC-0)
It was very tempting to separate out the dashboard activity feed from the main activity feed (and I did actually start to do this before realising how much work it would be), but I instead opted to add a few new props to the `useActionsTableProps` hook and the `Table` component. This probably isn't ideal but both the hook and the table component are in need of a refactor at some point and this didn't feel like the right place to do it.
The newly added props are used to remove the horizontal padding, remove the table header and border, hide the user avatar.
Note: The empty state for …
> [Dashboard] Feat: Update recent activity table

- docker/colony-cdapp-dev-env-block-ingestor
- docker/colony-cdapp-dev-env-network
This PR doesn't change anything _(other than updating the relevant `network` and `block-ingestor` docker images hashes)_, but merely it serves a platform for testing the problem fixed by JoinColony/block-ingestor#269, so if you need a refresher on what this actually is, please see the aforementioned block ingestor PR.
Note that because of the urgency of this problem happening in production, I deployed the block ingestor fix already: https://github.com/JoinColony/block-ingestor/actions/runs/10815566377
**1.** Start your dev environment _(note that `network` and `block-ingestor` images will take longer to build as they were updated)_
**2.** Run the `create-data` script
**3.** Start the `frontend`
**4.** Make a note your colony's address
**5.** Go to your incoming funds page, make sure the …
> Testing scenario for block ingestor #269

- docker/colony-cdapp-dev-env-network
Just realign the network hash so Multi-Sig shows up as expected :)
1. Open up the app and go to the extensions list, Multi-Sig should show up
> build: update network image hash to latest multi-sig commit

- src/components/frame/Extensions/pages/partials/InstallButton.tsx
- src/components/frame/Extensions/pages/partials/SaveSettingsButton.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/VotingStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/utils.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/CancelButton/CancelButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/RemoveVoteButton/RemoveVoteButton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/VoteButton/VoteButton.tsx
- src/components/v5/shared/Button/ActionButton.tsx
- src/components/v5/shared/Button/types.ts
This PR addresses a few issues with the motion voting step.
On occasion, the UI would not update after a successful transaction to show the status of the vote. This PR resolves this by memoizing the transform function.
This PR also removes the single option after voting, and instead just handles the vote change when clicking the "Change vote" button.
The "Change vote" button uses the `ActionButton` component, which I have added a `loadingBehavior` prop to which allows for the button to be disabled when submitting to match how the "Submit vote" button works.
The "Oppose" and "Support" vote buttons are now disabled whilst the form is submitting.
(Note: The pending count issue described in the original issue will be handled in a separate PR.)
* Step 1 - Install the reputation voting …
> Fix: Motion change vote

- src/redux/actionCreators/transactions.ts
- src/redux/sagas/actions/createDomain.ts
- src/redux/sagas/actions/editColony.ts
- src/redux/sagas/actions/editDomain.ts
- src/redux/sagas/actions/manageExistingSafes.ts
- src/redux/sagas/actions/managePermissions.ts
- src/redux/sagas/actions/manageReputation.ts
- src/redux/sagas/actions/moveFunds.ts
- src/redux/sagas/actions/payment.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/expenditures/fundExpenditure.ts
- src/redux/sagas/expenditures/lockExpenditure.ts
- src/redux/sagas/motions/createDecisionMotion.ts
- src/redux/sagas/motions/escalateMotion.ts
- src/redux/sagas/motions/stakeMotion.ts
- src/redux/sagas/transactions/transactionsToDb.ts
- src/redux/sagas/utils/annotations.ts
- src/state/transactionState.ts
Whilst working on #2992 I uncovered an issue with how `yield put(transactionPending(transactionId))` is being used.
The intention is to update the transaction status in the database to `pending`. This is usually followed by setting transaction parameters, before setting the status to `ready`. However, the pending mutation is done asynchronously leading to some edge cases where the `ready` mutation can complete before the `pending` mutation which can cause the `sendTransaction` function to fail.
This PR replaces `yield put(transactionPending(transactionId))` with a new `yield transactionSetPending(transactionId)` function which waits for the mutation to complete before proceeding.
Test that none of the sagas have been broken, create a few actions and motions.
* …
> Feat: Transaction pending mutation should be blocking

- src/components/v5/common/ArrowScroller/ArrowScroller.module.css
- src/components/v5/common/ArrowScroller/ArrowScroller.tsx
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/shared/TeamFilter/TeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/AllTeamsItem.tsx
- src/components/v5/shared/TeamFilter/partials/CreateNewTeamItem.tsx
- src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/DesktopTeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/helpers.ts
- src/components/v5/shared/TeamFilter/partials/LeftButton.tsx
- src/components/v5/shared/TeamFilter/partials/MobileTeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/RightButton.tsx
- src/components/v5/shared/TeamFilter/partials/TeamItem.tsx
- src/components/v5/shared/TeamFilter/partials/TeamsDropdown/TeamsDropdown.tsx
- src/hooks/useScrollIntoView.ts
Changing the solution from the dropdown to use the newly designed tabs.
Removing the current dropdown should be done as part of #2860.
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4887-20952&t=XheoZNvOyt62DJXq-4)
Needs to be tested functionality wise and UI wise.
1. Make sure that when you click a team, it shows up in the search params and everything starts getting filtered
2. Clicking on another one should immediately change the filter:
3. Clicking on the same one should disable it and highlight `All teams`:
4. Clicking on `All teams` when a domain is selected, should disable the filter
5. Clicking on the `+` button should open up the sidebar with the "Create new team" action
1. Set the screen to a mobile size and verify that you see the arrows:
2. …
> [Dashboard] feat: add new team filter component

- src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/ColonySwitcherAvatar.tsx
- src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebar.styles.ts
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/consts.ts
- tailwind.config.js
1. Connect Dev Wallet 1
2. Visit the planex colony
3. Observe the Colony Sidebar and verify that Activity Feed is now called Activity
4. Click the Colony Switcher component and verify that it maintains its hover state when the colony switcher popover is present
Resolves #3092
> [New Nav] Fix: Colony Sidebar UI adjustments

- src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx
1. Click Finances
2. Verify that
- the Sidebar is not dismissed
- the Accordion items are revealed
3. Click Balances
4. Verify that
- the Sidebar is dismissed
- you are taken to the Balances page
Resolves #3098
> [New Nav] Fix: Update Route Accordion Item behaviour on non-desktop view

- src/components/v5/frame/ColonyHome/partials/ReputationChart/ReputationChart.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/TeamActionsMenu.tsx
Implement dropdown chart with team actions for the reputation donut chart.
I didn't use our existing `DropdownMenu` component, because it's way too cumbersome and I've instead opted for a simple solution using `popper` and a `div`. 
I think we will be able to decouple this in due time, but I didn't start on it right now.
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-88566&t=ZEsiLeswZqxoEGLv-4)
1. Verify that the dropdown opens showing all 3 items
2. Clicking on `View all teams` goes to the teams page
3. Clicking on `Create new team` opens the sidebar with the `Create new team` option preselected
4. Clicking on `Edit new team` opens the sidebar with the `Edit new team` option preselected
I couldn't find any designs for the hover state so I just …
> [Dashboard] feat: reputation chart dropdown menu

- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/TitleSections/BaseTitleSection.tsx
1. Log in as Dev Wallet 4
2. Verify that the No colonies joined UI matches figma for both [web](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4537-8328&t=vlXtmtccpV2qDRfS-4) & [mobile](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4728-22352&t=vlXtmtccpV2qDRfS-4)
Resolves #3090
> [New Nav] Fix: Colony Switcher UI Adjustments

- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
This PR fixes an issue where the "Passed" pill briefly shows when an Advanced payment is created before correcting itself to "Review". This issue was caused by the "Passed" pill not checking if the expenditure is loading.
* Step 1 - Create an action and select "Advanced payment"
* Step 2 - Fill out the action form
* Step 3 - After submitting, as the completed action screen is loading, the first pill to be shown should be "Review"
Compared to master (or see the original issue for a video) where "Passed" will briefly be shown.
https://github.com/user-attachments/assets/18d7ac34-50b9-4658-9322-1531429ecf25
**Changes** 🏗
* Added `!loadingExpenditure` check to the "Passed" pill
Resolves #2930
> Fix: Advanced payment briefly shows "Passed" pill on creation

- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
This PR changes the "Finalize" button to a "Pending" button whilst the form is submitting. Previously the "Finalize" button was not disabled meaning it was possible to click the button multiple times opening up multiple transactions.
The same fix has been applied to the "Claim" button.
* Step 1 - Install the reputation voting extension
* Step 2 - Create any motion
* Step 3 - Stake both sides, vote to support, reveal your vote to get to the finalize step
* Step 4 - Click the Finalize button - notice the "Pending" state whilst the transaction is submitting. (To make this even more apparent, switch to the metamask wallet. When you click "Finalize" the transaction should pop up, ignore it and try clicking the "Pending" button again. No new transactions should be opened.)
**Changes** 🏗
* …
> Fix: Finalize button goes to pending state when isSubmitting

- src/hooks/useNetworkMotionStates.ts
- src/redux/sagas/utils/safeHelpers.ts
- src/redux/sagas/wallet/RetryProvider.ts
- src/redux/sagas/wallet/index.ts
- src/types/wallet.ts
I pair-programmed this with @jakubcolony, and we agreed on the solution with @rdig 🙌 Thank you guys for helping!
The issue was that we encountered an error when creating advanced payments:
The history of this bug is quite long. It seems @rdig implemented the `getSigner` method 9 months ago to make the Provider work. However, 7 months ago, @chmanie added this method to the Provider class itself, and by using the spread operator, we unintentionally lost a couple of methods from the Provider prototype (such as `getBlock`).
In my PR for the Metamask refactor (https://github.com/JoinColony/colonyCDapp/pull/2908), I removed the usage of the getBasicWallet method. As a result, this error now appears every time, rather than just once when logging in (getFullWallet), which makes the issue more …
> fix: remove getSigner spread as it is no longer needed and getSigner already included in the RetryRpcProvider class

- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
- src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx
Adds a blur to page layout components when a modal is visible.
1. Visit http://localhost:9091/planex/balances
2. Click the "Add funds to the colony" button
3. Verify that the rest of the page is blurred
Resolves #3079
> fix: adjust blur when modal is active

- src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx
This PR simply replaces the Sidebar Route Items with anchor elements
1. CMD + click a Sidebar Route item
2. Verify that it opens the route to a new tab
3. Inspect a Route Item
4. Verify it's an anchor element
Resolves #3153
> fix: use link component instead of button

- src/Entry.tsx
- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/components/frame/Extensions/layouts/MainLayout.tsx
- src/components/frame/LandingPage/LandingPage.tsx
- src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
- src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
- src/components/v5/frame/PageLayout/partials/PageHeading/PageHeading.tsx
- src/components/v5/frame/PageLayout/partials/PageHeading/types.ts
- src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx
- src/components/v5/shared/Breadcrumbs/consts.ts
- src/components/v5/shared/Breadcrumbs/partials/BreadcrumbItem.tsx
- src/components/v5/shared/Breadcrumbs/types.ts
- src/components/v5/shared/Breadcrumbs/utils.ts
- src/context/BreadcrumbsContext/BreadcrumbsContext.ts
- src/context/BreadcrumbsContext/BreadcrumbsContextProvider.tsx
- src/context/PageHeadingContext/PageHeadingContext.ts
- src/context/PageHeadingContext/PageHeadingContextProvider.tsx
- src/routes/ColonyRoute.tsx
- src/routes/routeConstants.ts
- src/stories/frame/PageLayout.stories.tsx
- src/stories/shared/Breadcrumbs.stories.tsx
This PR introduces a new `BreadcrumbsContext` instead of reusing the `PageHeaderContext` which will be removed soon.
The context enables us to toggle showing of the breadcrumbs and what the first item should be (this is due to the colony route being just `/:colonyName` and it's hard to route match otherwise)
Spin up the app and see how the breadcrumbs work.
1. Verify that under the colony routes, the first item is always `Dashboard`
2. All the other pages should display the URL they are on but in breadcrumb mode
3. Pages with more tabs also have the tab under the breadcrumbs
4. Extension pages get the correct breadcrumbs
5. They don't appear on the colony creation page, landing page and the profile creation page
6. The user account page breadcrumbs link to the landing page and change …
> [Dashboard] feat: breadcrumbs

- src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
- src/components/shared/Extensions/Tabs/Tabs.tsx
- src/components/shared/Extensions/Tabs/types.ts
- src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/types.ts
- src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx
- src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/types.ts
- src/components/v5/shared/Navigation/Sidebar/sidebars/AccountPageSidebar/AccountPageSidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/consts.ts
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/partials/SidebarRoutesSection.tsx
- src/i18n/en.json
- src/routes/Routes.tsx
- src/routes/UserRoute.tsx
This PR updates the Account Page so that it uses the new Sidebar design.
> [!NOTE]
> The dark theme issue with Sidebar-related components will be dealt with separately
1. Visit the Account page
2. Set the browser width to 1025px
3. Verify that the Sidebar matches the Figma designs
4. Verify that on tablet view and above, the in-page tabs are not present and that they take you to the correct tab
5. Set the browser width to 1024px
6. Verify that the sidebar is not present
7. Verify that the in-page tabs are present
Resolves #2874
> [New Nav] Account Page Sidebar & Tab updates

- src/components/v5/frame/ColonyHome/partials/ChartCustomTooltip/ChartCustomTooltip.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/ReputationChart.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/Chart.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/ChartTooltip.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/LegendItem.tsx
- src/context/ReputationChartContext/ReputationChartContext.ts
- src/context/ReputationChartContext/ReputationChartContextProvider.tsx
Feat: Add legend item active state on non-empty chart hover
Hovering over a section of the chart:
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-89693&node-type=frame&t=3xGH3p1iB0FF8qa7-0)
TODO: Check the hover state over a section of the chart matches Figma.
* Step 1. Make sure you have data to test against
* Step 2. Go to http://localhost:9091/planex
* Step 2. Either leave the `All teams` or `General` team
* Step 3. Hover over a section of the `Influence by team` chart
* Step 4. Check hover state for the legend item is matching Figma
* Step 5. Select another team
* Step 3. Hover over a section of the `Top contributors` chart
* Step 4. Check hover state for the legend item is matching Figma
* `ReputationChartContext` and provider
* …
> [Dashboard] Add legend item active state on non-empty chart hover

- amplify/backend/function/initializeUser/function-parameters.json
- amplify/backend/function/initializeUser/initializeUser-cloudformation-template.json
> Fix: intialize user lambda

- src/components/v5/frame/ColonyHome/partials/ReputationChart/utils.ts
- src/utils/numbers.ts
This PR makes sure that percentages add up to 100 if there are fewer than 5 people with reputation in the colony.
Bonus: I also did that for the domains graph :1st_place_medal:
Look at this graph within the dashboard
The percentages should add up to 100 if there are 4 or less contributors.
* Add a `adjustPercentagesTo100` function
**Changes** 🏗
* Apply that function to domains and top contributors
Resolves #3119
> [Dashboard] Top contributors numbers should add up to 100

- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/consts.ts
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/hooks.ts
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/BarChart.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/ChartCustomBottomAxisLayer.tsx
- This PR replaces the use of the `useCssProperties` hook with a `cssVariables` const for the `Total in and out` chart
TODO: Just check this change does not affect the `Total in and out` chart between light and dark mode
`General` or `All teams`
`Andromeda`
`Rocinate`
* `cssVariables`
* `useCssProperties` hook
Resolves [#3172](https://github.com/JoinColony/colonyCDapp/issues/3172)
> [Dashboard] Refactor bar chart css variables

- src/components/v5/common/ActionSidebar/partials/GroupedAction/GroupedActionItem.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/PaymentsSection.tsx
- Clicking on `Pay` in the `Total in and out` card should open the `Payment section` side panel with the team-preselected
TODO: Check clicking `Pay` in the `Total in and out` card opens the `Payment section`. Then select any action from the ones available (`Simple payment` or `Advanced payment`) and check the selected domain is pre-filled in the `From` field of the action form. Switch between domains and have fun 🎉 
https://github.com/user-attachments/assets/7e7c5c4d-b442-4684-9e9f-dfeb2bac3925
**Changes** 🏗
* Using `actionSidebarInitialValues` in the `GroupedActionItem`
Contributes to #3173
> [Dashboard] Pay opens Payment section with team pre-filled

- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/TitledSection.tsx
- Use NumeralCurrency component for the income and payments in Total in and out card based on [this PR](https://github.com/JoinColony/colonyCDapp/pull/3126)
Check the values displayed in the `Total in and out` card for `Income` and `Payments` include 2 decimals for values having less than 8 digits
**Before**
**After**
Step 1. Transfer `1,500,000` CREDS from `General` to `Andromeda` and check the values
Step 2. Now transfer `10,000,000` CREDS from `General` to `Andromeda` and check the values
Step 3. You can create also some Simple/Advanced payments to check the value changes for the `Payments`
**Changes** 🏗
* Use `NumeralCurrency` for `Income` and `Payments`
Contributes to #3173
> [Dashboard] Income and Payments values with decimals

- src/components/common/Onboarding/Wizard/DesktopWizardSidebar.tsx
- src/components/shared/FeedbackButton/FeedbackButton.tsx
- src/components/shared/FeedbackButton/types.ts
- src/components/v5/shared/Navigation/Sidebar/sidebars/AccountPageSidebar/AccountPageSidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/BasicPageSidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
- src/constants/externalUrls.ts
- src/typedefs/intercom/index.d.ts
This PR is not going to update any piece of logic that happens within the Intercom widget. This includes attempting to hide the Previews from an Operator when the Widget is hidden.
This PR simply aims to do the following:
- Control the visibility of the Intercom Widget via  custom triggers
- Control the page offset of the Intercom Widget via Intercom's javascript API
- Redirect the user to https://help.colony.io/ if Intercom is not accessible
> [!IMPORTANT]
> There might be a delay when you click the Help & Feedback button for the first time on page load. I have discussed this extensively with Arren including options of how to handle the delay with loaders perhaps etc. etc.. But TLDR: It's fine as it is because it's not our fault that their widget takes time to be initialised. Even their …
> [New Nav] Trigger the Intercom Widget using the Help & Feedback button

- src/components/v5/common/ActionSidebar/partials/ManageColonyGroup/ManageColonyGroup.tsx
- src/components/v5/common/ActionSidebar/partials/PaymentGroup/PaymentGroup.tsx
Before:
----------------
Now:
Step 1. Open inspector and see console errors
Step 2. Click "Make payment" in the sidebar, modal should be opened
Step 3. Ensure that there are no errors in the console
Step 4. Click "Manage colony" in the sidebar, modal should be opened
Step 5. Ensure that there are no errors in the console
* Property id was added to: GROUP_LIST, GROUP_FUNDS_LIST, GROUP_TEAMS_LIST, GROUP_ADMIN_LIST
> [Navigation]: Fix/key console error

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
- src/components/v5/payments/TmpAdvancedPayments.tsx
- src/redux/sagas/actions/moveFunds.ts
- src/redux/sagas/expenditures/fundExpenditure.ts
- src/redux/sagas/utils/proofs.ts
- src/redux/types/actions/colonyActions.ts
- src/redux/types/actions/expenditures.ts
This PR addresses an issue with the funding modal where the payload was hardcoded to fund the expenditure from the root domain.
This PR properly passes the intended domain in the payload. It also fixes a permissions issue with the saga.
I also refactored the `getMoveFundsPermissionProofs` util to use `getPermissionProofsLocal` whilst I was at it.
The important changes are in the `fundExpenditure` saga and the `FundingModal` component.
* Step 1 - Create an action and select advanced payment
* Step 2 - Select any team other than general
* Step 3 - Add however many payment rows you like and submit (the expenditure ID will be logged to the console, copy it for later)
* Step 4 - Confirm the review stage
* Step 5 - Confirm the funding stage, select permissions as the decision method in the …
> Fix: Fund expenditure should use proper funding pot

- src/components/v5/frame/PageLayout/PageLayout.tsx
This simply sets the max width of the main container to 1278px:
1. Maximise the browser width
2. Verify that even if the browser width exceeds 1278px, the main content width can only ever be a maximum of 1278px
Resolves #3180
> Maintenance: Udpate main content max width to 1278px

- src/hooks/useUserByAddress.ts
Pairprogrammed it with @bassgeta. Thank you for your help :) 
-------------- 
1. Ensure you have past activity in our colony.
2. Ensure your screen is wide enough to see the activity feed and open the action panel.
3. Open and close the action panel.
4. Note the activity feed isn't blicking now.
Resolves #2806
> fix: update get user query to be 'cache-first' to solve reloading issue

- amplify/backend/function/fetchDomainBalance/src/api/graphql/operations.js
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/PaymentStepDetailsBlock.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/hooks.ts
This PR ensures the domain funds cards and total in / out amounts automatically refresh when an advanced payment is successful.
The `getDomainBalance` cache is evicted after the release transaction successfully completes as any payments with a claim delay of `0` will be paid at this point.
The same cache is also evicted after a successful expenditure claim for payments which have passed their claim delay when the "Make payment" button is clicked.
* Step 1 - Create a new colony `node scripts/create-colony-url.js` with a new token
* Step 2 - Mint some tokens in the new colony
* Step 3 - Create an advanced payment action
* Step 4 - Create one row paying 1 token to Leela with a claim delay of 0.
* Step 5 - Advance through the advanced payment steps, review the expenditure and fund the …
> [Dashboard] Domain balances and total in / out should update on successful advanced payment action

- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/ActionsTableFilters.tsx
- src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementsPageFilters/AgreementsPageFilters.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/Filters/BalanceFilters/BalanceFilters.tsx
- src/components/frame/v5/pages/FundsPage/partials/Filter/Filter.tsx
- src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/TeamsPageFilter.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/BankDetailsModal.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/VerificationModal.tsx
- src/components/v5/common/Filter/Filter.tsx
- src/components/v5/shared/Modal/Modal.tsx
| ----- | ----- |
|  ![image](https://github.com/user-attachments/assets/6805c1b1-ce9d-43f1-8e8d-00e00c5e74ff) | <img alt="image" src="https://github.com/user-attachments/assets/0a01ca32-1064-42ba-968f-4148a304f013"> |
Step 1. Set the screen size to mobile.
Step 2. Open Members or Contributors Page - http://localhost:9091/planex/members 
Step 3. Open filters modal
Step 4. Ensure that Modal has padding bottom
- http://localhost:9091/planex/activity (filter, search modal)
- http://localhost:9091/planex/permissions (filter, search modal)
- http://localhost:9091/planex/teams (filter, search modal)
- http://localhost:9091/planex/agreements (filter, search modal)
- http://localhost:9091/planex/balances (filter, search modal)
- http://localhost:9091/planex/incoming (filter, …
> fix: add bottom paddings for 'filter & sort' modal

- src/components/frame/v5/pages/TeamsPage/hooks.tsx
- src/components/v5/common/TeamCard/TeamCard.tsx
- src/components/v5/common/TeamCard/types.ts
- src/components/v5/shared/UserAvatars/UserAvatars.tsx
Make avatars on teams page clickable
- Go to the `/{colony_name}/teams` page
- Click the avatars on teams card
- After click, You should be redirected to contributors page with the relevant team filter applied
Add link for avatars inside `TeamCard` component
Resolves [#31415](https://github.com/JoinColony/colonyCDapp/issues/3121)
> feat: make avatars clickable

- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/shared/TeamFilter/TeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/AllTeamsItem.tsx
- src/components/v5/shared/TeamFilter/partials/TeamItem.tsx
- src/context/GlobalFiltersContext/ColonyFiltersContext.ts
- src/context/GlobalFiltersContext/ColonyFiltersContextProvider.tsx
- src/routes/RootRoute.tsx
This PR enables a selected team filter to persist across Colony pages that uses the `<TeamFilter />` component. 
However, it will not persist the selected team filter for a Colony if you:
- Close the tab/browser
- Visit another Colony
- Visit a non-Colony route
> [!NOTE]
> 1. No, we specifically do not want to persist the selected team filter in between tab sessions. If you open a new tab and you visit the Planex colony, do not expect the filtered team value to persist
> 2. Yes, I also thought about persisting the selected team on a per-Colony basis i.e. Persist Team Andromeda for the Planex Colony & Team Research and Development for the Wayne Colony. It's very doable with what's done on this PR, just have to slightly tweak things around. But that's up to Product to decide if they want it …
> Feat: Colony-wide team filter persistence

- amplify/backend/function/bridgeXYZMutation/src/handlers/checkKyc.js
- amplify/backend/function/bridgeXYZMutation/src/handlers/getUserLiquidationAddress.js
- amplify/backend/function/bridgeXYZMutation/src/handlers/updateExternalAccount.js
- amplify/backend/function/bridgeXYZMutation/src/handlers/utils.js
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetails/BankDetails.tsx
This PR fixes the bug where bank accounts where deleted before a new one was created, resulting in deleting _all_ bank accounts when there was an error.
It's done by first getting _all_ bank accounts for that customer, then creating a new account, then deleting all of the old ones (most of the time that should be just a single one).
Testing this is _hard_, so bring some time.
* First, follow the steps lined out in [this PR](https://github.com/JoinColony/colonyCDapp/pull/2761), to be able to do and bail out of the KYC flow
* Then, create a bank account using USD
* Then, update this bank account to use EUR instead of USD and fill all the forms (EUR will not work in the sandbox and produce an error similar to the one in the issue)
* Then see that the bank details are not deleted
**New …
> fix: delete old bank account only _after_ creating a new one

- src/context/PageLayoutContext/PageLayoutContextProvider.tsx
- src/hooks/useResize.ts
When I minimise the browser, the mobile nav is automatically triggered open. This shouldn't be triggered and take over the UI, instead the closed default mobile header should be displayed. 
This PR addresses this issue by introducing a `resetSidebars` function that resets the navigation or colony switcher upon window resizing if on a device > `table`
TODO: Please test opening either the navigation or colony switcher and then resize to a viewport wider than > `1024px`. Then switch again to a viewport less wide than < `1024px`. None of these sidebars should be opened by default.
https://github.com/user-attachments/assets/7ba3beb6-7d68-44fd-b9b1-a62c0c85ccf7
* `resetSidebars` callback used for `useResize` in `PageLayoutContextProvider`
Resolves …
> [Dashboard] Mobile navigation menu opened by default

- src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
- src/components/v5/common/TableHeader/TableHeader.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/ChartCustomBar.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/ClaimFundsButton.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/IncomeSection.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/PaymentsSection.tsx
- src/components/v5/shared/Button/Button.tsx
- src/components/v5/shared/Button/ButtonLink.tsx
- src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
- tailwind.config.js
This PR fixes the following issues
Current spinner showing: 
* Step 1. In order to test the `Claim` button part, please create a `.diff` file with the following content
```
diff --git a/src/redux/sagas/actions/mintTokens.ts b/src/redux/sagas/actions/mintTokens.ts
index d13052bee..12c7658e7 100644
--- a/src/redux/sagas/actions/mintTokens.ts
+++ b/src/redux/sagas/actions/mintTokens.ts
@@ -62,18 +62,18 @@ function* createMintTokensAction({
ready: false,
});
-    yield fork(createTransaction, claimColonyFunds.id, {
-      context: ClientType.ColonyClient,
-      methodName: 'claimColonyFunds',
-      identifier: colonyAddress,
-      params: [nativeTokenAddress],
-      group: {
-        key: batchKey,
-        id: metaId,
-        index: 1,
-      },
-      ready: false,
-    });
+    // …
```
> [Dashboard] Total in and out card UI fixes

- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/MembersInformation/MembersInformation.tsx
The members / followers count should always be Colony wide and not filter when a team is selected.
This PR removes the now redundant team filtering code from the MembersInformation component.
A "member" is any user who hasPermissions or hasReputation in the colony, referred to as a contributor in the members context just to make it nice and confusing. :)
* Step 1 - Open the dashboard, switch through the different teams, the member / follower count should not change.
* Step 2 - Create a new team
* Step 3 - Select the new team in the team switcher, the member / follower count should not change.
Further testing:
* Step 4 - Give permissions to a member who currently has no permissions. The member count should increase by 1. The follower count should not change.
* Step 5 - Switch to dev wallet …
> [Dashboard] Fix: Members / followers count

- src/components/v5/shared/TeamFilter/partials/TeamsDropdown/TeamsDropdown.tsx
- tailwind.config.js
This PR addresses an issue where hovering over the team switcher dropdown items would cause the text font weight to change to bold, this would cause the container width to increase. This PR resolves this by adding an after pseudo element with the same text content set to bold to "pre-reserve" the necessary space for the bold text when hovered. It is hidden so shouldn't cause any accessibility concerns, but please raise in the comments if you see any issues with this approach.
Shrink the screen width enough so that teams drop into the dropdown filter (or add new teams). Hover each of the items, ensure that the dropdown width does not increase when hovering the longest item.
https://github.com/user-attachments/assets/56c8a191-f28b-4653-a4ad-62fc147b7f13
**Changes** 🏗
* After pseudo element …
> [Dashboard] Team switcher dropdown fixes

- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification.tsx
This PR just adds the navigation part since marking as read was already done :D 
As per usual, make sure you have the following in your `.env.local.secrets`
```
MAGICBELL_API_KEY=<ask somebody for this>
MAGICBELL_API_SECRET=<ask somebody for this>
MAGICBELL_DEV_KEY=
```
1. Create a simple payment as `leela` to `leela` two times :D 
2. Wait for them to show up in the notifications list (for sanity's sake, close the sidebar first).
3. Notice they show up and have an unread counter next to them:
4. Click one, it should mark it as read and open up the action sidebar. Verify that the action doesn't load from scratch, since it was prepopulated into the cache by this component :sunglasses: 
5. After clicking another notification it should open up another action, closing the UserHub
6. Clicking …
> [Notifications] feat: open completed action when clicking on notification in list

- src/components/common/ColonyActionsTable/RecentActivityTable.tsx
- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/common/ColonyActionsTable/hooks/useColonyActionsTableColumns.tsx
- src/components/common/ColonyActionsTable/types.ts
- src/components/frame/v5/pages/ActivityPage/ActivityPage.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/Table/partials/TablePagination/TablePagination.tsx
- src/components/v5/common/Table/partials/TablePagination/types.ts
- src/components/v5/common/Table/types.ts
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
This PR implements many UI changes to address the following 3 issues with the recent activity table.
1. When there are not enough items for there to be more than 1 page, the recent activity table should go as tall as it can until it either fills the bottom of the dashboard area, or reaches the max height it would be with 7 items.
2. The spacing between the table title and the first row was too large.
3. The hover background colour change did not extend to the full width of the table.
* Step 1 - Create a new colony using `node scripts/create-colony-url.js`
* Step 2 - Create any action so that at least one appears in the recent activity table.
* Step 3 - Check the table extends to the bottom of the dashboard on desktop and tablet. Figma: …
> [Dashboard] Recent activity table fixes

- src/components/shared/Numeral/Numeral.tsx
- src/components/shared/Numeral/NumeralBase.tsx
- src/components/shared/Numeral/NumeralCurrency.tsx
- src/components/shared/Numeral/helpers.tsx
- src/components/v5/common/WidgetCards/WidgetCardsList.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/FundsCards.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/hooks.ts
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsItem.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsSubTitle.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalDescription.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalItem.tsx
1. Run `node scripts/create-colony-url.js` and create new team
2. See that "Create team" item is shown under "All teams" and "General" filter 
Design requirements:
Result:
3. Check that all items match the design (link: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4867-40639&node-type=frame&t=yyk6XVtMJFk4l0TJ-0 ):
Pixel perfect example: 
4. Create a team and check that the "Create team" item is no longer shown
5. Go to planex colony and check that items matches the design (link: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4859-36367&node-type=frame&t=pXOwAsU0iYnga3iH-0 ):
Pixel perfect example:
6. Click on any team is selected, it should redirect to balance page with selected team:
**Changes** 🏗
* Updated NumeralCurrency formating in case …
> fix: update UI to match the design

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/NotificationsList.tsx
- src/components/common/Extensions/UserHub/partials/UnreadNotifications.tsx
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/components/common/Extensions/UserHubButton/partials/NotificationDot.tsx
- src/components/v5/common/NotificationsEnabledWrapper/NotificationsEnabledWrapper.tsx
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/useMuteColonyItem.ts
- src/context/Notifications/NotificationsDataContext/NotificationsDataContext.ts
- src/context/Notifications/NotificationsDataContext/NotificationsDataContextProvider.tsx
- src/context/Notifications/NotificationsUserContext/NotificationsUserContext.ts
- src/context/Notifications/NotificationsUserContext/NotificationsUserContextProvider.tsx
- src/routes/RootRoute.tsx
This PR achieves what the title says by splitting up the `NotificationsContext` into two parts: `NotificationsUserContext` for user's configured data regarding notifications such as muted colonies and if notification are even enabled and `NotificationsDataContext` for reading data from MagicBell and interacting with it.
For ease of use I've created a component called `NotificationsEnabledWrapper` that renders any component conditionally if the user has notifications enabled.
Should be relatively straight forward!
In case you haven't tested any other notification PRs add the following to your `.env.local.secrets` and run `npm run prepare`
```
MAGICBELL_API_KEY=<ask somebody for this>
MAGICBELL_API_SECRET=<ask somebody for this>
MAGICBELL_DEV_KEY=
```
1. Login as `leela`, create some simple …
> [Notifications] feat: do not show unread counters and the notification tab if user has notifications disabled

- src/components/v5/common/ArrowScroller/ArrowScroller.tsx
- src/components/v5/shared/TeamFilter/partials/AllTeamsItem.tsx
- src/components/v5/shared/TeamFilter/partials/CreateNewTeamItem.tsx
- src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/DesktopTeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/MobileTeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/TeamItem.tsx
- src/components/v5/shared/TeamFilter/partials/TeamsDropdown/TeamsDropdown.tsx
- tailwind.config.js
Just a bunch of CSS fixes :melting_face: 
Basically I had to make all the team items border boxes, because in Figma the border is on the inside, so it was either that or make all things 2px less tall and paddings 1px less, which would be a hassle.
Likewise, the parent item doesn't control the outer border anymore, but it's composed from the children, because we need to display a full size background when a team is selected (border included).
Go over the cases covered in #3214 and see if it works now! Additionally make sure that hovering on desktop doesn't enlarge the item.
**Changes** 🏗
* All filter items are full height flex align center items with their own border
* Added hover effects to All teams and unselected domain items
Resolves  #3214
> [Dashboard] fix: team filter CSS fixes

- src/components/v5/common/ActionSidebar/partials/hooks.ts
After open Action Sidebar to create agreement, during fetching extensions data, the no extension error banner is visible even though all required extensions are installed.
- Set network connection to eg. 3G
- Click `Create agreement` on agreements page
- Error banner should not be visible when data is fetching
**Changes** 🏗
add checking if data is not loading inside `useIsFieldDisabled` hook
Resolves https://github.com/JoinColony/colonyCDapp/issues/3239
> fix: prevent display error banner when extension data is loading

- src/redux/sagas/wallet/RetryProvider.ts
- src/redux/sagas/wallet/index.ts
Please see linked issue #3275 for more details.
This PR ensures that `getSigner` will return the signer for the current wallet unless a different address is specified. Apparently not providing an address makes it return the very first address it gets from `eth_accounts`. 
I noticed this issue in the notifications branch, but it also affects other areas, for example when updating a user profile. The auth proxy performs a similar check, comparing the GraphQL mutation's address variable with the authenticated wallet address. And because it always thinks it's the first dev wallet address, updating any other profile will fail.
1. Disconnect your wallet and clear your browser data, including cookies.
2. Connect any dev wallet other than the first one.
3. Navigate to User account and update any …
> Fix: set current wallet address as the default getSigner address

- src/components/v5/common/ActionSidebar/partials/ActionSidebarLoadingSkeleton/ActionSidebarLoadingSkeleton.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
This PR addresses an issue introduced by #3108 which caused oppose motions to be revealed. `!!userVote` was incorrectly validating MotionVote.Nay as false and has been replaced with a more explicit check `(userVote === MotionVote.Nay || userVote === MotionVote.Yay)`.
Completely unrelated, but I also fixed up a tiny key issue with the ActionSidebarLoadingSkeleton which was causing console errors.
* Step 1 - Install the reputation voting extension
* Step 2 - Create a motion, stake it on both sides.
* Step 3 - Vote to oppose the motion. When the sidebar updates to the reveal stage, it should be possible to reveal your oppose vote.
https://github.com/user-attachments/assets/b5a1a6d8-c67e-47a1-9f72-3eac7b294c71
Compared to master:
https://github.com/user-attachments/assets/20606992-f1e7-4bdb-8a …
> Fix: Unable to reveal motion oppose

- src/components/frame/Extensions/layouts/consts.ts
- src/components/frame/v5/pages/StreamingPaymentsPage/StreamingPaymentsPage.tsx
- src/routes/Routes.tsx
- src/routes/routeConstants.ts
Create subpage for streaming payments
-Open `Finances` in navigation and click `Streaming payments`
Add new Route for `Streaming subpages`
TO DO
Implement rest of the features inside the subpage
Main issue - https://github.com/JoinColony/colonyCDapp/issues/3260
> feat: add streaming payments subpage

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/MultisigNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Notification.tsx
- src/types/notifications.ts
- Send notifications for multisig actions. This includes creation, full approval, rejection and finalization.
Part of the work for this PR was done in the block ingestor here: https://github.com/JoinColony/block-ingestor/pull/275
Ensure that the following is added to your .env.local.secrets and run npm run prepare.
```
MAGICBELL_API_KEY=<ask me for this>
MAGICBELL_API_SECRET=<ask me for this>
MAGICBELL_DEV_KEY=
```
Also ensure the API_KEY and SECRET are both in the .env file inside `amplify/backend/function/createUserNotificationsData`
* Log in as Leela in one browser, and Amy in another incognito browser. As Leela, install the multisig extension. Set the threshold to be fixed at "2".
* Give Leela and Amy multisig owner permissions. Check that you receive notifications for these.
* Create …
> Send notifications on multisig actions

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
Input background not change color when dark mode is active
-Create new Advanced payment action
-The `Enter amount` input should follow current theme background color
**Changes** 🏗
Add `bg-base-white` to input class
The background is displaying correctly when theme color is changed
Resolves https://github.com/JoinColony/colonyCDapp/issues/3241
> fix: input background in darkmode

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Extension/ExtensionNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Extension/ExtensionNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Notification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/NotificationsList.tsx
- src/components/common/Extensions/UserHubButton/UserHubButton.tsx
- src/types/notifications.ts
[See block-ingestor counterpart](https://github.com/JoinColony/block-ingestor/pull/278)
This PR adds notifications whenever an extension is installed, upgraded, enabled, deprecated, uninstalled or has settings changed.
* Step 1 - Install the "Weighted Voting Reputation" extension - you should see the notification appear a few seconds later
* Step 2 - Select a "Governance style" and click enable - check for a notification.
* Step 3 -  Click the deprecate button - check for a notification.
* Step 4 - Re-enable the extension, check you get a notification for re-enabling.
* Step 5 - Deprecate the extension again and also uninstall it. You should get notifications for both.
* Step 6 -  Navigate to the Staking Advanced Payments extension and go to the extension settings tab.
* Step 7 - Change …
> [Notifications] Feat: Extensions notifications

- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/FundsClaimed/FundsClaimedNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Notification.tsx
This PR ensures that when you click a notification that it opens actions in the colony in which it was created. (Note: Similar fixes will be required for some of the other open notifications PRs, it's a very small change being added here so it can be easily copied across regardless of which order the PRs are merged.)
* Step 1 - Create a simple payment action in planex, the notification indicator should appear, don't click on the notification yet.
* Step 2 - Switch to the wayne colony.
* Step 3 - Open the UserHub and click on the notification. You should be redirected to the planex colony and the action sidebar should open with the relevant action open. Note also that the notification should be marked as read.
* Step 4 - Navigate to another page on planex, balances for example. Click the …
> [Notifications] Feat: Notification should take you to relevant colony

- src/components/v5/shared/SearchSelect/partials/CheckboxSearchItem/CheckboxSearchItem.tsx
- src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
- Action dropdown menu doesn't have hover state
Example of hover state that is expected:
1. Open Motion modal
2. Check Action type hover:
3. Check UserSelect. Select "Manage permissions" and check "Select member" dropdown:
4. Check NonVerifiedMembersSelect. Select "Manage verified members" action type. Select "Add members"
5. Check VerifiedMembersSelect. Select "Manage verified members" action type. Select "Remove members":
6. Check TeamsSelect. Select "Manage permissions" and check "Select team" dropdown.
Resolves #2898
> fix: add hover to action dropdown menu

- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsItem.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalDescription.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalItem.tsx
Seems like during merge or a lot of changes UI brake a little bit
Check that Funding cards align with the design:
> [Dashboard]: fix: align funding cards with the design

- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/CancelModal/CancelModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneReleaseModal/MilestoneReleaseModal.tsx
- src/hooks/useActivityFeed/helpers.ts
- src/redux/sagas/expenditures/releaseExpenditureStages.ts
This PR contains changes aimed at resolving advanced payment issues identified in production deployment:
- Split payment crashing: A race condition that only occurred when fetched expenditure contained a slot but no payouts (UI needed to poll it right in between 2 chain events) and unsafe array access led to the entire app intermittently crashing while creating a split payment.
- "Make next payment" button stuck: When releasing milestone using permissions, the button could get stuck in Pending state. The app had to be refreshed.
- Release expenditure stages action was showing in the activity feed as a Generic action.
- Cancel expenditure modal was missing a translation for its submit button.
- `releaseExpenditureStages` saga was unnecessarily claiming payouts twice.
> Hotfix: Advanced payments production issues

- src/components/common/ColonyActions/helpers/getActionTitleValues.ts
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
- src/components/common/ColonyActionsTable/partials/ActionMobileDescription/ActionMobileDescription.tsx
- src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakeItem.tsx
- src/constants/actions.ts
- src/hooks/useAmountLessFee.ts
- src/utils/getAmountLessFee.ts
This PR fixes an issue where all amounts in the activity feed were assumed to include a network fee. This resulted in Mint Token actions and Move Funds actions to show an incorrect amount. This PR updates the `mapColonyActionToExpectedFormat` function to show the correct amount including or excluding the network fee based on the action type.
Note: Once this is merged and `feat/in-app-notifications` is rebased, we should update the uses of `getActionTitleValues` within the notification components to include the `networkInverseFee`.
Mint Tokens
* Step 1 - Create a Mint Tokens action (I like to include the amount in the custom title to make it easier to check the correct amount is shown in the description line)
* Step 2 - Check the action has the correct amount in the activity feed
Transfer …
> Fix: Activity feed description should use correct amount value

- src/redux/sagas/actions/manageVerifiedMembers.ts
This PR fixes an issue with the Manage Verified Members action saga which was preventing actions with descriptions from being created.
Create a Manage verified members action, make sure you enter a description. It should be created without issue.
**Changes** 🏗
* Manage Verified Members action saga takes from the correct channel
Resolves #3285
> Fix: ManageVerifiedMembers action saga should use correct annotation channel

- src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
Fix pagination inside `Incoming funds` table
-Send multiple payments to a colony of the same token, 16 or more.
-Navigate to the Incoming funds page.
-Expand the token to see the individual incoming funds.
-Pagination should work now properly
https://github.com/user-attachments/assets/4445b75c-6799-4965-aeb7-4c7f8630b23f
**Changes** 🏗
Add pagination props for table
Resolves https://github.com/JoinColony/colonyCDapp/issues/3282
> fix: pagination inside incoming founds table

- src/components/v5/common/TableHeader/TableHeader.tsx
According to descussion here - https://github.com/JoinColony/colonyCDapp/pull/3257#issuecomment-2393667391 padding should be updated to 14px to match the Design System
1. Open Balance table
2. Ensure that padding is 14px
3. Open incoming table
4. Ensure that padding is 14px
Resolves #3353
> fix: update padding according to the design system

- src/components/v5/common/Fields/InputBase/InputBase.tsx
Motions "Create new team", "Edit a team" or "Edit colony" have input with white bg in dark mode.
1. Enable "Dark mode"
2. Open "Create new team" motion
3. Ensure that there is no white bg for inputs
4. Check "Edit a team", "Edit colony" as well
5. Check "Split payments":
Resolves #3319
> fix: InputBase dark mode background

- src/redux/sagas/motions/paymentMotion.ts
O N E L I N E R
Basically, the lookup for the voting reputation's permission proofs was done for the motion domain instead of the domain the funds are getting sent from.
2. Create a simple payment motion sending some CREDS to `leela` from `Andromeda`, but create the motion in `General` (you can note how many CREDS she has)
3. Fully support it and run `npm run forward-time 1` to get to the finalization step
4. Try finalizing it, it should pass (double check if the CREDS came to `leela`'s wallet
5. For a sanity check, create a simple payment motion paying some CREDS from `Serenity` and create the motion in `Serenity`, support it, forward time, finalize it
**Changes** 🏗
* use `domainId` instead of `motionId` for permission proofs lookup of the …
> fix: get permissions for the extension for the payment domain instead of motion domain

- src/components/common/Onboarding/wizardSteps/CreateColony/StepColonyNameInputs.tsx
Display characters length inside colony name input 
- Start "Create colony" flow
- Enter some chars in the Colony name field
**Changes** 🏗
Add flag `shouldNumberOfCharsBeVisible` to input
Before:
After:
Resolves https://github.com/JoinColony/colonyCDapp/issues/3294
> fix: display characters length in colony name input

- src/components/common/ColonyActionsTable/hooks/useColonyActionsTableColumns.tsx
- src/components/common/ColonyActionsTable/partials/ActionBadge/ActionBadge.tsx
- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
- src/components/common/ColonyActionsTable/partials/ActionMobileDescription/ActionMobileDescription.tsx
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/MembersInformation/MembersInformation.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/ReputationChart.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/Chart.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/Legend.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/ClaimFundsButton.tsx
- This PR addresses several issues
The rounded corners don't match the components above the table, and it would be nice to closer match the data coming into the table. 
Currently: 
Figma:
Hover: 
Once selected: 
"There is no reputation in the team yet"
Row in question:
Currently positioned at the top close to the bottom of the chart:
Figma, positioned at the bottom of the widget:
TODO: Please test the above mentioned issues are solved
* Step 1. For first issue you need to check the loading state of the `Recent activity table` rows. 
So either refresh the page or set `loading` in `useColonyActionsTableColumns.tsx` and `isLoading` in `ActionDescription.tsx` to `true`
* Step 2. Check the `members` and `folowers` links in the Dashboard page header link to the correct page …
> [Dashboard] UI fixes after review

- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
This PR updates the hover style of the Colony Switcher component's CTA button.
It should follow the [following design](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1801-442&t=nv2Gpt6jBfFgIjrI-4):
1. Open the Colony Switcher component
2. Hover on the button
3. Make sure that the hover state follows the Figma design
Resolves #3369
> [New Navigation] Update Colony Switcher hover style

- src/components/shared/FeedbackButton/FeedbackButton.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/BasicPageSidebar.tsx
This PR enables the hover behaviour of the feedback button in the basic sidebars:
1. Visit http://localhost:9091
2. Hover on the Feedback button
3. Verify that the full Help & Feedback button [appears as an overlay](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3962-9052&t=hzVYQp5JhZ8uVwNQ-4)
Resolves #3375
> Feat: Update Feedback button hover behaviour

- amplify/backend/api/colonycdapp/schema/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Extension/ExtensionNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Notification.tsx
- src/graphql/generated.ts
- src/types/notifications.ts
This PR implements notifications when a new extension version has been added to the network.
[Block-ingestor PR](https://github.com/JoinColony/block-ingestor/pull/281)
Not that different from testing the colony versions!
__Note:__ I've actually accidentally gave `amy` permissions in `wayne`, not `planex`, but you can test it that way too, doesn't matter :')
1. Open the app as `leela` and also as `amy` to get necessary notification data on both of them
2. As `leela` assign `amy` `Owner` permissions in `wayne`
3. Run `npm run hardhat`. In the console, run the following to generate a new extension version of `OneTxPayment` (you can use any of these as the second argument)
```
deployNext=require("./scripts/deployOldUpgradeableVersion.js").deployNextExtensionVersion
cn = await …
```
> [Notifications] feat: send notifications when there is a new extension version available

- docker/colony-cdapp-dev-env-block-ingestor
New block ingestor hash which contains work to not show users mentions from actions that they created themselves.
Block ingestor PR: https://github.com/JoinColony/block-ingestor/pull/282
* First, log in as both Leela and Amy.
* As Leela, create a simple payment to Leela.
* As Leela, create a simple payment to Amy.
* Check Leela's notifications - there should not be a **mention notification** about either action.
* Check Amy's notifications - there should be one **mention notification**, about the action which sent a payment to Amy.
**Changes** 🏗
* Changes in block ingestor: https://github.com/JoinColony/block-ingestor/pull/282
Resolves #3387
> Fix: Dont send mention notifications to the same address as the creator

- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/MotionNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/MultisigNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/FundsClaimed/FundsClaimedNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/NotificationWrapper.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx
- src/components/v5/common/DropdownMenu/partials/DropdownMenuItem/DropdownMenuItem.tsx
- src/components/v5/common/DropdownMenu/partials/DropdownMenuItem/types.ts
- src/components/v5/common/InfiniteScrollLoader/index.ts
- src/components/v5/common/InfiniteScrollTrigger/InfiniteScrollTrigger.tsx
- src/components/v5/common/InfiniteScrollTrigger/index.ts
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/useHeaderLinks.ts
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/useMuteColonyItem.tsx
After an in-depth review of the in app notifications branch with product and design, there were a few minor UI fixes / changes which needed to happen. This PR is a small bundle of these minor fixes (the big ones have been split out into their own separate tickets)
The changes include:
* Adding a hover state to the notifications in the user hub
* Navigate to the incoming funds page (instead of the balances page) when a user clicks on an incoming funds notification
* Don't show "No more results" at the end of the notifications list unless there has been pagination loaded
* Show a toast when a colony is muted / unmuted, and change the loading state slightly
* Edit the action created notification messages to differentiate between different decision methods
As always, please ensure you have …
> Fix: UI fixes for in app notifications after review

- src/components/frame/v5/pages/UserAdvancedPage/UserAdvancedPage.tsx
- src/components/frame/v5/pages/UserAdvancedPage/partials/UserAdvancedSettings/UserAdvancedSettings.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/CryptoToFiatPage.tsx
- src/components/frame/v5/pages/UserPreferencesPage/UserPreferencesPage.tsx
- src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/UserAccountForm.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/UserAccountPage/UserAccountPage.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/hooks/useTitle.ts
This PR aims to align the latest breadcrumb with the account page headings.
> [!NOTE]
> The only exception is the Advanced settings page. Even though the breadcrumb says "Advanced", we're still expecting the page heading to be "Advanced settings"
1. Visit http://localhost:9091/account/profile
2. Verify that the page heading is "Profile"
3. Click the "Preferences tab" on the left sidebar
4. Verify that the page heading is "Preferences"
5. Click the "Advanced settings tab" on the left sidebar
6. Verify that the page heading is "Advanced settings"
7. Click the "Crypto to fiat" on the left sidebar
8. Verify that the page heading is "Crypto to fiat"
Resolves #3371
> [Dashboard] Update Account Page Headings

- src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateToken.tsx
- src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenInputs.tsx
This PR makes sure that the selected Token logo is persisted even if you leave the page where you get to select/modify the Token logo.
1. Generate a create colony URL: `node scripts/create-colony-url.js`
2. Set a Colony name and a Custom Colony URL and click Continue
3. Select Create a new token and click Continue
4. Set a Token name and a Token symbol
5. Select a Token logo
6. Click the Back button
7. Click Continue
8. Verify that the Token logo persists
9. Click the Continue button
10. Click the Back button
11. Verify that the Token logo persists
12. Finish up the Colony creation flow
13. Visit the Balances page http://localhost:9091/{yourColonyName}/balances
14. Verify that your Token logo is definitely uploaded properly
Resolves #3300
> Fix: Persist selected Token logo during Colony creation

- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/MultiSigWidget/partials/ApprovalStep/ApprovalStep.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/partials/Signees/partials/RoleApprovalTooltip/RoleApprovalTooltip.tsx
- src/components/v5/shared/Button/ActionButton.tsx
- src/hooks/multiSig/useDomainThreshold.ts
Just tidying up stuff according to the issue :broom: 
Check out the issue for some more details.
1. Install the multisig extension, set the global threshold to 2
2. Give `leela` the multisig owner role in `General` and `amy` a multisig payer role in `General`
3. Create a simple payment multisig motion in `General`
4. Verify that the tooltip over `Signatories` is aligned to the top
5. Verify that the text in the top is reworded to `This action requires a bundled approval. Each approval is based on the permissions you hold.`
6. The tooltip over the role counter should say "core multi-sig permissions" instead of just "core permissions"
7. Try removing a vote, voting again, the loader should now not be a spinner
8. Finally, try refreshing the page with the action txHash in the URL, the …
> fix: multisig widget UI tweaks

- src/components/frame/v5/pages/MembersPage/utils.ts
- src/transformers/index.ts
Funny thing, this bug has been fixed at least three times, but it’s still present. 😁
Here is previous fixes for reference: https://github.com/JoinColony/colonyCDapp/pull/2971 , https://github.com/JoinColony/colonyCDapp/pull/3024 , https://github.com/JoinColony/colonyCDapp/pull/2485 
I decided to use the implementation from my last PR, but if you have any concerns, I’m open to refactoring.  🙌
Step 1. Assign Admin permissions to fry in Andromeda
Step 2. Assign Payer permissions to fry in General
Step 3. Assign Payer permissions to amy in Andromeda
Step 4. Assign Admin permissions to amy in General
Step 5. Navigate to the permissions page to check fry's and amy's roles in Andromeda
Step 6. fry should be an admin, amy should be an admin with inherited pill
Step 7. Install multi-sig extension …
>  fix: permissions inherited roles visability

- src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx
- src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
This applies the suggested padding adjustments to both the Colony Sidebar and the Breadcrumbs.
> [!NOTE]
> I appreciate that it might be quite tricky to test the paddings using a Browser's inspect element tool if you used the Figma examples as a reference. This is because the Figma example is showing the distance from the Colony Logo and not from the Colony Switcher button's border.
>
> A good way to test the Colony Page sidebar top padding is using the Pixel Perfect extension:
**Pixel perfect: Colony Page Sidebar**
As for the Breadcrumbs component, I simply added a 10px top padding as per the instruction on the issue.
A good way to check the alignment is to make sure that the bottom part of the letters of the Colony name and the bottom part of the Breadcrumbs letters are aligned. …
> [Dashboard] Update Colony Page sidebar and non-mobile Breadcrumbs paddings

- docker/colony-cdapp-dev-env-block-ingestor
When a multisig is fully approved, we should ensure that only one notification is fired about this approval.
Previously one notification was being sent for each role the user voted with, which in the case of a simple payment for example is three, so you would end up with three notifications all at the same time saying that the multisig motion was approved.
Block ingestor changes here: https://github.com/JoinColony/block-ingestor/pull/283
* Install the multisig extension and set the threshold to 2
* Give both Leela and Amy owner permissions for multisig
* Create a simple payment multi sig action
* You should not receive an "approved: " notification about the multisig yet since the threshold wasn't yet met, although Leela should have had her approval automatically added as the creator
* Log …
> Fix: Only fire one notification on multisig approval

- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/hooks/useLocationChange.ts
- This PR fixes the issue of having the `Create new action` sidebar replacing the completed action sidebar when navigating to another route by closing it if previously the `tx` parameter was present or the action sidebar is opened.
TODO: Please check the action sidebar is closed when navigating to another route which removes the `tx` parameter. Easiest way to test this is via the notifications
* Step 1. Create a mint tokens action
* Step 2. Click the "mint tokens" notification to have a transaction open in the sidebar.
* Step 3. Click the "incoming funds" notification which will navigate you to the balances page.
https://github.com/user-attachments/assets/c3ac460e-abea-4f26-bff5-ac8669adac2f
* `useLocationChange` hook
Resolves #3311
> [Notifications-ish] Action Sidebar should automatically close when tx params is removed from the URL

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureFundingMotionNotificationMessage.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Notification.tsx
- This PR handles the notifications sent for the `FundExpenditureMotion` actions when an expenditure is funded with reputation.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/286)
TODO: Let's test the notifications indeed appear when we fund an expenditure with Reputation. 
* Step 1. Install the `Reputation weighted` extension
* Step 2. Create an advanced payment
* Step 3. At the `funding` step, please select `Reputation`
* Step 4. Up until this point you should see only the notifications related to the extension installation and advanced payment creation
* Step 5. Now let's support the motion
* Step 6. Two more notifications should have appeared 
- one for the motion creation: Reputation decision: Funding for `advanced_payment_title`
- and the other one for being …
> Notifications: Send motion notifications for expenditures funded with motions

- src/components/common/Onboarding/wizardSteps/CreateColony/StepColonyName.tsx
I solved this by comparing it to the colony name creation, figuring out that one works and this one doesn't, what's the difference?
Well basically it wasn't a race condition, but it instead "revalidated" when the field changed focus :melting_face: 
1. Run the create data script
2. Run `node ./scripts/create-colony-url.js` and open the URL
3. Into the URL field, enter `planex` and wait for this to appear
4. Enter something else and URL should be available
Notice how you don't see the URL available flashing into URL already taken behaviour described in the original issue
**Changes** 🏗
* `onChange` revalidation mode to the colony name step
Resolves #3309
> fix: validation mode for checking if colony url exists form

- amplify/backend/function/bridgeXYZMutation/src/handlers/getUserLiquidationAddress.js
- amplify/backend/function/bridgeXYZMutation/src/index.js
- amplify/backend/function/colonycdappSSMAccess/lib/nodejs/getParams.js
In preparation for this month's payroll, we needed a way to override some of the liquidation addresses returned from Bridge and replace them with ones created under Metacolony. This PR adds the ability to override liquidation address for a given wallet address using env variable (locally) and SSM parameter (in QA and prod).
Create or update the .env file of the bridgeXYZMutation lambda (`amplify/backend/function/bridgeXYZMutation/.env`). It should have the following 3 values in it:
```
BRIDGE_API_URL=https://api.sandbox.bridge.xyz
BRIDGE_API_KEY=<sandbox key, ping me if you don't know it>
LIQUIDATION_ADDRESS_OVERRIDES="{"0xb77D57F4959eAfA0339424b83FcFaf9c15407461": "test address override"}"
```
The last variable is a JSON object mapping wallet addresses to their respective overrides. In …
> Feat: Allow overriding user's liquidation address

- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx
This PR applies the fix introduced in #3307 for the amount in the activity feed and applies it to the notification messages.
Due to the way notification messages are structured, it is very unlikely this would ever actually show up in production as it priorities the custom title, so would only ever show if a custom title was not provided (which is not possible via the UI). However it is such a tiny fix that we will apply it regardless!
* Step 1 - Go to `src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/MotionNotificationMessage.tsx` and remove actionTitle from the `secondPart` variable.
```
const secondPart =
actionTitle || actionMetadataDescription || formatText(MSG.unknownAction);
```
Should become:
```
const secondPart = …
```
> [Notifications] Fix: Notifications should use correct amount

- src/components/frame/v5/pages/AgreementsPage/AgreementsPage.tsx
- src/components/frame/v5/pages/AgreementsPage/hooks.ts
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementCard/AgreementCard.tsx
- src/components/frame/v5/pages/AgreementsPage/utils.ts
- src/components/v5/common/ActionSidebar/partials/SaveDraftButton/SaveDraftButton.tsx
- src/components/v5/common/Pills/PillsBase.tsx
- src/components/v5/common/Pills/types.ts
- display the most recent agreement, but only to the creator, even if staking threshold is not met
- fixed an issue where the entire list was reloaded on add. Now, only the first item is added to the list without refreshing the entire content
* Go to agreements page.
* Create a agreements using Reputation decision method. Some passing 10% threshold and some not.
* After adding new agreements, check if it's visible without staking and if whole list is not reloading when adding new agreements.
Resolves https://github.com/JoinColony/colonyCDapp/issues/3240
> feat: show newest agreement

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/VotingReputationSettings/VotingReputationSettings.tsx
Nice simple fix - as the title describes.
* Step 1 - Install voting reputation extension
* Step 2 - Enable voting reputation
* Step 3 - Switch to extensions setting tab - check the body font color.
Figma: https://www.figma.com/design/6qONTE1uD9K4yoIbfFzidg/Extensions?node-id=301-36307&t=SK0TZL8h23Z4rmxW-4
**Changes** 🏗
* Extension setting body font is text-gray-600
Resolves #2897
> Fix: Voting reputation settings body font color should be text-gray-600

- src/components/v5/common/TokensModal/TokensModal.tsx
- src/components/v5/shared/Modal/Modal.tsx
On mobile, the CTA buttons for all modals should be aligned to the bottom.
Check any modals on mobile and ensure the buttons are aligned to the bottom.
* Activate tokens (accessed via userhub)
* Withdraw tokens (accessed via userhub)
* Uninstall extension confirmation
* Re-enable extension confirmation
(Note there is a separate issue for the UserHub icons blocking the close modal button which is out of scope for this PR - #3440)
Confirm that modals have not broken on desktop, or that other modals which do not have buttons (such as the activity feed filters) still work as expected.
**Changes** 🏗
* Modal should take up full height on mobile and align buttons to bottom
Resolves #3291
> Fix: Modal button alignment on mobile

- amplify/backend/function/bridgeXYZMutation/src/index.js
- src/redux/sagas/utils/expenditures.ts
Cosmetic-looking change that caused the linked issue when Bridge API went down earlier today. The JSON response got stringified and a payment was attempted to `{ success: false }`.
This PR changes the return value of the bridge mutation to `null` if error is thrown. 
To test the fix, you will need to simulate an error in `getUserLiquidationAddress` handler, and make a payment that will trigger liquidation address swapping.
While you could set your native token address as `USDC_LOCAL_ADDRESS` in `.env.local`, go through KYC, add bank details and enable auto offramp, you can also create a file called `diff` with the contents below and apply the patch with `git apply diff`. It will make liquidation address swapping happen for any token and recipient, and throw an error inside the lambda …
> Fix: bridgeXYZMutation to return null on error

- src/components/common/ColonyFunding/ColonyFunding.tsx
This PR comments out the team filter on the incoming funds page. The contracts are being worked on to allow incoming funds per team so this will be re-enabled at a later point.
Navigate to the incoming funds page. Confirm the team filter is not visible.
**Changes** 🏗
* Commented out team filter
Resolves #3476
> Fix: Hide team filter on incoming funds page

- src/components/frame/v5/pages/FundsPage/context/IncomingFundsLoadingContext.ts
- src/components/frame/v5/pages/FundsPage/context/IncomingFundsLoadingContextProvider.tsx
- src/components/frame/v5/pages/FundsPage/partials/AcceptButton/AcceptButton.tsx
- src/components/frame/v5/pages/FundsPage/partials/FundsTable/FundsTable.tsx
* Step 1. Login with metamask
* Step 2. Clean Metamask history (Metamask -> Settings -> Advanced -> Clear activity tab data)
* Step 3. Navigate to Balance page
* Step 4. Click Add funds to the Colony and Copy Wallet address
* Step 5. Metamask -> send -> Paste Colony Wallet Address -> Send something to the colony (1 eth or if you choose xDai as Ganache Currency symbol choose xDai)
> [!TIP]
> If you don't have ETH to send try to delete Account and Import it again
> If something doesn't work anyway, try to delete Ganache network and install it again
* Step 6. Navigate to Wayne Enterprises
* Step 7. Create simple payment from General to Colony Wallet Address that you copied at Step 4. 
* Step 8. Navigate back to Planet Express
* Step 9. Navigate to Incoming funds
* Step 10. Try to Accept this …
> fix: disable 'Accept' incoming funds buttons when other button was clicked

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx
- src/components/v5/shared/NotificationBanner/NotificationBanner.tsx
- src/components/v5/shared/NotificationBanner/types.ts
For 720-768px error message was broken: 
I really hope that my fix will not break anything else, but all I tested now works 😄  
* Step 1. Login with MetaMask
* Step 2. Create Simple payment motion
* Step 3. Reject transaction
* Step 4. Open UserHub -> Transactions and ensure that all screens looks good
Resolves  #3056
> fix: update UserHub transactions to have correct styles for 720-768px screen

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/hooks.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/ExtensionSettingsForm.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/utils.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/PermissionsNeededBanner.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/utils.tsx
- src/i18n/en.json
- src/redux/sagas/extensions/extensionEnable.ts
- src/redux/sagas/extensions/extensionInstallAndEnable.ts
This PR aims to improve failed transactions when installing / enabling / assigning permissions for extensions.
Currently, when installing an extension it will call the `extensionInstallAndEnable` saga which includes transactions for install, initialise and setUserRoles (and will conditionally call them depending on the extension configuration).
However, if either the initalise or setUserRoles transaction fails or is rejected, the UI will not handle this error state correctly and will appear as though the extension has not been installed (even though the install transaction succeeded).
This PR aims to resolve this by adding error steps to the `extensionInstallAndEnable` saga and pick these up in the error handler to update the UI as appropriate.
Whilst working on this, I discovered the …
> Feat: Improve failed extension transaction handling

- src/components/v5/frame/PageLayout/PageLayout.tsx
- tailwind.config.js
This PR adds scrollbar-gutter: stable to the main content area. It reserves space for the scrollbar so it will prevent content from jumping around when the scrollbar appears / disappears. It is not fully supported, so we should be aware that this does not resolve this issue for Safari / iOS (https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter).
Set the screen size so that there is no scrollbar. Resize so that the scrollbar appears. The content should not jump around.
This branch:
https://github.com/user-attachments/assets/e3b42737-69cd-46a0-92d5-8d3848d0b209
Master:
https://github.com/user-attachments/assets/5d7e8ce7-ad9c-4678-857e-5453722e358e
* Added `scrollbar-gutter-stable` utility class
* Added new class to main content area
Resolves #3513
> [Dashboard] Fix: Scrollbar shifts main content

- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
- src/hooks/useLockBodyScroll/index.ts
Currently, the scrolling behaviour of our app can be interacted with while the Tablet Colony Sidebar is active, which is not ideal. This PR locks the scroll of the body when the Tablet Colony Sidebar is active.
1. Visit a Colony
2. Set your browser to a mobile viewport
3. Expand the Colony Sidebar by clicking the Menu button
4. Hover on the top nav and attempt to scroll it
5. Verify that you are unable to
6. To compare, check out to the `master` branch and attempt to scroll it and you will be able to
| This branch | Master branch |
| ![scrollable NOT](https://github.com/user-attachments/assets/cb078dbb-a4bb-497a-8918-c11dae1a2042) | ![scrollable](https://github.com/user-attachments/assets/42b24eae-bb84-46ed-9df7-cc565d441492) |
* I added a new hook called …
> Fix: lock the body scroll when the tablet Colony Sidebar is active

- src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx
When a user is in a child menu item of the Finances area, the mobile navigation isn't expanded by default to show the active page being visited by the user. This causes confusion as nothing shows as being active in the menu and I do not know where I am, since the mobile is full screen.
This PR makes sure that the current page is highlighted.
1. Set the view to mobile
2. Visit the Incoming page: http://localhost:9091/planex/incoming
3. Click the Menu button
4. Verify that the Finances accordion is auto-expanded and Finances is highlighted
5. Please do the same for the Balances page
Resolves #3505
> Fix: Auto-expand accordions to reveal the current route

- src/components/v5/shared/Navigation/Sidebar/sidebars/AccountPageSidebar/AccountPageSidebar.tsx
This PR will only show the Crypto to fiat nav item on the Account Page Sidebar if the `CRYPTO_TO_FIAT` feature flag is initialised and enabled.
> [!NOTE]
> Visit http://localhost:9091/account/profile
> Please make these changes in the `FeatureFlagsContextProvider.tsx` file
> Simply replace the `[FeatureFlag.CRYPTO_TO_FIAT]: cryptoToFiatFeature,` with the following code blocks
```js
[FeatureFlag.CRYPTO_TO_FIAT]: {
isLoading: true, // NOT INITIALISED
isEnabled: false, // DISABLED
},
```
**Expected outcome:** The Crypto to fiat nav item is hidden.
```js
[FeatureFlag.CRYPTO_TO_FIAT]: {
isLoading: false, // INITIALISED
isEnabled: false, // DISABLED
},
```
**Expected outcome:** The Crypto to fiat nav item is hidden.
```js
[FeatureFlag.CRYPTO_TO_FIAT]: {
isLoading: true, // NOT INITIALISED …
```
> Fix: Conditionally show the crypto to fiat nav item

- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
This PR fixes the bottom padding padding for the Teams page.
During development, I noticed that the Activity table on the Dashboard page has a redundant margin bottom so I removed it as well.
| <img width="1075" alt="Screenshot 2024-10-29 at 20 27 30" src="https://github.com/user-attachments/assets/ea12d029-dff2-4ca4-b251-a65ac54250d8"> | <img width="1075" alt="Screenshot 2024-10-29 at 20 27 16" src="https://github.com/user-attachments/assets/d508e5e4-f574-459c-880b-b5971c2a3332"> |
1. Go to the `TeamCardList.tsx` file
2. Replace line 15 with this:
```js
// This basically just increases the team cards rendered
{[items, items, items].flat().map(({ key, ...item }) => (
```
3. Visit the Teams page: http://localhost:9091/planex/teams
4. Scroll to the very …
> Fix: Teams Page bottom padding adjustment

- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/constants.ts
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/validation.ts
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/useBankDetailsFields.tsx
This PR adjusts the validation for the crypto to fiat bank account validation to allow for spaces or hyphens as separators. This will make it easier for users copying their bank details into the forms.
It adds an alphanumeric check to each account number field and will display a specific error message if any non alphanumeric values are entered (ignoring the two valid separators).
The separators are stripped out before validating against regex and when submitting the values to the API.
Please check Arren's comment on the original issue for the exact specs: https://github.com/JoinColony/colonyCDapp/issues/2961#issuecomment-2307001840
* Step 1: Edit `src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetails/consts.ts` and replace line 95 with `false` to enable the CTA button …
> Fix: Allow separators in bank account number validation

- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/ColonyLinks.tsx
Wee update to the contract address copy button:
1. Visit a Colony
2. Click this button
3. Verify that the tooltip copy changes to "Contract address copied!"
Resolves #3493
> Fix: Update contract address copied copy

- src/components/frame/Extensions/layouts/hooks.tsx
This PR ensures the "Upgrade" button on the Calamity Banner is always enabled for all users when a new colony version is available.
To save you the hassle of deploying a colony on an older version, we must first update the `canColonyBeUpgraded` function in `src/utils/checks/canColonyBeUpgraded.ts` to return true.
* Step 1 - Connect to a colony as a user with root permissions. Confirm the Calamity Banner is visible and the upgrade button is enabled.
* Step 2 - Connect to a colony as a user without root permissions. Confirm the Calamity Banner is visible and the upgrade button is enabled.
* Removed `canUpgradeColony` and related uses from `useCalamityBannerInfo`
Resolves #3340
> Fix: "Upgrade" button on Calmity Banner should be enabled for all users

- src/components/v5/shared/UserInfoPopover/UserInfoPopover.tsx
At the moment, we're only closing the popover User Info popover which is used on Desktop mode. So I'm just simply handling the Modal we use on mobile as well.
1. Visit the followers page: http://localhost:9091/planex/members/followers
2. Set the browser to mobile view
3. Click an unverified user i.e. jasmine-jolt
4. Verify that the User Info modal shows up
5. Click the Add as verified member button
6. Verify that the Modal is closed when the Action Form comes up
Resolves #3527
> Fix: Close the user info modal when the Action Form comes up

- src/components/frame/v5/pages/UserAdvancedPage/partials/NotificationsSection/NotificationsSection.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/CryptoToFiatPage.tsx
- src/components/frame/v5/pages/UserPreferencesPage/UserPreferencesPage.tsx
- src/components/frame/v5/pages/UserPreferencesPage/partials/EmailSection/EmailSection.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/UserAccountForm.tsx
- src/components/v5/common/SettingsRow/SettingsRowContainer.tsx
- src/components/v5/common/SettingsRow/SettingsRowContent.tsx
- src/components/v5/shared/Navigation/Sidebar/partials/SidebarContentDivider.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/AccountPageSidebar/AccountPageSidebar.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
- src/i18n/en.json
These fixes are only within the scope of what's been raised in issue #3509 and #3501.
1. The mobile version of the Email Preferences field should follow the [Figma designs](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6401-11782&t=QSsB9RdPVTORnWg3-4):
2. These components should have a 24px (gap-6) spacing in between them:
3. Rename "Advanced settings" to "Advanced"
4. The H4 elements for the account pages should be brought back as per these [Figma designs](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=7505-8667&t=vfU0W3QeCMXUzTNU-4)
Here's Crypto to fiat's H4: https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=4441-108444&t=9p1Uvq5xWxYFmdVW-4
5.  The horizontal divider should match the style of the horizontal …
> Fix: Account Page UI Updates

- src/components/v5/common/ActionSidebar/partials/PaymentGroup/GroupList.ts
- src/components/v5/common/ActionSidebar/partials/PaymentGroup/PaymentGroup.tsx
- src/components/v5/common/ActionSidebar/partials/PaymentGroup/useGetGroupList.tsx
The "Staged payment" action is missing from the payment group
Step 1 - Install the "Staged Payment" extension
Step 2 - Click the "Make payment" menu item
Step 3 - Verify that "Staged Payment" in the list
Step 4 - Deprecate the "Staged Payment" extension
Step 5 - Click the "Make payment" menu item
Step 6 - Verify that "Staged Payment" is NOT in the list
Resolves #3441
> fix: show staged payment (if it enabled) in payments list

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilderEdit/PaymentBuilderEdit.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilderEdit/hooks.ts
- src/redux/sagas/utils/expenditures.ts
This PR modifies how `editExpenditure` saga treats the modified payouts. Previously, when editing expenditures, removed payout slots were being recycled for new payouts. For example, if you removed payout #3 and added a new payout, the new one would take slot #3. This led to issues with displaying the list of changes since the UI saw it as "modifying slot #3" rather than "removing one payout and adding another."
It also updates block-ingestor hash to one from [block-ingestor#291](https://github.com/JoinColony/block-ingestor/pull/291), which fixes another edge case with editing expenditures.
> Fix: Editing expenditures

- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/MultiSigMembersError/useHasEnoughMembersWithPermissions.ts
- src/hooks/multiSig/useEligibleSignees.ts
The not enough multi-sig permissions error banner flashes when selecting the "Multi-sig" decision method.
[372548146-d5615d2e-5119-410f-ad4d-b4f47fdcc742.webm](https://github.com/user-attachments/assets/b4058c9d-3e49-4e49-98de-0b33993adc34)
Step 1. Enable Multi-sig extension 
> [!TIP]
> Give leela Multi-sig permission in General to have Authority "via Multi-sig" available 
Step 2. Create a Simple payment motion
Step 3. Verify that Multi-Sig error is NOT flashed
Because `isLoading` was `false` by default and set to `true` using the async function, it was the very first render with `"isLoading": false`. This led to our component understanding it as "okay, we have all data rendered and it's empty—let's render an error then."
So I changed it for the very first rendering `isLoading` will be …
> fix: hide multi-sig error if there are still loadings

- src/components/common/LoadingSkeleton/LoadingSkeleton.tsx
- src/components/frame/Extensions/themes/consts.ts
- src/components/frame/Extensions/themes/utils.ts
- tailwind.config.js
Change gradient color for loading skeleton in dark mode
- Set app to dark mode
- Open any loading skeleton while fetching data
**Changes** 🏗
Before:
After:
Resolves [#31415](https://github.com/JoinColony/colonyCDapp/issues/3293)
> fix: change loading skeleton gradient for dark mode

- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/ChartLoadingLayer.tsx
It simply removes Pie Chart's boxy black background:
1. Open the app on a Safari browser
2. Go to a Colony Dashboard
3. Reload the page and just observe the Pie Chart as it loads
4. Verify that it doesn't have a black box background for both light and dark themes:
Resolves #3570
> Fix: Remove Pie Chart's black box background

- src/components/shared/Extensions/Tabs/Tabs.tsx
Just a simple adjustment to how these components are aligned.
| <img width="500" alt="Screenshot 2024-10-31 at 22 48 04" src="https://github.com/user-attachments/assets/93fcc79d-7a84-452b-937e-306a83d1ce77"> | <img width="501" alt="Screenshot 2024-10-31 at 22 47 40" src="https://github.com/user-attachments/assets/b97ccbc2-6e06-4c74-a3c7-b8d9a2bc583f"> |
1. Visit the account page
2. Set the view to iPhone SE
3. Verify that the arrows are aligned along the same line as the tab copies:
Resolves #3542
> Fix: Mobile tab arrow alignment update

- src/components/common/ColonyActionsTable/RecentActivityTable.tsx
- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/Table/partials/TableRowDivider.tsx
- src/hooks/useActivityFeed/useActivityFeed.ts
- This PR aims to solve multiple issues related to the activity table:
Please keep in mind I did resist the urge to refactor the `Table` component.
TODO: Please test all these scenarios are resolved. For the first issues you can use `Chrome` as on this branch a bug regarding the pagination is still present (fixed by ), for the second issue any browser would do, but for the last 2 issues please use Safari or a mobile simulator - shout if you need help configuring a mobile simulator 😉 
* Step 1.1. Let us test the pagination no longer resets when requesting new data. In `ColonyHome` please update the `pageSize` to `3` for the `RecentActivityTable` component - thus you'll have more pages of data to test this.
* Step 1.2. Click as fast as possible on the `Next` button to make sure the correct …
> Fix: Activity feed table fixes

- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransferDescription.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransferDescriptionRow.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/consts.ts
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/hooks.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/Table/types.ts
| **Before** | **Now** |
| ----- | ----- |
| ![Screenshot 2024-07-29 at 12 24 20](https://github.com/user-attachments/assets/8fa675b4-9ea6-4e1a-9800-a0d4d2446bef) | <img width="589" alt="image" src="https://github.com/user-attachments/assets/8d983f0b-fcdf-4ae8-a8ee-fa24a998d4a5"> |
1. Create `.diff` file in your root direction
2. Insert this changes:
```
diff --git a/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx b/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
index 6108cd1dc..167bc241a 100644
--- a/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
+++ b/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTab …
```
> fix: update table for mobile view

- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
This adds a vertical overflow for the action sidebar content
1. Go to a Colony
2. On the left sidebar, click Manage Colony
3. Verify that:
- the action sidebar content isn't overflowing
- the action sidebar content's hidden components can be viewed via scrolling
4. Click Edit Colony Details
5. Make sure that the content is scrollable if the Colony Description text area causes the rest of the form contents to go out of view 
Resolves #3620
> Fix: Add action sidebar overflow

- src/components/shared/Extensions/Toast/Toast.css
A wee update to our Toast component's non-mobile container style. We're now setting it width: 390px to adhere to our [Toast's global sizing based on Figma](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-10106&t=nHVBRUN2ELg9KKdd-4).
1. Set your browser width to 768px
2. Open the `NotificationTypeToggle.tsx` file and add the following param to the `toast.success` function:
```js
{
autoClose: false, // <-- add me!
},
```
3. Go to the Preferences page: http://localhost:9091/account/preferences
4. Toggle Payments and Funds
5. Verify that the Toast is 390px in width
6. Go to the Advanced Settings page: http://localhost:9091/account/advanced
7. Toggle Notifications
8. Verify that the Toast is 390px in width
Resolves #3573
> Fix: Set the non-mobile Toast width to 390px

- src/components/v5/common/WidgetCards/WidgetCardsItem.tsx
This ensures that the heights are following the [Figma design](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=5047-39385&t=aaxvUcV1z11FkHDL-4).
1. Visit a Colony Dashboard
2. Inspect the financial cards
3. Verify that their heights are 111px
Resolves #3554
> Fix: Make the financial card height match the Figma designs

- src/utils/currency/convertFromTokenToCurrency.ts
- src/utils/currency/currency.ts
- This PR ensures selecting `CLNY` as currency no longer breaks the app. 
- The issue was caused by getting `0` as an exchange rate from CLNY in USD, causing the reverse to be `Infinity`
- Also, updated the `getCLNYPriceInUSD` to use the proper chain id and token address
TODO: Select `CLNY` as preferred currency and make sure the app no longer breaks.
Currently the values for the total cards remain to `0` because of a bug that is resolved in #3614
Resolves #3557
> Fix: CLNY conversion breaks the app

- amplify/backend/function/fetchDomainBalance/src/api/graphql/operations.js
- amplify/backend/function/fetchDomainBalance/src/api/graphql/schemas.js
- amplify/backend/function/fetchDomainBalance/src/config/coinGeckoConfig.js
- amplify/backend/function/fetchDomainBalance/src/config/networkConfig.js
- amplify/backend/function/fetchDomainBalance/src/consts.js
- amplify/backend/function/fetchDomainBalance/src/index.js
- amplify/backend/function/fetchDomainBalance/src/package-lock.json
- amplify/backend/function/fetchDomainBalance/src/package.json
- amplify/backend/function/fetchDomainBalance/src/services/exchangeRates.js
- amplify/backend/function/fetchDomainBalance/src/services/networkBalance.js
- amplify/backend/function/fetchDomainBalance/src/services/tokens.js
- amplify/backend/function/fetchDomainBalance/src/utils.js
- docker/colony-cdapp-dev-env-network
- Given the incoming funds entries are not available for prior to May 2024 - previously when an incoming funds action was claimed, the entry got deleted, we need to change a bit our approach to the balances. So, in order to get our data right, at least for the overall amounts shown in the Total cards we need to make use of the actual network balance at colony level or domain level. This PR addresses that ✨ 
TODO: Let's test the changes in this PR retrieve the correct total balance for a domain, for `All teams` and also the caching.
* Step 1. First things first, run your dev environment
* Step 2. Run the `create-data` script
* Step 3. Visit http://localhost:9091/planex check the `All teams` or `General` `Total` card correctly reflects the `Income` - `Payments`
* Step 4. Now select …
> Fix: [QA Dashboard] Total funds bug

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/ExtensionDetailsHeader.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionPermissionsBanner/ExtensionPermissionsBanner.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionPermissionsBanner/PermissionsEnabledBanner.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionPermissionsBanner/PermissionsNeededBanner.tsx
This PR fixes an issue where the "Missing permissions" banner would show when re-enabling an extension, even if the extension had previously been assigned permissions.
* Step 1 - Switch to the metamask wallet so you can reject specific transactions.
* Step 2 - Navigate to the Multi-Sig extension page.
* Step 3 - Click Install. Accept the "Installation" transaction but reject the "setUserRoles" transaction.
* Step 4 - The "Missing permissions" banner should be visible. Do not interact with it yet.
* Step 5 - Deprecate the extension. The "Missing permissions" banner should disappear.
* Step 6 - Re-enable the extension.
* Step 7 - The "Missing permissions" banner should reappear.
* Step 8 - Click "Enable permissions" on the banner and accept the transaction.
* Step 9 - The "Missing …
> Fix: Missing permissions banner should not show when reenabling

- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Notification.tsx
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
I updated `useGetColonyForNotificationQuery`'s fetch policy to cache-and-network to ensure data freshness. 
1. Edit the Colony's name and logo
2. ⚠️  **IMPORTANT** Don't refresh the page
3. Complete a transfer fund action via Permissions
4. ⚠️ **IMPORTANT** Don't refresh the page
5. Wait for the notification to come through
6. Verify that the latest Colony name and logo are shown
Resolves #3576
> Fix: Prevent stale response data from useGetColonyForNotificationQuery

- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/CompletedAction/partials/SetUserRoles/SetUserRoles.tsx
- src/redux/sagas/motions/managePermissionsMotion.ts
Basically the solution to this was that instead of always getting the role delta in our block-ingestor handler, we just use what the contracts get called with. If we ever want to display the delta, we can get the user's latest historical roles :shrug: 
It also fixes a bug where all the multisig motions created motions to manage a user's multisig roles instead of whichever authority you chose.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/289)
We need to test if both motions and multi-sig works for updating a member's roles. I'll mix and match multisig and voting reputation just so we cover as many cases as possible without having 20 test cases.
For sanity checks, let's use 2 browsers, `leela` and `amy`.
2. As `leela` …
> fix: always use roles passed to contract for motions

- amplify/backend/function/fetchDomainBalance/src/services/actions.js
- amplify/backend/function/fetchDomainBalance/src/utils.js
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/utils.ts
- src/context/TotalInOutBalanceChartContext/TotalInOutBalanceChartContextProvider.tsx
- This PR addresses the bug related to overlapping timeframe keys. 
- Given for the moment we query data only for the `last 4 months` (which is less than the actual number of months in a year), the issue was not immediately visible.
TODO: Let's test the retrieved data contains the full date keys and the changes didn't impact the `Total in and out` chart
* Step 1. First make sure you have started your dev env and have data in your colony
* Step 2. Visit http://localhost:9091/planex and make sure the chart has data to display for the current month
* Step 3. Now let us run some queries
* Step 4. Go to http://localhost:20002/ and run the following query
```
getDomainBalance(
input: {
colonyAddress: "<COLONY_ADDRESS_HERE>", 
timeframePeriod: 4, 
timeframeType: WEEKLY
}
) { …
```
> Fix: Overlapping timeframe keys

- src/hooks/useTokenLockStates.ts
This PR removes useCallback from `fetchTokenStates` and instead calls it on initial render to ensure the latest token lock state is used.
Bit of an edge case here. The `fetchTokenStates` function previously used `useCallback` and is only called when either the `getColonyTokenLockedState` or `tokens` passed from the colony context change.
When a token is unlocked, the `tokens` array passed from the colony context doesn't actually change as the locked status is not stored on the token model. This means the `fetchTokenStates` `useCallback` is not re-run as there are no changes. As a result, if a user has the app opened, and a token's locked status is changed by another user, this change will not be reflected in the token select component / validation until the user refreshes the entire app. …
> Fix: Locked token validation should properly refresh

- src/components/frame/v5/pages/MembersPage/utils.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/utils.ts
The owner role from the parent domain should be shown as the "Admin" inherited role for sub-domains. These changes are related to the permission page and the Manage Permissions Motion.
Step 1. Assign fry Admin role in Andromeda
Step 2. Assign fry Owner role in general
Step 3. Navigate to the Permissions page with the filter General
Step 4. Verify that fry is under the Owner category
Step 5. Navigate to the Permissions page with the filter Andromeda
Step 6. Check that fry is under the Admin category without inherited pill
Step 7. Navigate to the Permissions page with the filter Serenity
Step 8. Check that fry is under Admin category with **inherited** pill
Step 9. Create Manage Permissions action with following:
| Field | Value |
| ------ | ------ |
| User | **fry** | 
| Team | …
> [Permissions] fix: subdomain owner should be an admin

- src/components/shared/Fields/Form/Form.tsx
- src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
- src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx
There was a weird race condition being caused by a `useEffect` inside `ActionSidebarContextProvider`. It was resetting a state which ended up clearing the current action which we're using to conditionally render either the GroupedTransactionContent or the actual Action Form.
There was also an issue wherein if you're already on an action-specific form i.e. Simple payment, clicking the "Create agreement" button on the Sidebar doesn't do anything. I fixed those up to make sure that the actionType correctly propagates, which should hopefully make the form update correctly depending on what action has been set.
1. Click the Manage Colony Sidebar button
2. Verify that you see the Manage Group Content
3. Click the Make Payment Sidebar button
4. Verify that you see the Payments Group Content
5. …
> Fix: Correctly show the expected Action Form content

- src/components/v5/shared/TeamFilter/partials/TeamItem.tsx
I guess the best way to explain this fix is we're currently faking the semibold effect via the `after` pseudo-element to prevent the font weight change from affecting the rest of the layout. The problem is that `font-medium` is only being applied for team items that are not selected. So when a team item is selected, this `font-medium` doesn't get applied and it's causing the rest of the layout to sort of "shift".
So I'm just applying the `font-medium` style as the base style for these team items regardless if they're selected or not which should keep the layout in tact. When a team item does get selected, our "fake" semibold effect gets applied which doesn't affect our layout.
1. Visit a Colony Dashboard and make sure there's at least 2 subdomains in there
2. Keep on clicking the first …
> Fix: Prevent shifting of other team filter copies

- src/components/shared/Fields/Form/Form.tsx
- src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
There's a bit of code that resets the default values for any given form whenever a form mounts. In issue #3656, the reason why it says "Not enough tokens" is because the "selectedToken" field value for the Simple Payment form is being cleared on mount. This makes the `hasEnoughFundsValidation()` function trigger the form error because it pretty cannot calculate your funds correctly.
This was also causing the issue which Raul raised about the Mint Tokens form -- it's because `selectedToken` is undefined at this point -- it got cleared on mount.
For the create domain action, it complains about the `createdIn` field, and same issue, it's because it got cleared on mount.
But these changes should make all of those go away and unblock testing on QA 🙏 
| Minting tokens | Creating domains | …
> Fix: Do not clear the required default form values on form mount

- src/components/v5/common/CompletedAction/partials/CompletedExpenditureContent/CompletedExpenditureContent.tsx
Just needed to add a null guard for the payouts array item to make sure we're not referencing a property from undefined.
1. Create an Advanced Payment
2. Verify that the app doesn't crash as soon as the Advanced Payment Completed Action Component mounts
Resolves #3626
> Fix: Prevent crash when the Advanced Payment's Completed Action Component mounts

- src/components/v5/common/ActionSidebar/partials/GroupedActionWrapper/GroupedActionWrapper.tsx
- src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/SocialLinksTable.tsx
- src/components/v5/common/CompletedAction/partials/rows/SocialLinksTable.tsx
- src/hooks/useSocialLinksTableColumns.tsx
I just updated the mobile styles of the table so that the `th` contents are properly contained within the `th` components. I also removed the dividers and I based this from the Figma designs:
**Mobile:** [Mobile Figma URL](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-156523&t=qaKy19kp8aAlTYrP-4)
**Non-mobile:** [Mobile Figma URL](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-156462&t=qaKy19kp8aAlTYrP-4)
1. Open the EditColony Details form
2. Set your view to mobile
3. Verify that the UI matches the designs
Resolves #3488
> Fix: Update external links mobile styles

- amplify/backend/function/fetchDomainBalance/src/config/networkConfig.js
- amplify/backend/function/fetchDomainBalance/src/index.js
- amplify/backend/function/fetchDomainBalance/src/services/actions.js
- amplify/backend/function/fetchDomainBalance/src/utils.js
- This PR aims to solve the following issues identified on QA
TODO: Please test the fetchDomainBalance lambda and check these edge cases are covered. 
Don't know how to easily do this on `DEV` without actually changing directly into code the used values as in for eg. adding a `null` token or using `arbitrumOne` as a value for the `network` env var etc. So let's do this 🦾 
> [!IMPORTANT]
> To check the values returned or logged in a lambda, you need to always run the `getDomainBalance` query and then check the `amplify` logs
Step 1. Let's make sure the query runs as expected first
```
getDomainBalance(
input: {
colonyAddress: "<COLONY_ADDRESS_HERE>", 
timeframePeriod: 1, 
timeframeType: MONTHLY
}
) {
total
totalIn
totalOut
}
}
```
Step 2. Now let's try to break it by using …
> Fix: Fixes for fetchDomainBalance lambda edge cases

- playwright/e2e/create-colony.spec.ts
- playwright/utils/create-colony.ts
- Added e2e tests for the Create Colony flow / Details step
- Set up playwright eslint plugin
**Prerequisites**: The test script simulates user interactions with the local instance of the web app, which means that the BE is expected to be set up and running. For now, backend services should be started manually and the initial test data should be seeded . Therefore, ensure that the development environment is properly set up by following the instructions in the README file
- Start your local dev environment  `npm run dev` 
- Seed the mock data `node scripts/create-data.js` 
- If it's the first time you run e2e tests on your machine - run `npm e2e:install` 
- run `npm run e2e` or `npm run e2e:ui`
- Ensure all tests pass
- playwright folder is added to the lint script
- added …
> test: add e2e tests for 2nd step of create colony flow 

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/StagedPaymentTable.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/partials/ReleaseAllButton/ReleaseAllButton.tsx
Align buttons to right in staged payments action
- Download extension for Staged payment
- Create Staged payment
- Finalize payment
**Changes** 🏗
Before:
After:
Resolves - https://github.com/JoinColony/colonyCDapp/issues/3342
> fix: staged payment buttons alignment

- amplify/backend/api/colonycdapp/schema/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/graphql/generated.ts
[See block-ingestor PR](https://github.com/JoinColony/block-ingestor/pull/292)
Previously when a split payment is released, a notification would be sent for each recipient resulting in multiple notifications being sent to all users.
This PR adds a flag to the expenditure model to avoid sending multiple notifications for each split payment payout claimed event.
* Step 1 - Create a split payment action with multiple recipients
* Step 2 - Proceed through all the steps and release the payment
* Step 3 - Check you only receive 1 payment notification
**Changes** 🏗
* Added new `splitPaymentPayoutClaimedNotificationSent` flag to expenditure model
* Made changes to payoutClaimed handler to only send notification on first split payment payout claim
Resolves #3574
> Fix: Split payment should not send multiple notifications

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/NotificationWrapper.tsx
Just some styling updates to follow the Figma designs:
1. Our fonts have a default line height which causes them to have extra vertical spacing. On Figma, you'll find that the Avatar has compensated for this by having a top spacing of 4px from the container. So I just added it:
2. Then made a little style update for the UserHub tabs to sort of align the Balance icon's top edge with the notification title's top edge as shown in #3578 
So yeah, here's the result:
1. Create a Simple Payment
2. Wait for the notification to arrive
3. Open the UserHub
4. Go to the Notifications tab
5. Verify that the issue raised on #3678 is addressed by referring to these designs: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-51509&t=9BgEXHLnQiK6dmp0-4
Resolves …
> Fix: Userhub styling adjustments

- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
Adjust the height of the Colony Switcher to match the sidebar.
Step 1. Open Planet Express colony
Step 2. Press "Planet Express" to open Colony Switcher
Step 3. Verify that the Colony Switcher appears as expected 😄 :
Step 4. Apply the following .diff file:
> [!TIP]
> Save this code to a .diff file in the root directory, then apply it by running `git apply .diff` in the terminal.
```
diff --git a/src/components/frame/Extensions/layouts/ColonyLayout.tsx b/src/components/frame/Extensions/layouts/ColonyLayout.tsx
index 9dee9daf5..918523ca9 100644
--- a/src/components/frame/Extensions/layouts/ColonyLayout.tsx
+++ b/src/components/frame/Extensions/layouts/ColonyLayout.tsx
@@ -156,9 +156,7 @@ const ColonyLayout: FC<PropsWithChildren> = ({ children }) => {
<>
<PageLayout
topContent={
- …
```
> fix: make colony switcher the same height as sidebar

- src/components/common/ColonyActionsTable/ColonyActionsTable.tsx
- src/components/common/ColonyActionsTable/RecentActivityTable.tsx
- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/common/ColonyActionsTable/hooks/useBuildRedoEnabledActionsMap.ts
- src/components/common/ColonyActionsTable/hooks/useGetMenuProps.tsx
- src/components/common/ColonyActionsTable/hooks/useHandleRedoAction.ts
- src/components/common/ColonyActionsTable/hooks/useRedoAction.ts
- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/ManageReputationDescription.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/utils.ts
- src/components/v5/common/CompletedAction/partials/ManageReputation/ManageReputation.tsx
- src/components/v5/common/CompletedAction/partials/SetUserRoles/SetUserRoles.tsx
- src/components/v5/common/CompletedAction/partials/SetUserRoles/utils.ts
- src/utils/numbers.ts
This PR enables the Dashboard page's Activity Table Item Redo Function and aligns it with Activity page's Activity Table.
> [!NOTE]
> I had to fix the following existing `master` bug and do some refactoring as well. It is unrelated to issue #3551 but you know what, it makes sense to include it in this PR:
>
> @iamsamgibbs  "The only reason I'm rejecting is that not all actions should have the redo option"
> @rdig  "I've tested this with Simple Payments and which work as expected, however, as Sam noted, not all actions require it, so this needs to be enabled on a case by case basis"
>
> I've added a testing section for it 😄 
>
> I also had to handle the Redo flow for Reputation-related actions in the Activity Table items so please test that as well.
>
> I'll find a way to refactor the …
> Fix: Enable Recent Activity Table Item Redo Functionality

- src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
The Authority field value was being hardcoded for the Manage Permissions action and this was because at the time this was written, we didn't have any other values for the Authority field. So this PR just makes it dynamic.
1. Install the multi-sig extension
2. Bring up the Manage Permissions form
3. Set the Authority field to "Take actions via Multi-Sig"
4. Fill in the rest of the required fields
5. Submit the form
6. Visit the Dashboard page
7. Redo the action from the Recent Activity table
8. Verify that the Authority field is set to "Take actions via Multi-Sig"
9. Visit the activity page
10. Redo the action from the Latest Activity table
11. Verify that the Authority field is set to "Take actions via Multi-Sig"
Resolves #3699
> Fix: Dynamically set the Manage Permissions form Authority field

- .eslintrc.js
- playwright.config.ts
- playwright/e2e/create-colony.spec.ts
- playwright/utils/common.ts
- playwright/utils/create-colony.ts
- playwright/utils/graphqlHelpers.ts
- added e2e tests for the Create Colony flow
- enabled parallelization for tests of a single file
- use `fill` instead of `pressSequentially` to speed up the tests a bit
**Prerequisites**: The test script simulates user interactions with the local instance of the web app, which means that the BE is expected to be set up and running. For now, backend services should be started manually and the initial test data should be seeded . Therefore, ensure that the development environment is properly set up by following the instructions in the README file
- Start your local dev environment  `npm run dev` 
- Seed the mock data `node scripts/create-data.js` 
- If it's the first time you run e2e tests on your machine - run `npm e2e:install` 
- run `npm run e2e` or `npm run e2e:ui`
- Ensure all tests …
> est: add e2e tests for final step of create colony flow 

- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
This small PR fixes unsafe array access when generating action description.
I came across a case where a newly created expenditure gets returned from the DB, but it does not yet have any slots (block-ingestor has not processed them yet). In such a scenario, the entire app would crash due to it trying to read the recipient of the first slot.
It would also be possible to run into this issue when an empty expenditure is created, such as in #3302 or through direct contract interaction (it is possible to create an expenditure with 0 slots).
Create a couple of advanced payments and confirm the app does not crash.
Resolves #3677
> Fix: Advanced payments crashing due to unsafe array access

- src/components/v5/common/Fields/Select/Select.module.css
This PR adds disabled styling to the selects on the multi-sig extension settings page. (The inputs were already disabled, just missing the styling.)
* Step 1 - Login as a user with permissions to install extensions (Leela)
* Step 2 - Install the multi-sig extension and check the inputs are enabled on the extension settings page
* Step 3 - Switch to a user who does not have permissions to update extensions (Amy / Fry)
* Step 4 - Navigate to the extension settings page and check the inputs are disabled and the select styling is as expected
* Added disabled styling to select inputs
Resolves #3227
> Fix: Add disabled styling to multi-sig setting selects

- src/apollo/utils.ts
- src/auth/index.ts
- src/components/shared/Fields/Form/ActionForm.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/types.ts
- src/redux/sagas/actions/createDomain.ts
- src/redux/sagas/actions/editColony.ts
- src/redux/sagas/actions/editDomain.ts
- src/redux/sagas/actions/initiateSafeTransaction.ts
- src/redux/sagas/actions/manageExistingSafes.ts
- src/redux/sagas/colony/colonyCreate.ts
- src/redux/sagas/expenditures/createStreamingPayment.ts
- src/redux/sagas/motions/createDecisionMotion.ts
- src/redux/sagas/motions/domains/utils/handleDomainMetadata.ts
- src/redux/sagas/motions/editColonyMotion.ts
- src/redux/sagas/motions/initiateSafeTransactionMotion.ts
- src/redux/sagas/users/index.ts
- src/redux/sagas/utils/annotations.ts
- src/redux/sagas/utils/createActionMetadata.ts
- src/redux/sagas/utils/expenditures.ts
- src/state/transactionState.ts
This PR attempts to improve the way we handle failed mutations. There are few instances on QA and Production where actions were failing due to apollo 403 errors, the transaction would still succeed but the form would not proceed to the completed action screen due to the failed apollo calls. This meant the form could be resubmitted over and over resulting in multiple transactions.
It is likely these issues are caused by auth proxy rejecting the mutation. This can happen if auth proxy restarted after the saga has started running as the user will no longer be authenticated.
This PR attempts to improve this experiencing by adding a retry with re-authentication mechanism to all mutations and authentication attempts. If auth proxy rejects the mutation it will prompt the user to sign in again …
> Feat: Improve failed auth handling

- src/components/shared/Fields/Form/ActionForm.tsx
- src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/CreateStakedExpenditureModal/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/PaymentBuilderForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/StagedPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/hooks.ts
I found some time to refactor the `ActionSidebarContent`. I took out expenditure staking-specific logic and handled it in their respective forms instead.
I create a new hook called `useShowCreateStakedExpenditureModal` which encapsulates logic for showing/hiding the expenditure modal. Basically, we're meant to show this modal for the following actions if the decision method is set to `DecisionMethod.Staking`:
```js
export const actionsWithStakingDecisionMethod = [
Action.PaymentBuilder,
Action.StagedPayment,
Action.SplitPayment,
];
```
For future reference, you can control the Action Form's primary button type and onClick props via the `useActionFormBaseHook` hook i.e.
```js
useActionFormBaseHook({
...otherOptions,
primaryButton: { <<-- This one! 😄 
type: shouldShowStakedExpenditureModal …
```
> Fix: Enable the Advanced Payment form's staking submission logic

- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/ColonyLinks.tsx
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/helpers.ts
- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/hooks/useCopyToClipboard.ts
- src/hooks/useOnElementScroll.tsx
TLDR: The `trigger` and `isOpen` props were clashing and led to situations whereby the tooltip still lingers even if we don't want it to. As a workaround, I had to manually detect hover states for the Tooltip's children and conditionally update the `isOpen` prop ✌️ 
| Production | Current Master | This Branch |
| ---- | ---- | --- |
| ![Production](https://github.com/user-attachments/assets/261eb9a0-83d2-4bfe-8f34-ef06a62991da) | ![master](https://github.com/user-attachments/assets/8a25ca3d-248e-4fac-a728-ac35c1080496) | ![my branch](https://github.com/user-attachments/assets/5676e880-9ddc-4998-a7f2-6510bf1498ed) |
This is how it behaves on mobile now, on this branch:
1. Hover on the Copy Contract Address button
2. Click it
3. Scroll the page
4. Verify that its tooltip is not visible
5. …
> Fix: Dismiss lingering tooltips when the page is scrolled

- src/components/shared/Fields/Form/Form.tsx
This PR aims to preserve other existing form values whenever a form field is updated.
1. Open the Manage Tokens form
2. Mark a token for removal
3. Update the Decision method field
4. Verify that the tokens you marked for removal are still marked for removal
Resolves #3675
Resolves #3683
> Fix: Do not clear other existing Form values when you update a field value

- src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/hooks.tsx
This PR fixes an issue on the username field on the profile page which would always show `0/30`. I made a decision to hide the counter all together when the field is disabled as this seems more logical to me - I can easily add this back in if preferred.
Step 1 - Navigate to [http://localhost:9091/account/profile](http://localhost:9091/account/profile) and ensure the max character limit does not display.
Step 2 - Open `src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/hooks.tsx` and change line 131 to `shouldNumberOfCharsBeVisible: true,` and line 134 to `isDisabled: false,`. Confirm the character count is visible and updates correctly.
**Changes** 🏗
* Added default value prop to display name field
* Made `shouldNumberOfCharsBeVisible` dependant on whether field is …
> Fix: Username field should show correct count

- src/components/shared/Numeral/Numeral.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentPayoutsTotal/SplitPaymentPayoutsTotal.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentPayoutsTotal/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentPercentField/SplitPaymentPercentField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/SplitPaymentRecipientsField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/hooks.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/SplitPayment.tsx
- src/components/v5/common/Fields/InputBase/FormInputBase.tsx
- src/components/v5/common/Fields/InputBase/types.ts
- Equal distribution method now uses fractions to calculate amount instead of percentages
- Changed decimals to dots everywhere in payment table
- Total amounts is not higher then the originally intended value
* Create a split payment and play with it
Closed PR with comments - https://github.com/JoinColony/colonyCDapp/pull/3042
Resolves https://github.com/JoinColony/colonyCDapp/issues/3012
> fix: split payment table ui

- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/utils.ts
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/partials/StagedPaymentRecipientsField/StagedPaymentRecipientField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/shared/hooks/useBuildTokenSumsMap.ts
- src/components/v5/common/Table/partials/VirtualizedRow/VirtualizedRow.tsx
> [!NOTE]
>
> **💡 What this PR aims to do**
> Prevent an app crash when uploading a CSV file with at least 200 rows
>
> **🚫 What this PR doesn't attempt to fix:**
> This PR is not aiming to address the issue with the Completed Action component's payments incorrect order
Currently, there is a palpable performance hit whenever we're calculating the sums for each token present on the Advanced Payment form. This is because we're performing this calculation for each and every single payment row present. This means that when you upload a CSV file with like 200 rows, you are pretty much performing the calculation 200 times which is causing the huge lag and could oftentimes cause our app to crash.
This PR aims to semi-resolve this lag issue by building a map of token sums outside of the …
> Fix: Optimise token sums calculation for multi-row advanced payments

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
- src/redux/sagas/motions/expenditures/fundExpenditureMotion.ts
- src/redux/sagas/utils/proofs.ts
- src/redux/types/actions/motion.ts
This PR reimplements the fund expenditure via voting reputation saga so it uses the new helpers and it adds support for changing the funding motion created in domain.
2. Create an advanced payment as `leela` sending some funds to some recipients from `General`
3. Get to the funding step and fund it via Reputation
4. Fully support the motion, run `npm run forward-time 1` and try to finalize it. Then release it and verify that the funds were sent (`leela` had 396 at start, now she has 398 so hooray!)
ALright so funding from general works which is all fine, now let's check out 2 more cases
1. Create an advanced payment as `leela` sending some funds to some recipients from `Andromeda`
2. Get to the funding phase and choose `Reputation` as the …
> fix: fund expenditure via motion permission proofs and domains

- src/components/v5/shared/SearchSelect/SearchSelect.tsx
- src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
Add auto onfocus on input after click `Select member`.
- create new Advanced payment
- click `Select member`
add auto focus for input
https://github.com/user-attachments/assets/08e6a1e7-520c-4af0-ab5b-9491cf7493cf
Resolves https://github.com/JoinColony/colonyCDapp/issues/3455
> fix: auto focus after open search input

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StreamingPaymentForm/hooks.ts
Remove validation for checking tokens amount.
- Create new streaming payments action
- Input amount higher than available tokens
**Changes** 🏗
remove validation for checking tokens
Before:
After:
Resolves  [#31415](https://github.com/JoinColony/colonyCDapp/issues/3647)
> fix: add only numeric values and remove tokens validation

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/StagedPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/partials/StagedPaymentRecipientsField/StagedPaymentRecipientField.tsx
- src/components/v5/common/ActionSidebar/partials/hooks.ts
- src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
This PR disables the staged payments form and shows an error when the staged payments extension is not installed.
* Step 1 - Install the staged payment extension
* Step 2 - Create a staged payment action
* Step 3 - Deprecate the staged payment extension
* Step 4 - Open the previous stage payment action and select "Redo" from the meatball menu
* Step 5 - Check the form shows an error and that the fields are disabled
**Changes** 🏗
* Error now shows on Staged Payments form if extension is not enabled
* Staged Payment form inputs are disabled if extension is not enabled
* `useIsFieldDisabled` now returns true if Staged Payments extension is not enabled
Resolves #3420
> Fix: Staged payments form should be disabled when extension is not enabled

- amplify/backend/function/fetchDomainBalance/src/utils.js
Fix: Remove unnecessary subtraction for timeOffset
- There was an issue introduced by [this commit](https://github.com/JoinColony/colonyCDapp/commit/f6ca7655143dacc7976dbd82223b8e80f957e41b) causing the domain balance to no longer include the last timeframe key - actually it duplicated the first key in the `periodBalance`.
- With this PR, all requested timeframe entries are properly retrieved
TODO: Please check the `getDomainBalance` query retrieves all entries as requested. 
* Step 1. Let's start easy with testing the fix, so please visit http://localhost:9091/planex
* Step 2. Check the `Total in and out` card's chart includes latest `4 months` - not only the latest `3 months` as in `master`
* Step 3. Now let us run some queries, so go to http://localhost:20002/
* Step 4. Run the …
> Fix: Remove unnecessary subtraction for timeOffset

- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/hooks.tsx
- src/i18n/en.json
This PR resolves a couple of issues when finalizing agreements with the "Return stakes" button not showing, and the stake details not showing.
* Step 1 - Install the voting reputation extension
* Step 2 - Create an agreement using the "Create agreement" button in the menu
* Step 3 - Fully stake both support and oppose.
* Step 4 - Vote to oppose the agreement.
* Step 5 - Reveal your vote.
* Step 6 - Check the "Return stakes"  button appears, the stake information is shown, and the correct message is shown.
* Step 7 - Click the "Return stakes" button. Check the button disappears, the message updates and the claimed pill appears.
* Step 8 - Repeat the process, this time voting to support the agreement.
Further testing: Check the other motions are unaffected and advanced payment motions are …
> Fix: Finalize agreement issues

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
- src/state/transactionState.ts
I found that some grouped transactions do legitimately have transactions with a zero address hash so I removed the part inside `getGroupStatus` where it determines if a transaction group is considered to have succeeded if there are no transactions with an address zero hash.
> [!NOTE]
> If you do end up seeing the TX Button in a "stuck" pending state, verify if it is indeed pending by checking the same transaction inside the User Hub. If the transaction is marked as Pending inside the User Hub then, it really is in a "Pending" state. Maybe it's an environment issue or something 🤔 
1. Connect Leela's wallet
2. Install the Reputation extension
3. Uninstall it
4. Repeat steps 1-2 a couple of times and verify that the TX Button is not stuck in a Pending state
5. Install the Multi-Sig extension …
> Fix: Prevent TX button from being stuck in a pending state

- src/components/frame/v5/pages/TeamsPage/hooks.tsx
- src/components/v5/shared/TeamFilter/TeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/DesktopTeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/MobileTeamFilter.tsx
This PR sorts the order of the teams in the team switcher so that the teams with the highest reputation will show first, then sorting by alphabetical order.
* Step 1 - Check the team switcher on the dashboard. It should already be in the correct order, although this will be hard to tell apart from it being different than the usual order, so lets manipulate some reputation values for the sake of testing.
* Step 2 - Copy your colony address, and run this mutation.
```
updateDomain(input: {id: "{COLONY_ADDRESS}_3", reputationPercentage: "50"}) {
id
}
}
```
* Step 3 - Refresh the dashboard, Serenity will now have a reputation percentage of 50 and appear at the front of the list.
* Step 4 - Run another mutation to set Ascendant to also have a reputation percentage of 50. …
> fix: team filter should order by reputation then alphabetically

- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/PaymentsSection.tsx
- src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx
- The issue was caused by the fact the other two payment action forms (`Simple Payment` and `Advanced Payment`) were relying on the team field to be called `from`, while `Split payment` was using `team` as the field id.
TODO: Please check opening the action sidebar by clicking `Pay` and having a team filter in place will populate the `Simple payment`/`Advanced payment`/`Split payment` with the active team filter. 
* Step 1. Go to http://localhost:9091/planex
* Step 2. Select `Andromeda` from the team filters
* Step 3. Click `Pay` from the `Total in and out` card
* Step 4. The `Payments` actions sidebar should open
* Step 5. Check for each individual action - `Simple`, `Advanced` and `Split` - that `Andromeda` is pre-filled
* Step 6. Now let's move to checking the actions sidebar triggered …
> Fix: Split payment action form has pre-selected team filled

- src/i18n/en-motion-states.ts
- src/utils/colonyMotions.ts
Display badge with opposed greeement
- create agreement
- fully oppose the agreement
- display item in `Recent activity`
**Changes** 🏗
Resolves https://github.com/JoinColony/colonyCDapp/issues/3463
> fix: add info about opposed agreement

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/MultiSigSettings/MultiSigSettings.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/utils.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/utils.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/utils.ts
- src/utils/waitForCondition.ts
This PR adds an improvement and fixes an issue with the extensions settings tabs.
The extension data is now refetched when saving changes to an extension and properly waits for these updates to be reflected in the database.
The multi-sig custom settings accordion is now open by default if any threshold is different than the colony threshold.
* Step 1 - Install the Multi-Sig extension
* Step 2 - Change the threshold setting to "Fixed threshold" with a value of `2`.
* Step 3 - Without refreshing, navigate to the dashboard, then back to the multi-sig extension page. Check the threshold is still set to 2. (If you really want to be sure the threshold has updated correctly, then go through the extra steps of assigning multi-sig permissions and checking the threshold is as expected)
* Step 4 - …
> Fix: Multi-sig extension settings issues

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
- src/components/v5/shared/SearchSelect/SearchSelect.tsx
- src/context/MemberContext/MemberContextProvider.tsx
- src/graphql/generated.ts
- src/graphql/queries/contributors.graphql
- src/hooks/useGetColoniesMembersCount.ts
Issue #3622 is a bit misleading. It's not that the app doesn't ever show the new contributor. It's just that on `master`, you'd have to reload the app to make our app refetch our contributors list.
So I added a subscription logic to make the app automatically aware that a new contributor has been added to a Colony.
And the result is nothing short of spectacular ✨ 
1. Connect Leela's wallet
2. Create a new Colony using this script:
```console
node scripts/create-colony-url.js
```
3. Visit your new Colony
4. Stay on the Dashboard
5. Open an incognito tab
6. Connect Amy's wallet (Wallet 2)
7. Generate an invite code for the new Colony:
```gql
getColonyByName(name: "your-new-colony's-name") { <<-- NOTE: Update this with your new Colony's name
items {
colonyMemberInviteCode
}
} …
```
> Fix: Make our app automatically aware of new Colony Contributors

- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
- src/components/v5/shared/UserInfoPopover/partials/UserInfoPopoverTrigger.tsx
1. Connect Leela's wallet
2. Make a Simple Payment
3. Visit the Activity page
4. Click on Leela's avatar
5. Verify that the user popover comes up
Resolves #3702
> Fix: Show user popover for user avatars in activity table

- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/ClaimDelayField/ClaimDelayField.tsx
I'm just simply doing a check to see if the most recent version of the input conforms with our cleave rule. If not, then don't allow the field value to be updated.
1. Bring up the Advanced Payment form
2. Enter a space or a letter inside the Claim delay field
3. Verify that the field value doesn't get updated
Resolves #3479
> Fix: Adjust the input allowed for the Claim Delay input field

- src/components/shared/Fields/Form/Form.tsx
- src/hooks/useStableDepsEffect.ts
The issue was that, the `defaultValues` dependency was unstable. And so the hook in charge of initialising the form kept on resetting the form to use the default values. So even if Olga was setting the decision field to "Staking", under the hood, it kept on resetting back to "Decision". Fry doesn't have permissions in that scenario, hence the error banner.
This PR introduces a new hook called `useStableDepsEffect` which basically uses lodash's `isEqual` function to perform a comparison for the dependencies. So now, even if the `defaultValues` has a different reference on re-render, because its contents are identical each time, it won't cause the effect to run:
1. Connect Leela's wallet
2. Make sure that the Staking extension is enabled
3. Assign Payer permissions to Fry in team Andromeda …
> Fix: Correctly keep track of form field value updates when redoing an action

- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/AddTransactionModal/AddTransactionModal.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/ArbitraryTransactionsTable/ArbitraryTransactionsTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/ArbitraryTransactionsTable/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/ArbitraryTransactionsTable/translation.ts
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/types.ts
Implement meatball menu with "edit", "duplicate row" and "delete functionality"
Figma: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=24968-204505&node-type=frame&t=JJb12klGvkI2mJ8F-0
> [!TIP]
> I recommend reviewing [this PR](https://github.com/JoinColony/colonyCDapp/pull/3694) beforehand to better understand the context of Arbitrary transactions. 🙌
> [!NOTE]  
>  Add ARBISCAN_API=https://api.arbiscan.io/api to .env.secrets. For ARBISCAN_API_KEY, contact me or create a personal key [here](https://arbiscan.io/myapikey).
Step 1. Open "Arbitrary transaction" Motion (Open any motion and then select "Arbitrary transaction" from dropdown) 
Step 2. Add a New Transaction. Create a transaction with the following values:
| Field | Value |
| ----- | ----- |
| …
> feat: add meatball menu and duplicate and delete functionality

- src/components/v5/common/ActionSidebar/hooks/useActionsList.ts
- src/context/FeatureFlagsContext/FeatureFlagsContextProvider.tsx
- src/context/FeatureFlagsContext/types.ts
Add `ARBITRARY_TXS_ACTION` feature flag to disable arbitrary transactions on prod 
Step 1. Ensure that you have a QA or local API keys for POSTHOG
Step 2. Open any motion
Step 3. Verify that you can see Arbitrary transactions in Action Type list:
Step 4. Navigate to `src/context/FeatureFlagsContext/FeatureFlagsContextProvider.tsx` and update like 46 with: 
```
{
isEnabled: false,
isLoading: false,
}
```
Step 5. Ensure that there is no "Arbitrary transactions" in Motion Action Type list:
Resolves #3797
> feat: add feature flag to arbitrary transactions

- src/components/v5/common/ActionSidebar/hooks/permissions/helpers.ts
We have a hook called `getPermissionsDomainIdForAction` which checks if there is an available decision method for a user on any given form. It has a section where it checks if the user has permissions to do the current action based on the currently selected team on the form itself.
The problem was that, we weren't handling the Staged and Split payment types. As a result, the form's "team" value is being incorrectly set to the root domain ID even before the user gets the chance to select the team on the form. So what ends up happening is that the hook incorrectly asserts that the user doesn't have permissions to do the current action type since the user doesn't have any permissions on the root domain. This is wrong because the user hasn't even selected the team at this point.
This PR adds …
> Fix: Handle decision method validation properly for Split and Staged payments

- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/common/ColonyActionsTable/hooks/useColonyActionsTableColumns.tsx
- src/components/frame/v5/pages/FundsPage/partials/TokenTable/TokenTable.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/partials/PermissionsTable/PermissionsTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/partials/StagedPaymentRecipientsField/StagedPaymentRecipientField.tsx
- src/components/v5/common/Table/Table.tsx
- src/components/v5/common/Table/partials/TableFooter.tsx
- src/components/v5/common/Table/partials/TableLayout/HorizontalLayout.tsx
- src/components/v5/common/Table/partials/TableLayout/HorizontalTableCell.tsx
- src/components/v5/common/Table/partials/TableLayout/HorizontalTableHeader.tsx
- src/components/v5/common/Table/partials/TableLayout/TableLayout.tsx
- src/components/v5/common/Table/partials/TableLayout/VerticalLayout.tsx
- src/components/v5/common/Table/partials/TableLayout/types.ts
- src/components/v5/frame/ColonyHome/ColonyHome.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
This PR aims to refactor (a tiny bit) the `Table` component and addresses the following issues
[Figma link](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1776-8565&t=JazItdUIdCedG0rv-4)
**Tabs closed (note the position of the pill, title and metadata):**
**With one tab open (again, note the position of the pill, title and metadata):**
TODO: Please test the above mentioned issues have been resolved, as well as the `Table` component refactoring didn't introduce bugs. 
* Step 1. Visit http://localhost:9091/planex
* Step 2. Set your viewport to mobile
* Step 3. Try expanding an existing action
https://github.com/user-attachments/assets/f4844621-3029-4b7c-8c87-a36e37623b37
* Step 4. Ensure the description and status pills of the other actions doesn't …
> Fix: Activity table fixes and table refactoring

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/NotificationsTab.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/ActionNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Expenditure/ExpenditureNotification.tsx
- src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/NotificationWrapper.tsx
- src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx
- Fix some minor UI issues with the notifications tab
- Add a border bottom to each notification (matching the transactions tab)
- Add a hover state to the 'Mark all as read' button (gray-900)
- Align the padding top and bottom of the notifications items with the design (14px or 0.875rem - also matching the transactions tab)
* Make a couple of simple payments or mint tokens actions or something simple, so that you have a few notifications.
* Check that there is a border bottom on each item, which matches the border bottom of the transactions in the transactions tab.
* Check that when you hover over 'Mark all as read' it turns gray-900
* Check that the padding top and bottom of each item is correct
Figma:
Localhost:
**Changes** 🏗
* Classname tweaks to userhub / notifications components …
> Fix: Minor UI fixes for notifications tab

- src/redux/sagas/motions/moveFundsMotion.ts
This PR just uses the new helpers for getting move funds permission proofs for motions and thus fixes the bug :100: 
Best way is to just test **everything** :D 
2. Install the Multi-sig extension, set the global threshold to 1, give `leela` the `Owner`/`Payer` multi-sig role in `General`
3. Create a move funds voting reputation motion moving 1 CREDS from `Andromeda` to `General`. Fully support it, `npm run forward-time 1` and finalize it.
4. Create a move funds voting reputation motion, moving 1 CREDS from `Andromeda` to `Rocinante`. Fully support it, `npm run forward-time 1` and finalize it.
5. Create a move funds voting reputation motion moving 1 CREDS from `General` to `Rocinante`. Fully support it, `npm run forward-time 1` and finalize it.
6 …
> fix: use correct domain permission proofs for move funds motion

- src/components/common/ColonyActions/helpers/getActionTitleValues.ts
Just a wee one-liner. It also fixes copies in the Activity Table for Simple Payment Reputation and Multi-Sig motions.
1. Enable the Reputation and Multi-Sig extensions
2. Create a Simple Payment via Reputation motion
3. Stake it
4. Open the User Hub and open the Stakes tab
5. Verify that the correct copy is shown
6. Create a Simple Payment Multi-Sig motion
7. Go to the Dashboard
8. Verify that the correct copies are shown for the Simple Payment Reputation and Multi-Sig motions
Resolves #3755
> fix: Update payment message descriptor case

- src/components/frame/v5/pages/TeamsPage/hooks.tsx
- src/hooks/useTeamsOptions.ts
This PR adjusts the filter sorting on the teams page so that when the filter values are equal (i.e. if you have the reputation filter selected, and two teams have the same reputation) that they are then sorted alphabetically.
The same sort order has also been applied to the team select for all action forms.
We are going to set 3 teams to have the same reputation. Copy your colony address from the dashboard and run these mutations.
```
updateDomain(input: {id: "{COLONY_ADDRESS}_2", reputationPercentage: "20"}) {
id
}
}
```
```
updateDomain(input: {id: "{COLONY_ADDRESS}_3", reputationPercentage: "20"}) {
id
}
}
```
```
updateDomain(input: {id: "{COLONY_ADDRESS}_6", reputationPercentage: "20"}) {
id
}
}
```
Now Andromeda, …
> Fix: Sort teams page alphabetically

- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/hooks.ts
- src/components/v5/common/CompletedAction/partials/ManageReputation/ManageReputation.tsx
- src/components/v5/common/CompletedAction/partials/ManageReputation/partials/ManageReputationTableCompletedState/ManageReputationTableCompletedState.tsx
- src/components/v5/common/CompletedAction/partials/ManageReputation/partials/ManageReputationTableInMotion/hooks.ts
- src/utils/numbers.ts
- src/utils/reputation.ts
The calculation wasn't happening because this boolean check fails:
```js
typeof newPercentageReputation === 'number' && typeof percentageReputation === 'number'
```
It was failing because I guess that the real intention was to check if the values are numerically parsable. So I just tweaked it to set it free and reach its full potential 🪽
This is an issue on the Completed Action component as well so I fixed it there too.
BUT WAIT ✋🏻There's more!
I also updated the Completed Action form to handle the Manage Reputation Multi-Sig action. The Reputation motion's logic is that it shows the `<ManageReputationTableInMotion />` table when the motion hasn't finished yet. So I just did the equivalent of that for the Multi-Sig motion.
1. Bring up the Manage Reputation form
2. Set it to Award …
> Fix: Properly calculate the reputation percentage

- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
- src/components/v5/common/CompletedAction/partials/Blocks/Blocks.tsx
Step 1. Create any motion with the title: `12312321312312312312312312312313123123123123412341234124312`
Step 2. Create second motion with the title: `long long long name long long long name long long long name`
Step 3. Open Activity page
Step 4. Change the screen size to Mobile and check that the title is truncated in 2 lines 🎉 
Step 5. Open each motion from the activity feed (you probably need to open the wider screen to open motion from the list) and verify that the title for Completed Action still looks good:
Resolves #3433
> fix: long activity title overflow issue

- src/components/v5/common/CompletedAction/partials/SetUserRoles/utils.ts
Just had to properly filter out the actual enabled roles for the user.
1. Enable the Reputation extension
2. Bring up the Manage Permissions form
3. Set the Decision method to Reputation
4. Assign any role for chris-coder
5. Submit the form
6. Verify that the role is correct on the Completed Action form
Resolves #3822
> Fix: Show correct role for the Manage Permissions form's completed action component

- src/utils/currency/location.ts
- src/utils/currency/tokenHistoricalPriceByName.ts
- src/utils/currency/tokenPriceByAddress.ts
- src/utils/currency/tokenPriceByName.ts
- src/utils/currency/tokenPriceDataByName.ts
- src/utils/currency/utils.ts
This PR handles the annoying Coingecko URL error.
Additionally I changed the API of the `fetchData` function and renamed it to make a bit more sense (I was on the fence of removing it as it seemed kind of superfluous but I decided against it). That was done for the purpose of consistency and better error handling.
* Step 1. Run the CDapp in dev mode
* Step 2. See that there are no error messages in the console
**Changes** 🏗
* Promisify `fetchData` into `fetchJsonData`
* Add check for dev environment before throwing token url errors
> Fix: gracefully handle coingecko url error

- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
Had to add an extra boolean check to identify if a motion has indeed ended before we proceed to check if the motion has been supported or opposed.
**Prerequisitse**
1. Install the Reputation extension
2. For the extension options, select `Custom (Advanced)`
3. Scroll the page down
4. Enter `0.01` for the following fields:
- Staking Phase Duration
- Voting Phase Duration
- Reveal Phase Duration
5. Enable the extension
**Reveal flow** 
1. Create a Simple Payment via the Reputation decision method
2. Fully stake the Oppose option
3. Fully stake the Support option
4. Click Support and submit your vote
6. Reveal your vote
7. Verify that the motion pill for the vote is showing "👍🏻 Support wins"
8. Verify that the motion pill for the vote didn't initially show "👎🏻 Oppose wins"
**Non-reveal …
> Fix: Show the correct motion passed or failed pill state

- src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/Chart.tsx
- src/components/v5/frame/ColonyHome/partials/ReputationChart/utils.ts
- Any team which has zero reputation should be showing in the legend of the pie chart on the dashboard, but it should take up zero space in the actual pie chart.
- There should be a maximum of 5 teams shown in that legend. If there are more than 5 teams then it should show 4 teams and a 'All other' item which includes all of the others.
Full details and spec here: https://www.notion.so/colony/Dashboard-Colony-Home-322f296cb46240d3afddeddd7472ddd7?pvs=4#95f462343e974c048d88206eaaa860d8
* Step 1. Go to Wayne Enterprises colony (it is easier to test with this colony since it starts with 4 subdomains by default). Check the Influence By Team chart on the dashboard (ensure you aren't filtering the app by a team). It should show 4 teams in both the pie chart and the legend below.
* Step 2. …
> Fix: Add zero reputation teams to dashboard influence-by-team list

- src/components/v5/common/ActionSidebar/partials/ActionSidebarLoadingSkeleton/ActionSidebarLoadingSkeleton.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarWidgetLoadingSkeleton/ActionSidebarWidgetLoadingSkeleton.tsx
- src/components/v5/common/ActionSidebar/partials/MultiSigSidebar/MultiSigSidebar.tsx
- Fix the loading state of the multisig action sidebar widget to match the Figma designs. Previously it showed an awkward spinner in the top left of the sidebar, whereas it should really be matching the general loading state for this widget.
- As part of this work, I refactored that general action sidebar loading component a little and extracted the widget part into a more reusable component so it could also be used here.
Figma: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=26993-210663&t=jBC7dx6GQVefvIes-4
* Step 1. Install the multisig extension
* Step 2. Make any multisig action
* Step 3. Load that action so that it opens in the sidebar. As it loads, check the loading state. I used a screen recorder, and also changed line 35 of …
> Fix multisig widget loading state

- src/components/frame/v5/pages/TeamsPage/hooks.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/FundsCards.tsx
- src/components/v5/shared/TeamFilter/partials/TeamItem.tsx
- src/hooks/useTeamsOptions.ts
- src/redux/sagas/actions/editDomain.ts
- src/utils/domains.ts
This PR adds fallbacks for when a team name is missing. This can occur when there is a database issue when creating a new team (although hopefully the likelihood of this occurring is less now that #3669 is merged).
It also makes a change to the "Edit domain" saga so that if a team is missing metadata that it will be properly created.
* Step 1 - First we need to delete a domain metadata entry to simulate a failed metadata mutation when creating a team. Copy the colony address from the dashboard and run this mutation to remove the Andromeda metadata entry.
```
deleteDomainMetadata(input: {id: "{COLONY_ADDRESS}_2"}) {
id
}
}
```
* Step 2 - Refresh and navigate to the teams page, check the fallback appears correctly in both the team switcher and the team cards. (Note the …
> Fix: Add team name fallbacks

- src/redux/sagas/actions/createDomain.ts
- src/redux/sagas/actions/editColony.ts
- src/redux/sagas/actions/editDomain.ts
This PR resolves an issue with the sagas involving metadata mutations, which was causing the onSuccess handler not to fire to evict the cache, and causing the `isSubmitting` form variable to return to false too soon.
* Step 1 - Create an edit colony action
* Step 2 - Submit the form, check that the submit form stays pending until the form shows the completed action screen
* Step 3 - Without refreshing, check the new action appears in the recent activity table
https://github.com/user-attachments/assets/028d44a5-e9f3-4aef-9ce3-92677eab4988
Further testing: Check the same with create a new team and edit a team.
**Changes** 🏗
* Changed the mutation order in the sagas
Resolves #3693 
Resolves #3812
> Fix: Actions with metadata not completing correctly

- src/components/common/ColonyActionsTable/hooks/useBuildRedoEnabledActionsMap.ts
- src/components/shared/Fields/Form/Form.tsx
**Testing Steps for #3871**
1. Bring up the manage tokens form
2. Add a token
3. Enter a title
4. Select a decision method
5. Submit the form
6. Verify the form is submitted
7. On the Colony Actions table, verify that there is no Redo option for the Manage Tokens action
**Testing Steps for #3860**
1. Make sure Andromeda has funds
2. Make sure the Reputation extension is enabled
3. Bring up the Transfer Funds from
4. Set the From field to Andromeda
5. Set the To field to General
6. Set the Decision method to Reputation
8. Verify that Created in is correctly set to the Root domain
9. Fill in all other required fields
10. Submit the form
11. Verify you are able to create the action successfully
Resolves #3871, #3860
> Fix: Preserve existing form value changes when the form re-renders

- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/utils.ts
- src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/utils.tsx
- Fix an issue with simple payments accidentally sending multiple payments inside on transaction. This occurs when you 'redo' an advanced payment, and then change the action type to be simple payment.
* Create an advanced payment to Amy / whoever you like, just not Leela.
* Open the completed action modal and in the top right click on the hamburger menu to redo the action.
* Change the action type to simple payment and set the recipient as Leela. Complete the action, and it should complete successfully and show a normal completed action screen.
**Changes** 🏗
* Don't pass the payments (form value) array to the Simple Payment saga, since you should never be allowed to send more than one payment.
Resolves #3851
> Fix: Simple payments when redoing an advanced payment

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
Thanks to an insightful investigation by @olgapod, the fix was straightforward and simply required clearing the expected expenditure type on `PaymentBuilder` unmount.
- Install Staged Payment extension
- Create a staged payment
- Without refreshing the page, create an advanced payment
- Observe that advanced payment loads fine 
On master, it would keep loading forever due to a stale value of `expectedExpenditureType`.
Resolves #3862
> Fix: Clear expected expenditure type to prevent infinite loading

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/ManageReputationTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/hooks.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/SplitPayment.tsx
This PR fixes an issue where small amounts using the equal split type were defaulting to scientific notation which was breaking the amount fields in the table.
Whilst working on this I also found a weird edge case issue where entering `1M` (as in 1 million) would get adjusted by the cleave-zen `unformatNumeral` function to `1.` and if you added another `M` (`1.M`) the amount field would appear unchanged, but the action subtitle would show `1M00000000`.
* Step 1 - Create a split payment action
* Step 2 - Select the "Equal" split type
* Step 3 - Enter the amount `0.00000001` - check that the app does not crash
* Step 4 - Clear the amount field and enter `1M` check that the `M` is not entered and that the amount field just shows `1`, enter another `M` and check the amount field still just …
> Fix: Equal split payment amount issue

- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/useMuteColonyItem.tsx
- src/context/MemberContext/MemberContextProvider.tsx
- src/hooks/useOnElementScroll.tsx
- src/hooks/useTokenLockStates.ts
- Fix a few warnings which we had in the app (to do with dependency arrays) which were showing up on every PR under the `Unchanged files with check annotations` section. Kinda ugly and distracting having these warnings on each PR...
Example:
Just some basic testing to make sure nothing broke might be a good idea. Also check this PR to see that there's no warnings in the files changed section under `Unchanged files with check annotations`.
* Check the mute colony button to ensure it still toggles on / off correctly
* Check that the members context still works by looking at the members page for example
* Check that the useOnElementScroll hook still works by copying a colony address on the dashboard, and then scrolling the page. The green tooltip should disappear on scroll.
* Check that the …
> Fix warnings to clean up 'Unchanged files with check annotations' section of PRs

- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/components/common/Extensions/UserNavigation/partials/UserMenu/consts.ts
- src/components/frame/Extensions/themes/utils.ts
- src/context/FeatureFlagsContext/FeatureFlagsContextProvider.tsx
- src/context/FeatureFlagsContext/types.ts
- src/styles/main.css
This PR adds feature flags to the in app product tour, it currently only hides the menu item, which is the only way to trigger tours.
In the future the plan is to have some auto triggered tours, which will likely need a different solution when the time comes, unless anyone has some suggestion for moving the feature flag further up the chain now.
There is also a fix for the tooltip arrow in dark mode.
1. Ensure you are in dark mode.
2. Start the "Using the app" guided tour.
3. Note the arrow on the tooltip.
1. Enable or disable the feature flag within Posthog.
2. The "Guided tours" menu item should not be visible when the feature flag is disabled.
* Added "dark" class to `html` tag for CSS selector targeting.
* Added feature flag for guided tours.
> Guided tour feature flag and dark mode fixes

- amplify/backend/api/colonycdapp/schema/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- src/graphql/generated.ts
Opening this PR to allow @CzarekDryl to merge into #3322.
See https://github.com/JoinColony/block-ingestor/pull/302 for description/testing instructions.
> Feat: Add `willPunishExpenditureStaker` field to colony motion

- src/components/shared/Fields/Form/Form.tsx
After rebasing the master "Edit details," the form starts working incorrectly. Considering that this is dynamic fields for some reason "watch" was called during first load, so some values were deleted.
Thanks to @rumzledz for the fast one-line solution. 🙌  
Step 1. Open "Arbitrary transaction"
Step 2. Add a random transaction (You can use this contract: `0xeeeafa86903cf2cb5c74a61d3e67844e226730c0`)
Step 3. Submit form
Step 4. Select "Edit details" in the transaction table
Step 5. Verify that form inputs and values are the same as it was submitted:
Resolves #3866
> fix: 'edit details' form to render a correct inputs and values

- playwright/e2e/simple-payment.spec.ts
- playwright/utils/simple-payment.ts
- src/components/common/LoadingSkeleton/LoadingSkeleton.tsx
- src/components/shared/Fields/Form/ActionForm.tsx
- src/components/shared/Fields/Form/Form.tsx
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/AmountField/partials/TokenList.tsx
- src/components/v5/common/Fields/CardSelect/CardSelect.tsx
- src/components/v5/shared/MenuContainer/MenuContainer.tsx
- src/components/v5/shared/MenuContainer/types.ts
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
- src/components/v5/shared/NotificationBanner/NotificationBanner.tsx
- src/components/v5/shared/NotificationBanner/types.ts
- src/components/v5/shared/SearchSelect/SearchSelect.tsx
- src/components/v5/shared/UserInfoPopover/partials/UserInfo.tsx
Added tests for Simple Payment action.
Test cases included in the PR:
- Should successfully create a simple payment
- Should display validation errors for required fields and invalid inputs
- Should display tooltips and user info on hover and click actions
- Should display the confirmation modal when the user tries to close the form
- Should not allow to create a simple payment with no permissions
Step 1. Spin up the dev env and seed the test data 
`npm run dev`  followed by `node scripts/create-data.js`
Step 2. Remove your local playwright trace files
`rm -rf playwright-report/` (from the root of the project )
Step 3. Build and start the frontend in preview mode
`npm run preview` 
Step 4. Run the tests in a separate terminal 
`npm run e2e simple-payment`
Step 5. The tests should pass ( …
> test: simple payment e2e tests

- src/components/common/ColonyActionsTable/partials/ActionsTableFilters/ActionsTableFilters.tsx
- src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageContent.tsx
- src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
- src/components/frame/v5/pages/AgreementsPage/AgreementsPage.tsx
- src/components/frame/v5/pages/AgreementsPage/partials/AgreementsPageFilters/AgreementsPageFilters.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
- src/components/frame/v5/pages/BalancePage/partials/BalanceTable/Filters/BalanceFilters/BalanceFilters.tsx
- src/components/frame/v5/pages/FundsPage/partials/Filter/Filter.tsx
- src/components/frame/v5/pages/FundsPage/partials/Filter/types.ts
- src/components/frame/v5/pages/FundsPage/partials/FundsTable/FundsTable.tsx
- src/components/frame/v5/pages/TeamsPage/TeamsPage.tsx
- src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/TeamsPageFilter.tsx
- src/components/v5/common/Filter/Filter.tsx
- src/components/v5/common/Filter/hooks.ts
- src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
- src/components/v5/common/Pills/SearchPill/SearchPill.tsx
- src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
- src/components/v5/shared/SearchSelect/partials/SearchInput/types.ts
- Added search pill next to filters
- When clicking 'enter' key while typing in search input - filter menu closes
* Go to any page with filters i.e. activity feed, balances
* Open filters menu and use search
* Click 'enter' key and check if menu closes
Resolves https://github.com/JoinColony/colonyCDapp/issues/3666
> feat: add search pill to filters

- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/StagedPaymentsDescription.tsx
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/DecisionMethodField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/PaymentBuilderForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/StagedPaymentForm.tsx
The issue was that the Reputation decision method isn't available for the Advanced, Split & Staged payment forms. So this PR clears the decision method field if the form attempts to set it to an unavailable decision method.
I also took the liberty of removing the `<CreatedIn />` component from the aforementioned forms because I thought they were redundant. But if I'm wrong in my assumption, do let me know and I'll bring them back.
This PR also includes a crash fix raised in #3892.
1. Enable the Reputation extension
2. Create a Simple Payment action via the Reputation decision method
3. Redo this action
4. Change the action to Advanced payments/Split payments/Staged payments
5. Submit the form
6. Verify that you see the validation error for the decision method field
Resolves #3889 , #3892
> Fix: Clear invalid decision method and prevent Staged Payment form crash

- src/components/shared/Extensions/Tabs/Tabs.tsx
This PR fixes an issue where the right arrow of the tabs component was showing on top of the loader.
Navigate to http://localhost:9091/account/preferences Make sure you don't see the right arrow whilst the page is loading.
https://github.com/user-attachments/assets/4ca928fb-0824-434a-bcf8-3508fbe55425
**Changes** 🏗
* Removed unnecessary z-index
Resolves #3749
> Fix: Tabs right arrow showing over loader

- src/components/v5/common/ActionSidebar/hooks/permissions/consts.ts
- src/components/v5/common/ActionSidebar/hooks/permissions/useHasNoDecisionMethods.ts
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/DecisionMethodField.tsx
- src/components/v5/common/ActionSidebar/partials/DecisionMethodField/types.ts
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/PaymentBuilderForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/StagedPaymentForm.tsx
- src/components/v5/common/ActionSidebar/utils.ts
This PR fixes an edge case issue where users with multi-sig permissions would be able to access the expenditure actions when the staking advanced payments is uninstalled and there are no decision methods available.
* Step 1 - Uninstall the staking advanced payments extension
* Step 2 - Install the staged payments extension
* Step 3 - Install the multi-sig extension
* Step 4 - Assign Owner multisig permissions to Fry
* Step 5 - Switch to the Fry wallet
* Step 6 - Create an advanced payment action, observe the "no permissions" validation error
* Step 7 - Check the same is true for split payments and staged payments
* Step 8 - Reinstall the staking advanced payments extension and check the decision method is available
* Added an `actionsWithoutMultiSigDecisionMethod` const …
> Fix: Show no permissions validation for expenditures without multisig

- amplify/backend/api/colonycdapp/schema/balance.graphql
- amplify/backend/function/fetchDomainBalance/src/api/graphql/operations.js
- amplify/backend/function/fetchDomainBalance/src/api/graphql/schemas.js
- amplify/backend/function/fetchDomainBalance/src/config/networkConfig.js
- amplify/backend/function/fetchDomainBalance/src/index.js
- amplify/backend/function/fetchDomainBalance/src/services/exchangeRates.js
- amplify/backend/function/fetchDomainBalance/src/services/networkBalance.js
- src/graphql/generated.ts
There were some issues discovered while doing the prod deployment, causing for the displayed values to be always `0`.
The main one was due to the used fallback value for the `chainId` property. Given we don't really want to be a parametrisable property, this value has been removed from the lambda's input values. Also, given we want to use this value to filter out the coins list from `CoinGecko` this value has been renamed to `supportedNetwork` and will be set in `NetworkConfig`.
Another issue we might face is not having the token used for an action already stored in the DB - which we need to determine the number of decimals - so, we should use the `getTokenFromEverywhere`. This query relies on the `fetchTokenFromChain` lambda that will try to find the token if it is not already stored and …
> Fix: Solve fetchDomainBalance lambda issues

- src/utils/members.ts
This PR fixes an issue with the username not correctly updating within a colony if you had previously loaded that colony.
Before testing, we need to adjust the code to work around the 90 day username change restriction. Open up this file: `src/components/frame/v5/pages/UserProfilePage/partials/UserAccountPage/hooks.tsx` and change line 31 to `return { canChangeUsername: true, daysTillUsernameChange };`.
* Step 1 - Navigate to the planex dashboard: http://localhost:9091/planex
* Step 2 - Without refreshing, navigate to the manage account page
* Step 3 - Change the username to something new and click save changes. Notice the success toast.
* Step 4 - Without refreshing, navigate back to the colony and go to the members page. Check the name has changed.
**Changes** 🏗
* Fixed issue with the …
> Fix: Username change is not reflected in colony

- src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/partials/ManageReputationTable/ManageReputationTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/ClaimDelayField/ClaimDelayField.tsx
- src/components/v5/common/Fields/InputBase/InputBase.tsx
- src/components/v5/common/Fields/TextareaBase/TextareaBase.tsx
What it says on the tin. This PR adds a blue hover state to input fields in the action form.
Check the text input fields on all the various actions, check the placeholder hovers to blue and that the text hovers to blue.
This PR does change both the InputBase component and the TextareaBase component, so feels like there could be unintended changes elsewhere in the app, but I could not find any during my testing.
**Changes** 🏗
* Add hover state to inputs
Resolves #3740
> Fix: Input field should hover to blue

- src/components/v5/common/CompletedAction/partials/SetUserRoles/SetUserRoles.tsx
- src/components/v5/common/CompletedAction/partials/SetUserRoles/utils.ts
- src/context/AppContext/AppContextProvider.tsx
- src/context/MemberContext/MemberContextProvider.tsx
- src/graphql/generated.ts
- src/graphql/queries/contributors.graphql
- src/utils/objects/index.ts
> [!NOTE]
> Please note that there is an existing issue where the Permissions table on the Completed Action form is not correctly showing the permissions that were removed from the user after a Reputation or Multi-Sig motion has successfully been supported/approved and finalised. This is kind of a complex issue and **it will not be addressed on this PR**. 
>
> There is also an existing issue with reputation motions where the Finalise button has the possibility of getting stuck in a Pending state: https://github.com/JoinColony/colonyCDapp/issues/3859. You may or may not come across it but just know that this PR has nothing to do with it.
This PR makes use of subscriptions to automatically refresh member permissions information whenever it's updated.
**Out of scope yet relevant and …
> Fix: Automatically propagate user permission updates

- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/hooks.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneReleaseModal/MilestoneReleaseModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/ReleaseActions/ReleaseActionItem.tsx
- src/i18n/en.json
- Fix issues with making staged payment using tokens which are not native to your colony.
- Four issues are fixed here:
- You should not be able to make a staged payment milestone using a token which is locked
- When using a token for a milestone which is not your colonies native token, it needs to be passed to the transaction for it to be claimed properly (previously only the colony native token was being sent)
- If a milestone payment failed for whatever reason, the status pill should not show as 'passed'
- Duplicate milestones were appearing in the sidebar (related to them silently failing)
* Open Wayne Enterprises colony and check that the native token (GGG) is locked (this is the default state from the create-data script)
* Go to the Planet Express colony
* Open the incoming funds …
> Fix: Staged payments with locked tokens

- src/components/v5/shared/RichText/RichText.tsx
1. Bring up the Simple Payment form
2. Enter the following text on the Description field:
```
jfkladfjkladfkldjlk;ajflkjadkl;fjadlk;fjadlk;fjkladsjflk;adjfkljadklfjadlkfjadkl;jflk;ajfkladjlf;jalk;fjadkl;fjakld;jfkladjl;adjlkdajflkadjfkljadklfjadlkfjkladjflk;adsjflkadsjflkadjfkladjfal;kfjklajfl;kadjflkadjflkadjfl;kajfl;kadjflk;adjfl;kadjfl;kdajflk;adjflkadjfkladjkfjadlk;fjlka;djfjadlk;jfkladjf;la
```
3. Collapse the Description field
4. Verify that the description is properly clamped to 2 lines and truncated
5. Change the viewport to mobile
6. Verify that it's still properly clamped and truncated
Resolves #2985
> Fix: Wrap long descriptions

- src/components/v5/common/ActionFormRow/ActionFormRow.tsx
- src/components/v5/common/ActionSidebar/partials/Description/Description.tsx
- src/components/v5/common/CompletedAction/partials/rows/Description.tsx
- src/i18n/en.json
This PR adds back tooltips to the description field.
I took some creative liberty to reword the tooltip in the completed action from:
```
Provide a description for why this action is being performed including any relevant details.
```
to
```
The description for why this action is being performed including any relevant details.
```
since it makes no sense grammatically otherwise :shrug: 
1. Try to create any action and hover the description field. Verify that the tooltip appears :eyes: 
2. Create the action and verify that the tooltip appears, but with slightly different text
**Changes** 🏗
* The ActionForm `DescriptionField` now renders the tooltip
* The completed action's `Description` row now render a slightly different tooltip
Resolves  #3739
> fix: show description tooltip in action form and completed action

- src/i18n/en-motion-states.ts
- Changed `Staked` motion text to `Supported`
**Simple payment**
1. Ensure you have Reputation extension enabled.
2. Create a Simple payment action.
3. Use the Reputation decision method.
4. Fully stake the motion.
6. Check the status of the motion in the activity feed.
**Advanced payment**
1. Ensure you have Reputation extension enabled.
2. Create an Advanced payment action.
3. Perform any step with the Reputation decision method. e.g. Funding.
5. Check the status of the motion in the motion widget.
Resolves https://github.com/JoinColony/colonyCDapp/issues/3971
> fix: changed supported state copy

- src/components/v5/common/CompletedAction/partials/StreamingPayment/partials/StreamingPaymentWidget/StreamingPaymentWidget.tsx
- An error appeared about funds even though there are funds in the colony
* Install Streaming Payments extension
* Create a stream with a Start immediately option and with a relatively low (compared to your colony balance) amount
* Watch the completed action view
https://github.com/user-attachments/assets/0c7a298c-de79-457e-b765-6471cbcd6537
Resolves https://github.com/JoinColony/colonyCDapp/issues/3901
> fix: refresh available funds

- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentPercentField/SplitPaymentPercentField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/SplitPaymentRecipientsField.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/SplitPayment.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/hooks.tsx
- Move the team field above the amount field in both the creation and completed states.
- Add the 'Add row' feature (currently in the 'Advanced payments' payment table) to the split payments table.
- Ensure the padding between the percentage icon and the placeholder/inputted value matches the Figma design across all responsive states for both creation and completed states.
* Create split payment action
* Check team field placement, add row option in meatball menu and padding between % and amount
Resolves https://github.com/JoinColony/colonyCDapp/issues/3972
> fix: split payment ui/ux

- src/components/v5/common/CompletedAction/partials/CreateDecision/CreateDecision.tsx
- src/components/v5/common/CompletedAction/partials/rows/Description.tsx
- Description field for the “Create agreement” action type is expanded by default when in the completed state
* Install Reputation Weighted (Lazy Consensus method) extension
* Create a new agreement
* Check if description field is expanded by default
Resolves https://github.com/JoinColony/colonyCDapp/issues/3991
> feat: expand agreement desc by default

- src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
- src/components/v5/shared/TeamFilter/partials/TeamsDropdown/TeamsDropdown.tsx
- tailwind.config.js
- This PR addresses the issue of having the loading skeletons overlapping the teams dropdown list
**Before**
**Now**
* Step 1. Make sure your dev env is running
* Step 2. Go to http://localhost:9091/planex
* Step 3. Please save these changes in a `.diff` file
```
diff --git a/src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx b/src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
index 37d904089..62fdbcc63 100644
--- a/src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
+++ b/src/components/common/ColonyActionsTable/hooks/useActionsTa …
```
> Fix: Update and rename z-index used for TeamsDropdown

- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/partials/ActionNotFound.tsx
- src/components/v5/common/FourOFourMessage/FourOFourMessage.tsx
- src/components/v5/common/FourOFourMessage/types.ts
- src/hooks/useLocationPathnameChange.ts
- This PR aims fixing the broken styling for the not found action sidebar content, as well as the navigation to creating a new action from its `Create a new action` link
https://github.com/user-attachments/assets/1a403449-6d33-4754-bcdd-94b0dc763208
TODO: Please check the navigation to creating a new action works properly, UI adjustments match [Figma](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=23947-236415&t=bsEF0JbB2xNLxycb-4) and then we'll proceed to some regression testing 🙌 
* Step 1. Navigate to http://localhost:9091/planex?tx=0x
* Step 2. Check the action sidebar content matches the [Figma](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=23947-236415&t=bsEF0JbB2xNLxycb-4) 
* Step 3. Click on `Create a new action` …
> Fix: No transaction action sidebar styling and behaviour

- src/components/frame/v5/pages/ColonyPreviewPage/ColonyPreviewPage.tsx
This PR fixes an issue where [http://localhost:9091/go/colonyname](http://localhost:9091/go/colonyname) would still load even if there is no colony with this name.
Navigate to [http://localhost:9091/go/colonyname](http://localhost:9091/go/colonyname) you should be redirected to a 404 page.
As a logged in user with access to Planex, navigate to [http://localhost:9091/go/planex](http://localhost:9091/go/planex) you should be directed to the planex colony.
As a logged out user, navigate to [http://localhost:9091/go/planex](http://localhost:9091/go/planex) you should see the preview page.
**Changes** 🏗
* If no colonyAddress is found, redirect to 404 route
Resolves #3809
> Fix: go/colonyname redirects to 404 if no colony exists

- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsItem.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsSubTitle.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalDescription.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalItem.tsx
- This PR aims to fix the total funds cards content alignment
https://github.com/user-attachments/assets/23b8e7de-2ee5-4480-b5ae-f33888e10a21
TODO: Make sure the total funds cards on the dashboard match [Figma](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-89693&t=qZsUrtUGdZQc0mXw-0) 
TODO: Please also test the loading state, by setting `loading` to `true` in `src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalItem.tsx` and `src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsItem.tsx`
> [!TIP]
> If you want to test this PR easier, you can use the [Pixel Perfect](https://chromewebstore.google.com/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) extension
> Then, you'll need to download [this …
> Fix: Total fund cards alignment on dashboard

- src/components/common/ColonyActionsTable/FiltersContext/FiltersContextProvider.tsx
- src/components/frame/v5/pages/AgreementsPage/FiltersContext/FiltersContextProvider.tsx
- Ensure that you cannot select more than one date option when filtering the actions / agreements table. The reasoning is that selecting `Past hour` and `Past week` for example at the same time is actually just equal to selecting only `Past week`. Custom date ranges are slightly different to this, but after some discussion with product, it is not worth the work of making them multi selectable alongside presets (currently, if you have a custom date range selected it ignores any preset you also select).
* Go to the activity page and filter by the date. You should only be able to select one at a time.
* Go to the agreements page and filter by the date. You should only be able to select one at a time.
https://github.com/user-attachments/assets/ecb2c434-7e25-451a-a6f6-4868d621e79f
**Changes** …
> Fix: Make date filters single choice

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/InstallButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/ReenableButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/SubmitButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/UpgradeButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/hooks.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/DeprecateButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/UninstallButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/hooks.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionPermissionsBanner/PermissionsNeededBanner.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/utils.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/utils.tsx
- Ensure that while extensions are being managed (installed, settings changed, enabled, deprecated, and uninstalled) the other buttons to manage the extension are disabled. This prevents you from, for example, uninstalling an extension, and then while that loads, attempting to enable it as described here: https://github.com/JoinColony/colonyCDapp/issues/3577.
* Go to any extension page
* Install the extension
* Change the extension settings (and save)
* Enable the extension
* Deprecate the extension
* Uninstall the extension
* At each stage, check that you cannot do another extension management action, and that any other buttons for extension management from the list above are disabled if they are shown. The video below may help: …
> Fix extension settings loading states

- src/components/shared/Fields/Form/Form.tsx
The problem is that the form was being reset when submitted even though errors are present. We don't want that to happen.
1. Open the `UserAccountPage/hooks.tsx` file and update line 31 to:
```js
return { canChangeUsername: true, daysTillUsernameChange };
```
2. Connect Amy's wallet (Wallet 2)
3. Go to the profile page: http://localhost:9091/account/profile
4. Enter "leela" in the Username field
5. Click the Save changes button repeatedly
6. Verify that the form doesn't submit
Resolves #3730
> Fix: Prevent form reset on submit when errors are present

- src/components/v5/common/ArrowScroller/ArrowScroller.tsx
The left scroll's distance multiplier was somehow causing the team filter to shift way beyond the boundaries so I set it to match the right scroll's distance multiplier, `0.5`.
| ![team-filter-scroll-bug](https://github.com/user-attachments/assets/7fa86a75-2e5c-4bd5-8796-8b6e7804b7cd) | ![team-filter-scroll-fix](https://github.com/user-attachments/assets/6f779f6c-bafc-450b-aa1b-39eaf269e3b9) |
> [!NOTE]
> I don't know any other way for anyone to test this apart from doing this in a Simulator
1. Open the app on an iOS simulator
2. Go to the Planex colony dashboard
3. Click the right arrow for the Teams filter
4. Click the left arrow for the Teams filter
5. Verify that the Team filter is not overly scrolled to the point that there is an empty space to its …
> Fix: Do not overscroll the Teams filter

- src/components/v5/common/WidgetCards/WidgetCardsItem.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsItem.tsx
- src/components/v5/frame/ColonyHome/partials/FundsCards/partials/FundsCardsTotalItem.tsx
This PR addresses an issue where the funds cards were clickable before the card content had loaded in. It also fixes the hover styling.
Reload and hover over the funds whilst they are loading, make sure they are not clickable.
Once the are fully loaded, check the hover styling matches figma.
Figma: [https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-84953&t=OpWCmWBoyrScYokI-4](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-84953&t=OpWCmWBoyrScYokI-4)
* Added `isLoading` prop to WidgetCardsItem component and disabled button wrapper whilst loading
**Changes** 🏗
* Fixed hover styling
Resolves #3654
> Fix: Funds card hover state

- src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
The app was crashing because the GroupedTransaction component is attempting to access the Colony Context before the app even navigates to a Colony. I slightly tweaked the logic to make sure this doesn't happen.
1. Generate a create Colony URL using the following command:
```console
node scripts/create-colony-url.js
```
2. Proceed to create a Colony
3. Verify that the app doesn't crash during Colony creation 
Resolves #4083
> Fix: Prevent app crash during colony creation

- src/components/common/Extensions/UserNavigation/partials/UserSubmenu/partials/Currency/Currency.tsx
- src/context/CurrencyContext/CurrencyContextProvider.tsx
- src/hooks/useCurrency.ts
- src/utils/currency/tokenPriceByAddress.ts
This PR addresses mainly the problem of having the `CLNY` token migrated to another address on `Arbitrum One`.
This caused the `fetchTokenPriceByAddress` to throw an error and render the `Balances` page blank, due to a missing `try...catch` block.
Also given that for the moment we don't have data based on which to convert amounts to `CLNY`, we'll hide the option from the user menu, while also refreshing the `preferredCurrency` stored in the user profile.
TODO: Let's test our changes do work as expected. 
* Step 1. Please add this at `line 55` in `src/components/shared/CurrencyConversion/CurrencyConversion.tsx`
```
const conversionRate = useCurrency({
contractAddress: '0xd611b29dc327723269bd1e53fe987ee71a24b234',
chainId: Network.ArbitrumOne,
conversionDenomination: …
```
> Fix: Remove CLNY from currency list and add try catch for CoinGecko errors

- src/components/common/ColonyActionsTable/consts.ts
- src/components/common/ColonyActionsTable/hooks/useActionsTableProps.tsx
- src/components/common/ColonyActionsTable/hooks/useColonyActionsTableColumns.tsx
- src/components/common/ColonyActionsTable/hooks/useRenderRowLink.tsx
- src/components/common/ColonyActionsTable/partials/ActionMobileDescription/ActionMobileDescription.tsx
- src/components/common/ColonyActionsTable/partials/ColonyActionLinkWrapper.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
- src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/hooks.tsx
- src/components/v5/common/Table/consts.ts
- The purpose of this PR is to address the fact that the activity table rows do not open the action sidebar on mobile when clicked
**Before**
https://github.com/user-attachments/assets/9584878b-7cdc-403f-980e-e7ec6ad905e9
**After**
https://github.com/user-attachments/assets/47dcef74-21a3-47dc-b9b0-7e23637de627
Please use a mobile simulator or just switch your browser to a width of `< 1024px`. 
* Step 1. Go to `planex` and scroll to the `Recent activity` table
* Step 2. Click on any action and check that it opens the action sidebar
* Step 3. Try expanding the action and check it still works as expected
* Step 4. Check the column spacing is as expected
* Step 5. Go to http://localhost:9091/planex/activity
* Step 6. Repeat steps `2-4` and confirm everything still works as expected …
> Fix: Expandable rows not opening transaction

- src/hooks/useActivityFeed/helpers.ts
Searching the action feed was matching against the ColonyActionType (i.e. `UNLOCK_TOKEN`) rather than how the action type appears in the UI. (`Unlock token`) This PR adjusts the search to use the correctly formatted action type.
You can test this with any action type, but for the sake of testing lets use the `Unlock token` action.
Create an `Unlock token` action, do not use the words "Unlock token" in the custom title.
Navigate to the action feed and type into the search "unlock token", the action should appear.
Compared to master:
**Changes** 🏗
* Activity feed search now uses the formatted action type
Resolves #3701
> Fix: Search activity feed by formatted action type

- amplify/backend/function/fetchColonyBalances/src/package-lock.json
- amplify/backend/function/fetchColonyBalances/src/package.json
- amplify/backend/function/fetchDomainBalance/src/package-lock.json
- amplify/backend/function/fetchDomainBalance/src/package.json
- amplify/backend/function/fetchMotionState/src/package-lock.json
- amplify/backend/function/fetchMotionState/src/package.json
- amplify/backend/function/fetchMotionTimeoutPeriods/src/package-lock.json
- amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
- amplify/backend/function/fetchVoterRewards/src/package-lock.json
- amplify/backend/function/fetchVoterRewards/src/package.json
- amplify/backend/function/getUserReputation/src/package-lock.json
- amplify/backend/function/getUserReputation/src/package.json
- amplify/backend/function/getUserTokenBalance/src/package-lock.json
- amplify/backend/function/getUserTokenBalance/src/package.json
- amplify/backend/function/qaSSMtest/src/package-lock.json
- amplify/backend/function/qaSSMtest/src/package.json
- amplify/backend/function/updateContributorsWithReputation/src/graphql.js
- amplify/backend/function/updateContributorsWithReputation/src/index.js
- amplify/backend/function/updateContributorsWithReputation/src/package-lock.json
- amplify/backend/function/updateContributorsWithReputation/src/package.json
- amplify/backend/function/updateContributorsWithReputation/src/utils.js
- docker/colony-cdapp-dev-env-block-ingestor
- docker/colony-cdapp-dev-env-network
- package-lock.json
- package.json
This PR fixes the way the `updateContributorsWithReputation` Lambda updates the cached reputation for users by shedding it's the network _(and implicitly `colonyJS`)_, making only the db and the Reputation miner the only parts required for it to work.
The initial issue that triggered this was when a block ingestor fell behind the network, and when it caught up, and processed the `ReputationMiningCycleComplete` event, it used the wrong timestamp and delayed the reputation for the whole app for at least one mining cycle.
This was facilitated by the introduction of a `/rootHashes` route in the miner on the network side, which will return the current root hash as well as the upcoming one https://github.com/JoinColony/colonyNetwork/commit/3f8df23173f840226fb8da42547e12664f10c290
Using the …
> Fix Reputation Cache Update Lambda

- src/components/frame/v5/pages/AgreementsPage/hooks.ts
This just simply filters out the Agreements to show based on the domain filter.
1. Install and enable the Reputation extension
2. Create an agreement for the Daedalus team
3. Visit the Agreements page
4. Set the Teams filter to All teams
5. Verify that you can see the Agreement you just made
6. Set the Teams filter to Andromeda
7. Verify that you cannot see the Agreement you just made
8. Set the Teams filter to Daedalus
7. Verify that you can see the Agreement you just made
Resolves #3992
> Fix: Apply Domain filter to the Agreements Page

- package-lock.json
- package.json
- playwright/e2e/advanced-payment.spec.ts
- playwright/fixtures/expenditures_batch.csv
- playwright/fixtures/expenditures_batch_invalid.csv
- playwright/fixtures/test-data.ts
- playwright/models/advanced-payment.ts
- playwright/setup/index.ts
- src/components/v5/common/ActionSidebar/partials/ExpenditureActionStatusBadge/ExpenditureActionStatusBadge.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderPayoutsTotal/PaymentBuilderPayoutsTotal.tsx
- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
- src/components/v5/common/AvatarUploader/partials/ErrorContent.tsx
- src/components/v5/common/Pills/PillsBase.tsx
- src/components/v5/common/Pills/types.ts
E2e tests for Advanced Payment. Also updated playwright to the latest version. 
Test cases included in the PR:
- Happy path of Advanced payment (Permissions and Staking method)
- Canceling the Advanced payment 
- Form fields validation
- Recipients table actions - Add/Remove/Duplicate row
- Uploading CSV - Happy path
- Uploading CSV - invalid field values/missing values 
- Uploading CSV of invalid format
The playwright package version has been upgraded in this PR. 
Please run `npm run e2e:install` and `npm install`. 
**Step 1**. Spin up the dev env and seed the test data 
`npm run dev`  followed by `node scripts/create-data.js`
**Step 2 (optional)**. Remove your local playwright trace files
`rm -rf playwright-report/` (from the root of the project )
**Step 3**. Build and start the …
> test: advanced payment e2e tests

- src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/hooks.ts
From what I understand, at least for the time being anyway since we don't have nested teams yet, the Permission Domain ID (created in field value) should be set to the Parent Domain of the From and To domains. This is currently reflected by how we're filtering the domains list for the Created in field to only contain the Root domain. Either that or the Permission Domain ID should be equal to both of them, but this isn't an option since we can't do fund transfers from and to the same domain. So the Created In field should really be the Root domain. We'll cross the bridge of dealing with nested domains when we get there 🌉 
1. Install and enable the Reputation extension
2. Go to the Dashboard page
3. Using the teams filter, click a subdomain i.e. Daedalus
4. Bring up the Transfer funds form …
> Fix: Set the Created In field for Fund Transfers to the Parent domain

- src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/partials/TokensTable/TokensTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/SplitPaymentRecipientsField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/hooks.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/SplitPaymentTable.tsx
- src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/hooks.tsx
- src/components/v5/common/Table/partials/TableFooter.tsx
- src/components/v5/common/Table/partials/TableLayout/VerticalTableLayout.tsx
- src/typedefs/@tanstack_react-table/index.d.ts
- There were the following findings while testing #3935 described [here ](https://github.com/JoinColony/colonyCDapp/issues/4046)
TODO: Let's test these issues are fixed. 
> [!NOTE]
> Make sure to start a fresh environment using `node scripts/create-data.js --timeout 100 --coloniesCount 12`
* Step 1. Create a `Manage tokens` action
* Step 2. Copy the token addresses from the other colonies and add them to the table until there are more than 10
* Step 3. Check the padding bottom is not shown for mobile/tablet/desktop
* Step 1. Create a `Split payment` action
* Step 2. Add more than 10 recipients
* Step 3. Check pagination is not shown
* Step 4. Switch to a mobile/tablet view
* Step 5. Check `Percent` is shown for each row
* Step 6. Check the footer amount and percent are right-aligned and …
> Fix: Findings regarding table refactoring

- src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionCountDownTimer/hooks.ts
Special shoutouts to @davecreaser for helping me figure out that there was a little bit of delay on Contract side when it comes to the motion state updates 💯 
So I ended up changing my solution to using the safe polling timeout as the interval delay for refetching the motion state. And it works like a charm ✨ 
> [!NOTE]
> There is a bug on `master` whereby if you don't stake the motion and you just allow the motion countdown timer to finish, then the button gets stuck to Pending. We'll fix this in a separate PR.
1. Install the Reputation extension
2. On the Reputation extension's config page, select "Custom (Advanced)
3. Set the following fields to `0.005` (this will make your life easier)
- Staking Phase Duration
- Voting Phase Duration
- Reveal Phase Duration
4. Enable the Reputation …
> Fix: refetch action data after the motion countdown timer is finished

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/StakedExpenditureSettings.tsx
- src/components/frame/Extensions/pages/ExtensionsPage/ExtensionsPage.tsx
- src/constants/extensions.ts
Display extensions in alphabetical order and change copy for `Staking Advanced Payments`
Order:
- Open `Extensions` page
Staking Advanced Payments copy:
- Open `Staking Advanced Payments` extension
- Go to `Extension settings` tab
Order before install extension:
Order after install extension:
Staking Advanced Payments copy:
Resolves https://github.com/JoinColony/colonyCDapp/issues/2928
> fix: extensions order

- amplify/backend/api/colonycdapp/schema/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- docker/colony-cdapp-dev-env-proxy-block-ingestor
- src/components/v5/common/ActionSidebar/hooks/permissions/helpers.ts
- src/components/v5/common/ActionSidebar/partials/forms/ManageSupportedChainsForm/ManageSupportedChainsForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ManageSupportedChainsForm/hooks.ts
- src/components/v5/common/CompletedAction/CompletedAction.tsx
- src/graphql/generated.ts
- src/i18n/en-actions.ts
- src/redux/sagas/motions/proxyColonies/createProxyColony.ts
- src/redux/types/actions/motion.ts
- src/utils/multiSig/index.ts
- This PR adds functionality to create a proxy colony via voting reputation.
Block ingestor changes [here](https://github.com/JoinColony/block-ingestor/pull/312)
* On a fresh dev env, install the multisig extension, and give multisig owner permissions to Leela
* Run the following query to ensure that no proxy colonies currently exist
```graphql
listProxyColonies {
items {
chainId
colonyAddress
createdAt
id
isActive
updatedAt
}
}
}
```
* Create a `Manage supported chains` action and choose multisig as the decision method
* Finalize the multisig motion
* Run the query again to ensure that a proxy colony was made
```graphql
listProxyColonies {
items {
chainId
colonyAddress
createdAt
id
isActive
updatedAt
}
}
}
```
* New block ingestor hash …
> Feat: Allow addition of proxy colonies with multisig

- src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
- src/components/v5/common/CompletedAction/partials/StreamingPayment/StreamingPayment.tsx
Display streaming payment metadata for action and activity feed
- Create streaming payment action
- Display streaming payment in action sidebar
- Display streaming payment in activity feed
Resolves https://github.com/JoinColony/colonyCDapp/issues/4044
> fix: display streaming payment metadata for action and activity feed

- src/components/frame/v5/pages/AgreementsPage/partials/DraftCard/DraftCard.tsx
- src/components/shared/Fields/Form/ActionForm.tsx
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/hooks/useActionFormBaseHook.ts
- src/components/v5/common/ActionSidebar/hooks/useCloseSidebarClick.ts
- src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/hooks.ts
- src/components/v5/common/ActionSidebar/types.ts
- src/hooks/useDraftAgreement.ts
Current behaviour is when you save a draft agreement and you click outside the form, then the form closes without prompting you. The problem is that when save a draft agreement and you click the close button of the form then it will still show you the "Do you wish to cancel the action creation" modal. So this PR just aligns the behaviour between clicking outside the form component and clicking the close form button.
1. Install the Reputation extension
2. Set the viewport to mobile
3. Bring up the Create agreement form
4. Fill in all required fields
5. Click the close button
6. Verify that the "Do you wish to cancel the action creation" modal is shown
7. Click the Save draft button
8. Click the close button
9. Verify that the form just closes without showing you the "Do you wish to cancel …
> Fix: Close the saved draft agreement form without the cancel modal prompt

- src/components/common/ColonyActionsTable/hooks/useGetMenuProps.tsx
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
- src/components/v5/common/ActionSidebar/hooks/useGetActionGroup.ts
- src/components/v5/common/ActionSidebar/partials/GoBackButton/GoBackButton.tsx
- src/components/v5/common/ActionSidebar/utils.ts
- src/context/ActionSidebarContext/ActionSidebarContext.ts
- src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx
- Added back button to action sidebar
1. Back Arrow:
- Appears only after an action is selected.
- Navigates to the relevant action list view category.
- Not visible on the main action list view.
2. Completed Actions:
- Navigates to the relevant list view category.
3. Browser Back Button:
- Returns to the previous action transaction if clicked after navigating away.
4. Hover State:
- On desktop, matches other action header icons and uses the blue-400 color.
Resolves https://github.com/JoinColony/colonyCDapp/issues/3973
> feat: add back button to action sidebar

- src/components/v5/common/ActionSidebar/partials/UserSelect/hooks.ts
- src/components/v5/common/ActionSidebar/partials/UserSelect/index.ts
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/SplitPaymentRecipientsField.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/hooks.tsx
Basically I started propagating the `domainId` on to `UserSelect` and fixed a `find` statement.
Not sure if we should do this for form validation too? Seems a bit overkill for now.
Right so it may be tricky with create data being semi-flaky and all, but let's go
1. After running the `create-data` script, open up `Wayne` (`Planex` would work too, just use a member with no reputation in a child team
2. Create a `Split payment` action, use `Reputation percentage` for `Distribution`. 
3. Verify that the member select has all the members when `General` is selected as the team
4. Verify that the members with 0 reputation in `Advanced technologies` are filtered out when choosing that as the `Team`
**Changes** 🏗
* `UserSelect` now doesn't fallback to reputation in `General`
* …
> fix: if split payment uses split by reputation, filter out if reputatation in that team is 0

- src/components/v5/common/CompletedAction/consts.ts
- src/i18n/en-actions.ts
Classic `en-actions.ts` mismatch :D 
2. Create an agreement motion, observe that in the form the action type is `Create agreement`
3. Verify that when it's created it still says `Create agreement` for the action type
**Changes** 🏗
* Fixed the string for `ColonyActionType.CreateDecisionMotion` in `en-actions.ts`
* unused translations objects in completed action
Resolves #3986
> fix: string for create agreement motion action type

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
This PR fixes an issue where long recipient names would overflow the action form on mobile.
* Step 1 - Connect to Dev Wallet 4 and create a profile making full use of the 30 character limit.
* Step 2 - Copy the user's wallet address.
* Step 3 - Switch back to dev wallet 1
* Step 4 - Create a simple payment and paste the wallet address into the recipient field. Switch to mobile and check the name does not overflow the edge of the screen.
Feel free to also check when the user is verified too if you wish:
**Changes** 🏗
* UserSelect toggle now has a max width
Resolves #3348
> Fix: Long recipient names should not be cut off

- src/redux/sagas/utils/expenditures.ts
This issue was a bit of a pain to pin down, but luckily has a very simple solution!
This issue only occurred when more than 164 payment rows are added. This is because we chunk the payouts into multiple transactions as otherwise they become too big to process. There was a bug where the slotId was being overwritten for each chunk, so every chunk would start back at slotId 1. Effectively meaning the later chunks were editing the values for the previous chunks.
This PR resolves the issue by using the existing slotId value if it already exists.
Create an advanced payment with more than 164 rows.
[Feel free to use this CSV](https://drive.google.com/file/d/1kNvrcIYzkfUDda7lbpV8GB11NYusjMvw/view?usp=sharing)
Check the completed action screen loads all the payments in the expected order (may take …
> Fix: Advanced payments not processing all slots

- src/components/frame/v5/pages/FundsPage/context/IncomingFundsLoadingContext.ts
- src/components/frame/v5/pages/FundsPage/context/IncomingFundsLoadingContextProvider.tsx
- src/components/frame/v5/pages/FundsPage/context/hooks.ts
- src/components/frame/v5/pages/FundsPage/partials/AcceptButton/AcceptButton.tsx
- This PR aims to keep the `Accept` buttons on the `Incoming funds` page disabled until the funds claims data is refetched and their `isClaimed` state has updated.
> [!NOTE]
> I have considered using subscriptions, however setting a subscription on the `Colony` model would not get triggered when updating the `fundsClaims`, while setting subscriptions for all unclaimed funds claims seems like a too-big of a performance overhead for what we want to achieve. Thus, I have introduced a new `isFundsUpdatePending` state on the `IncomingFundsLoadingContext` and make use of two new hooks, one for refreshing the colony data and one for checking the funds claims state.
TODO: Now let's proceed to testing these changes behave accordingly.
* Step 1. Visit http://localhost:9091/planex and copy the …
> Fix: Disable accept incoming funds button until updated data

- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
- src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/hooks.tsx
After much investigation, I found that the effects I removed were redundant and were causing issues with how we control the claimed state. I have not been able to find an issue after removing them, hopefully this didn't break a flow that I'm not fully aware of 🤞
1. Enable the Reputation extension
2. Create a Mint Tokens motion
3. Oppose and fully stake it
4. Support and fully stake it
5. On the Voting phase, approve it
6. Finalise it
7. Claim back the tokens
8. Verify that
- the Claim button doesn't linger
- the Pending button doesn't linger
Resolves #3859
> Fix: Prevent stale claimable state

- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/UninstallButton.tsx
- src/components/v5/common/ActionSidebar/partials/TimeRow/TimeRow.tsx
- src/components/v5/common/ActionSidebar/partials/TimeRow/partials/TimeRowField/TimeRowField.tsx
- src/styles/main.css
- tailwind.config.js
Display future year in date picker and adjust dropdown background for dark mode
Display future year:
- Create action for `Streaming payment`
- Select custom date and time
- open dropdown with year
Display dropdown for custom time:
- Create action for `Streaming payment`
- Select custom date and time
- click `Time`
Display future yaer:
Display dropdown for dark mode:
Resolves https://github.com/JoinColony/colonyCDapp/issues/4022 https://github.com/JoinColony/colonyCDapp/issues/4023
> fix: date picker select future year and time dropdown style

- docker/colony-cdapp-dev-env-block-ingestor
- scripts/generate-local-notifications-key.js
- src/context/Notifications/NotificationsDataContext/NotificationsDataContextProvider.tsx
Currently we have notifications turned on in dev, QA and production (of course). We use two separate projects on Magicbell - one for production, and one shared between QA and our development environments. 
The PR aims to reduce the amount of unnecessary notifications being fired, especially since we are now paying for Magicbell, and lots of notifications has the potential to push us up a pay bracket.
This PR will turn off notifications being sent in our development environments, whilst keeping it super easy to turn them back on in case you're developing something that needs them. 
The idea here is that you will run `npm run dev --notifications` if you want to have notifications enabled locally. This will ensure that the MAGICBELL_DEV_KEY is generated for you (if you don't pass the …
> Chore: Turn off notifications in dev by default

- src/components/frame/Extensions/pages/ExtensionDetailsPage/context/ExtensionDetailsPageContext.ts
- src/components/frame/Extensions/pages/ExtensionDetailsPage/context/ExtensionDetailsPageContextProvider.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/ExtensionDetailsHeader.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/InstallButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/ReenableButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/SubmitButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/UpgradeButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsHeader/hooks.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/DeprecateButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/UninstallButton.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetailsSidePanel/hooks.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionPermissionsBanner/PermissionsNeededBanner.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/ExtensionSettingsForm.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/MultiSigSettings/MultiSigSettings.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/StakedExpenditureSettings.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/VotingReputationSettings/VotingReputationSettings.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionSettings/utils.tsx
- src/components/frame/Extensions/pages/ExtensionDetailsPage/utils.tsx
- src/components/shared/Extensions/Accordion/partials/AccordionContent.tsx
- src/components/shared/Extensions/ConnectForm/partials/SpecialHourInput.tsx
- src/redux/sagas/expenditures/setStakeFraction.ts
- Attempt number two at fixing the super awkward and spaghetti like extension management loading states! 🎉 
Our talented QA engineer spotted some bugs with my previous fix - mostly to do with the `Save Changes` button when saving the settings for an extension. Also when testing with Metamask, which highlighted some other issues.
⚠️  You'll need to login as Leela using Metamask. If you need help with that, let me know. Alternatively, log in as a random dev user with Metamask, but ensure they have permissions to manage extensions in a colony.
* Install the multisig extension.
* Change the threshold, and while that form is submitting, and the changes are pending, check that the `deprecate extension` button is disabled.
* Click on a different threshold, but **don't** click save changes (just …
> Fix extension management enable / save loading states

- src/components/common/Extensions/ExtensionItem/ExtensionItem.tsx
- src/components/common/Extensions/ExtensionItem/hooks.ts
- tailwind.config.js
- This PR aims to solve the issue on the `Extensions` page of having both the extension button and status pill change state after the extension data has been fetched by adding a loading skeleton before actually showing the button and status pill
**Before**
https://github.com/user-attachments/assets/53777465-9159-4e19-9d07-320cc8e87bde
**After**
https://github.com/user-attachments/assets/b5b301fd-5cb6-4ab2-85c2-f6f57b846962
TODO: Please test the loading skeleton is shown instead of the button while the extension data is fetched on the `Extensions` page
> [!NOTE]
> If you want to skip the page refresh, just change line `14` in `src/components/common/Extensions/ExtensionItem/hooks.ts` with
> ```
>  const { extensionData /* loading */ } = useExtensionData(extensionId);
>  const loading = …
```
> Fix: Buttons on the extensions page should show a loader whilst extension data is being fetched

- src/redux/sagas/actions/arbitraryTx.ts
- src/redux/sagas/motions/arbitraryTx.ts
- src/redux/sagas/utils/arbitraryTxs.ts
- src/utils/arbitraryTxs.ts
This PR fixes an issue with array encoding when creating arbitrary transactions. The cause of the issue was passing a string representation of an array (e.g. `"[]"`) instead of a "first-class" JS array.
It also improves the decoding of array arguments when showing a completed action.
To ensure thorough coverage, we'll deploy a test contract that has a function with nearly all possible argument types.
1. Ensure your dev env is fully running.
2. Create a new file called `TestContract.sol` in your CDapp root directory with the following contents:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
contract TestContract {
function testFunction(
uint256 uint256Arg,
uint256[] memory uint256ArrayArg,
uint256[][] memory uint256NestedArrayArg,
bool boolArg,
bool[] memory …
```
> [Arbitrary Txs] Fix array encoding issue

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FinalizePaymentModal/FinalizePaymentModal.tsx
This PR fixes an issue spotted by @rumzledz where users creating a motion to release a staked advanced payment would see the submit button stuck on Pending infinitely. This was because the UI would try to reclaim expenditure stake no matter the decision method used to release. In case of motions, this can only happen once the motion has been finalized, not at its creation.
1. Install and enable Voting Reputation extension.
2. Create an advanced payment using Staking decision method.
3. Advance the payment to the release step.
4. In the release payment modal, select Reputation decision method and submit.
The modal should close as soon as the motion to release gets created.
> Fix: Motion to release a staked payment gets stuck on pending

- src/redux/sagas/transactions/estimateGasCost.ts
- src/redux/sagas/utils/getGasPrices.ts
This issue came about after the introduction of #4123 which, while technically correct, runs into the a problem with Metamask, and more specifically Metamask's provider.
Even while running a manually set RPC endpoint which can be confirmed as supporting [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559)
Metamask will **block the `eth_maxPriorityFeePerGas` call**
While waiting to see if this ever gets resolved _(see this PR MetaMask/metamask-extension#29818 by our very own @area)_ we are accounting for it by setting it to zero (`0`).
This means that the transaction sender will not pay anything extra, besides the required gas fee, for their transaction to be mined.
This works great on Arbitrum, Arbitrum Sepolia since they make user of a Sequencer, however, on something like Mainnet this …
> Account for Metamask not supporting the `eth_maxPriorityFeePerGas` call

- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/components/common/Extensions/UserNavigation/partials/WalletConnectedTopMenu/WalletConnectedTopMenu.tsx
- src/components/v5/shared/UserDetails/UserDetails.tsx
- tailwind.config.js
This PR unifies the settings menu UI between mobile and tablet so that it is more consistent.
[Figma link](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-9053&t=D7AA2e4XkWQsCcqB-4)
Open the settings menu and confirm they are styled the same between mobile and tablet, and that it matches the figma design.
**Changes** 🏗
* Use `CaretRight` instead of `CaretDown` on mobile
* Swap a bunch of `sm` for `md` and `isMobile` for `isTablet`
Resolves #3454
> Fix: Unify settings menu between mobile and tablet

- src/components/v5/common/ActionSidebar/partials/NonVerifiedMembersSelect/hooks.ts
- src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/hooks.ts
- src/components/v5/common/ActionSidebar/utils.ts
This PR aims to solve multiple issues encountered with the member select dropdown:
- Same blockies shown for different user addresses
- Searching wrongly matches other addresses as well
These two issues were caused by the fact that on `prod` there were contributors in the list having the user set to `null`, thus the `walletAddress` and `value` for a member option were not set/set to an empty string. Given there was no avatar to be shown and the wallet address was not existing, the same blockie was displayed. Also, given the option `value` was empty, upon searching, given the React list `key` was set to an empty value, these items were not reliably unmounted.
The solution was to fallback to the `contributorAddress`
Regarding the other issues mentioned in #3164
- The members table …
> Fix: Manage verified members member selection dropdown issues

- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/utils.ts
- src/context/TotalInOutBalanceChartContext/TotalInOutBalanceChartContext.ts
- src/context/TotalInOutBalanceChartContext/TotalInOutBalanceChartContextProvider.tsx
- This PR aims to fix the `Total in and out` chart bars sorting.
The issue was caused by the fact that once the `GetDomainBalance` would retrieve the data, we would subtract from the `timeframe.key` the `Month` and then perform a sort based on this value. This would behave properly if the keys are within the same year, however, it would cause an incorrect sorting once a new year starts - issue that can be observed on `master`. To fix this, once the `GetDomainBalance` retrieves data we would map the items to the `BarChartDataItem` type, followed by a sort on the label (the `timeframe.key`) and only after mapping the label to the full date format `dd-MM-yyyy`. Then the `getMonthShortName` will be responsible to retrieve the short month label format (`Jan`, `Feb` etc.)
**On this branch** …
> Fix: Correctly sort timeframe bar chart items

- amplify/backend/api/colonycdapp/schema/proxyColonies.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- docker/colony-cdapp-dev-env-proxy-block-ingestor
- src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
- src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/ManageSupportedChainsDescription.tsx
- src/components/v5/common/ActionSidebar/partials/ChainSelect/hooks.ts
- src/components/v5/common/CompletedAction/partials/ManageSupportedChain/ManageSupportedChain.tsx
- src/constants/index.ts
- src/constants/proxyColonies.ts
- src/graphql/fragments/proxyColonies.graphql
- src/graphql/generated.ts
- src/graphql/queries/proxyColonies.graphql
- src/utils/proxyColonies.ts
This PR introduces lookup of supported proxy chains from the database.
We still need to keep them in a local config, due to all the titles and lookups.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/319)
1. Run your dev env and check that we got supported chains in the database by running the following query
```
listSupportedChains {
items {
id
isActive
}
}
}
```
2. Run the create-data script and go to `planex`. Try to create a `Manage supported chains` action and verify that you only get "Local proxy chain 1" and "Local proxy chain 2" in the dropdown.
> [!IMPORTANT]
> Unfortunately when stopping a docker container the `SIGTERM` event doesn't get properly propagated to the child process which in our case would be the process started with `pnpm …
> [Proxy colonies M1] Feat: Fetch available chains from DB and update SUPPORTED_CHAINS config

- src/components/common/ColonyActionsTable/hooks/useGetMenuProps.tsx
- src/components/frame/Extensions/layouts/ColonyLayout.tsx
- src/context/ActionSidebarContext/ActionSidebarContextProvider.tsx
- src/hooks/useLocationKeyChange.ts
Fix: Open empty action sidebar on back navigation
- The original issue stated the `Redo action` opens an empty action sidebar, even though this is no longer reproducible.
https://github.com/user-attachments/assets/10c051d0-35dd-4a05-9811-217f5f345ec2
- However there was an issue when opening a completed action, followed by the action sidebar back button and then using the browser back button a couple of time that would trigger the empty action sidebar being shown.
https://github.com/user-attachments/assets/42a3dac9-2982-47fd-a3e3-37950deecb5b
This was mainly caused by the fact that on back navigation, if the action sidebar was opened, we didn't react to the absence of a `txHash` and `actionType`. So my solution involved listening to location key changes (the `key` should update once the …
> Fix: Open empty action sidebar on back navigation

- scripts/create-data.js
<p align="center">
</p>
In #4150, I saw @mmioana had experienced one of my most hated things while trying to run the `create-data` script: _an intermittent error_
so I went hunting and think I've arrived at a simple fix. 
Currently, when the script is run:
* Colonies get between 1 and 100 million of a token
* Domains get between 100 and 500 of a token
So far, so good.
Individual users are then paid out from each domain by calling [`userPayments`](https://github.com/JoinColony/colonyCDapp/blob/0f0e20ee01635902183852292d09e85d0dac5616/scripts/create-data.js#L1626) with the three `walletUsers` (which are the first three ganache accounts) and a random contributor address.
Users are paid out a random amount between [1 and 3 tokens](https://github.com/JoinColony/colonyCDapp/blob/0f0e20ee01635902 …
> Fix (?) intermittent error in create-data script

- playwright.config.ts
- playwright/e2e/manage-account-advanced-settings.spec.ts
- playwright/e2e/manage-account-avatar.spec.ts
- playwright/e2e/manage-account-preferences.spec.ts
- playwright/e2e/manage-account-profile.spec.ts
- playwright/e2e/split-payment.spec.ts
- playwright/models/simple-payment.ts
- playwright/models/split-payment.ts
- playwright/utils/common.ts
- src/components/shared/Preloaders/SpinnerLoader.tsx
Initiatal set of E2E tests for the Split Payment motion. Also, I updated some selectors related to the `selectWallet` test helper to fix tests that began failing after the homepage redesign. 
Test cases included in the PR:
- Happy path of Split payment (Permissions/Staking method of create motion, Equal/Unequal distribution, Permissions release method)
- Form fields validation
- Recipients table actions: Add/Remove/Duplicate a row
- Redo a payment
**Step 1**. Spin up the dev env and seed the test data 
`npm run dev`  followed by `node scripts/create-data.js`
**Step 2**. Build and start the frontend in preview mode
`npm run preview` 
**Step 3.** Run the tests in a separate terminal 
`npm run e2e split-payment`
**Step 4**. The tests should pass ( if any failures - please send me .zip files …
> test: split payment e2e tests

- amplify/backend/api/colonycdapp/schema/proxyColonies.graphql
- amplify/backend/api/colonycdapp/schema/schema.graphql
- scripts/deploy-token-to-chain.js
- scripts/mint-tokens-on-chain.js
- scripts/unlock-mint-tokens-on-chain.js
- scripts/utils/unlockMintTokens.js
- src/redux/sagas/proxyColonies/createProxyColony.ts
- This PR addresses the fact that once a proxy colony gets deployed, on the `DEV` env we'll need to deploy the associated native token on the respective chain in order to have some data to work with. 
- Also this PR adds a script for supporting unlocking and minting tokens
Thank you @iamsamgibbs and @bassgeta for all the help
TODO: Let's test the colony native token gets deployed on a new chain and we actually store that information.
* Step 1. Go to http://localhost:9091/planex
* Step 2. Create a `Manage supported chains` action/motion for chain `Local Proxy Chain 1`
* Step 3. Close the action sidebar and copy the colony address.
* Step 4. Once the action is completed, please run `node scripts/deploy-token-to-chain.js`
Please use the following values for the input
foreignChainId …
> Feat: Add script for deploying colony native token on chain

- src/components/v5/common/ActionSidebar/partials/VerifiedMembersSelect/VerifiedMembersSelect.tsx
- src/components/v5/shared/SearchSelect/partials/CheckboxSearchItem/CheckboxSearchItem.tsx
- src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
- src/components/v5/shared/SearchSelect/partials/SearchItemLabelText/index.tsx
Just a good ol' combination of text and address truncation.
> [!IMPORTANT]
> ### 1. Update amy's username
> 1. Open the `UserAccountPage/hooks.tsx` file and update line 31 to:
> ```js
> return { canChangeUsername: true, daysTillUsernameChange };
> ```
> 2. Connect amy's wallet
> 3. Visit your profile page: http://localhost:9091/account/profile
> 4. Update your username to: 
> ```js
> QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
> ```
> ### 2. Add a wallet address to the list of recippients
> 1. Visit the Wayne colony: http://localhost:9091/wayne
> 2. Copy its address
> 3. Visit the Planex colony: http://localhost:9091/planex
> 4. Bring up the Manage verified members form
> 5. Add Wayne's address and submit the form
1. Bring up the Simple payment form
2. Bring up the recipients list popover
3. Verify …
> Fix: Truncate Search Item label text

- src/redux/sagas/motions/claimMotionRewards.ts
Thanks to @jakubcolony for helping me with the painful debugging process... which turned out to require a very straightforward fix 😅 
We had this logic in the saga that incorrectly prevents you from claiming your stakes. A little tweak was needed in order to allow all stakers to reclaim their tokens.
1. Install the Reputation extension
2. As leela, create a Simple Payment motion using the Reputation decision method
3. As leela, during the Staking phase, Oppose and fully stake it
4. Copy the URL
5. Open an incognito window and connect amy's wallet
6. As amy, visit the URL you just copied
7. As amy, Support and fully stake it
8. Go back to leela's window
9. Reload the page
10. During the Voting phase, submit a Support vote
11. Reveal your vote
12. Finalise the motion
13. Reclaim your stakes …
> Fix: Ensure you can reclaim your stakes even if you staked the losing side

- src/components/v5/shared/CardWithCallout/CardWithCallout.tsx
- src/routes/Routes.tsx
- This is a small fix to remove console error about react keys and div inside p.
Step 1. Open http://localhost:9091/planex
Step 2. Open dev tools and check that there is no error regading keys
Step 3. Disconnect wallet
Step 4. Verify that there is no error regarding div inside p at page http://localhost:9091/go/planex
> fix: add keys to avoid console keys error

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/components/v5/common/ActionSidebar/ActionSidebar.tsx
- src/components/v5/common/ActionSidebar/partials/TokenSelect/partials/TokenSearchSelect/TokenSearchSelect.tsx
- src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/BarChartLoadingLayers.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/components/v5/shared/Navigation/ColonySwitcher/partials/MobileJoinedColonies/MobileJoinedColonies.tsx
- src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/colonyPageSidebar.styles.ts
- src/components/v5/shared/SearchSelect/SearchSelect.tsx
- src/components/v5/shared/UserInfoPopover/partials/DomainPermissionList/DomainPermissionList.tsx
- src/components/v5/shared/UserInfoPopover/partials/UserInfo.tsx
- tailwind.config.js
Basically 100vh is problematic on browsers like Safari mobile due to the presence of the address bar. 100vh ignores Safari mobile's URL bar whereas 100dvh takes that into account and removes its height from the overall screen estate calculation, which is suitable for our use case:
> [!NOTE]
> The best way to test this is with the iOS simulator
1. Go to the Colony dashboard
2. Verify that the children for these components are fully visible
- Colony Switcher
- Colony Action sidebar
- User Hub
- User Menu
- Action form
Resolves #3352
> Fix: Ensure contents are not clipped on mobile browsers

- playwright/e2e/manage-account-avatar.spec.ts
- src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenInputs.tsx
- src/components/frame/v5/pages/UserProfilePage/partials/consts.ts
- src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/ColonyDetailsFields.tsx
- src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/partials/ColonyAvatarField/hooks.ts
- src/components/v5/common/AvatarUploader/hooks.ts
- src/components/v5/common/AvatarUploader/partials/ErrorContent.tsx
- src/components/v5/common/AvatarUploader/partials/FileUpload.tsx
- src/components/v5/common/AvatarUploader/types.ts
- src/components/v5/common/AvatarUploader/utils.ts
- src/hooks/useDropzoneWithFileReader.ts
- src/stories/common/FileUpload.stories.tsx
As discussed with Product, files being uploaded should have a dimension of at least 120x120px.
**Pika**
1. Generate a create colony URL: node scripts/create-colony-url.js
2. On the token creation page, upload Pikachu
3. Verify that:
- the error message says: "Image dimensions should be at least 120x120px"
- you hear an audio clip of an angry Pikachu (of course I'm kidding, don't request changes because of this)
4. Visit the Planex colony: http://localhost:9091/planex/
5. Bring up the Edit colony details form
6. Upload Pikachu as the Colony logo
7. Verify that the error message says: "Image dimensions should be at least 120x120px"
Resolves #3858
> Fix: Ensure minimum dimension of 120x120px for file uploads

- src/components/frame/v5/pages/AgreementsPage/AgreementsPage.tsx
- src/components/v5/common/ActionSidebar/consts.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/hooks.ts
- src/components/v5/common/ActionSidebar/partials/SaveDraftButton/SaveDraftButton.tsx
- This PR addresses the fact that the draft agreement is not always showing up upon saving due to being fetched on the `Agreements` page directly from local storage. However, given the component might not re-render, the draft agreement wouldn't always be rendered. The solution was to make use of `Redux` store which already saves this value and re-populates the store with the values persisted in the local storage on page refresh.
- Also there was a validation error regarding the missing reputation when creating a new colony. Given the `Save draft` is of `type=button` and not `type=submit`, the error message was not showing up, but neither was the draft saved. In this case, the solution was to check if among the form errors there is only the `isMissingReputation`, in which case the draft …
> Fix: Display persisted draft agreement

- src/components/frame/v5/pages/FundsPage/partials/FundsTable/FundsTable.tsx
- src/components/v5/common/ActionSidebar/partials/SaveDraftButton/SaveDraftButton.tsx
- src/components/v5/shared/Filter/FilterButton.tsx
This PR resolves an issue where the "save draft" button and "filters" button had too much big of a gap between the icon and the text.
Check all instances of the filters buttons.
Check the filter button on the incoming funds page reads "All filters".
Check the "Save draft" button for creating agreements has the correct spacing.
**Changes** 🏗
* Updated filter text to "All filters"
* Removed additional padding around save draft and filter button icons.
Resolves #3351
> Fix: Button with icon bug

- docker/colony-cdapp-dev-env-block-ingestor
- src/context/Notifications/NotificationsDataContext/NotificationsDataContextProvider.tsx
- Since this is really a block ingestor change, the description is here: https://github.com/JoinColony/block-ingestor/pull/320
* ⚠️  You'll need to restart your dev environment and make sure you run `npm run dev --notifications` to enable notifications locally.
* Once it's up and running, stop the block ingestor in docker. Open `.env` of the CDapp and copy the auto generated MAGICBELL_DEV_KEY, and add it to the `.env` of your block ingestor. Now run the block ingestor locally with `npm run dev`.
* Now you need a way to trigger more than 60 notifications inside a minute. The easiest way is probably to open `src/handlers/actions/mintTokens.ts` in the block ingestor, and go to line 35 where it calls `sendPermissionsActionNotifications`. Just add a for loop around this call to fire it like 80 …
> Add rate limited notifications queue

- amplify/backend/api/colonycdapp/schema/schema.graphql
- docker/colony-cdapp-dev-env-block-ingestor
- docker/colony-cdapp-dev-env-proxy-block-ingestor
- src/graphql/generated.ts
This PR changes how our multiChainInfo works. It's now a new entity so we can modify it from anywhere, and it has 2 flags for cross-chain completion, so it's more granular too!
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/323)
Let's make sure all of our deploy proxy colony actions still work :crossed_fingers: 
Queries we'll be using
**Get permissions action**
```
getColonyAction(
id: "<YOUR_TX_HASH>"
) {
multiChainInfo {
completedOnMainChain
completedOnProxyChain
id
wormholeInfo {
emitterAddress
emitterChainId
sequence
}
}
type
id
}
```
**List proxy colonies**
```
listProxyColonies(
filter: {colonyAddress: {eq: "<YOUR_COLONY_ADDRESS>"}}
) {
items {
chainId
colonyAddress
id
isActive
}
}
```
**List multichain info(s)**
```
listMultiChainInfos {
items { …
```
> [Proxy colonies M1] feat: handle cases where the main chain ingestor is slower than the proxy one

- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/utils.ts
- Change the way the total percentage is being calculated to not do any rounding until the final step, increasing accuracy.
- This also fixes a bug where switching from distribution type `equal` (which will always be 100%) to unequal suddenly makes the percentage not 100%.
* Step 1. Make a split payment using equal as the distribution type. Have an awkward number of recipients compared to the total amount so that the percentages have a number of decimals.
* Step 2. Change the distribution type to unequal. The total percentage should still say 100%, and you should be able to submit the form.
* Step 3. Play around with different amounts / recipients with an uneven distribution type. The percentage should always be correct.
**Changes** 🏗
* Change the way the total percentage is calculated …
> Fix: changing distribution type should show accurate percentage

- src/hooks/useToggle/index.ts
- Change the useToggle hook to only toggle modals on a left click.
- This comes from this bug: https://github.com/JoinColony/colonyCDapp/issues/3888 where right clicking on a dropdown menu item _inside_ a modal was accidentally closing the modal (since the useToggle hook didn't recognise the menu item as a descendant of the modal) and it was causing all kinds of weird behaviours.
- I've checked this change in toggle behaviour with design and received approval
* Start an advanced payment and proceed to the Funding step.
* In the Fund Payment modal, open the decision method dropdown.
* Right-click on the 'Permissions' option inside the Select component within the funding modal. It should _not_ close the modal. 
* Try right clicking outside the modal - it should also not close the modal. A …
> Fix: modal toggle should only happen on left click

- docker/colony-cdapp-dev-env-auth-proxy
- docker/colony-cdapp-dev-env-block-ingestor
- src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/utils.ts
- src/components/v5/common/CompletedAction/partials/CompletedExpenditureContent/CompletedExpenditureContent.tsx
- src/graphql/generated.ts
- src/graphql/mutations/actions.graphql
- src/redux/sagas/expenditures/createExpenditure.ts
- So this was a bit of a tricky bug (original ticket: https://github.com/JoinColony/colonyCDapp/issues/4033) which is basically caused by the action being created and put in the actions list a little prematurely. If a user cancels the final transaction in metamask, or if the final transaction just fails, then the action is not properly created and gets into a weird state where it is technically created but shouldn't really be seen by the user or show in the lists.
- This PR aims to fix this by not setting showInActionsList by default to true for createExpenditure actions. The saga will instead set it to true once it has finished all of the necessary transactions. There's also a couple of very small cleanup things tacked on.
There's also a couple of changes in PRs in other repos so please …
> Fix: Dont show failed expenditures in actions list

- docker/colony-cdapp-dev-env-block-ingestor
[See block-ingestor PR](https://github.com/JoinColony/block-ingestor/pull/328)
This PR makes a change to how the `creator` name is set for extension related actions.
Previously the block-ingestor used `receipt.from` as the creator for all extension related actions as the extension event does not emit the msg_sender. This works fine when metatransactions are disabled, but when they are enabled the metatransaction address in place of the original creator.
This PR adds a new `getTransactionSignerAddress` function to the block-ingestor (courtesy of @bassgeta 's implementation on the proxy colony PRs!) and replaces uses of `receipt.from` to get the address of the user who actually installed the extension.
This means the correct user now shows in both notifications and the extension details.
> …
> Fix: Extension notifications should show the username when using metatransactions

- src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/FileUploadModal/hooks.ts
The oneliner fix for Advanced Payment validation. When you upload CSV with an empty recipient address, our app sets a default address, and we can submit a form with default address. We want to show an error in case if recipient field is empty in CSV file. 
Step 1. Download CSV: 
[expenditures_batch.14.csv](https://github.com/user-attachments/files/18619285/expenditures_batch.14.csv)
Step 2. Open Advanced Payments
Step 3. Upload file
Step 4. Submit form and verify that you can see an error "Recipient is required"
Resolves #3964
> fix: remove default recipient address for correct advanced payments validation

- src/components/frame/v5/pages/FundsPage/partials/FundsTable/FundsTable.tsx
This PR fixes a bug with the "Accept all funds" button where it would stay enabled even after claiming all funds.
This was caused by checking if the length of the unclaimed array is longer than 0, however we always insert an unclaimed native token chain claim so that the token appears on the page. The fix is to also filter claims with a balance of 0.
Note: The original issue also shows an issue with claims not working at all on QA. I've not been able to recreate this at all locally.
On a fresh dev environment, navigate to the incoming funds page. (If not on a fresh environment just send some tokens to the colony).
Accept all available funds and after the transactions process the button should disappear.
**Changes** 🏗
* Unclaimed funds with a balance of 0 are now filtered out.
Resolves …
> Fix: Hide accept all funds button after claiming funds

- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/StagedPaymentStep.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneReleaseModal/MilestoneReleaseModal.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneReleaseModal/types.ts
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/StagedPaymentTable.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/partials/ReleaseAllButton/ReleaseAllButton.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/partials/ReleaseButton/ReleaseButton.tsx
- src/context/PaymentBuilderContext/PaymentBuilderContext.ts
- src/context/PaymentBuilderContext/PaymentBuilderContextProvider.tsx
- src/context/StagedPaymentContext/StagedPaymentContext.ts
- src/context/StagedPaymentContext/StagedPaymentContextProvider.tsx
- src/context/StagedPaymentContext/types.ts
- src/context/StagedPaymentContext/utils.ts
- src/routes/ColonyRoute.tsx
- This PR addresses an issue in the `Staged payment` action where the `Pay now` and `Pay all` buttons remained enabled until payments were successfully claimed in case of actions. 
To resolve this, I introduced a context dedicated specifically for the `Staged payments` (and refactored everything related to this type of action that was unnecessarily polluting the `PaymentBuilderContext`). The context stores the current milestones for release, all the milestones awaiting release, and a flag for the pending release. Based on the last two props, we can easily decide the `enabled`/`disabled` state of the buttons, the first prop being used only for the release modal and the saga. In case of using motions to release a payment, once the motion got created, the button will be re-enabled in order …
> Fix: Disable payment buttons for staged payments when release is in progress

- src/redux/sagas/proxyColonies/createProxyColony.ts
This PR gets the Pending button unstuck on create proxy colony actions. I also checked other actions and could not recreate the issue.
Nice and straightforward to test. Create a "Manage Supported Chains" action and add "Proxy Chain 1" as a supported chain. Check the "Pending" button in the header does not get stuck at any point.
https://github.com/user-attachments/assets/a31d3489-e7ab-45aa-a93d-83b528f71f18
**Changes** 🏗
* `createProxyColony` saga now yields puts
Resolves #4232
> [Proxy Colonies] Fix: Pending Button gets stuck on createProxy action

- src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/partials/SplitPaymentRecipientsField/hooks.tsx
- src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/AmountField/AmountField.tsx
- src/components/v5/common/CompletedAction/partials/rows/Amount.tsx
- Fix an issue with the app crashing when the split payment type is too small.
- Took a while to figure out the actual root cause of this, since the crash was caused by an invalid input to BigNumber, but I had to actually trace it back about 6 steps to find out why it was ending up in that format.
- Long story short, when the user changes the percentage of a payout in a split payment, there is a function run to calculate the amount. When this amount is set, we need to use the `toFixed` instead of `toString` method from `decimal.js`, because otherwise when the amount is small it will be in scientific notation, which down the line (after trying to move the decimal point and convert to wei and then pass to BigNumber) causes the crash 😥 
- Small side note: I also fixed some awkward padding / …
> Fix: App crashes when split payment total is small

- playwright.config.ts
- playwright/e2e/simple-payment.spec.ts
- playwright/e2e/staged-payment.spec.ts
- playwright/models/extensions.ts
- playwright/models/staged-payment.ts
- playwright/setup/index.ts
- playwright/utils/common.ts
This MR adds some initial e2e test suit for the Staged Payment motion. 
Test cases included in the PR:
1. Staged payment with
- Permission decision method
- Staking decision method
- Reputation decision method
2. Form validation 
3. Milestones table interactions (duplicate/delete entries)
**Step 1**. Spin up the dev env and seed the test data 
`npm run dev`  followed by `node scripts/create-data.js --yes`
**Step 2**. Build and start the frontend in preview mode
`npm run preview` 
**Step 3.** Run the tests in a separate terminal 
`npm run e2e staged-payment`
**Step 4**. The tests should pass ( if any failures - please send me .zip files from `/playwright-report/data` directory)
> test: staged payment e2e tests

- src/components/v5/common/ActionSidebar/partials/Motions/MotionStep/StakingStep/StakingStep.tsx
This PR just cleans up the booleans a bit and makes sure that when a motion is completed, the errors don't show up.
1. Run your dev env and the create-data script, install the voting reputation extension in planex
2. Open up 2 more browsers (trust me, it's gonna be the fastest). 
3. Be logged in as `leela` in browser 1. In browser 2, go to `http://localhost:9091/go/planex` with `Dev wallet 4`. Name the user "has-nothing" or something
4. In browser 2, go to `http://localhost:9091/go/planex` with `Dev wallet 5`. Name the user "has-no-coins"
5. Run the following query and copy the invite code.
```
getColony(id: "<planex_address>") {
colonyMemberInviteCode
}
}
```
6. Open up the URL `http://localhost:9091/invite/planex/<that_code>` as `has-nothing` and `has-no-coins` and join …
> fix: dont show staking errors if the motion is completed

- src/components/v5/common/ActionSidebar/partials/UserSelect/hooks.ts
This PR fixes an issue where blockies were not being properly generated for colony members who no longer had user accounts.
* Step 1 - We need to delete some user accounts to replicate the production scenario. Go to [http://localhost:9091/planex/members/followers](http://localhost:9091/planex/members/followers).
* Step 2 - Ignore our dev wallet pals, but copy the wallet address of the first non-dev wallet follower.
* Step 3 - Run the following mutation in graphiql to delete the user.
```
deleteUser(input: {id: "<USER_ADDRESS>"}) {
id
}
}
```
* Step 4 - Repeat for the first few users.
* Step 5 - Refresh and create a simple payment action.
* Step 6 - Open the recipient list, each user should have a unique blockie.
Compared to master:
**Changes** 🏗
* Fallback to …
> Fix: Use contributorAddress when no user wallet address found

- src/components/v5/common/Fields/InputBase/InputBase.tsx
This PR removes the max length restriction from the input in the `InputBase` component. The component should instead show `currentLength / maxLength` in the UI next to the input and not restrict the max length on the input itself. The form validation still restricts submitting a name which exceeds the max length.
I could not find any other places where this component is consumed that uses the maxLength property so do not believe it breaks anything elsewhere, but please do check.
Create an "Edit team" or "Create team" action and enter a team name that exceeds the 20 character limit. You should be able to keep typing past the character limit and the `currentLength / maxLength` UI should display.
* Removed the max length restriction from the input in the `InputBase` …
> Fix: Team name max length should not be enforced on input

- src/components/v5/common/CompletedAction/CompletedAction.tsx
This PR resolves an issue where the motion timeline was stuck at the top of the page on mobile making it difficult to see the motion details.
* Step 1 - Install the reputation extension
* Step 2 - Create any motion
* Step 3 - Switch to a mobile width and scroll! The motion timeline should scroll letting you fully view the details.
**Changes** 🏗
* `CompletedAction` is height fit-content
Resolves #3878
> Fix: CompletedAction should be height fit content on mobile

- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/AddTransactionModal/AddTransactionForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/AddTransactionModal/ContractAddressInput.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/AddTransactionModal/translation.ts
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/AddTransactionModal/useGenerateABI.ts
The Target Address input won't be an error, because there is nothing wrong with the input content. But we'll show the orange 'Alert' box above it to warn the user.
Figma: https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=29345-217753&t=4Px73UQMsihEvSqf-4
Step 1. Open Custom transaction action ("Manage Colony" -> "Custom transactions")
Step 2. Add transaction and insert a Contract address `0xeF841fe1611ce41bFCf0265097EFaf50486F5111`
Step 3. Verify that Warning is shown according to the figma design https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=29345-217753&t=4Px73UQMsihEvSqf-4
Step 4. Insert Verified Contract address `0xeeeafa86903cf2cb5c74a61d3e67844e226730c0 `
Step 5. Verify that Warning disappear and ABI is loaded …
> Arbitrary txs: show warning instead of error if contract address is not verified

- playwright/models/advanced-payment.ts
- playwright/models/simple-payment.ts
- playwright/models/split-payment.ts
- playwright/models/staged-payment.ts
- src/components/v5/common/ActionSidebar/consts.ts
- src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
- src/components/v5/common/Fields/TextareaBase/TextareaBase.tsx
- src/i18n/en.json
The counter wasn't even absolutely positioned to the parent div :(
I've taken creative liberty here to include the counter outside of the textarea so we don't get overlapping elements (much like it's already done in other parts of the app).
[Figma link](https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Actions-%26-Motions?node-id=2729-248940&t=ZWLElrFeEJsftbZZ-0)
1. Try to create a `Create new team` action. Input something long for the name, purpose and the action title
2. Verify that all the textarea fields have the max counter below them to the right 
**Changes** 🏗
* Renamed the i18n string to just `errors.text.maxLength`
* The counter is now absolutely positioned relative to its parent div
Resolves  #4014
> fix: show max length counter on action title

- src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
Well turns out that all the places where we use `UserSelect` it's applicable to show empty content if user was not found :shrug: 
Basically test out that the user select works as it should in all possible payment actions!
**Changes** 🏗
* `UserSelect` now by default shows empty content if the user was not found
Resolves #3738
> fix: UserSelect now shows empty content when no user was found

- src/components/v5/common/ActionSidebar/partials/Description/Description.tsx
- src/components/v5/common/CompletedAction/partials/rows/Description.tsx
It's only fitting that I remove it after I've mistakenly added it back in.
1. Start creating any action, verify that on hover, the description row doesn't have a tooltip (can't see my cursor here :') )
2. Create the action and verify that the tooltip doesn't appear on the completed action view
**Changes** 🏗
* Removed the tooltip from the form row and completed action row
Resolves #4104
> fix: remove the description form row tooltip

- src/utils/tokens.ts
This PR fixes an issue where token balances were failing to load in the amount field.
* Step 1 - Create any action with an amount field (simple payment)
* Step 2 - Check the tokens have the expected balances
**Changes** 🏗
* Check domainId is not `''`
> Fix: Token balances not showing in amount field

- src/components/common/Extensions/UserHub/UserHub.tsx
- src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
- src/components/frame/Extensions/layouts/LandingPageLayout.tsx
- src/components/v5/common/DropdownMenu/DropdownMenu.tsx
- src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/ColonyLinks/useHeaderLinks.ts
- src/components/v5/frame/ColonyHome/partials/ReputationChart/ReputationChart.tsx
- src/components/v5/frame/PageLayout/PageLayout.tsx
- src/components/v5/shared/Dropdown/DropdownMenu.tsx
- src/components/v5/shared/PopoverBase/PopoverBase.tsx
- src/components/v5/shared/PopoverBase/types.ts
- src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/DesktopTeamFilter.tsx
- src/components/v5/shared/TeamFilter/partials/TeamsDropdown/TeamsDropdown.tsx
- src/hooks/useHeightResizeObserver.ts
- src/hooks/usePopperCustomPositioning.ts
- This PR aims to fix the popper dropdown menus present on the dashboard that were overflowing over the page navigation header when scrolling on `mobile`. The same issue was present also for the team filter dots menu on `tablet`. However I did not manage to reproduce the other layout breaking mentioned in the original issue.
- While solving this, I encountered some issues with the user navigation which on `desktop` was occupying the whole screen height due to `!h-dynamic-screen` overridding the `md:h-auto`. Also, on the landing page, once opening the user navigation, the page header was no longer visible due to having 2 instances of the `PageHeader`, their visibility being manipulated through `css` classes. This wouldn't have been a problem, if the `PageHeader` wouldn't have set a css …
> [Dashboard] Fix: Broken dashboard layout on mobile 

- src/components/v5/common/ActionSidebar/hooks/useGetStreamingPaymentData.ts
Fix displaying status for advanced payments
- Go to `feat/streaming-payments-ui` branch
- Create advanced payment
- Display the advanced payment in activity feed
Status badge is displaying correctly
Resolves https://github.com/JoinColony/colonyCDapp/issues/4210
> fix: advanced payment status

- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/ArbitraryTxsForm.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/ArbitraryTransactionsTable/ArbitraryTransactionsTable.tsx
- src/components/v5/common/ActionSidebar/partials/forms/ArbitraryTxsForm/partials/ArbitraryTransactionsTable/hooks.tsx
- src/components/v5/common/ActionSidebar/partials/hooks.ts
- src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
For any colony version older than v17, the following error callout should show when "Custom transaction" action is selected:
"Custom transactions requires Colony Network version 17 or higher."
It should also include a link to the Upgrade colony action with the link text "Upgrade colony".
Step 1. Open `src/components/v5/common/ActionSidebar/partials/hooks.ts` and update line 116 to 18 version. 
Step 2. Open "Custom transactions"
Step 3. Verify that form is disabled and you can see an error
Step 4. Verify that 'Upgrade colony' button redirect to 'Upgrade colony' action 
Step 5. Open `src/components/v5/common/ActionSidebar/partials/hooks.ts` and update line 116 to 17 version. 
Step 6. Verify that the form is enabled again
Resolves #4261
> feat: disable custom transactions for colony version less then 17 and show an error
