JoinColony/colonyCDapp

src/components/common/ColonyHome/ColonyMembersWidget/ColonyMembersWidget.css
src/components/common/ColonyHome/ColonyMembersWidget/MembersSubsection.tsx
src/components/shared/Button/Button.css
src/components/shared/Button/Button.css.d.ts
src/components/shared/Button/Button.tsx
src/components/shared/Button/InviteLinkButton.css
src/components/shared/Button/InviteLinkButton.css.d.ts
src/components/shared/Button/InviteLinkButton.tsx
src/components/shared/Button/index.ts
src/components/shared/ClickableHeading/ClickableHeading.css
src/components/shared/ClickableHeading/ClickableHeading.css.d.ts
src/components/shared/ClickableHeading/ClickableHeading.tsx
src/components/shared/ClickableHeading/index.ts
src/hooks/useAvatarDisplayCounter.ts

This is an attempt to clean up the colony home members/watchers aside and other related components.
* Ported `InviteLinkButton` component
* Ported `ClickableHeading` component
Resolves #38

Refactor colony home members/watchers aside

---

src/components/frame/RouteLayouts/Default/Default.css
src/components/shared/ColonyAvatar/ColonyAvatar.tsx

It seems like most of the work described in the issue has already been done by Raul, I just cleaned up the typings and imports and applied a fix from [colonyDapp#3830](https://github.com/JoinColony/colonyDapp/pull/3830). That is unless I missed something 🙂
Resolves #64

Clean up `ColonyAvatar`

---

src/components/common/CreateColonyWizard/StepColonyNameValidation.ts
src/components/common/CreateColonyWizard/TokenSelector.tsx
src/graphql/generated.ts
src/graphql/mutations/colony.graphql
src/graphql/mutations/token.graphql
src/graphql/queries/token.graphql
src/redux/sagas/colony/colonyCreate.ts

I merged my PR #90 without realising it breaks some of @willm30's colony creation changes, this PR fixes those.
**Changes** 🏗
* Colony creation wizard now uses new codegen hooks

Fix GraphQL codegen issues

---

src/components/common/ColonyActions/ColonyActions.tsx
src/components/common/ColonyActions/index.ts
src/components/common/ColonyHome/ColonyHome.tsx
src/redux/sagas/actions/index.ts
src/redux/sagas/actions/mintTokens.ts
src/redux/sagas/setupUserContext.ts

This PR cleans up/refactors Mint Tokens saga. There's still some missing bits (annotations, fetching balance, redirection) that will be added in future PRs.
To test, you have to create a colony using the CDapp's create colony flow. If you try to use one of the colonies created by `temp-create-data`, the action will fail. 
There's a test button in Colony Home that should trigger the mint tokens action. The action should complete successfully:
Resolves #202

Port mint tokens action saga

---

src/components/common/Members/Members.tsx
src/components/common/Members/MembersTitle.css
src/components/common/Members/MembersTitle.tsx
src/components/common/Members/filterMembers.ts

Port search bar functionality
Adds filterMembers function
Adds filtering based on search text to `Members`
Resolves #181

Port Member's search functionality

---

src/components/common/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
src/components/common/ColonyHome/ColonyDomainSelector/CreateDomainButton.tsx
src/components/common/Dialogs/CreateDomainDialog/CreateDomainDialog.tsx

[ebda8e2e-da32-4e8e-a717-fa414fa72002.webm](https://user-images.githubusercontent.com/18473896/227390916-03d8c7e3-4a59-4126-9026-d35948b947a3.webm)
Resolves #187

Wire up buttons of ColonyDomainSelector with domain dialogs

---

src/components/frame/AvatarDropdown/AvatarDropdown.tsx
src/components/frame/AvatarDropdown/AvatarDropdownPopoverMobile.tsx
src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx

Thanks to Will for spotting this, the avatar should be back in place on landing page:
Resolves #351

Fix missing user avatar on landing page

---

src/components/common/Extensions/ExtensionStatusBadge-new/ExtensionStatusBadge.tsx
src/components/common/Extensions/UserPermissionsBadge/UserPermissionsBadge.tsx
src/stories/common/ExtensionStatusBadge.stories.ts

lint project

---

docker/colony-cdapp-dev-env-block-ingestor
src/components/common/ColonyActions/ColonyActions.tsx
src/redux/sagas/motions/index.ts
src/redux/sagas/motions/paymentMotion.ts
src/redux/types/actions/motion.ts
src/utils/colonyActions.ts

This PR wires in the payment motion saga.
Install voting rep. Give yourself some rep. Click the "Test Create Payment" button. You will need to add the correct permissions to your voting rep extn:
```
c.setFundingRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<voting-rep-extn-address>', 1, true)
c.setAdministrationRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<voting-rep-extn-address>', 1, true)
```
Should be directed to the payment motion page: 
**Changes** 🏗
* Wire in saga
* Modify details widget
Resolves #427

Wire payment motion saga

---

docker/colony-cdapp-dev-env-block-ingestor
src/components/common/ColonyActions/ColonyActions.tsx
src/redux/sagas/motions/index.ts
src/redux/sagas/motions/moveFundsMotion.ts
src/redux/types/actions/motion.ts
src/utils/colonyActions.ts

This PR wires in the MoveFundsMotion saga.
1. Install voting rep
2. Give yourself rep
3. Click "Test Create Domain", then "Test Move Funds"
Your user will need architecture:
```
c.setArchitectureRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<user-address>', 1, true)
```
And the voting rep extn will need funding:
```
c.setFundingRole(1, "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", '<voting-rep>', 1, true)
```
**Changes** 🏗
* Wire in the move funds motion saga
Resolves #431

Wire MoveFundsMotion saga

---

src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx

fix banner height

---

src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx

fix: 15420186 banner color

---

scripts/temp-create-data.js

Following the most recent `colony-js` update in the CDapp, the script got broken. This PR fixes the imports that caused it to fail.
To test, start the dev env and run the script.
Thanks to @chmanie for his assistance.
Resolves #463

Fix `temp-create-data` script

---

src/components/shared/Extensions/Tabs/Tabs.tsx

added ignore to invalid typed prop in react-tabs-scrollable

---

src/components/common/Extensions/UserPermissionsBadge/UserPermissionsBadge.tsx
src/components/common/Extensions/UserPermissionsBadge/types.ts
src/components/shared/Extensions/Tooltip/Tooltip.tsx
src/stories/common/UserPermissionsBadge.stories.ts
src/stories/shared/Tooltip.stories.tsx

added auto placement to tooltip

---

src/components/common/Extensions/SupportingDocuments/SupportingDocuments.tsx

fix/15399699: fix font size

---

src/redux/sagas/actions/createDomain.ts
src/redux/sagas/actions/editColony.ts
src/redux/sagas/actions/editDomain.ts
src/redux/sagas/actions/manageReputation.ts
src/redux/sagas/actions/mintTokens.ts
src/redux/sagas/actions/moveFunds.ts
src/redux/sagas/actions/payment.ts
src/redux/sagas/actions/unlockToken.ts
src/redux/sagas/actions/versionUpgrade.ts

This PR ensures that the action sagas are redirected correctly to the ActionDetailsPage.
Fire some actions via the UAC. You should be redirected to the ActionDetailsPage.
**Changes** 🏗
* Add `isRedirect` over navigation state
Resolves #411

Fix action saga redirect

---

.github/workflows/amplify-push-backend.yaml

add amplify push backend workflow
**Changes** 🏗

Cicd: add amplify push backend workflow

---

.storybook/main.css
src/components/shared/Extensions/Tabs/Tabs.module.css
src/styles/main.global.css

fixed tabs

---

src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VoteOutcome/VoteResults/VoterAvatars.tsx

- Display the currently logged in user's profile pic first (to the far left) when displaying the voting details
Resolves #415

Show logged in user first in VoteDetails

---

src/stories/common/ImageCarousel.stories.ts

fix/15433241: carousel fix storybook styles

---

src/components/shared/Extensions/UserAvatarPopover/partials/UserInfo.tsx

changed font size in user info component

---

src/components/shared/Extensions/FormError/FormError.tsx

fixed full size width in form error

---

src/components/common/Extensions/ColonySwitcher/partials/ColoniesDropdown.tsx

fix font weight in colony dropdown

fix font weight

---

src/components/common/Extensions/ColonySwitcher/ColonySwitcher.module.css
src/components/common/Extensions/ColonySwitcher/ColonySwitcher.tsx
src/components/common/Extensions/ColonySwitcher/partials/ColoniesDropdown.tsx
src/components/common/Extensions/ColonySwitcher/partials/ColonyItem.tsx
src/stories/common/ColonySwitcher.stories.tsx

fix/15399749: fix colony switcher styles

---

src/components/shared/Extensions/Accordion/Accordion.tsx
src/stories/common/MainNavigation.stories.tsx

 fix/15399697: accordion mobile

---

src/components/common/Extensions/SpecificSidePanel/partials/ContractAddress.tsx

fix/15437047: contract address-safari

---

src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx

fix/15420184: fix notification banner on mobile

---

.storybook/main.css
src/components/common/Extensions/ExtensionStatusBadge-new/ExtensionStatusBadge.tsx
src/components/common/Extensions/NotificationBanner/CopyUrl.tsx
src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.module.css
src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.tsx
src/components/common/Extensions/SpecificSidePanel/partials/ContractAddress.tsx
src/components/common/Extensions/SpecificSidePanel/partials/InstalledBy.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakesTabItem.tsx
src/components/shared/Extensions/Card/Card.tsx
src/components/shared/Extensions/Tabs/Tabs.tsx
src/components/shared/Extensions/UserAvatarPopover/UserAvatarPopover.tsx
src/styles/main.global.css

fix: fix styles after QA tests

---

src/components/common/Extensions/SubNavigation/partials/DropdownContent/DecideDropdown.tsx
src/components/common/Extensions/SubNavigation/partials/DropdownContent/DropdownContent.module.css
src/components/common/Extensions/SubNavigation/partials/DropdownContent/PayDropdown.tsx
src/components/shared/Extensions/LearnMore/LearnMore.tsx
src/stories/common/SubNavigation/SubNavigation.stories.tsx
src/styles/shared/queries.css

sub navigation fixes

---

src/stories/shared/Tooltip.stories.tsx

added top variant tooltip

---

src/components/common/Extensions/SpecialInput/SpecialInput.module.css
src/components/common/Extensions/SpecialInput/SpecialInput.tsx

fixed safari/ios radius bug

---

src/components/shared/Extensions/Card/Card.tsx
src/components/shared/Extensions/Card/types.ts
src/stories/common/UserNavigation.stories.tsx

fixed user hub card

---

amplify/backend/function/getMembersForColony/src/index.js

ROOT_DOMAIN_ID was not defined. Changing this to Id.RootDomain

Fix Rootdomain in getMembersForColony

---

src/components/common/Extensions/CalamityBanner/CalamityBanner.module.css
src/components/common/Extensions/CalamityBanner/CalamityBanner.tsx
src/components/common/Extensions/CalamityBanner/types.ts
src/components/frame/Extensions/Header/Header.tsx
src/components/frame/Extensions/layouts/ExtensionLayout.tsx
src/i18n/en.json

Implemented calamity banner on page, added functionality to upgrade colony.

feat: added calamity banner to website

---

src/components/frame/Extensions/layouts/ExtensionsLayout.tsx
src/components/shared/Extensions/Spinner/Spinner.tsx
src/components/shared/Extensions/Toast/Toast.module.css
src/components/shared/Extensions/Toast/Toast.tsx
src/components/shared/Extensions/Toast/types.ts
src/stories/shared/Toast.stories.tsx

fix: moved styles to css, added toastContainer to layout, changed types

---

.github/workflows/build-deploy-dev.yaml
.github/workflows/build-deploy.yaml

update cdapp workflow deployment
**Changes** 🏗

ci: update cdapp workflow deployment

---

amplify/backend/api/colonycdapp/schema.graphql
src/components/common/ColonyActions/ActionDetailsPage/Layout/ActionDetailsPageLayout.css.d.ts
src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementForm.tsx
src/components/common/Dialogs/RecoveryModeDialog/RecoveryModeDialog.tsx
src/components/common/Dialogs/RecoveryModeDialog/RecoveryModeDialogForm.tsx
src/transformers/index.ts

This PR fixes typecheck errors and cherry-picks the `IngestorStats` model changes from `qa-attempt`.

Fix typecheck errors

---

src/stories/common/SpecialHourInput.stories.tsx

fixed type in special hour input

---

src/components/common/Extensions/MainNavigation/MainNavigation.tsx
src/components/common/Extensions/ThemeSwitcher/ThemeSwitcher.tsx
src/components/common/Extensions/TitledContent/TitledContent.tsx
src/components/common/Extensions/UserNavigation/UserNavigation.tsx
src/components/common/Extensions/UserNavigation/partials/MemberReputation/MemberReputation.tsx
src/components/common/Extensions/UserNavigation/partials/Token/Token.tsx
src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
src/components/common/Extensions/UserNavigation/partials/WalletConnectedTopMenu/WalletConnectedTopMenu.tsx
src/components/common/Extensions/UserNavigation/partials/WalletPopover/WalletPopover.tsx
src/components/frame/Extensions/Header/Header.tsx
src/components/shared/Extensions/Toast/Toast.tsx
src/components/shared/Extensions/UserAvatarPopover/UserAvatarPopover.tsx
src/stories/common/UserNavigation.stories.tsx

added missing text to button in nav

---

src/components/frame/Extensions/Header/Header.tsx
src/i18n/en.json

handle missing colonies state

---

src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetails/ExtensionDetails.tsx

fix button copy

---

docker/colony-cdapp-dev-env-block-ingestor
package-lock.json

Block ingestor PR counterpart: https://github.com/JoinColony/block-ingestor/pull/90
Resolves #623

Filter out action events emitted by creating the colony/installing extensions

---

.github/workflows/build-deploy-dev.yaml

Fix workflow dispatch type
**Changes** 🏗

fix cdapp dev only dispatch type

---

.github/workflows/amplify.yaml
.github/workflows/scripts/amplify_script.sh

Add amplify workflow to push new changes to AWS
**Changes** 🏗

ci: add first version of amplify workflow

---

src/components/v5/common/Navigation/partials/NavItem/NavItem.tsx
src/components/v5/common/SubNavigation/partials/SubNavigationItem/SubNavigationItemMobile.module.css

fixed margins in sub nav mobile item and hover in nav link

---

src/components/v5/common/Pills/ExtensionStatusBadge/ExtensionStatusBadge.tsx
src/components/v5/common/Pills/PillsBase.module.css
src/components/v5/common/Pills/PillsBase.tsx
src/components/v5/common/Pills/UserStatus/UserStatus.tsx
src/components/v5/common/Pills/UserStatus/index.ts
src/components/v5/common/Pills/types.ts
src/stories/common/UserStatus.stories.tsx

moved user status pills to seaparate component

---

.github/workflows/amplify.yaml

Update amplify deploy script
**Changes** 🏗

cicd: fix amplify script and enable deployment notifications

---

amplify/backend/api/colonycdapp/schema.graphql
amplify/backend/function/getUserTokenBalance/src/graphql.js
amplify/backend/function/getUserTokenBalance/src/index.js
amplify/backend/function/getUserTokenBalance/src/package-lock.json
amplify/backend/function/getUserTokenBalance/src/package.json
amplify/backend/function/getUserTokenBalance/src/utils.js
src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/StakingControls/useStakingControls.tsx
src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/useEnoughTokensForStaking.ts
src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/StakingWidget/StakingInput/useStakingSlider.ts
src/components/frame/RouteLayouts/UserNavigation/UserNavigation.tsx
src/graphql/generated.ts

This PR does the wiring for the Staked Tokens entry in the Token Popover. 
I recommend testing https://github.com/JoinColony/colonyCDapp/pull/704 first, then come back for code review.
* Add ColonyStake model and link to User model
**Changes** 🏗
* Wire in Staked tokens to `getUserTokenBalance`
Resolves #336

Wire in Staked Tokens to Token Popover

---

amplify/backend/backend-config.json
amplify/backend/custom/lambdaParams/lambdaParams-cloudformation-template.json
amplify/backend/function/colonycdappSSMAccess/colonycdappSSMAccess-awscloudformation-template.json
amplify/backend/function/colonycdappSSMAccess/parameters.json
amplify/backend/function/createUniqueColony/createUniqueColony-cloudformation-template.json
amplify/backend/function/createUniqueUser/createUniqueUser-cloudformation-template.json
amplify/backend/function/fetchColonyBalances/fetchColonyBalances-cloudformation-template.json
amplify/backend/function/fetchColonyNativeFundsClaim/fetchColonyNativeFundsClaim-cloudformation-template.json
amplify/backend/function/fetchMotionState/fetchMotionState-cloudformation-template.json
amplify/backend/function/fetchMotionTimeoutPeriods/fetchMotionTimeoutPeriods-cloudformation-template.json
amplify/backend/function/fetchTokenFromChain/fetchTokenFromChain-cloudformation-template.json
amplify/backend/function/fetchVoterRewards/fetchVoterRewards-cloudformation-template.json
amplify/backend/function/getMembersForColony/getMembersForColony-cloudformation-template.json
amplify/backend/function/getReputationForTopDomains/getReputationForTopDomains-cloudformation-template.json
amplify/backend/function/getUserReputation/getUserReputation-cloudformation-template.json
amplify/backend/function/getUserTokenBalance/getUserTokenBalance-cloudformation-template.json
amplify/backend/function/qaSSMtest/qaSSMtest-cloudformation-template.json
amplify/backend/function/setCurrentVersion/setCurrentVersion-cloudformation-template.json
amplify/backend/function/updateExtensionByColonyAndHash/updateExtensionByColonyAndHash-cloudformation-template.json
amplify/backend/types/amplify-dependent-resources-ref.d.ts
amplify/team-provider-info.json

Update custom ssm and remove env vars for lambdas
**Changes** 🏗

fix: update lambdas and custom ssm

---

src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.tsx
src/components/common/Extensions/UserHub/partials/ReputationTab/types.ts

fixed the horizontal rule

---

.storybook/main.css
src/components/common/Extensions/CalamityBanner/CalamityBanner.tsx
src/components/common/Extensions/SupportingDocuments/SupportingDocuments.tsx
src/components/v5/common/TableFiltering/TableFiltering.tsx
src/components/v5/shared/Button/CloseButton.module.css
src/components/v5/shared/Button/CloseButton.tsx
src/components/v5/shared/Button/types.ts
src/components/v5/shared/Modal/Modal.module.css
src/components/v5/shared/Modal/Modal.tsx
src/components/v5/shared/Modal/ModalBase.tsx
src/images/icons.json
src/images/icons/x.svg
src/styles/main.global.css

fixed modal css issues and close button color and hover

---

src/components/common/ColonyExtensions/ExtensionCard/ExtensionCard.tsx
src/components/common/ColonyTotalFunds/ManageFundsLink/ManageFundsLink.tsx
src/components/common/Extensions/ColonySwitcher/partials/ColonyItem.tsx
src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
src/components/common/Extensions/UserNavigation/partials/UserSubmenu/UserSubmenu.tsx
src/components/frame/TokenActivation/TokensTab/TokensTab.tsx
src/components/frame/v5/pages/MembersPage/partials/SubNavigation/SubNavigation.tsx
src/components/shared/DecisionHub/DecisionOption.tsx
src/components/shared/DetailsWidget/ActionTypeDetail/ActionTypeDetail.tsx
src/components/shared/Icon/Icon.module.css
src/components/shared/Icon/Icon.module.css.d.ts
src/components/shared/Icon/Icon.tsx
src/components/shared/IndexModal/IndexModalItem.tsx
src/components/shared/QuestionMarkTooltip/QuestionMarkTooltip.tsx
src/components/v5/common/SubNavigation/partials/SubNavigationItem/SubNavigationItem.tsx
src/components/v5/shared/Modal/Modal.tsx

fixed sub menu icons

---

src/components/common/Extensions/UserNavigation/partials/Token/Token.module.css
src/components/common/Extensions/UserNavigation/partials/Token/Token.tsx
src/components/frame/Extensions/Header/Header.tsx
src/components/v5/shared/Button/Hamburger.module.css

fixed menu styles

---

src/components/v5/shared/UserAvatar/UserAvatar.module.css
src/components/v5/shared/UserAvatar/UserAvatar.tsx
src/components/v5/shared/UserAvatarDetails/UserAvatarDetails.tsx
src/components/v5/shared/UserAvatarPopover/UserAvatarPopover.tsx

added truncateto user name

---

src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.module.css
src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
src/components/common/Extensions/UserNavigation/partials/UserSubmenu/UserSubmenu.tsx

fixed user account height

---

src/components/common/Extensions/ExtensionItem/ExtensionItem.tsx
src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.module.css
src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.tsx
src/components/common/Extensions/NavigationTools/NavigationTools.tsx
src/components/v5/common/SubNavigation/partials/LinkItem/LinkItem.module.css
src/components/v5/common/SubNavigation/partials/LinkItem/LinkItem.tsx

removed help and account from mobile, fixed anchor nesting

---

src/components/v5/common/Fields/Select/Select.tsx
src/components/v5/common/Fields/Switch/Switch.module.css
src/components/v5/common/Fields/Switch/Switch.tsx
src/components/v5/common/Fields/Switch/index.ts
src/components/v5/common/Fields/Switch/types.ts
src/components/v5/common/Fields/Textarea/Textarea.tsx
src/components/v5/common/Fields/Textarea/types.ts
src/components/v5/common/Modals/ManageMemberModal/ManageMemberModal.tsx
src/components/v5/common/Modals/ManageMemberModal/types.ts
src/i18n/en.json
src/stories/common/Switch.stories.tsx
src/stories/common/Textarea.stories.tsx

prepare ui in modal for banned not banned member

---

src/components/frame/v5/pages/MembersPage/MembersPage.tsx
src/components/v5/common/MembersList/MembersList.tsx

Fixed list styles and added teams component with mocked data

fix: added missing teams component, fixed list styles

---

src/components/common/Extensions/UserHub/partials/ReputationTab/ReputationTab.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/StakesTab.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx

fixed margins in user hub

---

src/components/common/Extensions/MainNavigation/partials/Nav.module.css
src/components/common/Extensions/MainNavigation/partials/NavMobile/NavMobile.tsx
src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.module.css
src/components/v5/common/Fields/Switch/Switch.tsx

fixed styles in More submenu

---

src/components/common/Extensions/UserHub/UserHub.tsx
src/components/common/Extensions/UserHub/partials/ReputationTab/partials/PendingReputation.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/StakesTab.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/consts.ts
src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakesTabItem.module.css
src/components/common/Extensions/UserHub/partials/StakesTab/partials/StakesTabItem.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/types.ts
src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/TransactionList.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/TransactionsItem/TransactionsItem.module.css
src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
src/components/common/Extensions/UserNavigation/partials/UserSubmenu/UserSubmenu.tsx
src/components/common/Extensions/UserNavigation/partials/WalletConnectedTopMenu/WalletConnectedTopMenu.tsx
src/components/shared/Extensions/Tabs/Tabs.module.css
src/components/shared/Extensions/Tabs/Tabs.tsx
src/components/shared/Extensions/Tabs/types.ts
src/components/v5/common/SubNavigation/partials/SubNavigationItem/SubNavigationItem.tsx

fixes in wallet

---

src/components/common/Extensions/ColonySwitcher/ColonySwitcher.module.css
src/components/common/Extensions/ColonySwitcher/partials/ColoniesDropdown.tsx
src/components/frame/Extensions/Header/Header.module.css

fixed css styles in colony dropdown

---

.github/workflows/build-deploy.yaml

Add prod environment for cdapp deployment.
**Changes** 🏗

Add github workflow prod env

---

Readme.md

Fix 2 minor README typos

---

src/components/common/Extensions/ExtensionItem/ExtensionItem.tsx
src/components/shared/Icon/Icon.module.css
src/components/shared/Icon/Icon.module.css.d.ts
src/components/shared/Icon/Icon.tsx

fixed extension avatar size

---

src/components/common/Extensions/SpecificSidePanel/SpecificSidePanel.tsx

fixed sidebar padding

---

src/components/common/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.css
src/components/common/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.css.d.ts
src/components/common/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.tsx
src/components/common/Dialogs/AddExistingSafeDialog/ConfirmSafe/ConfirmSafe.css
src/components/common/Dialogs/AddExistingSafeDialog/ConfirmSafe/ConfirmSafe.css.d.ts
src/components/common/Dialogs/AddExistingSafeDialog/ConfirmSafe/ConfirmSafe.tsx
src/components/common/Dialogs/AddExistingSafeDialog/ConfirmSafe/index.ts
src/components/common/Dialogs/AddExistingSafeDialog/ConnectSafe/ConnectSafe.css
src/components/common/Dialogs/AddExistingSafeDialog/ConnectSafe/ConnectSafe.css.d.ts
src/components/common/Dialogs/AddExistingSafeDialog/ConnectSafe/ConnectSafe.tsx
src/components/common/Dialogs/AddExistingSafeDialog/validation.ts

Nothing much to say, this step is quite simple.
- Check that the validation works as expected.
- Check that the styles match with the ones that we have in Figma and/or Dapp.
Resolves #687

Port step 3 of "Add a Safe" dialog

---

src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialog.tsx
src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.css
src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.css.d.ts
src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.tsx
src/components/common/Dialogs/RemoveSafeDialog/SafeListItem.css
src/components/common/Dialogs/RemoveSafeDialog/SafeListItem.css.d.ts
src/components/common/Dialogs/RemoveSafeDialog/SafeListItem.tsx
src/components/common/Dialogs/RemoveSafeDialog/helpers.ts
src/components/common/Dialogs/RemoveSafeDialog/index.ts
src/components/common/Dialogs/index.ts
src/components/common/NewActionButton/wizardConfig.ts
src/components/shared/Fields/Checkbox/HookForm/Checkbox.css
src/components/shared/Fields/Checkbox/HookForm/Checkbox.css.d.ts
src/components/shared/Fields/Checkbox/HookForm/Checkbox.tsx
src/constants/index.ts
src/styles/main.css

- Port RemoveSafeDialog from colony dap
- Added pink variant for checkbox
- Updated main.css to now show weird borders
Resolves #692

Add remove safes dialog

---

.github/workflows/nodejs.yml
package.json
src/redux/sagas/wallet/onboard.ts

This PR gives the Node.js CI GitHub workflow some love.
Failing typecheck tests are now passing, and removed scripts have been added back in.
Actions have also been updated and now the CI is passing and is 3 times are fast
Resolves #752

Fix nodejs CI

---

.github/workflows/amplify.yaml

Add amplify prod env deployment.
**Changes** 🏗

cicd: add amplify prod env

---

src/components/common/Extensions/Fields/RadioList/RadioBase.tsx
src/components/common/Extensions/Fields/RadioList/RadioList.module.css

select box hover

---

src/components/common/Extensions/Fields/RadioList/RadioBase.tsx
src/components/common/Extensions/Fields/RadioList/RadioList.module.css
src/components/common/Extensions/SpecialInput/SpecialInput.module.css
src/components/common/Extensions/SpecialInput/SpecialInput.module.css.d.ts
src/components/common/Extensions/SpecialInput/SpecialInput.tsx

fixex hover states

---

src/components/common/Extensions/SpecialInput/SpecialInput.module.css
src/components/shared/Extensions/Accordion/partials/SpecialHourInput.tsx
src/components/shared/Extensions/Accordion/partials/SpecialPercentageInput.tsx

special input error state

---

src/components/v5/common/MembersList/MembersList.tsx

fix members statuses

---

src/components/frame/Extensions/pages/LazyConsensusPage/hooks.tsx
src/components/shared/Extensions/Accordion/partials/AccordionHeader.tsx
src/components/shared/Extensions/Accordion/partials/AccordionNested/AccordionNestedHeader.tsx
src/components/shared/Extensions/Accordion/partials/AccordionNested/AccordionNestedItem.tsx
src/components/v5/common/Filter/partials/AccordionItem.tsx

added nested accordion - example scenario

---

src/components/frame/v5/pages/UserAdvancedPage/partials/FeesForm/FeesForm.tsx
src/components/frame/v5/pages/UserAdvancedPage/partials/RpcForm/RpcForm.tsx
src/components/v5/common/Fields/Switch/Switch.tsx
src/components/v5/common/Fields/Switch/types.ts
src/components/v5/common/SettingsRow/SettingsRow.tsx
src/components/v5/common/SettingsRow/types.ts

Fixed switch, removed register from component

fix: switch register

---

.storybook/main.css
src/components/common/Extensions/MainNavigation/MainNavigation.tsx
src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.tsx
src/components/common/Extensions/UserHub/UserHub.tsx
src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.module.css
src/components/frame/Extensions/Header/Header.tsx
src/components/frame/Extensions/layouts/PageLayout.tsx
src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
src/components/shared/Avatar/Avatar.module.css
src/components/v5/common/Fields/Select/Select.module.css
src/components/v5/common/Fields/Select/Select.tsx
src/components/v5/common/PageTitle/PageTitle.module.css
src/components/v5/common/PageTitle/PageTitle.tsx
src/components/v5/shared/CardWithBios/partials/SubNavigation.tsx
src/i18n/en.json
src/styles/main.global.css

mobile header padding

---

src/components/common/Extensions/Fields/RadioList/RadioList.module.css
src/components/common/Extensions/SpecialInput/SpecialInput.module.css
src/components/frame/Extensions/layouts/PageLayout.tsx
src/components/frame/Extensions/pages/Pages.module.css
src/components/frame/Extensions/pages/partials/ActionButtons.tsx
src/components/frame/Extensions/pages/partials/ActiveInstalls.tsx
src/components/frame/Extensions/pages/partials/HeadingIcon.tsx

hide active installs on tablet

---

src/components/common/Extensions/UserHub/UserHub.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/StakesTab.tsx
src/components/common/Extensions/UserHub/partials/StakesTab/types.ts
src/components/shared/Extensions/Tabs/Tabs.tsx

claimable items

---

src/components/v5/common/Pills/ExtensionStatusBadge/ExtensionStatusBadge.tsx
src/components/v5/common/Pills/types.ts
src/stories/common/ExtensionStatusBadge.stories.ts

Added new pill mode 
https://tw.auroracreation.com/app/tasks/15519171

feat: added new pill mode

---

package.json
src/components/common/Extensions/UserHub/UserHub.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/TransactionsTab.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/TransactionList.tsx

Added custom scrollbar for transaction list
https://tw.auroracreation.com/app/tasks/15516332

fix: added custom scrollbar for transaction list

---

.storybook/main.css
src/components/frame/v5/Header/Header.tsx
src/components/v5/common/Filter/Filter.tsx
src/components/v5/common/Filter/partials/SearchInput/SearchInput.module.css
src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
src/components/v5/shared/CardWithBios/CardWithBios.tsx
src/components/v5/shared/CardWithBios/partials/SubNavigation.tsx
src/components/v5/shared/SubNavigationItem/partials/Header.tsx
src/components/v5/shared/UserAvatarDetails/UserAvatarDetails.tsx
src/components/v5/shared/UserAvatarDetails/types.ts
src/images/icons/magnifying-glass.svg
src/images/icons/search.svg
src/styles/main.global.css

members user nav fixes

---

src/components/common/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
src/components/common/Dialogs/ControlSafeDialog/TransactionHeader/TransactionHeader.css
src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/RawTransactionSection.tsx
src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/shared.tsx
src/components/common/Dialogs/ControlSafeDialog/types.ts
src/components/common/Dialogs/ControlSafeDialog/validation.ts
src/components/common/Dialogs/RemoveSafeDialog/SafeListItem.css
src/components/shared/Fields/Input/HookForm/Input.tsx
src/styles/variables.css
src/types/index.ts

Port over the raw transaction section. The validation should work as we expect (only allow WEI and hex strings in their respective fields, for example.)
Resolves #735

Add raw transaction section

---

amplify/backend/function/fetchColonyBalances/src/package.json
amplify/backend/function/fetchMotionState/src/package.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
amplify/backend/function/fetchVoterRewards/src/package.json
amplify/backend/function/getMembersForColony/src/package.json
amplify/backend/function/getReputationForTopDomains/src/package.json
amplify/backend/function/getUserReputation/src/package.json
amplify/backend/function/getUserTokenBalance/src/package.json
src/cache/colony/balances.ts

Bump colony js version in lambdas to use latest.

Bump colony js version in lambdas

---

Dockerfile

Changed node version of dockerfile

fix: node version

---

src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/constants/actions.ts
src/i18n/en.json

fix: added missing actions

---

src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.tsx

fix/5551351: more submenu on mobile

---

src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
src/components/frame/v5/pages/UserProfilePage/hooks.tsx
src/components/v5/common/AvatarUploader/AvatarUploader.tsx
src/components/v5/common/AvatarUploader/hooks.tsx
src/components/v5/common/AvatarUploader/partials/FileUpload.tsx
src/components/v5/common/AvatarUploader/partials/ProgressContent.tsx
src/components/v5/common/AvatarUploader/types.ts
src/utils/convertBytes.ts

added progress bar of uploaded user avatar in User profile section

ui/15535339: avatar uploader progress bar

---

.env.example
src/components/common/CreateColonyWizard/StepColonyName.tsx
src/components/common/CreateColonyWizard/StepColonyNameInputs.tsx
src/components/common/CreateColonyWizard/StepCreateToken.tsx
src/components/common/CreateColonyWizard/StepCreateTokenInputs.tsx
src/components/common/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
src/components/common/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
src/components/common/Dialogs/ControlSafeDialog/TransactionHeader/TransactionHeader.tsx
src/components/common/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
src/components/common/Dialogs/ControlSafeDialog/helpers.ts
src/components/common/Dialogs/ControlSafeDialog/index.ts
src/components/common/Dialogs/ControlSafeDialog/types.ts
src/components/common/Dialogs/ControlSafeDialog/validation.ts
src/components/common/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
src/components/common/Dialogs/EditDomainDialog/EditDomainDialogForm.tsx
src/components/common/Dialogs/TokenAmountInput/TokenAmountInput.tsx
src/components/common/UserProfileEdit/CustomEndpointInput.tsx
src/components/common/UserProfileEdit/UserMainSettings.tsx
src/components/shared/Fields/Input/HookForm/FormattedInputComponent.tsx
src/types/safes.ts
src/utils/intl.ts
src/utils/lodash.ts
src/utils/safes/contractParserValidation.ts
src/utils/safes/getContractUsefulMethods.ts
src/utils/safes/index.ts

- This PR ports the contract interaction functionality of safe control ~It doesn't port over the validation~ including validation
[Screencast from 2023-08-01 16-06-07.webm](https://github.com/JoinColony/colonyCDapp/assets/32598350/3df8bd64-16d3-4f5e-ad8d-07a2f3fecd47)
* Two new env vars have been added to the `.env.example` 
```
BSCSCAN_API_KEY=<bscscan-api-key>
ETHERSCAN_API_KEY=<etherscan-api-key>
```
these need to be added to test this PR
Resolves #736

Port contract interaction transaction

---

src/components/common/Extensions/Fields/RadioList/RadioList.module.css
src/components/common/Extensions/UserNavigation/partials/Token/Token.module.css
src/components/common/Extensions/UserNavigation/partials/UserReputation/UserReputation.tsx
src/components/v5/common/Pills/ExtensionStatusBadge/ExtensionStatusBadge.tsx
src/components/v5/shared/Button/Button.tsx
src/components/v5/shared/Button/types.ts
src/components/v5/shared/Modal/Modal.tsx

fix: ui bugs

---

src/components/v5/common/ActionSidebar/hooks.ts
src/components/v5/common/ActionsContent/partials/UserSelect/UserSelect.tsx
src/components/v5/common/ActionsContent/partials/UserSelect/hooks.ts
src/components/v5/shared/RichText/RichText.tsx
src/components/v5/shared/RichText/hooks.ts

fix  recipient value and tiptap container height

---

src/components/v5/common/ActionSidebar/hooks.ts

fixed form params

---

src/components/v5/shared/RichText/RichText.tsx
src/components/v5/shared/RichText/hooks.ts

fix: action-sidepanel-description-field

---

src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
src/context/AppContext.tsx

Disconnect wallet

---

src/components/common/Extensions/MainNavigation/partials/Nav/Nav.tsx
src/components/common/Extensions/MainNavigation/partials/NavMobile/NavMobile.tsx
src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
src/components/v5/common/ActionSidebar/partials/ActionForm/ActionForm.tsx
src/components/v5/common/ActionSidebar/partials/MintTokenForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/SinglePaymentForm/SinglePaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/SinglePaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/TransferFundsForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/UnlockTokenForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/UpgradeColonyForm/hooks.ts
src/components/v5/common/ActionSidebar/types.ts
src/components/v5/common/ActionsContent/hooks.ts
src/components/v5/common/ActionsContent/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionsContent/partials/DecisionField/DecisionField.tsx
src/components/v5/common/ActionsContent/partials/DefaultField/DefaultField.tsx
src/components/v5/common/ActionsContent/partials/TeamColourField/TeamColourField.tsx
src/components/v5/common/ActionsContent/partials/TeamsSelect/TeamsSelect.tsx
src/components/v5/common/ActionsContent/partials/UserSelect/UserSelect.tsx
src/components/v5/shared/Link/Link.tsx
src/components/v5/shared/RichText/RichText.tsx
src/components/v5/shared/RichText/hooks.ts
src/context/ActionSidebarContext.tsx

Fix - added controller to all fields, default values, cancel modal

fix: added controller to all fields, default values, cancel modal

---

src/components/frame/Extensions/Header/Header.tsx
src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/partials/ActionForm/ActionFormContext.tsx
src/components/v5/common/ActionSidebar/partials/ActionForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/CreateNewTeamForm/CreateNewTeamForm.tsx
src/components/v5/common/ActionSidebar/partials/CreateNewTeamForm/hooks.ts
src/components/v5/common/ActionSidebarRow/ActionSidebarRow.tsx
src/components/v5/common/ActionSidebarRow/types.ts
src/components/v5/common/ActionsContent/ActionsContent.module.css
src/components/v5/common/ActionsContent/ActionsContent.tsx
src/components/v5/common/ActionsContent/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionsContent/partials/AmountField/types.ts
src/components/v5/common/ActionsContent/partials/DecisionField/DecisionField.tsx
src/components/v5/common/ActionsContent/partials/DecisionField/types.ts
src/components/v5/common/ActionsContent/partials/DefaultField/DefaultField.module.css
src/components/v5/common/ActionsContent/partials/DefaultField/DefaultField.tsx
src/components/v5/common/ActionsContent/partials/DefaultField/types.ts
src/components/v5/common/ActionsContent/partials/DescriptionField/DescriptionField.tsx
src/components/v5/common/ActionsContent/partials/DescriptionField/types.ts
src/components/v5/common/ActionsContent/partials/TeamColourField/TeamColourField.tsx
src/components/v5/common/ActionsContent/partials/TeamColourField/types.ts
src/components/v5/common/ActionsContent/partials/TeamsSelect/TeamsSelect.tsx
src/components/v5/common/ActionsContent/partials/UserSelect/UserSelect.tsx
src/components/v5/common/ActionsContent/types.ts
src/i18n/en.json

ui: handle fields validation

---

scripts/temp-create-data.js
src/constants/index.ts

We need to update a couple of env vars for use in the on-demand environments.

Update env vars for on-demand environments

---

amplify/backend/api/colonycdapp/schema.graphql
amplify/backend/function/updateContributorsWithReputation/src/graphql.js
amplify/backend/function/updateContributorsWithReputation/src/index.js
amplify/backend/function/updateContributorsWithReputation/src/utils.js
docker/colony-cdapp-dev-env-block-ingestor
src/graphql/generated.ts

Improve colony reputation caching

---

src/components/frame/Extensions/pages/ExtensionDetailsPage/ExtensionTopRow.tsx
src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetails/DeprecateButton.tsx
src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetails/ExtensionDetails.tsx
src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetails/ReenableButton.tsx
src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetails/UninstallButton.tsx
src/components/frame/Extensions/pages/ExtensionDetailsPage/partials/ExtensionDetails/hooks.tsx
src/components/frame/Extensions/pages/partials/ActionButtons.tsx
src/components/frame/Extensions/pages/partials/EnableButton.tsx
src/graphql/generated.ts

Fix enable btn

---

src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/hooks.ts
src/components/v5/common/ActionSidebar/partials/EnterRecoveryModeForm/EnterRecoveryModeForm.tsx
src/components/v5/common/ActionSidebar/partials/EnterRecoveryModeForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/EnterRecoveryModeForm/index.ts
src/components/v5/common/ActionsContent/partials/TeamsSelect/TeamsSelect.tsx
src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
src/i18n/en.json

https://tw.auroracreation.com/app/tasks/15536335

feat: added recovery mode, fixed color picker and createin field

---

src/components/common/Expenditures/ExpenditureForm/CreateExpenditureForm.tsx
src/components/common/Expenditures/ExpenditureForm/ExpenditureForm.module.css
src/components/common/Expenditures/ExpenditureForm/ExpenditureForm.module.css.d.ts
src/components/common/Expenditures/ExpenditureForm/helpers.ts
src/components/common/Expenditures/ExpenditureForm/types.ts
src/components/common/Expenditures/StakeExpenditureDialog/StakeExpenditureDialog.tsx
src/components/common/Expenditures/StakeExpenditureDialog/useExpenditureStaking.ts

This PR adds caching of expenditure payouts claimed status in the DB.
Resolves #982

Cache expenditure payout claimed status

---

amplify/backend/function/fetchColonyBalances/src/package-lock.json
amplify/backend/function/fetchColonyBalances/src/package.json
amplify/backend/function/fetchExpenditureBalances/src/package-lock.json
amplify/backend/function/fetchExpenditureBalances/src/package.json
amplify/backend/function/fetchMotionState/src/package-lock.json
amplify/backend/function/fetchMotionState/src/package.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package-lock.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
amplify/backend/function/fetchVoterRewards/src/package-lock.json
amplify/backend/function/fetchVoterRewards/src/package.json
amplify/backend/function/getMembersForColony/src/package-lock.json
amplify/backend/function/getMembersForColony/src/package.json
amplify/backend/function/getReputationForTopDomains/src/package-lock.json
amplify/backend/function/getReputationForTopDomains/src/package.json
amplify/backend/function/getUserReputation/src/package-lock.json
amplify/backend/function/getUserReputation/src/package.json
amplify/backend/function/getUserTokenBalance/src/package-lock.json
amplify/backend/function/getUserTokenBalance/src/package.json
amplify/backend/function/qaSSMtest/src/package-lock.json
amplify/backend/function/qaSSMtest/src/package.json
docker/colony-cdapp-dev-env-block-ingestor
docker/colony-cdapp-dev-env-network
package-lock.json
package.json
src/constants/extensions.ts
src/hooks/useEnabledExtensions.tsx

Small PR adding the required config to support Staged Expenditure extension.
There's not much to test other than the ability to install, deprecate, and uninstall the Staged Expenditure extension. It is initialized by default.
Resolves #975

Staged Expenditure extension support

---

src/components/common/Dialogs/AddExistingSafeDialog/AddExistingSafeDialog.tsx
src/components/common/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.tsx
src/components/common/Dialogs/AddExistingSafeDialog/CheckSafe/CheckSafe.tsx
src/components/common/Dialogs/AddExistingSafeDialog/SafeContractAddressInput/SafeContractAddressInput.tsx
src/components/common/Dialogs/AddExistingSafeDialog/types.ts
src/components/common/Dialogs/AddExistingSafeDialog/validation.ts

This PR fixes the validation for adding a safe. It removes the flickering that was present before as well as the brief flash of incorrect messages. All while removing code :scissors: 
[Screencast from 2023-09-01 19-07-07.webm](https://github.com/JoinColony/colonyCDapp/assets/32598350/5a8e7862-18d2-45fe-946e-df65d58e1fa7)
Resolves #812

Fix add existing safe validation

---

src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
src/components/common/Dialogs/CreatePaymentDialog/helpers.ts
src/redux/sagas/actions/payment.ts
src/redux/types/actions/colonyActions.ts

Multiple payments

---

.storybook/main.js

Added buffer to ProvidePlugin in storybook

---

src/redux/sagas/actions/initiateSafeTransaction.ts
src/redux/sagas/actions/manageExistingSafes.ts
src/redux/sagas/motions/initiateSafeTransactionMotion.ts

Self-explanatory title. With the recent rebase we did of the feature branch, annotations have become available for us to integrate with the feature.
Now the descriptions provided in the Control Safe and Add Safe dialog should appear in the action/motion page.

Integrate annotations with Safe Control

---

src/components/frame/Extensions/pages/ColonyDetailsPage/ColonyDetailsPage.tsx
src/components/v5/common/ObjectiveBox/types.ts
src/components/v5/shared/ProgressBar/ProgressBar.tsx
src/components/v5/shared/ProgressBar/types.ts
src/stories/common/ProgressBar.stories.tsx

https://tw.auroracreation.com/app/tasks/15579993

feat: added tall version and additional message

---

src/components/common/CreateUserWizard/validation.ts
src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
src/components/frame/v5/pages/UserProfilePage/hooks.tsx
src/components/frame/v5/pages/UserProfilePage/types.ts
src/components/frame/v5/pages/UserProfilePage/validation.ts
src/components/v5/common/Fields/Input/partials/InputPills.tsx
src/i18n/en.json

Fix user form validation

---

src/components/v5/common/Table/Table.tsx
src/components/v5/common/Table/index.ts
src/components/v5/common/Table/types.ts

ui table base

---

src/components/v5/common/TableWithMeatballMenu/TableWithMeatballMenu.tsx
src/components/v5/common/TableWithMeatballMenu/index.ts
src/components/v5/common/TableWithMeatballMenu/types.ts
src/components/v5/common/TableWithMeatballMenu/utils.tsx

table actions

---

package.json

Added @tanstack/react-table

---

src/components/v5/common/ActionSidebar/ActionSidebar.tsx

Changed toggle to toggleOff

---

package.json
src/components/frame/Extensions/Header/Header.tsx
src/components/v5/shared/Modal/ModalBase.tsx
src/hooks/useDisableBodyScroll/index.ts
src/hooks/useDisableBodyScroll/utils.ts

https://tw.auroracreation.com/app/tasks/15591667

fix: added body disable hook

---

.github/workflows/build-deploy-dev.yaml

Trigger deploy on push to extensions-new-ui

---

src/components/v5/common/ActionSidebar/partials/TransactionTable/TransactionTable.tsx
src/components/v5/common/ActionSidebar/partials/TransactionTable/hooks.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
src/i18n/en.json

Changed payload for simple action

---

src/components/common/Extensions/MainNavigation/partials/SubMenu/SubMenu.tsx
src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/TeamColourField/TeamColourField.tsx
src/components/v5/common/Fields/CardSelect/CardSelect.tsx
src/components/v5/common/TeamReputationSummary/TeamReputationSummary.tsx
src/components/v5/shared/Card/Card.tsx
src/components/v5/shared/CardWithSections/CardWithSections.tsx
src/components/v5/shared/PopoverBase/PopoverBase.tsx
src/hooks/useRelativePortalElement.ts

Removed w-full from Card

---

package.json
src/index.ts

Enabled hmr

---

src/redux/sagas/motions/createDecisionMotion.ts
src/redux/sagas/motions/createEditDomainMotion.ts
src/redux/sagas/motions/editColonyMotion.ts
src/redux/sagas/motions/managePermissionsMotion.ts
src/redux/sagas/motions/manageReputationMotion.ts
src/redux/sagas/motions/moveFundsMotion.ts
src/redux/sagas/motions/paymentMotion.ts
src/redux/sagas/motions/rootMotion.ts
src/redux/types/actions/colonyActions.ts
src/redux/types/actions/decisions.ts
src/redux/types/actions/index.ts
src/redux/types/actions/motion.ts

Refactor motion sagas to accept state setter

---

src/components/v5/common/ActionSidebar/hooks.tsx

change for tests isDisabled flag on false

---

src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx

fix font size to 14px in Amount field component 
https://tw.auroracreation.com/app/tasks/15535785

fix font size

---

.github/workflows/on-demand-env.yaml
.github/workflows/scripts/on-demand-env-script.sh

- Add workflow for deploying on demand dev env
**Changes** 🏗

add on demand env workflow

---

src/components/v5/common/ActionSidebar/partials/TeamColourField/TeamColourField.tsx

https://tw.auroracreation.com/app/tasks/15536329

fix: added default value to color field

---

src/utils/getEnumValueFromKey.ts

Fix for getEnumValueFromKey when defaultEnumValue is 0

fix: getEnumValueFromKey condition update

---

src/utils/getEnumValueFromKey.ts

Return correct value from enum - getEnumValueFromKey

fix: enuma values

---

src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/partials/AdvancedPaymentRecipentsField/hooks.tsx

https://tw.auroracreation.com/app/tasks/15536376

Hide error message inside of AdvancedPayment table

---

.github/workflows/on-demand-env.yaml
.github/workflows/scripts/on-demand-env-script.sh

Enable https for on demand envs
**Changes** 🏗

Enable https for on demand envs

---

src/components/v5/common/TableWithMeatballMenu/TableWithMeatballMenu.tsx

https://tw.auroracreation.com/app/tasks/15615792

fix: fixed meatballmenu on safari

---

src/components/v5/common/Fields/InputBase/FormFormattedInput.tsx
src/components/v5/common/Fields/InputBase/FormattedInput.tsx
src/components/v5/common/Fields/InputBase/hooks.ts
src/components/v5/common/Fields/InputBase/index.ts
src/components/v5/common/Fields/InputBase/types.ts
src/stories/common/FormattedInput.stories.tsx

feat: formatted input

---

src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionBadge/MotionBadge.tsx
src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionBadge/types.ts
src/components/v5/shared/Accordion/Accordion.tsx
src/components/v5/shared/Accordion/partials/AccordionItem/AccordionItem.tsx
src/components/v5/shared/Accordion/partials/AccordionItem/types.ts
src/components/v5/shared/Accordion/types.ts
src/components/v5/shared/UserAvatar/UserAvatar.tsx
src/components/v5/shared/UserAvatar/types.ts
src/components/v5/shared/UserInfoSectionList/UserInfoSectionList.tsx
src/components/v5/shared/UserInfoSectionList/index.ts
src/components/v5/shared/UserInfoSectionList/partials/UserInfoList/UserInfoList.tsx
src/components/v5/shared/UserInfoSectionList/partials/UserInfoList/index.ts
src/components/v5/shared/UserInfoSectionList/partials/UserInfoList/types.ts
src/components/v5/shared/UserInfoSectionList/types.ts
src/stories/shared/Accordion.stories.tsx
src/stories/shared/UserInfoList.stories.tsx
src/stories/shared/UserInfoSectionList.stories.tsx

feat: accordion update and user info section list component

---

src/components/shared/Fields/Form/ActionForm.tsx
src/components/shared/Fields/Form/Form.tsx
src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/hooks.tsx
src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
src/components/v5/shared/Card/Card.tsx
src/components/v5/shared/SearchSelect/SearchSelect.tsx
src/types/definitions/react/index.d.ts

https://tw.auroracreation.com/app/tasks/15623046

Added ref to Form and ActionForm

---

src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx

fix: revert change in SearchItem component

---

src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/EnterRecoveryModeForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/hooks.ts

Add motion to every action types

add motion to every actions

---

src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
src/components/common/Extensions/NotificationBanner/types.ts
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx

select recipient - do not allow selecting a value if it is not a wallet address

do not allow selecting a value if it is not wallet

---

src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/EnterRecoveryModeForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/utils.tsx

https://tw.auroracreation.com/app/tasks/15608712

Adjust metadata font weight and color

---

src/components/v5/common/Fields/Switch/Switch.module.css
src/components/v5/shared/Button/Button.module.css

- Task: https://tw.auroracreation.com/app/tasks/feat
**Changes** 🏗
- colors of Button and Swtich component
Old:
New:

Feat: 15629288 colors of main buttons

---

src/components/v5/common/Fields/Switch/Switch.tsx

Moved switch displayName to Object.assign

---

src/components/v5/common/Checkbox/Checkbox.tsx
src/components/v5/shared/Button/Button.module.css
src/components/v5/shared/Filter/FilterButton.tsx

A few more places were noticed that require a color change
**Changes** 🏗

Fix: 15629288 colors of main buttons

---

src/components/v5/shared/RichText/hooks.ts
src/components/v5/shared/RichText/partials/Menu.tsx

fix: richtext editor - change menu button to underline

---

src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/AmountField/types.ts
src/components/v5/common/ActionSidebar/partials/TransactionTable/TransactionTable.tsx
src/components/v5/common/ActionSidebar/partials/TransactionTable/hooks.tsx
src/components/v5/common/ActionSidebar/partials/TransactionTable/types.ts
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts

Single payment action:
not able to select token in the table.

fix: 15535688 - not able to change token in table

---

src/components/v5/shared/RichText/RichText.tsx
src/components/v5/shared/RichText/hooks.ts
src/i18n/en.json

fix: 15637167 richtext placeholder

---

src/components/frame/Extensions/layouts/Header.tsx
src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/types.ts
src/components/v5/common/SubNavigation/partials/DropdownContent/DecideDropdown.tsx
src/components/v5/common/SubNavigation/partials/DropdownContent/ManageDropdown.tsx
src/components/v5/common/SubNavigation/partials/DropdownContent/PayDropdown.tsx
src/context/ActionSidebarContext.tsx

Changed how initial action in ActionSidebar is set

Changed event to initialValues state

---

src/components/common/Extensions/ColonyNavigation/ColonyNavigation.tsx
src/components/common/Extensions/ColonyNavigation/partials/SubMenu/SubMenu.tsx

Avoid passing event to action sidebar toggle

---

.github/workflows/on-demand-env.yaml
.github/workflows/scripts/on-demand-env-script.sh

- Fixing https endpoints and ports, adding custom duration for on demand envs and discord notification for user.
**Changes** 🏗

cicd: fix on demand env https, add custom duration and discord notification

---

.github/workflows/build-deploy.yaml

- Enable auto deploy from master branch for qa/prod pipeline.
**Changes** 🏗

Add auto deploy master branch

---

src/components/v5/common/Fields/CardSelect/CardSelect.tsx
src/components/v5/common/Fields/CardSelect/types.ts
src/components/v5/frame/NavigationSidebar/NavigationSidebarContent.tsx
src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarMainMenu/NavigationSidebarMainMenu.tsx
src/components/v5/frame/PageLayout/PageLayout.tsx
src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
src/components/v5/frame/PageLayout/partials/PageHeader/index.ts
src/components/v5/frame/PageLayout/partials/PageHeader/types.ts
src/components/v5/frame/PageLayout/partials/PageHeading/PageHeading.tsx
src/components/v5/frame/PageLayout/partials/PageHeading/index.ts
src/components/v5/frame/PageLayout/partials/PageHeading/types.ts
src/components/v5/frame/PageLayout/types.ts
src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx
src/components/v5/shared/Breadcrumbs/index.ts
src/components/v5/shared/Breadcrumbs/types.ts
src/stories/frame/NavigationSidebar.stories.tsx
src/stories/frame/PageHeader.stories.tsx
src/stories/frame/PageLayout.stories.tsx
src/stories/shared/Breadcrumbs.stories.tsx

https://tw.auroracreation.com/app/tasks/15629286
Pull request includes:
- breadcrumbs - variant with link and dropdown
- page title
- space for user navigation inside the header
- changes in PageLayout component - PageHeader component was added and the interface updated

feat: page header

---

src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/AmountField/hooks.ts

https://tw.auroracreation.com/app/tasks/15639275

Adjust input width on mount with default value

---

src/components/v5/shared/SubNavigationItem/partials/NestedOptions.tsx

- Fixed issue with custom permission filters

Fix: filter with nested options

---

src/components/frame/Extensions/layouts/SharedLayout.tsx
src/components/v5/frame/PageLayout/PageLayout.tsx
src/redux/sagas/motions/paymentMotion.ts

Added connectWallet to layout

---

src/components/v5/shared/SearchSelect/hooks.ts

fix searching team by user name

---

src/components/v5/common/Fields/CardSelect/CardSelect.tsx

https://tw.auroracreation.com/app/tasks/15643415

Removed capitalize from card select selected option

---

src/components/v5/common/ActionSidebar/partials/DescriptionRow/DescriptionRow.tsx
src/components/v5/common/ActionSidebar/partials/DescriptionRow/index.ts
src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/AdvancedPaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/CreateDecisionForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/CreateNewTeamForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/EditColonyDetailsForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/UnlockTokenForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/UpgradeColonyForm.tsx

https://tw.auroracreation.com/app/tasks/15655927

fix: hiding description in motion when its empty

---

src/components/shared/Icon/Icon.tsx
src/components/v5/shared/IconWithTooltip/IconWithTooltip.tsx
src/components/v5/shared/IconWithTooltip/types.ts
src/components/v5/shared/SearchSelect/SearchSelect.tsx
src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
src/stories/shared/IconWithTooltip.stories.tsx

task: https://tw.auroracreation.com/app/tasks/15637012
Fixed UI issues with action type dropdown menu
Changes 🏗

Fix[15637012]: action type dropdown menu

---

src/components/v5/common/Fields/InputBase/InputBase.tsx
src/components/v5/common/Fields/InputBase/hooks.ts
src/components/v5/shared/SearchSelect/SearchSelect.tsx
src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
src/components/v5/shared/SearchSelect/partials/SearchInput/types.ts
src/i18n/en.json

I copied PR: https://github.com/JoinColony/colonyCDapp/pull/1272
(I couldn't do a rebase on the old branch because I had previously done a merge pull there)
Task: https://tw.auroracreation.com/app/tasks/15639563
Fixed issues with members dropdown menu
Changes 🏗

Fix[15639563]: members dropdown menu issues

---

src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/hooks.ts
src/components/v5/common/ActionSidebar/partials/UserSelect/types.ts

https://tw.auroracreation.com/app/tasks/15643399

Changed text color of selected user

---

src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
src/components/v5/common/Fields/TextareaBase/TextareaBase.tsx
src/components/v5/common/Fields/TextareaBase/hooks.ts
src/components/v5/common/Fields/TextareaBase/types.ts

https://tw.auroracreation.com/app/tasks/15647877

fix: amount decimals in payment description and field value

---

src/components/frame/Extensions/layouts/hooks.tsx
src/components/v5/frame/NavigationSidebar/NavigationSidebar.tsx
src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarContext/NavigationSidebarContext.tsx
src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarSecondLevel/NavigationSidebarSecondLevel.tsx
src/i18n/en.json

https://tw.auroracreation.com/app/tasks/15629286

feat: members related actions

---

src/components/frame/Extensions/layouts/hooks.tsx
src/i18n/en.json

feat: agreement actions

---

src/components/frame/Extensions/layouts/hooks.tsx
src/components/v5/frame/NavigationSidebar/consts.ts
src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarThirdLevel/NavigationSidebarThirdLevel.tsx

feat: admin actions

---

src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/AmountField/hooks.ts
src/components/v5/common/ActionSidebar/partials/AmountField/types.ts
src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/partials/AdvancedPaymentRecipentsField/hooks.tsx
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/TransferFundsForm.tsx
src/components/v5/common/Fields/InputBase/hooks.ts
src/utils/elements.ts

https://tw.auroracreation.com/app/tasks/15639275

Refactor input width adjustment logic in

---

docker/colony-cdapp-dev-env-block-ingestor
src/components/common/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx

Please see https://github.com/JoinColony/block-ingestor/pull/144 for details. In CDapp this PR simply updates the ingestor hash.
Resolves #991

Show Payment actions incoming funds

---

src/routes/LandingPageRoute/SimpleSidebar.tsx
src/routes/WizardRoute/WizardSidebar/WizardSidebar.tsx

- Updated the color of the border for the simple and wizard navbar
- Added missing styles to the "Visit our docs" link of the wizard sidebar
Contributes to #1279

Update styles of wizard sidebar

---

src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/ColonyDetailsFields.tsx
src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/CreateNewTeamForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
src/components/v5/common/Fields/InputBase/InputBase.tsx
src/components/v5/common/Fields/TextareaBase/TextareaBase.tsx

https://tw.auroracreation.com/app/tasks/15656927

Add message=false to FormTextareaBase components

---

src/components/v5/common/Checkbox/Checkbox.tsx
src/components/v5/common/Checkbox/types.ts
src/components/v5/shared/SubNavigationItem/partials/NestedOptions.tsx

Task: https://tw.auroracreation.com/app/tasks/15661617
**Changes** 🏗
before:
after:

Fix[15661617]: change color of checkboxes to blue when checked

---

src/components/common/ColonyFunding/ColonyFunding.tsx
src/components/frame/Extensions/layouts/consts.ts
src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx
src/context/PageHeadingContext/hooks.ts
src/i18n/en.json

https://tw.auroracreation.com/app/tasks/15577549
Small update to funding page:
- added proper link to navigation
- added breadcrumbs and page title according to design

fix: linked navigation, added breadcrumbs and page title

---

src/components/v5/common/Table/Table.tsx

Task: https://tw.auroracreation.com/app/tasks/15661617
**Changes** 🏗
before:
after:

Fix[15661617]: add horizontal line to verified members table

---

src/components/frame/v5/pages/VerifiedPage/partials/VerifiedTable/hooks.tsx

Task: https://tw.auroracreation.com/app/tasks/15661619
**Changes** 🏗
before:
after:

Fix[15661619]: remove left padding for "member" header

---

src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/TeamColourField/TeamColourField.tsx
src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/common/Fields/CardSelect/CardSelect.tsx
src/components/v5/shared/Avatar/Avatar.tsx
src/components/v5/shared/HoverWidthWrapper/HoverWidthWrapper.tsx
src/components/v5/shared/HoverWidthWrapper/index.ts
src/components/v5/shared/HoverWidthWrapper/types.ts
src/components/v5/shared/SearchSelect/SearchSelect.tsx
src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx

Task: https://tw.auroracreation.com/app/tasks/15637084
**Changes** 🏗
Examples of places that have been corrected:

Fix[15637084]: dropdown menus

---

amplify/backend/api/colonycdapp/schema.graphql
src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/partials/SocialLinksTable/partials/SocialLinkModal/consts.tsx
src/graphql/generated.ts

Add facebook to social links modal

---

src/hooks/members/useAllMembers.ts

Task: https://tw.auroracreation.com/app/tasks/15669633
**Changes** 🏗
before:
after:

fix: verified members table - show all users

---

amplify/backend/function/createPrivateBetaInvite/createPrivateBetaInvite-cloudformation-template.json
amplify/backend/function/createPrivateBetaInvite/function-parameters.json

Add complementary external layer

---

src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
src/components/v5/common/ActionSidebar/partials/TeamsSelect/types.ts
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/hooks.ts

https://tw.auroracreation.com/app/tasks/15670128

fix: mint token in root team only

---

src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
src/components/v5/common/ActionSidebar/partials/TeamColourField/TeamColourField.tsx
src/components/v5/common/ActionSidebar/partials/TeamsSelect/TeamsSelect.tsx
src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/common/Fields/CardSelect/CardSelect.tsx
src/components/v5/shared/PopoverBase/PopoverBase.tsx
src/components/v5/shared/SearchSelect/SearchSelect.tsx
src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
src/components/v5/shared/SearchSelect/types.ts

https://tw.auroracreation.com/app/tasks/15639357

feat: form dropdowns position on mobile updated

---

src/components/frame/Extensions/layouts/hooks.tsx
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/utils.tsx

https://tw.auroracreation.com/app/tasks/15622227

fix: remove token dropdown from value field in mint token form

---

src/components/v5/common/Pills/PillsBase.tsx
src/components/v5/common/Pills/UserStatus/UserStatus.tsx
src/components/v5/shared/Avatar/Avatar.module.css
src/components/v5/shared/UserAvatarDetails/UserAvatarDetails.tsx
src/components/v5/shared/UserPopover/partials/UserInfo.tsx

Task: https://tw.auroracreation.com/app/tasks/15661602
**Changes** 🏗
before:
after:

Fix[15661602]: user popover style issues

---

src/components/v5/shared/UserPopover/UserPopover.tsx

Task: https://tw.auroracreation.com/app/tasks/15660303
**Changes** 🏗

Fix[15660303]: UserPopover - border

---

src/components/frame/Extensions/layouts/hooks.tsx
src/components/v5/shared/CalamityBanner/CalamityBanner.tsx
src/components/v5/shared/CalamityBanner/partials/CalamityBannerContent.tsx

https://tw.auroracreation.com/app/tasks/15657574

fix: calamity banner upgrade colony version action in new ui

---

src/components/common/ColonyHome/ColonyHome.tsx
src/components/common/ColonyHome/hooks.ts
src/components/common/ColonyHome/types.ts
src/components/frame/Extensions/layouts/partials/DashboardContent/DashboardContent.tsx
src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
src/components/v5/common/ActionSidebar/partials/Motions/steps/OutcomeStep/partials/VoteStatuses/VoteStatuses.tsx
src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/hooks.ts
src/components/v5/common/Fields/CardSelect/CardSelect.tsx
src/components/v5/common/Fields/CardSelect/types.ts
src/components/v5/shared/Breadcrumbs/Breadcrumbs.tsx
src/components/v5/shared/Breadcrumbs/types.ts
src/components/v5/shared/UserAvatars/UserAvatars.tsx
src/components/v5/shared/UserAvatars/types.ts
src/context/MemberContext.tsx
src/hooks/useTeamsBreadcrumbs.ts
src/hooks/useUserAvatars/index.ts
src/i18n/en.json
src/routes/ColonyRoute.tsx
src/stories/common/WidgetBox.stories.tsx
src/stories/common/WidgetBoxList.stories.tsx
src/stories/shared/UserAvatars.stories.tsx
src/utils/urls.ts

https://tw.auroracreation.com/app/tasks/15662323

feat: added teams breadcrumbs

---

src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
src/utils/networkFee.ts

This PR fixes the bug described in the related issue. To test, create a payment action and confirm that the amount is shown without the network fee.
Resolves #1366

Network fee being added to total payout

---

src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
src/components/v5/common/ActionSidebar/partials/PopularActions.tsx

Task: https://tw.auroracreation.com/app/tasks/15665954
**Changes** 🏗
Resolved issues:
- The horizontal line should take the whole width.
- The paddings are not like on the design.
Before:
After:

Fix[15665954]: action sidebar paddings and horizontal line

---

amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js

Debug native funds claim lambda

---

.github/workflows/amplify.yaml
amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js

- Update amplify workflow to only trigger on master branch. Remove some console logs not required any longer.
**Changes** 🏗

cicd: fix amplify deploy branch, remove some amplify console logs

---

amplify/backend/function/validateUserInvite/src/graphql.js
amplify/backend/function/validateUserInvite/src/index.js

Hotfix for QA so that the validate user lamdba does not crash

Hotfix for user query's in validate user lamdba

---

amplify/backend/function/validateUserInvite/src/index.js

Fix user and contributor existence checks differ

Fix user and contributor existence checks differ

---

amplify/backend/function/validateUserInvite/src/index.js

This PR fixes the graphql input misalignments

Fix graphql request inputs misalignments

---

src/components/common/ColonyActions/ActionsListItem/ActionsListItem.tsx
src/components/common/ColonyHome/hooks.ts
src/components/common/Dialogs/ManageReputationDialog/ManageReputationDialog.tsx
src/components/common/Dialogs/PermissionManagementDialog/PermissionManagementCheckbox.tsx
src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransaction.tsx
src/components/frame/Extensions/layouts/ColonySidebar.tsx
src/components/frame/Extensions/layouts/MainSidebar.tsx
src/components/frame/Extensions/layouts/consts.ts
src/components/frame/Extensions/layouts/hooks.tsx
src/components/frame/Extensions/pages/LazyConsensusPage/LazyConsensusPageSetup.tsx
src/components/frame/v5/pages/MembersPage/AllMembersPage.tsx
src/components/frame/v5/pages/MembersPage/ContributorsPage.tsx
src/components/frame/v5/pages/MembersPage/MembersPage.tsx
src/components/frame/v5/pages/MembersPage/partials/MembersTabContent/MembersTabContent.tsx
src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingChart/StakingChart.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/hooks.ts
src/components/v5/shared/RichText/hooks.ts
src/components/v5/shared/SearchSelect/hooks.ts
src/components/v5/shared/SubNavigationItem/partials/NestedOptions.tsx
src/constants/permissions.ts
src/utils/intl.ts

fix: formatText now always returns a string

---

src/routes/RootRoute.tsx

Quick PR to completely disable dark mode until we get a chance to update the colors.
Resolves #1465

Quick PR to completely disable dark mode

---

src/components/common/ColonyHome/hooks.ts
src/components/common/Extensions/ThemeSwitcher/ThemeSwitcher.module.css
src/components/common/Extensions/ThemeSwitcher/ThemeSwitcher.tsx
src/components/common/Extensions/UserNavigation/partials/UserMenu/UserMenu.tsx
src/components/common/Extensions/UserNavigation/partials/UserSubmenu/UserSubmenu.tsx
src/components/common/Extensions/UserNavigation/partials/WalletConnectedTopMenu/WalletConnectedTopMenu.tsx
src/styles/main.global.css

Fixed the width being wrong on the disconnected state of user menu. 
Also tweaked a bit styles that weren't as aligned with the specs as they could have.
Resolves #1410

Tweak user menu styles

---

.github/workflows/amplify.yaml

cicd: add prod approval for amplify

---

src/components/frame/Extensions/layouts/ColonyLayout.tsx
src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/UserNavigationWrapper.tsx
src/components/frame/Extensions/layouts/partials/UserNavigationWrapper/types.ts

https://tw.auroracreation.com/app/tasks/15685309

fix: action sidebar moved to ColonyLayout component to avoid rerendering

---

amplify/backend/custom/lambdaParams/lambdaParams-cloudformation-template.json

fix: add env based condition for all relevant ssm params

---

.github/workflows/amplify.yaml

cicd: disable amplify auto deploy

---

src/components/common/InvitationBlock/InvitationBlock.tsx
src/components/frame/Extensions/layouts/ColonyLayout.tsx
src/components/v5/common/Modals/ColonyCreatedModal/ColonyCreatedModal.tsx

Pretty much what it says in the title.
Resolves #1518

Hide invite section of Colony Created Modal if user has no invites

---

.github/workflows/build-deploy.yaml

cicd: disable cdapp auto cicd

---

src/components/frame/v5/pages/MembersPage/hooks.ts
src/components/frame/v5/pages/MembersPage/utils.ts
src/components/v5/shared/UserPopover/partials/UserInfo.tsx
src/context/MemberContext.tsx
src/hooks/members/useColonyContributors.ts
src/hooks/members/useMemberFilters.ts

https://tw.auroracreation.com/app/tasks/15684419

feat: filter members by team

---

.env.example
.github/workflows/scripts/on-demand-env-script.sh
scripts/create-data.js
src/redux/sagas/utils/getNetworkClient.ts
src/redux/sagas/wallet/onboard.ts
webpack.dev.js

This PR adjusts the on-demand environment to all the things we've changed in between for production and makes it actually, truly work this time :)
You HAVE to set the `REPUTATION_ORACLE_ENDPOINT` variable in your `.env` file now. I did this to make it flexible and to make it consistent with the other variables.

On demand environment: adjust for new environment

---

src/components/common/ColonyHome/ColonyHome.tsx

fix: break-word in dashboard widgets

---

src/components/frame/v5/pages/UserAdvancedPage/partials/FeesForm/FeesForm.tsx
src/components/frame/v5/pages/UserAdvancedPage/partials/FeesForm/consts.ts
src/components/frame/v5/pages/UserAdvancedPage/partials/FeesForm/hooks.tsx
src/components/frame/v5/pages/UserAdvancedPage/partials/RpcForm/RpcForm.tsx
src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/consts.tsx
src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/utils.tsx
src/components/v5/common/Fields/Switch/FormSwitch.tsx
src/components/v5/common/Fields/Switch/Switch.tsx
src/components/v5/common/Fields/Switch/types.ts
src/components/v5/common/SettingsRow/SettingsRow.tsx
src/components/v5/common/SettingsRow/types.ts
src/transformers/index.ts

https://tw.auroracreation.com/app/tasks/15687548
[Recording 2023-12-11 125447.webm](https://github.com/JoinColony/colonyCDapp/assets/38806520/f0816514-eacd-4076-8fa7-abef9666205c)

Prefill user permissions and role on select, format data for display mode in Manage Permissions action

---

src/components/v5/shared/MeatBallMenu/MeatBallMenu.tsx

https://tw.auroracreation.com/app/projects/562144/tasks/15696323
Changes:
- fixed burger icon color

fix: 15696323 - kebab menu icon color

---

.github/workflows/amplify.yaml
.github/workflows/build-deploy.yaml

- Re enable auto deploy for cicd
**Changes** 🏗

cicd: enable auto deployments

---

src/components/common/Onboarding/wizardSteps/CreateColony/StepColonyNameInputs.tsx
src/components/common/Onboarding/wizardSteps/CreateColony/StepCreateTokenInputs.tsx
src/components/common/Onboarding/wizardSteps/CreateColony/TokenSelector.tsx
src/components/frame/v5/pages/FundsPage/partials/Filter/Filter.tsx
src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
src/components/v5/common/ActionSidebar/partials/DescriptionField/DescriptionField.tsx
src/components/v5/common/Fields/Input/Input.tsx
src/components/v5/common/Fields/Input/types.ts
src/components/v5/common/Fields/TextareaBase/FormTextareaBase.tsx
src/components/v5/common/Fields/TextareaBase/TextareaBase.tsx
src/components/v5/common/Fields/TextareaBase/types.ts
src/components/v5/common/Filter/partials/SearchInput/SearchInput.tsx
src/components/v5/shared/RichText/RichText.tsx
src/components/v5/shared/RichText/hooks.ts
src/components/v5/shared/RichText/types.ts
src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
src/components/v5/shared/SearchSelect/partials/SearchInput/types.ts

This PR introduces automatic focus on the fields specified in the issue. It also deals with a console warning that appeared every time the description field was expanded.
Resolves #1511

Focus on key inputs

---

src/components/common/ColonyHome/ColonyHome.tsx
src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/ExitRecoveryStep/ExitRecoveryStep.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/RevealStep.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/RevealStep/partials/RevealInformationItem/RevealInformationItem.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/VotingStep/VotingStep.tsx
src/components/v5/shared/ProgressBar/ProgressBar.tsx
src/components/v5/shared/Stepper/Stepper.tsx
src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
src/components/v5/shared/Stepper/partials/StepperButton/consts.ts
src/components/v5/shared/Stepper/partials/StepperButton/types.ts
src/images/icons/eye-closed.svg
src/stories/shared/StepperButton.stories.tsx

Adds various style fixes to motions as listed out here https://github.com/JoinColony/colonyCDapp/issues/1480 including an additional fix for the 0 appearing when the voting threshold progress bar loads.
Resolves #1480

Motion styling fixes #2

---

src/redux/sagas/colony/colonyCreate.ts

This PR removes the extra Token Client call to `setTokenAuthority` as it's already being sent, behind the scenes by the bundled call of `createColonyForFrontend`, meaning the second call changes nothing while incurring gas costs.
A secondary implication here is that due to how the Metatransactions broadcaster works, this call would actually fail each time, since permissions for it would no longer be available due to the first call going through.
Resolves #1597

Remove `SetTokenAuthority` from the Colony Creation flow

---

src/components/common/Extensions/SpecificSidePanel/partials/InstalledBy.tsx
src/components/frame/v5/pages/VerifiedPage/partials/MemberAvatar/MemberAvatar.tsx
src/components/shared/Avatar/Avatar.tsx
src/components/v5/common/ActionSidebar/hooks/useActionDescriptionMetadata.tsx
src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/PermissionSidebar.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/common/MemberCard/MemberCard.tsx
src/components/v5/shared/Avatar/types.ts
src/components/v5/shared/CardWithBios/CardWithBios.tsx
src/components/v5/shared/NotificationBanner/NotificationBanner.tsx
src/components/v5/shared/NotificationBanner/types.ts
src/components/v5/shared/UserAvatarDetails/UserAvatarDetails.tsx
src/components/v5/shared/UserAvatarDetails/types.ts
src/components/v5/shared/UserAvatarPopover/UserAvatarPopover.tsx
src/components/v5/shared/UserAvatarPopover/types.ts
src/components/v5/shared/UserPopover/UserPopover.tsx
src/components/v5/shared/UserPopover/partials/UserInfo.tsx
src/components/v5/shared/UserPopover/types.ts
src/components/v5/shared/UserPopoverAdditionalContent/UserPopoverAdditionalContent.tsx
src/components/v5/shared/UserPopoverAdditionalContent/index.ts
src/components/v5/shared/UserPopoverAdditionalContent/types.ts
src/stories/shared/UserAvatarPopover.stories.tsx

In every place where UserPopover is used, it should look the same.
**Changes** 🏗

Fix[15678862]: user popover

---

.github/workflows/build-deploy.yaml
Dockerfile

- Refactor docker file to be more efficient at cache and enable gh actions cache.
**Changes** 🏗

Enable gh actions cache

---

src/components/common/ColonyActionsTable/hooks.tsx
src/components/v5/common/Table/Table.tsx

https://tw.auroracreation.com/app/tasks/15695838
**Changes** 🏗
* Fixed table height on firefox
* Fixed actions table first row width on safari
Resolves [1585](https://github.com/JoinColony/colonyCDapp/issues/1585)

fix: table height, first action table row width

---

amplify/backend/function/createUniqueColony/src/index.js

https://tw.auroracreation.com/app/tasks/15637188
**Changes** 🏗
* Changed `root` team name to `general`. This change won't affect current colonies and will start working on new ones.
Resolves [1612](https://github.com/JoinColony/colonyCDapp/issues/1612)

fix: changed root team name to general

---

src/hooks/useCurrency.ts
src/utils/currency/currency.ts
src/utils/currency/types.ts

Master build was breaking so might as well fix it in a separate PR.

lint: currency hook, fixed breaking build

---

src/components/common/ColonyActions/helpers/getActionTitleValues.ts
src/components/v5/common/ActionSidebar/hooks/useActionDescriptionMetadata.tsx
src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/utils.tsx
src/components/v5/common/ActionSidebar/types.ts

Fix the `ManageObjective` action not displaying correctly. 
Making the title show up correctly required a workaround, if you have a better idea of doing it, open to suggestions :)
Created an issue for reworking our action form titles #1669
**Changes** 🏗
* Added display support for manage an objective action
Resolves #1524

fix: display of manage objective action

---

src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/PermissionSidebar.tsx

Removing stepped navigation for all forced actions 
Resolves #1556

Removing stepped navigation for all forced actions 

---

src/components/frame/Extensions/layouts/ColonyLayout.tsx
src/components/frame/Extensions/layouts/ColonySidebar.tsx
src/components/frame/Extensions/layouts/hooks.tsx

https://tw.auroracreation.com/app/tasks/15729070
**Changes** 🏗
* Now it's possible to create a new action when the ActionPanel is open with a transaction
Resolves [1663](https://github.com/JoinColony/colonyCDapp/issues/1663)

fix: added new action button logic to close sidebar

---

src/components/v5/common/MemberCardList/MemberCardList.tsx

https://tw.auroracreation.com/app/tasks/15693951
**Changes** 🏗
* Changed grid layout for members list on smaller desktops if there is less than 3 items
Resolves [1664](https://github.com/JoinColony/colonyCDapp/issues/1664)

fix: changed grid layout on smaller desktops

---

scripts/create-data.js

I have noticed the `create-data` script failing due to not being able to get colony metadata in time. This PR increases the max retries for the query to match the ingestor's value.

Increase create-data query max retries

---

amplify/backend/function/fetchColonyBalances/src/index.js
amplify/backend/function/fetchVoterRewards/src/utils.js
amplify/backend/function/getMembersForColony/amplify.state
amplify/backend/function/getUserReputation/src/index.js
amplify/backend/function/getUserTokenBalance/src/index.js
amplify/backend/function/updateContributorsWithReputation/src/index.js

This small PR adds logging to what previously was a silent try/catch block. In the past the silenced errors were not the "expected" ones and we had a hard time debugging it without proper logs.
Resolves #1580

Introduce lambda logging

---

scripts/create-data.js

With the introduction of temporary colony metadata in the database on colony creation (#1513), we created a race condition. I believe this is present in the frontend as well, but this fixes it for the `create-data` script, at least, to avoid issues that both myself and Chris have been seeing intermittently (as you'd expect with a race condition) with the script - for example:  
```
2024-01-16T15:42:02.022+02:00    ingestor | 2024-01-16T13:42:01.342Z Processing block 315
2024-01-16T15:42:04.028+02:00    ingestor | 2024-01-16T13:42:01.856Z Block 943 added to the queue
2024-01-16T15:42:04.028+02:00    ingestor | 2024-01-16T13:42:03.948Z Could not find metadata for colony 0x1133560dB4AebBebC712d4273C8e3137f58c3A65. Skipping...
```
Previously, we broadcast the transaction, then …

Fix create data race condition on colony creation

---

src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx

https://github.com/JoinColony/colonyCDapp/issues/1577
Added a fallback to get user data from user select options array to avoid the jumping effect after selecting a user from the dropdown.

fix: get user data from user select options fallback

---

src/components/v5/common/ActionSidebar/consts.tsx
src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/EnterRecoveryModeForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/consts.tsx
src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/TransferFundsForm/hooks.ts
src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/UpgradeColonyForm/consts.ts
src/components/v5/shared/RichText/RichText.tsx
src/components/v5/shared/RichText/hooks.ts
src/components/v5/shared/RichText/partials/RichTextContent/RichTextContent.module.css
src/components/v5/shared/RichText/partials/RichTextContent/RichTextContent.tsx
src/components/v5/shared/RichText/partials/RichTextContent/index.ts
src/components/v5/shared/RichText/partials/RichTextContent/types.ts
src/utils/elements.ts

Fixes some of the issues from #1611
The only issue left is clipping the content to 2 lines when it is not expanded.

Added proper richtext styles

---

src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/hooks.ts
src/components/v5/common/ActionSidebar/partials/DescriptionRow/DescriptionRow.tsx
src/components/v5/common/ObjectiveBox/ObjectiveBox.tsx

Small PR to fix existing linting issues in `master`, which brings us one step closer to disabling merges when checks fail.

Fix: Linting issues in `master`

---

src/components/v5/common/CompletedAction/partials/TransferFunds/TransferFunds.tsx
src/components/v5/common/CompletedAction/partials/rows/CreatedIn.tsx
src/components/v5/common/CompletedAction/partials/rows/TeamFrom.tsx

**Changes** 🏗
* Team badges property names got changed but somehow this wasn't adjusted

Fix team badges props

---

src/components/frame/v5/pages/VerifiedPage/partials/MemberAvatar/MemberAvatar.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/common/MemberCard/MemberCard.tsx
src/components/v5/common/Table/Table.tsx
src/components/v5/shared/Modal/ModalBase.tsx
src/components/v5/shared/UserAvatarPopover/UserAvatarPopover.tsx
src/components/v5/shared/UserPopover/UserPopover.tsx

https://tw.auroracreation.com/app/tasks/15660303
https://tw.auroracreation.com/app/tasks/15678862
Changes:
- added missing info in popover about not verified user
- added missing border in modal for top contributor type

add missing banner; purple border on mobile;

---

src/components/frame/v5/pages/FundsPage/partials/Filter/Filter.tsx
src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/hooks.ts
src/components/v5/common/ActionSidebar/partials/DescriptionRow/DescriptionRow.tsx
src/components/v5/common/Fields/InputBase/InputBase.tsx
src/components/v5/common/ObjectiveBox/ObjectiveBox.tsx
src/components/v5/common/Table/Table.tsx

https://tw.auroracreation.com/app/tasks/15741061
**Changes** 🏗
* Removed default input outline on focus
* Hide pagination while there is no enough items
Resolves [1695](https://github.com/JoinColony/colonyCDapp/issues/1695)

fix: input outline, hide pagination

---

src/components/common/ColonyActionsTable/hooks.tsx

Teamwork: https://tw.auroracreation.com/app/tasks/15750743
Corrected Activity feed share link
Resolves: #1737

fix: correct activity feed share link

---

src/components/v5/common/ActionFormRow/ActionFormRow.tsx

https://tw.auroracreation.com/app/tasks/15750753
**Changes** 🏗
* Change color for field label on error
Resolves #1735

fix: field label error color

---

src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx

https://tw.auroracreation.com/app/tasks/15753997
**Changes** 🏗
* Moved tooltip from SearchItem out of relative scope of button
Resolves #1720

fix: SearchItem relative wrapper

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a "Testing" section to the PR template so it's easier to adopt/maintain the habit of detailing for reviewers how to test the pr and what to expect

Add: Testing section to pr template

---

src/components/v5/shared/SearchSelect/SearchSelect.tsx
src/i18n/en.json

Changed placeholder for teams dropdown
Resolves: https://github.com/JoinColony/colonyCDapp/issues/1738

fix: change input placeholder for teams dropdown

---

src/components/common/Extensions/UserHubButton/UserHubButton.tsx
src/components/common/Extensions/UserNavigation/UserNavigation.tsx
src/components/common/Extensions/UserNavigation/partials/HeaderAvatar/HeaderAvatar.tsx
src/components/common/Extensions/UserNavigation/partials/Token/Token.tsx
src/components/common/Extensions/UserNavigation/partials/Token/types.ts
src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/ColonySwitcherContent.tsx
src/components/frame/Extensions/pages/PermissionsPage/hooks.tsx
src/components/v5/frame/NavigationSidebar/partials/NavigationSidebarMobileContentWrapper/NavigationSidebarMobileContentWrapper.tsx

https://tw.auroracreation.com/app/tasks/15787761
- Fixed UI styles for colony switcher on mobile
Resolves [1893](https://github.com/JoinColony/colonyCDapp/issues/1893)

fix: styles on mobile for main nav

---

src/components/common/Extensions/UserNavigation/partials/HeaderAvatar/HeaderAvatar.tsx

https://tw.auroracreation.com/app/tasks/15800401
- Fixed user avatar on pages without ColonyContext
Resolves [1942](https://github.com/JoinColony/colonyCDapp/issues/1942)

fix: user avatar on not colony pages

---

src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/ColonySwitcherContent.tsx

https://github.com/JoinColony/colonyCDapp/issues/1926
https://github.com/JoinColony/colonyCDapp/issues/1932

fix: colony switcher ui issue fix, header z-index update

---

src/stories/common/MemberCard.stories.tsx
src/stories/common/MemberCardList.stories.tsx

I fixed some imports so that the stories build again
Run `npm run storybook`
**Changes** 🏗
* Fixed some import paths

Fix story build

---

package-lock.json
src/components/frame/v5/pages/FundsPage/partials/Filter/types.ts
src/components/frame/v5/pages/TeamsPage/TeamsPage.tsx
src/components/frame/v5/pages/TeamsPage/hooks.tsx
src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/FilterItem.tsx
src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/TeamsPageFilter.tsx
src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/index.ts
src/components/frame/v5/pages/TeamsPage/partials/TeamsPageFilter/types.ts
src/components/frame/v5/pages/TeamsPage/types.ts
src/components/v5/common/EmptyContent/EmptyContent.tsx
src/components/v5/shared/Accordion/partials/AccordionItem/AccordionItem.tsx
src/components/v5/shared/Button/ButtonContent.tsx
src/components/v5/shared/Button/CloseButton.tsx
src/components/v5/shared/Button/types.ts
src/components/v5/shared/Filter/FilterButton.tsx
src/i18n/en.json

https://tw.auroracreation.com/app/tasks/15716167
- Added filters to teams page
Resolves [1617](https://github.com/JoinColony/colonyCDapp/issues/1617)

feat: added teams page filter

---

src/components/frame/Extensions/layouts/consts.ts
src/components/frame/Extensions/layouts/hooks.tsx
src/components/frame/Extensions/pages/PermissionsPage/IndividualPermissionsPage.tsx
src/components/frame/Extensions/pages/PermissionsPage/hooks.tsx
src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageRow.tsx
src/components/v5/common/MemberCard/MemberCard.tsx

https://tw.auroracreation.com/app/tasks/15763226
https://tw.auroracreation.com/app/tasks/15577569
**Changes** 🏗
* Member popover position changed to left instead of center
* Changed copy
* Moved permissions link to members menu
* Permission page loading

fix: popover position, loading, copy, menu item

---

src/components/frame/v5/pages/TeamsPage/TeamsPage.tsx
src/components/frame/v5/pages/TeamsPage/hooks.tsx
src/components/v5/common/TeamCard/TeamCard.tsx
src/components/v5/common/TeamCard/types.ts
src/components/v5/common/TeamCardList/TeamCardList.tsx

https://tw.auroracreation.com/app/tasks/15716167
https://tw.auroracreation.com/app/tasks/15795749
- Fixed mobile view grid
- Added search by team description
- Hide default filter pill

fix: mobile grid, search by description

---

src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/consts.ts
src/components/v5/frame/PageLayout/PageLayout.tsx
src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
src/components/v5/shared/ActionTypeNotification/types.ts
tailwind.config.js

tw tasks:
- [https://tw.auroracreation.com/app/tasks/15800786](https://tw.auroracreation.com/app/tasks/15800786)
- [https://tw.auroracreation.com/app/tasks/15692563](https://tw.auroracreation.com/app/tasks/15692563)
- [https://tw.auroracreation.com/app/tasks/15795751](https://tw.auroracreation.com/app/tasks/15795751)
- Added custom validation to description field because it was counting with HTML tags
- Fixed flashing permissions banner
- Reseting `decision method` field on action change
- Fixed padding on pages
- Meatball menu position on mobile

fix: desc validation, page layout margin, banner flash, menu position

---

src/components/frame/v5/pages/AgreementsPage/partials/DraftCard/DraftCard.tsx
src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
src/components/v5/frame/PageLayout/PageLayout.tsx
src/components/v5/shared/UserAvatars/UserAvatars.tsx

https://tw.auroracreation.com/app/tasks/15825815
- Fixed header and buttons in action sidebar on mobile
- draft agreement card line clamp
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2027](https://github.com/JoinColony/colonyCDapp/issues/2027)

fix: action header, buttons

---

src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
src/components/v5/common/CompletedAction/CompletedAction.tsx
src/components/v5/shared/Stepper/Stepper.tsx
tailwind.config.js

[https://tw.auroracreation.com/app/tasks/15833592](https://tw.auroracreation.com/app/tasks/15833592)
- Moved motion and permission widget to the top of action sidebar on mobile
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2042](https://github.com/JoinColony/colonyCDapp/issues/2042)

fix: moved motion/permission widget to the top on mobile

---

src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/CurrentUser.tsx
src/components/v5/common/ActionSidebar/partials/UserSelect/UserSelect.tsx
src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
src/components/v5/shared/UserPopover/UserPopover.tsx
src/components/v5/shared/UserPopover/types.ts

https://github.com/JoinColony/colonyCDapp/issues/2052

User verification status badge in select member dropdown

---

src/components/v5/common/ActionSidebar/partials/Motions/consts.ts
src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx
src/components/v5/common/Fields/RadioButtons/ButtonRadioButtons/ButtonRadioButtons.tsx
src/components/v5/common/Fields/RadioButtons/ButtonRadioButtons/types.ts
src/stories/shared/ButtonRadioButtons.stories.tsx

https://github.com/JoinColony/colonyCDapp/issues/2055
Updated colors for radio buttons

fix: staking widget radio buttons colors

---

src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
src/components/v5/shared/Stepper/partials/StepperTooltip/StepperTooltip.tsx
src/components/v5/shared/Stepper/partials/StepperTooltip/index.ts
src/components/v5/shared/Stepper/partials/StepperTooltip/types.ts
src/hooks/useRelativePortalElement.ts

- Changed tooltip so it's displaying under pill
Resolves [https://tw.auroracreation.com/app/tasks/15839358](https://tw.auroracreation.com/app/tasks/15839358)

fix: added new tooltip for motion on mobile

---

src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
src/components/v5/shared/Stepper/partials/StepperButton/types.ts

- Changed colors of outcome pill
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2056](https://github.com/JoinColony/colonyCDapp/issues/2056)

fix: changed outcome pill colors

---

src/components/v5/common/ActionSidebar/ActionSidebar.tsx
src/components/v5/common/ActionSidebar/hooks/useGetExpenditureData.ts
src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderPayoutsTotal/PaymentBuilderPayoutsTotal.tsx
src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderPayoutsTotal/types.ts
src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/hooks.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StepDetailsBlock/StepDetailsBlock.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StepDetailsBlock/types.ts
src/components/v5/common/CompletedAction/partials/rows/PaymentBuilderTable/AmountField.tsx
src/components/v5/common/CompletedAction/partials/rows/PaymentBuilderTable/PaymentBuilderTable.tsx
src/components/v5/common/CompletedAction/partials/rows/PaymentBuilderTable/types.ts

- Added logic to lock the expenditure when in review mode
* Step 1. Create Payment Builder Action
* Step 2. Click "Confirm details" button on the right
* handling lock expenditure functionality
**Changes** 🏗
* buttonProps from StepDetailsBlockProps extended with ActionButtonProps
* payouts array passed to PaymentBuilderTokensTotal updated to contain tokenAddress
* no deletions
Contributes https://github.com/JoinColony/colonyCDapp/issues/2005

feat: handle lock expenditure

---

src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts

- Opens the Release payment modal with the users possible decision methods
- If funded, the owner can release the funds for the payment, starting the claim delay.
- If any claim delays are 0, then those payments will happen immediately on release and also release the creators stake if present.
- Alternatively, users can use available decision methods, including "Admin" tiered permissions or higher (Arbitration on the contracts)

feat: release overview content

---

amplify/backend/custom/lambdaParams/lambdaParams-cloudformation-template.json

- Update lambda ssm for gnosis domain
**Changes** 🏗

fix: update lambda ssm params for new gnosis domain

---

src/components/frame/v5/pages/ActivityPage/ActivityPage.tsx
src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
src/components/v5/common/ActionSidebar/partials/MembersTable/MembersTable.tsx
src/components/v5/common/Table/Table.tsx
src/components/v5/frame/ColonyHome/ColonyHome.tsx
src/components/v5/shared/MeatBallMenu/MeatBallMenu.tsx

- Removed horizontal line on activity table on mobile
- Balance table issues on mobile
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2134](https://github.com/JoinColony/colonyCDapp/issues/2134) and [https://github.com/JoinColony/colonyCDapp/issues/2135](https://github.com/JoinColony/colonyCDapp/issues/2135)

fix: activity, balance, members table ui

---

src/components/frame/Extensions/layouts/partials/ColonySwitcherContent/hooks.ts
src/components/frame/v5/pages/UserProfilePage/partials/UserAccountForm/hooks.tsx
src/components/frame/v5/pages/UserProfilePage/partials/UserAccountPage/hooks.tsx
src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/utils.ts
src/context/AppContext/AppContext.ts
src/context/AppContext/AppContextProvider.tsx
src/hooks/useJoinedColonies.ts
src/redux/sagas/actions/addVerifiedMembers.ts
src/redux/sagas/actions/removeVerifiedMembers.ts
src/utils/members.ts

User avatar changes were not reflected in the UI until the page was refreshed.
1. Verify that the avatar changes in the members tab when you change it
2. Verify that verified member checkmark appears when adding verified members via permissions
3. Verify that verified member checkmark appears when adding verified members via reputation
4. Verify that verified member checkmark disappears when removing verified members via permissions
5. Verify that verified member checkmark disappears when removing verified members via reputation
* `updateMemberVerifiedStatus` helper
* `updateMemberProfile` helper
**Changes** 🏗
* `updateContributorQueries` now merges existing data with new data passed in
Resolves #2173

fix: when user changes their avatar, it gets reflected in the app

---

src/components/v5/shared/UserInfoPopover/UserInfoPopover.tsx
src/components/v5/shared/UserInfoPopover/partials/UserInfo.tsx

Update the paddings in the User Popover Card UI to match the Figma designs.
Check the user popover cards for each of the states:
* Top
* Dedicated
* Active
* New
* plus unverified for each of the above
**Changes** 🏗
* Update the markup and classnames in the UserInfo
Resolves #2259

Update user popover card UI

---

src/components/v5/common/ActionSidebar/partials/forms/UnlockTokenForm/UnlockTokenForm.tsx
src/components/v5/common/CompletedAction/partials/UnlockToken/UnlockToken.tsx
src/components/v5/common/CompletedAction/partials/rows/ActionData.tsx
src/i18n/en.json

Token readonly field added to `Unlock token` action
* Step 1. Create `Unlock token` action
* Step 2. Check completed state
* new rows with token data added to the form and to completed action component
**Changes** 🏗
* 
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2312

feat: unlock token action additional field

---

amplify/backend/function/fetchTokenFromChain/src/index.js

As always, when dealing with an ERC-20 token, I will rant about it's lax standard implementation: https://ethereum.org/en/developers/docs/standards/tokens/erc-20/
Due to the way it's set up and "valid" and "standard" token is a contract that is not required to have a "name", a "symbol" or "decimal" places. These are basic values everyone in the crypto world got to accept and expect.
It's mind boggling to me that these are not enforced.
This is exactly what happened in this case, we've had to deal with a token that didn't have decimal places, and the `decimal()` method on the contract did not exist.
Due to that, our lambda failed to fetch, and fail to save the token in the dabase, breaking some colonies in the process.
This fix puts in fallback values for all three: name, symbol and …

Fetch Tokens Lambda Handle "Irregular" Token Contracts

---

src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/PaymentBuilderDescription.tsx
src/components/v5/common/ActionSidebar/partials/Motions/Motions.tsx
src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/PaymentBuilderTable.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderTable/partials/ClaimStatusBadge/ClaimStatusBadge.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/partials/PaymentItem/PaymentItem.tsx
src/components/v5/common/MemberCard/MemberCard.tsx
src/components/v5/shared/Stepper/Stepper.tsx
src/components/v5/shared/Stepper/partials/StepperButton/StepperButton.tsx
src/components/v5/shared/UserInfoPopover/UserInfoPopover.tsx
src/i18n/en.json

- Payment builder UI fixes, check issue for more details.
Resolves issues from 1 to 6 [https://github.com/JoinColony/colonyCDapp/issues/2255](https://github.com/JoinColony/colonyCDapp/issues/2255)

fix: payment builder ui fixes part 1

---

src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentStepDetailsBlock/PaymentStepDetailsBlock.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/ReleasePaymentModal.tsx
src/components/v5/shared/Button/ActionButton.tsx
src/components/v5/shared/Button/types.ts

- In this PR I've fixed only UI part. Jakub told me to put the rest on hold and he will fix rejection/fail action.
* Create payment builder action
* Check for pending buttons instead of spinners
**Changes** 🏗
* Changed default spinner with pending button
- Handle action reject/fail
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2389](https://github.com/JoinColony/colonyCDapp/issues/2389)

fix: pending button ui, release modal box

---

src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/FileUploadModal/FileUploadModal.tsx
src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/FileUploadModal/types.ts
src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/PaymentBuilderRecipientsField/PaymentBuilderRecipientsField.tsx
src/i18n/en.json

- Changed error message and condition to show error
* Open payment builder action
* After changing data in any row error should show in CSV upload modal
Resolves [https://github.com/JoinColony/colonyCDapp/issues/2425](https://github.com/JoinColony/colonyCDapp/issues/2425)

fix: changed batch error logic

---

docker/colony-cdapp-dev-env-block-ingestor

This PR updates ingestor hash to point at [block-ingestor#203](https://github.com/JoinColony/block-ingestor/pull/203).
See ingestor PR for details.

Refactor: block-ingestor event listeners

---

src/components/v5/common/CompletedAction/partials/Blocks/Blocks.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx

Updated mobile styles for completed action subtitle
* Step 1. Create an action
* Step 2. When in a completed state, check the mobile view
* 
**Changes** 🏗
* `ActionSubtitle` component styles update
* `UserPopover` component replaced with `UserInfoPopover` component in `PaymentBuilder` component (completed action)
* 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2495

fix: action subtitle alignment on mobile

---

docker/colony-cdapp-dev-env-block-ingestor

Please see [block-ingestor#238](https://github.com/JoinColony/block-ingestor/pull/238) for details and testing instructions.

Fix: ingestor possibly skipping some events

---

src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx
src/routes/routeConstants.ts

Feat: Add search param for triggering verification modal
**Changes** 🏗

Feat: Add search param for triggering verification modal

---

amplify/backend/function/bridgeXYZMutation/src/handlers/checkKyc.js
docker/colony-cdapp-dev-env-mocking

Make things more accurate to production

Hackathon existing kyc

---

src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/partials/FileUploadModal/hooks.ts

This PR just updates the url we're adding to the CSB template that we generate via `useCSVFileTemplate`

Update CSV template URL

---

docker/colony-cdapp-dev-env-mocking

fix commit hash

---

src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetails/BankDetails.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/KYCModal/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/RowItem/RowItem.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/RowItem/types.ts
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/consts.ts
src/components/v5/common/Pills/PillsBase.tsx
src/components/v5/common/Pills/types.ts
src/graphql/generated.ts
src/graphql/mutations/bridgeXYZ.graphql

Fix: update user account modals and state pills for crypto to fiat feature

Fix: update user account modals

---

amplify/backend/api/colonycdapp/schema.graphql
src/graphql/generated.ts

Fix drains

---

src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/constants.ts
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/validation.ts
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/ContactDetailsForm/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FormInput.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FormSelect.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/PersonalDetailsForm/index.tsx
src/components/v5/common/Fields/Select/Select.tsx
src/components/v5/common/Fields/Select/SelectBase.tsx

Hackathon fix:  validation bug, console errors, add iban and bic validation

---

src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/ContactDetailsForm/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/ContactDetailsForm/validation.ts
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FormDatepicker.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/utils.ts
src/components/v5/common/Fields/InputBase/InputBase.tsx
src/components/v5/common/Fields/InputBase/types.ts
src/components/v5/common/Fields/Select/Select.module.css
src/components/v5/common/Fields/datepickers/Datepicker/Datepicker.tsx
src/components/v5/common/Fields/datepickers/Datepicker/partials/DatepickerCustomInput/DatepickerCustomInput.tsx

feat: implement date picker for birth date field

---

src/components/common/Extensions/UserHub/UserHub.tsx
src/components/frame/FourOFour/FourOFour.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/CryptoToFiatPage.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/constants.ts
src/components/frame/v5/pages/UserProfilePage/UserProfilePage.tsx
src/context/FeatureFlagsContext/FeatureFlagsContext.ts
src/context/FeatureFlagsContext/useFeatureFlag.ts

Add loading state for feature flags

Fix: Add loading state for feature flags

---

docker/colony-cdapp-dev-env-block-ingestor
scripts/create-data.js
src/components/frame/Extensions/pages/ColonyDetailsPage/ColonyDetailsPage.tsx
src/components/v5/common/ActionSidebar/partials/ColonyDetailsFields/ColonyDetailsFields.tsx
src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/consts.ts
src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/utils.tsx
src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/utils.tsx
src/components/v5/common/CompletedAction/CompletedAction.tsx
src/components/v5/common/CompletedAction/partials/UpgradeColonyObjective/UpgradeColonyObjective.tsx
src/components/v5/common/CompletedAction/partials/rows/ActionType.tsx
src/constants/index.ts
src/i18n/en-actions.ts
src/redux/sagas/motions/editColonyMotion.ts
src/redux/types/actions/motion.ts
src/types/actions.ts
src/types/transactions.ts
src/utils/colonyActions.ts
src/utils/motions.ts
src/utils/multiSig.ts

Create and finalize a multi-sig edit colony details and manage colony objective motions.
Check Edit Colony details motion and Manage objective motion can be created with both Multi-Sig and Permissions decision method.
* Step 1. Install Multi-Sig extension
* Step 2. Create new action - Edit Colony details 
* Step 3. Select Multi-Sig decision method
* Step 4. Update Colony description field
* Step 5. Create action
* Step 6. Finalise action - only for Multi-Sig
* Step 7. Check colony description was updated on dashboard
* Step 8. 🔁 Repeat above steps for the Permissions decision method 🔁
* Step 1. Install Multi-Sig extension
* Step 2. Create new action - Manage objective
* Step 3. Select Multi-Sig decision method
* Step 4. Update Objective description field
* Step 5. Create action
* Step 6. …

Feat: Edit colony description and objective for multi-sig

---

docker/colony-cdapp-dev-env-reputation-monitor

Updates the reputation monitor to include https://github.com/JoinColony/reputation-monitor-dev/pull/2
Start the dev environment and run the create-data script

fix: update reputation monitor to increase resilience

---

amplify/backend/api/colonycdapp/schema.graphql
amplify/backend/function/bridgeXYZMutation/src/handlers/checkKyc.js
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetails/BankDetails.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsForm/validation.ts
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/index.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/BankDetailsModal/useBankDetailsFields.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/types.ts
src/graphql/generated.ts
src/graphql/mutations/bridgeXYZ.graphql

feat: add update bank details prefilled values

---

.github/workflows/build-deploy.yaml

cicd: update gh workflow to arbitrum envs

---

src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/utils.ts
src/components/v5/common/CompletedAction/partials/CompletedExpenditureContent/CompletedExpenditureContent.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/StagedPaymentTable.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/partials/ReleaseAllButton/ReleaseAllButton.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentTable/types.ts

- Added preview to created staged payment action
- This PR includes only UI, logic will be handled in next one
- Includes preview action part of scope described in https://github.com/JoinColony/colonyCDapp/issues/2669
* Make sure you have the Staged payment extension installed.
* Create and complete stage payment action
* Check UI of left side of the action sidebar 
* To see release and release all buttons, you have to review and fund - buttons are visible only in release step

feat: staged payment preview

---

src/components/v5/common/CompletedAction/partials/PaymentBuilder/PaymentBuilder.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/CancelModal/CancelModal.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
src/context/PaymentBuilderContext/PaymentBuilderContext.ts
src/context/PaymentBuilderContext/PaymentBuilderContextProvider.tsx

- Added canceling of staged payment action
- Issue https://github.com/JoinColony/colonyCDapp/issues/2669
* Create staged payments action
* Cancel before or after review step using Permission

feat: add cancel to staged payment

---

amplify/backend/api/colonycdapp/schema/schema.graphql
docker/colony-cdapp-dev-env-block-ingestor
src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/ManageTokensForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/utils.ts
src/components/v5/common/CompletedAction/CompletedAction.tsx
src/components/v5/common/CompletedAction/partials/ManageTokens/ManageTokens.tsx
src/constants/actionsFilters.ts
src/context/ExtensionSaveSettingsContext/ExtensionSaveSettingsContextProvider.tsx
src/graphql/generated.ts
src/i18n/en-actions.ts
src/redux/sagas/motions/manageTokens.ts
src/redux/types/actions/motion.ts
src/utils/multiSig/index.ts

[block-ingestor counterpart](https://github.com/JoinColony/block-ingestor/pull/265)
This PR refactors the manage tokens motion saga to handle multi-sig, and makes the other necessary changes to support manage tokens via multi-sig.
Step 1 - Install the multi-sig extension
Step 2 - Assign Owner Multi-Sig permissions to Leela and Amy.
Step 3 - Create a manage tokens action, select multi-sig as the decision method and change the approved tokens.
Step 4 - Submit the form, check the completed action and multi-sig widget components show as expected (check the title, subtitle, action type, decision method)
Step 5 - Check the custom title shows correctly in the activity feed:
Step 6 - Check the activity shows in the activity feed when the manage tokens activity type filter is selected.
Step 7 - …

Feat: Implement manage tokens via multi-sig

---

src/components/common/Extensions/Fields/InputGroup/InputGroup.tsx
src/components/common/Extensions/Fields/RadioList/RadioBase.tsx
src/components/frame/Extensions/pages/MultiSigPage/MultiSigPageSetup.tsx
src/components/frame/Extensions/pages/MultiSigPage/hooks.ts
src/components/v5/common/Fields/Select/Select.module.css

Users without Owner permissions shouldn't be able to change multi-sig extension settings
Check multi-sig extension settings are disabled and Save settings button is not visible if user doesn't have owner permissions.
* Step 1. Install Multi-Sig extension as `leela`
* Step 2. Check 'Save settings' button is in place and settings options are enabled
* Step 3. Select `Fixed threshold` for Serenity and insert `3` approvals (please feel free to choose any other team but make sure to have at least one with a fixed threshold with a custom value)
* Step 4. In an incognito browser, connect as `amy`
* Step 5. Go to Admin > Extensions > Multi-sig Permissions > Extension settings tab
* Step 6. Check 'Save settings' button doesn't show up and all inputs are disabled
* Step 7. In the previous browser …

Fix: disable multi-sig extension settings form if user is not owner

---

src/components/frame/Extensions/layouts/ColonySidebar.tsx
src/components/shared/Extensions/LearnMore/types.ts
src/components/v5/frame/PageLayout/partials/PageHeader/PageHeader.tsx
src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/ColonySwitcherAvatar.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColonyItem/JoinedColonyItem.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColonyItem/partials/ActiveColonyIndicator.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColonyItem/types.ts
src/components/v5/shared/Navigation/ColonySwitcher/partials/MobileColonySwitcherToggle.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/MobileJoinedColonies/MobileJoinedColonies.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/TitleSections/BaseTitleSection.tsx
src/constants/externalUrls.ts
src/context/PageLayoutContext/PageLayoutContext.ts
src/context/PageLayoutContext/PageLayoutContextProvider.tsx
src/i18n/en.json

This PR updates the UI of the Colony Switcher.
> [!NOTE]
> The Create new colony button won't work. It will be addressed in a different PR.
1. Connect Dev Wallet 1 so you can view Colonies on the Colony Switcher
2. Verify the UI matches the [Figma designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4537-9201&t=Qz678dDXjP3Dwgfy-4)
3. Set the browser width to 1024px
4. Verify the UI matches the [Figma designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=3931-20270&t=Qz678dDXjP3Dwgfy-4)
Resolves #2885

UI: Update the Colony Switcher UI

---

src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageRow.tsx
src/components/frame/v5/pages/MembersPage/types.ts
src/components/frame/v5/pages/MembersPage/utils.ts
src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltip.tsx
src/components/v5/shared/UserInfoPopover/partials/PermissionTooltip/PermissionTooltipContent.tsx
src/constants/permissions.ts

1. Assign payer permissions to a user in a sub domain
2. Assign admin permissions to the same user in the root domain
3. Navigate to the permissions page and select the sub domain in the team filter
* Step 1. Assign Admin permissions to **fry** in Andromeda
* Step 2. Assign Payer permissions to **fry** in General
* Step 3. Assign Payer permissions to **amy** in Andromeda
* Step 4. Assign Admin permissions to **amy** in General 
* Step 5. Navigate to the permissions page to check **fry's** and **amy's** roles in Andromeda
* Step 6. **fry** should be an admin, **amy** should be an admin with _inherited_ pill
* Step 7. Install multi-sig extension
* Step 8. Assign Admin permissions to **amy** in Serenity  
* Step 9. Assign Payer permissions to **amy** in General
* Step 10. Assign Payer …

fix: update inherited roles in permissions page

---

src/components/v5/common/CompletedAction/partials/SplitPayment/SplitPayment.tsx
src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/hooks.tsx

Split payment preview loading state
* Create a split payment.
* Select the Reputation percentage distribution type.
* Select users with reputation.
* Create the action.
* Note the loading state of the split payment table.
* 
**Changes** 🏗
* loading states added into missing places and members loading state added to the table to show the loader when members data is fetched
* 
- 
Resolves https://github.com/JoinColony/colonyCDapp/issues/2843

feat: split payment preview skeleton loader

---

src/state/transactionState.ts

This PR fixes a very serious issue that was introduced by #2127, however a issue that is very hard to stop since it happens in a very specific, and hard to reproduce state.
The issue at hand was that BigNumber instances _(Class objects)_ now get saved in the database. Since GraphQL only supports [Scalar](https://graphql.org/learn/schema/#scalar-types) types, any object, or object like shape will get converted to a `string` via `JSON.stringify()`. This will make the object lose it's inherited props and values.
Upon fetching the transaction data back into the client, even though `JSON.parse()` was run on these values, it couldn't recreate the original BigNumbers Class instance, but rather an sparsely similar object.
Since there is a `.toString()` call on all standard Javascript objects, …

Properly convert BigNumber values in Transaction params

---

src/components/frame/Extensions/pages/Extensions/ExtensionDetailsPage/partials/ActionButtons/ActionButtons.tsx
src/components/frame/Extensions/pages/Extensions/ExtensionDetailsPage/partials/ActionButtons/types.ts
src/components/frame/Extensions/pages/Extensions/ExtensionDetailsPage/partials/ExtensionTopRow.tsx
src/components/frame/Extensions/pages/Extensions/ExtensionDetailsPage/partials/InstallButton.tsx
src/components/frame/Extensions/pages/Extensions/ExtensionDetailsPage/partials/PermissionsNeededBanner.tsx
src/components/v5/common/ActionSidebar/hooks/useGetExpenditureData.ts
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/ReleasePaymentModal.tsx

- Few fixes to unblock split payment
- It's best to go through each issue one by one
Resolves:
https://github.com/JoinColony/colonyCDapp/issues/2862
https://github.com/JoinColony/colonyCDapp/issues/2879
https://github.com/JoinColony/colonyCDapp/issues/2890
https://github.com/JoinColony/colonyCDapp/issues/2896

fix: button width, hide timer, cache query, remove extension banner

---

src/constants/actionsFilters.ts

- Added advanced payment filter to activity table
* Create some Advanced payment actions.
* Navigate to the actions page.
* Filter by Advanced payment action type.
Resolves https://github.com/JoinColony/colonyCDapp/issues/3002

feat: added adv payments filter

---

src/components/v5/frame/ColonyHome/partials/ReputationChart/utils.ts

- We want to update the domain reputation percentage shown in the reputation pie chart, excluding the General team from the total reputation. Based on the normalised total reputation value, we now compute the domain percentages and do not rely on the `reputationPercentage` each domain has.
**How it currently works:**
```
Total reputation: 12,500
General:     2,500 reputation (20%) (earnt specifically in General)
We show this in the chart:
Dev:         2,500 reputation (20%)
Design:      2,500 reputation (20%)
Ops:         2,500 reputation (20%)
All other:   2,500 reputation (20%)
```
**How we propose the calculation to work:**
```
Total reputation: 12,500
General:     2,500 reputation (earnt specifically in General)
Total team reputation: 12,500 - 2,500 = 10,000
We show this in the chart: …
```

Feat: Update reputation chart values

---

src/components/frame/v5/pages/BalancePage/partials/BalanceModal/index.ts
src/components/frame/v5/pages/BalancePage/partials/BalanceModal/types.ts
src/components/frame/v5/pages/BalancePage/partials/BalanceTable/BalanceTable.tsx
src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/ActionSidebarContent.tsx
src/components/v5/common/Modals/AddFundsModal/AddFundsModal.tsx
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/TotalInOutBalance.tsx
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/consts.ts
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/hooks.ts
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/ClaimFundsButton.tsx
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/IncomeSection.tsx
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/PaymentsSection.tsx
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/TitledSection.tsx
src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/utils.ts
src/hooks/useTimeout.ts

- This PR addresses the `Payments` and `Income` sections from the `Total in and out` card
TODO: Please check the payments and income sections are according to [Figma](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-89693&node-type=frame&t=xND2OvegDeZWkrKJ-0)
* Step 1. Run `create-data` script
* Step 2. Go to `planex` dashboard page http://localhost:9091/planex/
* Step 3. Check the Payments and Income values are the same as the ones displayed in the chart for the current month
* Step 4. Create a `Mint tokens` action/motion
* Step 5. After a bit, the income value should update
* Step 6. In order to not directly claim the minted tokens, please create a patch file with the following content - you can name it `.diff`
```
diff --git …
```

[Dashboard] Total in out card enhancement

---

src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesList.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColonyItem/JoinedColonyItem.tsx
src/context/AppContext/AppContext.ts
src/context/AppContext/AppContextProvider.tsx
src/hooks/useJoinedColonies.ts

1. Open the Colony Switcher and take note of the your Colony's avatar
2. Bring up the Action Form and set it to Edit Colony Details
3. Upload a different Colony avatar
4. Edit the Colony name
5. Fill in all other required form fields and submit the form
6. After the Action is successfully completed, open the Colony Switcher
7. Verify that the Colony Avatar is updated
8. Verify that the new Colony name is used for the Colony Switcher
Resolves #3096

[New Nav] Fix: Automatically apply Colony details updates to UI

---

src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/MobileJoinedColonies/MobileJoinedColonies.tsx
src/components/v5/shared/Navigation/hooks/useCreateNewColony/index.ts

Users who currently have a shareable beta invite code will be taken to the Colony Creation flow upon clicking the Create new colony button.
If they don't have a shareable invite code then for now, they will simply be taken to the Landing page.
> [!IMPORTANT]
> For testing purposes, please connect Leela's wallet (Dev Wallet 1) and create a new Colony using the `node scripts/create-colony-url.js` script.
> After your Colony is created, a shareable invite code should now be made available for Leela's user object.
1. As Leela, visit a Colony
2. Reload the page
3. Click the Colony Switcher
4. Click the Create new colony button
5. Verify that you are taken to the Colony creation page
1. Open an incognito tab
2. Connect Dev Wallet 2 (Amy)
3. Visit a Colony
4. Click the Colony Switcher
5. Click …

Feat: Create Colony Flow

---

src/components/common/Onboarding/Wizard/DesktopWizardSidebar.tsx
src/components/common/Onboarding/Wizard/WizardSidebarItem.tsx
src/components/common/Onboarding/Wizard/WizardSidebarItemFlowLine.tsx
src/components/common/Onboarding/Wizard/WizardSidebarSubItem.tsx
src/components/shared/FeedbackButton/FeedbackButton.tsx
src/components/v5/shared/Navigation/ColonySwitcher/ColonySwitcher.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/ColonySwitcherAvatar.tsx
src/components/v5/shared/Navigation/ColonySwitcher/partials/JoinedColoniesPopover/JoinedColoniesPopover.tsx
src/components/v5/shared/Navigation/Sidebar/Sidebar.tsx
src/components/v5/shared/Navigation/Sidebar/partials/SidebarActionItem/SidebarActionItem.tsx
src/components/v5/shared/Navigation/Sidebar/partials/SidebarRouteItem/SidebarRouteItem.tsx
src/components/v5/shared/Navigation/Sidebar/sidebar.styles.ts
src/components/v5/shared/Navigation/Sidebar/sidebars/ColonyPageSidebar/ColonyPageSidebar.tsx
src/components/v5/shared/SimpleSidebar/SimpleSidebar.tsx

1. Toggle on dark mode
2. Verify that the Colony Sidebar matches the [Desktop dark mode designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4663-19800&t=cNVkt1qzBSbIs3yI-4)
3. Verify that the Colony Sidebar matches the [Mobile dark mode designs](https://www.figma.com/design/uKxVl441Wnn02SNiOA24De/Navigation?node-id=4663-19996&t=cNVkt1qzBSbIs3yI-4)
Resolves #3049

[New Nav] Implement dark theme for the Colony Sidebar

---

amplify/backend/function/fetchColonyBalances/src/package-lock.json
amplify/backend/function/fetchColonyBalances/src/package.json
amplify/backend/function/fetchMotionState/src/package-lock.json
amplify/backend/function/fetchMotionState/src/package.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package-lock.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
amplify/backend/function/fetchTokenFromChain/src/package-lock.json
amplify/backend/function/fetchTokenFromChain/src/package.json
amplify/backend/function/fetchVoterRewards/src/package-lock.json
amplify/backend/function/fetchVoterRewards/src/package.json
amplify/backend/function/getUserReputation/src/package-lock.json
amplify/backend/function/getUserReputation/src/package.json
amplify/backend/function/getUserTokenBalance/src/package-lock.json
amplify/backend/function/getUserTokenBalance/src/package.json
amplify/backend/function/qaSSMtest/src/package-lock.json
amplify/backend/function/qaSSMtest/src/package.json
amplify/backend/function/updateContributorsWithReputation/src/package-lock.json
amplify/backend/function/updateContributorsWithReputation/src/package.json
docker/colony-cdapp-dev-env-block-ingestor
docker/colony-cdapp-dev-env-network
package-lock.json
package.json

Update versions of `colony-js`, `colony-events` and `colony-abis` to their latest releases which support streaming payments, multi-sig and many other goodies :candy: 
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/270/)
You can just make sure everything works
**Changes** 🏗
* Updated package versions

build: update colony package versions

---

amplify/backend/function/fetchDomainBalance/src/api/graphql/operations.js
amplify/backend/function/fetchDomainBalance/src/api/graphql/schemas.js
amplify/backend/function/fetchDomainBalance/src/services/actions.js
amplify/backend/function/fetchDomainBalance/src/services/tokens.js
amplify/backend/function/fetchDomainBalance/src/utils.js
src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/FundingModal/FundingModal.tsx
src/components/v5/payments/TmpAdvancedPayments.tsx
src/redux/sagas/actions/moveFunds.ts
src/redux/sagas/expenditures/fundExpenditure.ts
src/redux/sagas/utils/proofs.ts
src/redux/types/actions/colonyActions.ts
src/redux/types/actions/expenditures.ts

This PR addresses updating the income and payments values correctly based on the income funds,`PAYMENT` and `MOVE_FUNDS` action types and the expenditures both at colony level and domain level.
TODO: What needs to be tested here is that the income and payments values correspond to the financial actions happening within a colony or domain.
Easiest place to spot the changes included in this PR is the `Total in and out` card.
> [!IMPORTANT]
> Switching fast between the domain filters could show up the values from another domain.
> This issue is addressed in [another PR](https://github.com/JoinColony/colonyCDapp/pull/3080)
* Step 1. Please run the `create-data` script
* Step 2. Leave the `All teams` filter on
* Step 3. Check the income section of the card matches the value from the `Incoming …

[Dashboard] Update the total in/out values computed by the lambda

---

docker/colony-cdapp-dev-env-block-ingestor

When an action is created using the permissions decision method, a notification should be sent. The recipients of this notification should be everybody who is in the colony who has notifications turned on, and does not have this colony muted, as well as a separate notification for anybody directly affected by this action.
Here is a list of the actions which should be handled by this ticket:
- Transfer funds
- Mint tokens
- Unlock a token
- Manage tokens
- Create new team
- Edit a team
- Manage reputation
- Manage verified members
- Manage permissions
- Edit Colony details
- Upgrade Colony version
And a list of those that are not handled in this ticket:
- Simple payment (handled in another, earlier ticket)
- Advanced payment (will be handled in a ticket covering all expenditures later)
- …

Feat: Send notifications on permissions actions

---

src/components/frame/v5/pages/AgreementsPage/hooks.ts
src/components/v5/frame/ColonyHome/partials/Agreements/Agreements.tsx

Navigate to the Agreements page.
Create a new Agreement action.
Don't stake the agreement.
Check the Agreements page list.
Newly created agreement should not appears in the list.
**Changes** 🏗
Add filter for `showInActionsList`
Resolves [#31415](https://github.com/JoinColony/colonyCDapp/issues/3207)

feat: add agreements staking filter

---

src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/SplitPaymentForm.tsx
src/components/v5/common/ActionSidebar/partials/forms/StagedPaymentForm/StagedPaymentForm.tsx
src/components/v5/common/ActionSidebar/utils.ts

Fix: add helper function to remove unsupported decision methods from SplitPaymentForm
- This PR introduces a helper function `createUnsupportedDecisionMethodFilter` that can be used to exclude decisions methods from the `DecisionMethodField`.
- Currently it is used only for the `SplitPaymentForm` and `StagedPaymentForm` to exclude the `DecisionMethod.Reputation, DecisionMethod.MultiSig` decision methods
TODO: Test the `Multi-Sig` and `Reputation` decision methods don't show up in the `Split payment` action form
* Step 1. Install the `Reputation Weighted` extension
* Step 2. Install the `Multi-Sig` extension
* Step 3. Give `leela` `Owner` permissions to `Take actions via Multi-Sig`
* Step 4. Create a `Split payment` action
* Step 5. Check `Multi-sig` and `Reputation` are not showing up as …

Fix: Multi-sig showing as an option in Split payments

---

src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionProvider/helpers.ts
src/components/v5/common/ActionSidebar/partials/Motions/partials/MotionProvider/hooks.ts
src/components/v5/common/ActionSidebar/partials/Motions/steps/StakingStep/partials/StakingForm/StakingForm.tsx

This PR adds a check to the `useStakingWidgetUpdate` hook to determine if the motion stakes percentage has just passed the public threshold, and if so refetch the SearchActions query.
This means motions will now show in activity feed as soon as they pass the public threshold without the need to refresh.
* Step 1 - Install the Weighted Voting Reputation extension
* Step 2 - Create a motion of any type
* Step 3 - Support the motion with just a 0.1 stake so that it does not yet pass the public threshold
* Step 4 - Confirm the motion does not appear in the activity feed yet
* Step 5 - Open the UserHub and navigate to the stakes tab to re-open the motion
* Step 6 - Support the motion with just a 1 stake so that it will pass the public threshold
* Step 7 - Without refreshing, check that the …

Feat: Activity feed should be refetched if motion passes threshold

---

amplify/backend/function/cacheDomainBalance/cacheDomainBalance-cloudformation-template.json
amplify/backend/function/cacheDomainBalance/src/package-lock.json
amplify/backend/function/colonycdappSSMAccess/lib/nodejs/getParams.js
amplify/backend/function/fetchDomainBalance/fetchDomainBalance-cloudformation-template.json
amplify/backend/function/fetchDomainBalance/src/api/graphql/operations.js
amplify/backend/function/fetchDomainBalance/src/config/coinGeckoConfig.js
amplify/backend/function/fetchDomainBalance/src/config/envVars.js
amplify/backend/function/fetchDomainBalance/src/config/exchangeRates.js
amplify/backend/function/fetchDomainBalance/src/index.js
amplify/backend/function/fetchDomainBalance/src/package-lock.json
amplify/backend/function/fetchDomainBalance/src/services/exchangeRates.js
amplify/backend/function/fetchDomainBalance/src/services/tokens.js
amplify/backend/function/fetchDomainBalance/src/utils.js

Fix: Add missing imports and edge-cases handling
Fix: Update lambdas Timeout and MemorySize
After discussing with @bogdan-1337 it makes sense to refactor the coin gecko variables to be retrieved from ssm, so I added a few more refactoring commits
Refactor: Add coinGeckoApiUrl and coinGeckoApiKey to ssm lambda layer
Refactor: Use coingecko api url and key from ssm and rename env vars config
Refactor: Move and rename ExchangeRatesFactory to ExchangeRatesService

Domain balance lambdas fixes

---

src/utils/colonyMotions.ts

- Handle finalizable motion state
* Install `Reputation Weighted (Lazy Consensus method)` extension
* Create advanced payment action
* Go to funding step and create it with reputation
* Check motion status after revealing
Resolves https://github.com/JoinColony/colonyCDapp/issues/3377

feat: handle finalizable state

---

amplify/backend/api/colonycdapp/parameters.json

update graphql param to expiration epoch

---

src/routes/Routes.tsx

fix: reserved colony names

---

docker/colony-cdapp-dev-env-block-ingestor
docker/files/block-ingestor/run.sh.base

This PR fixes up our build process for our pnpm workspaces block-ingestor refactor :tada: 
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/297)
This is a boring one, just run the dev env and make sure everything still works :melting_face: 
**Changes** 🏗
* the docker files for the `block-ingestor` have been modified to just run the `main-chain` app
Contributes to #3768

[Proxy colonies] Refactor: Update block ingestor docker config

---

amplify/backend/api/colonycdapp/schema/schema.graphql
amplify/backend/function/cacheDomainBalance/src/package-lock.json
amplify/backend/function/cacheDomainBalance/src/package.json
amplify/backend/function/fetchColonyBalances/src/package-lock.json
amplify/backend/function/fetchColonyBalances/src/package.json
amplify/backend/function/fetchDomainBalance/src/package-lock.json
amplify/backend/function/fetchDomainBalance/src/package.json
amplify/backend/function/fetchMotionState/src/package-lock.json
amplify/backend/function/fetchMotionState/src/package.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package-lock.json
amplify/backend/function/fetchMotionTimeoutPeriods/src/package.json
amplify/backend/function/fetchVoterRewards/src/package-lock.json
amplify/backend/function/fetchVoterRewards/src/package.json
amplify/backend/function/getUserReputation/src/package-lock.json
amplify/backend/function/getUserReputation/src/package.json
amplify/backend/function/getUserTokenBalance/src/package-lock.json
amplify/backend/function/getUserTokenBalance/src/package.json
amplify/backend/function/qaSSMtest/src/package-lock.json
amplify/backend/function/qaSSMtest/src/package.json
amplify/backend/function/updateContributorsWithReputation/src/package-lock.json
amplify/backend/function/updateContributorsWithReputation/src/package.json
docker/colony-cdapp-dev-env-block-ingestor
docker/colony-cdapp-dev-env-proxy-block-ingestor
docker/files/block-ingestor/env.base
docker/files/proxy-block-ingestor/env.base
package-lock.json
package.json
src/graphql/generated.ts
src/redux/sagas/proxyColonies/createProxyColony.ts

This PR adds a new `ADD_PROXY_COLONY` action type and the `multiChainInfo` property to the colony action.
We will use this property to store information regarding the proxy colony deployment.
Also, the `MULTI_CHAIN_BRIDGE_ENDPOINT` was added to the block ingestors env vars aaaand took the chance to upgrade the `@colony` packages to `next.1` version ✨ 
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/300)
TODO: Now let us test that once we trigger a proxy colony deployment, there is data stored in the colony action.
* Step 1. First things first, please make sure you start a fresh new dev env.
> [!TIP]
> Maybe these commands will be of help: 
> To remove all docker entities: `docker system prune --all --volumes`
> To remove all node modules across the **CDapp**: `find . …

[Proxy colonies] Feat: Add multichain info to action

---

docker/colony-cdapp-dev-env-block-ingestor
docker/colony-cdapp-dev-env-proxy-block-ingestor

Due to the fact both `CHAIN_CONTRACT_ADDRESS` and `CHAIN_NETWORK_CONTRACT` should point to the same value, given the `CHAIN_NETWORK_CONTRACT` is already setup in the dApp, I have removed the `CHAIN_CONTRACT_ADDRESS`.
The only impact is for the `addNetworkEventListener` and `addProxyColoniesEventListener` utilities that will now add the listeners for the given network contract address.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/317)
TODO: Let's check these listeners actually subscribe to events for the given contract address.
> [!NOTE]
> You can find the [used contract address](http://localhost:3006/etherrouter-address.json) after you start your dev env.
> [!IMPORTANT]
> If you don't want to start the `block-ingestor` and `proxy-block-ingestor` locally, please …

[Proxy colonies M0] Align CHAIN_NETWORK_CONTRACT and CHAIN_CONTRACT_ADDRESS on block ingestor

---

src/components/common/ColonyActions/helpers/getActionTitleValues.ts
src/components/common/ColonyActions/helpers/mapItemToMessageFormat.tsx
src/components/common/ColonyActionsTable/partials/ActionsTableFilters/partials/filters/ActionTypeFilters/consts.ts
src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/ArbitraryTxsDescription.tsx
src/components/v5/common/CompletedAction/partials/ArbitraryTransaction/ArbitraryTransaction.tsx
src/constants/actionsFilters.ts
src/i18n/en-actions.ts
src/utils/arbitraryTxs.ts

Depends on at least one of the creating arbitrary transaction issues being completed.
Displaying arbitrary transaction actions in the activity feed.
Action metadata:
Metadata
- Default: “Arbitrary transaction by {creator_username}”
- One contract interaction added: “Arbitrary transaction with method mint by {creator_username}”
- Multiple contract interactions added: “Arbitrary transaction with multiple methods by {creator_username}”
Step 1. Enable Voting Reputation extension
Step 2. Create Custom transaction action ("Manage Colony" -> "Custom transactions")
Step 3. Before entering data, verify that action description has title "Arbitrary transaction by leela"
Step 4. Contract address `0xeF841fe1611ce41bFCf0265097EFaf50486F5111 `
ABI input: 
``` …
```

feat: implement conditional arbitrary description

---

docker/colony-cdapp-dev-env-block-ingestor

- Implement notifications for arbitrary transactions
> [!IMPORTANT]  
> Before testing: 
> - Open block-ingestor  branch:  https://github.com/JoinColony/block-ingestor/pull/321
> - Ensure that **block-ingestor** and **cDapp** have this variable in .env file: `MAGICBELL_DEV_KEY=267869931` (the number should be the same for block-ingestor and cDapp)
> - Run App locally (`npm run dev`, `node scripts/create-data.js`, `npm run frontend`)
> - Stop **block-ingestor** in the docker desktop
> - Run **block-ingestor**: `npm run dev --notifications`
Step 1. Create Custom transaction action ("Manage Colony" -> "Custom transactions")
Step 2. Contract address `0xeF841fe1611ce41bFCf0265097EFaf50486F5111 `
ABI input: 
```
[{"type":"constructor","payable":false,"inputs":[{"type":"string","name":"_name"},{" …
```

fix: implement arbitrary notifications, update block ingestor hash

---

src/components/frame/v5/pages/UserCryptoToFiatPage/context/CryptoToFiatContextProvider.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/Verification.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/VerificationModal.tsx
src/components/frame/v5/pages/UserCryptoToFiatPage/partials/Verification/helpers.ts

This PR fixes an issue with our Bridge integration discovered after a report from Etienne. At some point the KYC status stopped updating and customers were not able to get verified. Bridge support advised we need to pass some additional fields from the KYC link to Persona SDK so they can correctly associate the users.
Additionally, it fixes crypto-to-fiat content flash before switching to loading state again if the check KYC query was quicker than `GetUserByAddress` query.
As usual with C2F, it is not testable locally unless you connect to the live environment. These changes have been deployed to QA, but again the sandbox mode skips KYC verification.
Here are some screenshots of the fix in action:

[C2F] Fix: Bridge/Persona integration

---

amplify/backend/function/fetchDomainBalance/src/api/graphql/operations.js
amplify/backend/function/fetchDomainBalance/src/api/graphql/schemas.js
amplify/backend/function/fetchDomainBalance/src/config/basicColonyAbi.json
amplify/backend/function/fetchDomainBalance/src/config/basicUpdatedColonyAbi.json
amplify/backend/function/fetchDomainBalance/src/config/networkConfig.js
amplify/backend/function/fetchDomainBalance/src/consts.js
amplify/backend/function/fetchDomainBalance/src/services/actions.js
amplify/backend/function/fetchDomainBalance/src/services/exchangeRates.js
amplify/backend/function/fetchDomainBalance/src/services/networkBalance.js

- The goal of this PR is to aggregate proxy colony balances across all chains. Since we depend on completed `Payment`/`Move funds` actions, expenditures and claimed incoming funds for other timeframe types beside the `Total`, these changes will only affect the `Total` timeframe. This is because network calls are made specifically for fetching balances on a given chain to ensure accuracy.
> [!IMPORTANT]
> If in the future we need to filter balances by chain for display purposes, we'll have to add `chainId` as a parameter to the lambda function. This would involve filtering actions, expenditures, and claimed incoming funds by chain as well. The network balance fetching logic would also likely need the same parameter to retrieve balances only for the specific chain.
TODO: Enough talking, now …

[Proxy colonies M2] Update fetchDomainBalance lambda to account for proxy chains
